<h1 style="text-align: center;">HEISENBERG-BASED FAULT LOCALIZATION (HBFL)</h1>

<h2 style="text-align: center;">Download Initial Dependencies</h2>

In [8]:
import numpy as np
import pandas as pd
import json
import math
from tqdm import tqdm
from qiskit.quantum_info import SparsePauliOp, Operator, Pauli, Clifford
import qiskit.qasm2 as q2
from qiskit import QuantumCircuit
from IPython.display import display

from heisenbergUtilities import *

In [9]:
# from qiskit_aer import AerSimulator
# simulator = AerSimulator()

# print(simulator.available_devices())

<h2 style="text-align: center;">CONTROL PANEL</h2>

In [ ]:
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------GENERAL PARAMETERS---------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
ALG_NAME = "realamprandom"
ORIGINAL_QASM = f"{ALG_NAME}_5_qubits.qasm"                                                 #| The original algorithm QASM circuit file name.                           
ORIGINAL_QASM_FOLDER = "SBFL_circuits/MQTBench/"                                            #| The folder containing the original QASM circuit file.                    
QASM_MUTANT_FOLDER = f"SBFL_circuits/QMutBenchMutants/Mutants_{ALG_NAME}_5_qubits/"         #| The folder containing all mutants related to the original QASM circuit.  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------SB-QOPS PARAMETERS---------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
RUNS = 10                                                                                   #| Number of times SB-QOPS will run to find a failing or passing test case.            
SHOTS = 20000                                                                               #| Number of shots for SB-QOPS to use to create the compact program specification.     
EPOCH = 80                                                                                  #| Number of epochs SB-QOPS will run to navigate the search space of test cases.       
SBQOPS_TOL = 0.1                                                                            #| Tolerance value SB-QOPS uses to determine if a test case is failing or passing.     
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#---------------------------------------------------------------------HEISENBERG SBFL PARAMETERS-----------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
LAMBDA_PHASE = 2                                                                        #| The hyperparameter used to weight the phase change of the Pauli propagation
LAMBDA_CHANGE = 1                                                                         #| The hyperparameter used to weight the change of string of the Pauli propagation
LAMBDA_SIMILARITY = 1                                                                       #| The hyperparameter used to weight the similarity difference between current and target Pauli
ATOL = 1e-4                                                                                 #| The tolerance value used to prune negligible magnitudes during Pauli propagation.   
MAX_TERMS = 100                                                                             #| The maximum number of terms to keep during Pauli propagation. If None, use all.     
SEARCH_STEP = 3                                                                             #| The search step size used during Pauli propagation. If None, pauli-prop uses 4.     
VERBOSE = 1                                                                                 #| A boolean value to determine if the program should print out detailed information.  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#

Generate the linked list of all operations that take place in the inverse circuit

In [11]:
"""
LinkedListNode: A class that holds information related to a gate in a quantum circuit. 

PROPERTIES:
    - value (String): The name of the quantum gate
    - depth (int): The depth of the gate in the circuit
    - count (Int): The probability that the gate will meaningfully change the Pauli string.
    - next (LinkedListNode): The next gate in the circuit

"""

class LinkedListNode:
    def __init__(self, name="Initial", depth=0, count=0,  next=None):
        self.value = name
        self.depth = depth
        self.next = next
        self.count = count

class LinkedList:
    def __init__(self):
        self.head = None

    def append(self, name, depth):
        new_node = LinkedListNode(name, depth)
        if not self.head:
            self.head = new_node
            return
        last_node = self.head
        while last_node.next:
            last_node = last_node.next
        last_node.next = new_node

    def mark(self, depth):
        current_node = self.head
        while current_node:
            if current_node.depth == depth:
                current_node.count += 1
                return
            current_node = current_node.next

    def reset(self):
        current_node = self.head
        while current_node:
            current_node.count = 0
            current_node = current_node.next

<h3>Download MQT Benchmark circuits.</h3>

We'll start with DJ, RealAmpRandom, and GHZ since SB-QOPS caught those mutants 100% of the time for 5 qubit circuits

<h3>Generate mutants.</h3>

We'll start with mutants that add an unnecessary gate, then add mutants that replace a certain gate later.

The mutants were downloaded from QMutBench, choosing specifically mutants that added a gate anywhere with 0-10% survival scores

In [12]:
correct_circuit = load_program(ORIGINAL_QASM, ORIGINAL_QASM_FOLDER).copy()
correct_list = LinkedList()
correct_list = construct_list(correct_list, correct_circuit, inverse=False)

<h2 style="text-align: center;"> SB-QOPS </h2>

This is where we will use SB-QOPS on a provided circuit and its mutants

For a single mutant, it took about 2 minutes to generate a 20 test suite (10 fail, 10 pass) on an RTX 4090 SUPER. It can only be run on a Linux environment since the AER Simulator does not support Windows

There are 113 mutants for the DJ algorithm in use: 226 minutes or 3 3/4 hours

There are 89 mutants for the GHZ algorithm in use: 178 minutes or about 3 hours

There are 125 mutants for the RealAmpRandom algorithm in use: 250 minutes or just over 4 hours

BUT this cell should only need to be run once per algorithm with mutants under test. After it saves to the csv file at the end, this cell can be commented out as to not accidentally run it again. 

In the future if we want to test this methodology on higher qubit circuits or other algorithms, we'll likely either want to reduce the number of tests in the suite or the number of mutants we're analyzing

In [13]:
# import QOPS as qops
# from QOPS_test import get_compact_program_specification_Z
# from pathlib import Path

# ga_result = pd.DataFrame(columns=['Program',"path_to_mutant",'catch_avg','avg_fitness','failing_testcases', 'passing_testcases'])
# program_history = {}

# #program_specification = The compact program specification. SB-QOPS needs this to generate failing test cases.
# # In a public-use environment, this would be provided by the user.
# program_specification = get_compact_program_specification_Z(correct_circuit, shots=SHOTS)

# #mutants = A python list of qiskit QuantumCircuit variables with a mutation in them
# mutants = []
# mutants_names = []
# root = Path(QASM_MUTANT_FOLDER)
# for qasm_mutant in root.rglob("*.qasm"):
#     mutants.append(load_program(qasm_mutant.name, QASM_MUTANT_FOLDER))
#     mutants_names.append(qasm_mutant.name)

# for mutant_index,mutant in enumerate(mutants):
#     tester = qops.Circuit_Tester(CUT=mutant)
#     tester.set_applicable_families_Z(program_specification)
#     mutants_per_run = []
#     fitness_per_run = []
#     failing_testcases_per_run = []
#     history_per_run = []

#     print("NOW RUNNING TO FIND FAILING TESTS")
#     #For a predefined number of attempts, try to find a set of failing test cases (output is above predefined tolerance)
#     for runs in range(RUNS):
#         killed = 0
#         pauli = {}
#         fitness = 0
#         for i in range(len(tester.applicable_families)):
#             best_function,testcase, history = tester.run_mealoneplusone(i, EPOCH)
#             if best_function > SBQOPS_TOL:
#                 killed = 1
#                 pauli = testcase
#                 fitness = best_function
#                 break
#         mutants_per_run.append(killed)
#         failing_testcases_per_run.append(pauli)
#         fitness_per_run.append(fitness)
#         history_per_run.append(history)

#     avg_score = np.mean(mutants_per_run)
#     avg_fitness = np.mean(fitness_per_run)

#     #Here is our new, modified algorithm from the SB-QOPS method that attempts to find passing test cases as well. We'll need them for SBFL
#     passing_testcases_per_run = []

#     print("NOW RUNNING TO FIND PASSING TESTS")
#     for runs in range(RUNS):
#         pauli = {}
#         fitness = 0
#         for i in range(len(tester.applicable_families)):
#             best_function, testcase, history = tester.run_reverse_mealoneplusone(i,EPOCH)
#             if best_function < SBQOPS_TOL:
#                 pauli = testcase
#                 break
#         passing_testcases_per_run.append(pauli)

#     #Replace static program file with "program_name" when ready to test fully
#     """
#     ga_result: A pandas dataframe with the following columns
#         Program: Name of the mutant quantum circuit file
#         Path_To_Mutant: Path to the mutant file
#         Catch_Avg: The average number of times the mutant was identified by SB-QOPS
#         Avg_Fitness: The average fitness of the search algorithm used. Higher usually indicates higher Catch_Avg
#         Failing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a failing test case
#         Passing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a passing test case
#     """
#     ga_result = pd.concat([pd.DataFrame([[mutants_names[mutant_index],QASM_MUTANT_FOLDER,avg_score,avg_fitness,json.dumps(failing_testcases_per_run), json.dumps(passing_testcases_per_run)]],columns=ga_result.columns),ga_result],ignore_index=True)
#     ga_result.to_csv(f'realamprandom_ga_result', index=False)

ga_result is a slightly altered pandas Dataframe with similar structure found in SB-QOPS's results folder. The differences are changing the column "Program" to be the name of the mutant file instead of the original quantum circuit, changing "Mutant" to be the path to the mutant file instead of being an arbitrary index value, and adding a passing_testcases column that returns Pauli strings and coefficients that generate passing tests.

Now we want to run SBFL using Heisenberg evolution trees on each circuit placed in ga_result

Evolution analysis tends to take about 5 minutes for 10 failing tests on a very complex algorithm such as QNN, so about 10 minutes for 20 total tests

DJ was a relatively small algorithm with few to no branching gates, so it only ended up taking about 5-6 minutes to evolve and analyze all 113 DJ mutants

About 890 minutes for GHZ, or 14.8 hours to evolve and analyze all 89 GHZ mutants

About 1250 minutes for RealAmpRandom, or 20.8 hours to evolve and analyze all 125 RealAmpRandom mutants

The runtime of this code segment is directly tied to the depth of the circuit being analyzed and the number of 2-branching gates such as rotation or phase gates that exist in the circuit.

This is something to note in the final paper. Regardless of accuracy this methodology takes a long time to run. If results are promising, then we'll want to look into the tradeoffs between EXAM and hyperparameters to speed this up. Primarily the atol, max_terms, and search_step parameters in the evolve_pauli_exact method in HeisenbergUtilities.py

<h2 style="text-align: center;">HEISENBERG EVOLUTIONS (PAULI PROPAGATION)</h2>

In [14]:
from heisenbergTree import *

ga_result = pd.read_csv(f'{ALG_NAME}_ga_result.csv')
tarantula_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','exam_score'])
barinel_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','exam_score'])

#For each mutant of a circuit, run the SBFL implementation
for mutant, path in zip(ga_result.loc[:,"Program"], ga_result.loc[:,"path_to_mutant"]):
    print("Now evolving the following mutant: ", mutant)

    #Extract the raw test cases found for each mutant
    desired_failing_testcases = ga_result.loc[(ga_result["Program"] == mutant), ["failing_testcases"]]
    desired_passing_testcases = ga_result.loc[(ga_result["Program"] == mutant), ["passing_testcases"]]
    raw_failing_testcases = desired_failing_testcases["failing_testcases"].values[0].split("}")
    raw_passing_testcases = desired_passing_testcases["passing_testcases"].values[0].split("}")

    #Remove empty tests
    raw_failing_testcases = remove_null_tests(raw_failing_testcases)
    raw_passing_testcases = remove_null_tests(raw_passing_testcases)

    circuit_inverse = load_program(mutant,path).copy().inverse()  # Invert to track backward evolution of the operator
    forward_mutant = load_program(mutant, path).copy()

    #Create the linked list of operations in the inverse circuit
    operation_list = LinkedList()
    operation_list = construct_list(operation_list, circuit_inverse, True)

    forward_list = LinkedList()
    forward_list = construct_list(forward_list, forward_mutant, False)

    #Create list of nodes in linked list. Somewhere down the road remove the linked list implementation. It's unnecessary and giving me a headache
    node_list = []
    node = operation_list.head
    while node:
        node_list.append(node)
        node = node.next

    #Perform Pauli propagation (Heisenberg evolution) for all test cases. Returns a dataframe with all counts for all operations
    global_frame_fail = heisenberg_evolve(circuit_inverse, 
                                          operation_list, 
                                          raw_failing_testcases, 
                                          "fail", 
                                          LAMBDA_PHASE, 
                                          LAMBDA_CHANGE, 
                                          LAMBDA_SIMILARITY, 
                                          atol = ATOL, 
                                          max_terms = MAX_TERMS, 
                                          search_step = SEARCH_STEP)
    
    global_frame_pass = heisenberg_evolve(circuit_inverse, 
                                          operation_list, 
                                          raw_passing_testcases, 
                                          "pass", 
                                          LAMBDA_PHASE, 
                                          LAMBDA_CHANGE, 
                                          LAMBDA_SIMILARITY, 
                                          atol = ATOL, 
                                          max_terms = MAX_TERMS, 
                                          search_step = SEARCH_STEP)

    global_frame = pd.concat([global_frame_fail, global_frame_pass], ignore_index=True)

    global_frame = global_frame.drop(["Initial"],axis=1)
    if VERBOSE:
        display(global_frame)

    tarantula_scores = tarantula(global_frame)
    barinel_scores = barinel(global_frame)

    if VERBOSE:
        print("BARINEL SCORES")
        display(barinel_scores)
        print("TARANTULA SCORES")
        display(tarantula_scores)
    
    # Here is where analysis of the methodology begins. 
    # We first extract the position of the erroneous gate by comparing it to the original MQT gate
    # NOTE: This method is intended for single-added gates for now. Other types of mutants will require other methods later
    error_gate_location = find_erroneous_gate(forward_mutant, correct_circuit)

    if VERBOSE:
        print("ERROR GATE LOCATION:")
        print(error_gate_location)

    # Calculate the EXAM score for Barinel by counting the number of gates we would have to observe before we reach the erroneous gate.
    gates_observed = 0
    barinel_exam_score = 0
    for col_name, col_date in barinel_scores.items():
        gates_observed += 1

        #Extract depth from column name
        gate_depth = int(col_name.split()[1])

        if gate_depth == error_gate_location:
            barinel_exam_score = gates_observed/(circuit_inverse.size())
            break

    # Calculate the EXAM score for Tarantula by counting the number of gates we would have to observe before we reach the erroneous gate.
    gates_observed = 0
    tarantula_exam_score = 0
    for col_name, col_date in tarantula_scores.items():
        gates_observed += 1

        #Extract depth from column name
        gate_depth = int(col_name.split()[1])

        if gate_depth == error_gate_location:
            tarantula_exam_score = gates_observed/(circuit_inverse.size())
            break

    # Here we store the results from the HBFL analysis for both barinel and tarantula into a csv file for later analysis.
    barinel_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,barinel_exam_score]],columns=barinel_sbfl_result.columns),barinel_sbfl_result],ignore_index=True)
    barinel_sbfl_result.sort_values(by=['exam_score'], ascending=False)
    barinel_sbfl_result.to_csv(f'{ALG_NAME}_barinel_sbfl_result.csv', index=False)

    tarantula_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,tarantula_exam_score]],columns=tarantula_sbfl_result.columns),tarantula_sbfl_result],ignore_index=True)
    tarantula_sbfl_result.sort_values(by=['exam_score'], ascending=False)
    tarantula_sbfl_result.to_csv(f'{ALG_NAME}_tarantula_sbfl_result.csv', index=False)

if VERBOSE:
    display(barinel_sbfl_result)
    display(tarantula_sbfl_result)

Now evolving the following mutant:  AddGate_y_inGap_9_.qasm

  0%|          | 0/10 [00:00<?, ?it/s]

100%|██████████| 10/10 [00:00<00:00, 12.64it/s]
100%|██████████| 10/10 [00:00<00:00, 13.77it/s]

         y 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.423531  1.086551  0.880150  1.164215  1.407604  0.409445      fail
1   0.334381  1.004184  1.084039  1.510551  1.479059  0.339591      fail
2   0.513183  1.063364  1.063710  1.401660  1.253067  0.344852      fail
3   0.563684  1.016632  1.029099  1.150338  1.252753  0.401267      fail
4   0.486328  0.907934  0.978164  0.954245  1.008951  0.301443      fail
5   0.390597  0.957577  0.917749  1.072723  1.191579  0.293919      fail
6   0.422076  0.903410  0.926724  1.312365  1.251047  0.341099      fail
7   0.407532  0.693668  0.712082  0.973595  1.182265  0.226771      fail
8   0.421761  0.984849  0.731751  1.016585  1.330986  0.368405      fail
9   0.487222  0.933332  0.621954  0.909771  1.272966  0.371709      fail
10  0.347360  0.432684  0.721292  0.882940  0.933825  0.283575      pass
11  0.255015  0.708278  0.728050  1.057184  1.116542  0.383153      pass
12  0.105812  0.412981  0.454486  0.491031  0.482438  0.147745      pass
13  0.446730  0.947934  0.882685  1.158282  1.114766  0.334638      pass
14  0.218001  0.446379  0.644693  0.677660  0.694499  0.140451      pass
15  0.350258  0.724134  0.626324  0.695061  0.907959  0.249188      pass
16  0.453085  0.758599  0.756829  1.086815  1.005193  0.268888      pass
17  0.297048  0.876527  0.521760  0.620094  0.676647  0.233625      pass
18  0.263122  0.793578  0.547345  0.557478  0.595445  0.206470      pass
19  0.283029  0.741002  0.650045  0.778183  1.040158  0.307802      pass

BARINEL SCORES

         cx 1       y 5      cx 2      cx 4     cx 3       h 0
sum  0.595831  0.595775  0.588885  0.582636  0.57791  0.570789

TARANTULA SCORES

         cx 1       y 5      cx 2      cx 4     cx 3       h 0
sum  0.595831  0.595775  0.588885  0.582636  0.57791  0.570789

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_y_inGap_10_.qasm

100%|██████████| 10/10 [00:00<00:00, 12.66it/s]
100%|██████████| 10/10 [00:00<00:00, 12.52it/s]

         y 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.439540  0.800342  0.750866  1.163878  1.266413  0.312810      fail
1   0.416704  0.859317  1.011134  0.913480  0.751846  0.213919      fail
2   0.442119  0.871059  1.050945  1.404628  1.368834  0.348501      fail
3   0.377077  0.939073  1.067532  1.265608  1.332121  0.297418      fail
4   0.426567  0.804400  0.389738  0.519366  0.658572  0.192417      fail
5   0.590717  0.915471  0.825308  0.938354  1.013172  0.235679      fail
6   0.470803  1.058237  1.249754  1.472473  1.549390  0.376286      fail
7   0.464292  1.080409  0.949691  1.050299  1.009486  0.283929      fail
8   0.397058  1.087119  0.852462  1.246384  1.326930  0.308342      fail
9   0.468017  0.925425  0.678278  0.884531  1.154099  0.264594      fail
10  0.346720  0.839390  0.640844  0.866604  0.690489  0.218330      pass
11  0.212325  0.602411  0.545255  0.586260  0.818850  0.263633      pass
12  0.270255  0.709699  0.981005  0.945585  1.194490  0.340098      pass
13  0.306873  0.879198  0.813392  0.876587  1.092309  0.306490      pass
14  0.402737  1.038855  0.724398  0.806423  1.122327  0.350892      pass
15  0.333693  0.781615  0.683525  0.649707  0.706603  0.229403      pass
16  0.340108  0.961750  1.044676  0.941651  1.107512  0.310257      pass
17  0.432511  0.900586  0.801202  0.867616  0.691500  0.225207      pass
18  0.389427  0.957531  0.638639  0.845867  1.159850  0.239001      pass
19  0.315818  0.840131  0.653900  1.039296  1.215640  0.352809      pass

BARINEL SCORES

          y 5      cx 2      cx 3      cx 1      cx 4       h 0
sum  0.572828  0.563092  0.539715  0.538419  0.523238  0.499804

TARANTULA SCORES

          y 5      cx 2      cx 3      cx 1      cx 4       h 0
sum  0.572828  0.563092  0.539715  0.538419  0.523238  0.499804

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_x_inGap_4_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.17it/s]
100%|██████████| 10/10 [00:00<00:00, 10.86it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       x 0 pass/fail
0   1.158223  1.090392  1.368098  1.499374  0.359242  0.288530      fail
1   1.020662  0.666691  0.607572  0.692879  0.183973  0.193499      fail
2   0.882785  1.020180  1.364236  1.608972  0.385588  0.282313      fail
3   1.018039  1.054933  1.011409  1.029222  0.237876  0.233767      fail
4   0.528871  1.044307  1.048886  1.138708  0.259321  0.240791      fail
5   0.869262  0.972640  0.921519  0.904977  0.227556  0.250593      fail
6   0.734657  0.792501  0.881609  1.229080  0.335205  0.239510      fail
7   1.009833  1.030939  1.162494  1.152980  0.264864  0.261569      fail
8   0.980510  0.901174  0.860289  0.996235  0.274603  0.240990      fail
9   0.967280  1.151557  1.449199  1.408922  0.317960  0.255160      fail
10  0.673136  0.376452  0.465513  0.604975  0.183201  0.131851      pass
11  1.120642  0.940238  1.153229  1.361636  0.407409  0.251319      pass
12  1.091957  0.860187  1.174305  1.461498  0.495319  0.205574      pass
13  0.567997  0.297979  0.386411  0.560300  0.167060  0.112101      pass
14  0.887496  0.920723  0.984136  1.058403  0.311743  0.239231      pass
15  0.811561  0.943930  1.299847  1.372768  0.374426  0.226059      pass
16  0.936334  0.764080  0.671765  0.736660  0.155983  0.209970      pass
17  0.850445  1.051543  1.207737  0.996542  0.261232  0.281257      pass
18  0.611554  1.094102  1.333329  1.321135  0.386583  0.231897      pass
19  0.617239  0.907007  1.034188  0.909070  0.336659  0.184856      pass

BARINEL SCORES

          x 0      cx 4      cx 2      cx 5      cx 3       h 1
sum  0.545234  0.543874  0.528995  0.528888  0.523665  0.480304

TARANTULA SCORES

          x 0      cx 4      cx 2      cx 5      cx 3       h 1
sum  0.545234  0.543874  0.528995  0.528888  0.523665  0.480304

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_cx_inGap_3_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.50it/s]
100%|██████████| 10/10 [00:00<00:00, 11.44it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.892040  0.773729  1.135393  0.773516  0.777311  0.255560      fail
1   1.335410  1.041168  1.474238  1.100762  0.956265  0.360411      fail
2   0.458269  0.794524  0.733147  0.672502  0.854545  0.238342      fail
3   0.962727  1.206770  1.324015  1.148347  1.104721  0.266173      fail
4   1.098532  1.165445  1.352717  1.142763  0.853704  0.275422      fail
5   0.855117  0.771626  1.028632  0.831163  0.797367  0.208514      fail
6   0.849063  0.864810  1.117099  0.895875  0.932281  0.323371      fail
7   0.512138  0.649910  0.763002  0.565591  0.746679  0.173256      fail
8   0.703953  0.970040  1.394536  1.079423  0.754353  0.245541      fail
9   0.923329  1.030866  1.408850  1.135228  0.588605  0.187266      fail
10  1.213118  0.838730  1.150616  0.857244  0.666824  0.294572      pass
11  1.286001  1.222114  1.532983  1.296316  0.881679  0.325540      pass
12  0.755808  0.490934  0.669928  0.514490  0.517682  0.155159      pass
13  0.835381  0.868466  1.144802  0.913251  1.014814  0.291549      pass
14  0.617691  0.435851  0.486115  0.453037  0.491623  0.131620      pass
15  0.971091  0.743805  1.013803  0.765022  0.732628  0.253374      pass
16  0.714272  0.548625  0.866216  0.474793  0.354786  0.128086      pass
17  0.650295  0.726621  0.898049  0.738967  0.645493  0.145948      pass
18  0.656424  0.610520  0.437483  0.453986  0.770554  0.235892      pass
19  0.770640  0.862480  0.782239  0.864428  0.978772  0.326061      pass

BARINEL SCORES

         cx 3      cx 2      cx 4      cx 1       h 0      cx 5
sum  0.566366  0.560373  0.557794  0.542507  0.525516  0.503512

TARANTULA SCORES

         cx 3      cx 2      cx 4      cx 1       h 0      cx 5
sum  0.566366  0.560373  0.557794  0.542507  0.525516  0.503512

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_x_inGap_9_.qasm

100%|██████████| 10/10 [00:00<00:00, 12.86it/s]
100%|██████████| 10/10 [00:00<00:00, 13.77it/s]

         x 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.418355  0.991824  1.248283  1.426793  1.376510  0.357981      fail
1   0.334173  1.050200  0.784244  1.003962  1.036145  0.277546      fail
2   0.392034  0.785134  0.850759  1.017868  1.275409  0.359123      fail
3   0.475274  0.937783  0.962164  0.865864  0.838819  0.214669      fail
4   0.503601  1.143936  1.329856  1.611304  1.576374  0.418254      fail
5   0.432552  0.604367  0.613588  0.856206  0.899086  0.158882      fail
6   0.394002  0.801437  0.804602  0.975257  1.265529  0.281911      fail
7   0.434135  0.954520  1.208940  1.551203  1.769759  0.369582      fail
8   0.548660  1.085303  1.033261  0.977282  1.265230  0.277896      fail
9   0.381565  0.811569  0.830974  1.070116  0.965436  0.221664      fail
10  0.155773  0.596118  0.492919  0.696138  1.014926  0.250357      pass
11  0.466796  1.187617  1.073183  1.325371  1.385117  0.384847      pass
12  0.341816  1.005120  1.319239  1.443296  1.351481  0.376435      pass
13  0.388159  1.197219  1.052934  1.228935  1.309790  0.347216      pass
14  0.314838  0.971857  1.102574  1.381933  1.456939  0.284684      pass
15  0.388465  1.138650  1.008794  1.350825  1.222625  0.370505      pass
16  0.309745  0.663520  0.554047  0.756491  1.002987  0.292211      pass
17  0.191226  0.507000  0.571991  0.675678  0.827034  0.201370      pass
18  0.353194  1.166177  1.128122  1.154854  1.515296  0.460574      pass
19  0.351602  1.049772  1.108488  1.352285  1.427926  0.358883      pass

BARINEL SCORES

          x 5      cx 3      cx 2     cx 1      cx 4       h 0
sum  0.569479  0.506667  0.499781  0.49504  0.491502  0.468907

TARANTULA SCORES

          x 5      cx 3      cx 2     cx 1      cx 4       h 0
sum  0.569479  0.506667  0.499781  0.49504  0.491502  0.468907

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_x_inGap_5_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.40it/s]
100%|██████████| 10/10 [00:00<00:00, 11.56it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       x 0 pass/fail
0   1.266695  0.794930  1.219935  1.410459  0.340282  0.326719      fail
1   1.034569  0.747860  0.842311  1.206151  0.308555  0.255447      fail
2   1.200693  1.080925  1.094781  1.046187  0.286413  0.303860      fail
3   1.212974  0.914150  1.107906  1.081369  0.396899  0.267049      fail
4   1.023272  0.698890  1.058112  1.231021  0.342180  0.230102      fail
5   1.171946  0.755493  1.116347  1.345949  0.319048  0.293254      fail
6   0.984994  0.895132  1.224308  1.488662  0.280915  0.280964      fail
7   0.980486  0.762330  0.747075  0.808418  0.245642  0.222953      fail
8   0.718924  0.931251  0.907903  0.709430  0.188391  0.206111      fail
9   1.410642  0.863959  1.574650  1.729946  0.444038  0.327692      fail
10  1.052223  0.780134  1.068588  1.237296  0.379103  0.234243      pass
11  1.116908  1.123886  1.474872  1.639300  0.419518  0.287833      pass
12  0.712341  0.685476  0.805552  0.830713  0.266132  0.174519      pass
13  0.829509  0.693367  0.817104  0.783953  0.161377  0.231182      pass
14  0.896023  0.690069  0.893980  0.841742  0.204812  0.193280      pass
15  0.733772  0.908177  0.706485  0.885807  0.248401  0.175131      pass
16  1.178646  1.170538  1.511960  1.617672  0.453444  0.280001      pass
17  0.897036  0.886461  0.895948  0.857546  0.207867  0.244873      pass
18  0.772054  0.784750  0.655459  0.954810  0.314122  0.205757      pass
19  0.485243  0.323262  0.441256  0.414061  0.139919  0.098912      pass

BARINEL SCORES

          x 0      cx 5      cx 2      cx 3       h 1      cx 4
sum  0.560789  0.559237  0.545087  0.540222  0.530071  0.512091

TARANTULA SCORES

          x 0      cx 5      cx 2      cx 3       h 1      cx 4
sum  0.560789  0.559237  0.545087  0.540222  0.530071  0.512091

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_swap_inGap_2_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.34it/s]
100%|██████████| 10/10 [00:00<00:00, 10.25it/s]

        cx 5      cx 4      cx 3      cx 2    swap 1       h 0 pass/fail
0   0.887876  0.691941  0.945896  1.102229  0.193718  0.382400      fail
1   0.974545  1.140493  1.613514  1.627394  0.212784  0.396288      fail
2   0.838848  0.820281  0.931892  1.104907  0.132899  0.420303      fail
3   0.770369  0.675690  0.857752  0.658160  0.196280  0.249547      fail
4   0.977259  1.137336  1.147245  1.322048  0.217729  0.451740      fail
5   0.979938  0.965160  1.069114  1.059041  0.133785  0.262356      fail
6   0.869794  0.987615  1.000834  0.922859  0.186317  0.337392      fail
7   0.846387  0.753422  0.984763  1.183050  0.137231  0.374588      fail
8   1.065682  1.030157  1.170858  1.366614  0.180208  0.386249      fail
9   0.792846  0.577835  0.738336  0.864330  0.141338  0.330187      fail
10  0.895087  0.879646  1.108447  1.352837  0.202687  0.428013      pass
11  0.789037  0.764907  0.882786  1.316781  0.115713  0.334840      pass
12  1.093250  1.188292  1.331976  1.504047  0.179265  0.412287      pass
13  0.921677  0.946243  0.964161  1.388019  0.172222  0.349313      pass
14  0.623316  0.705464  0.603439  0.629046  0.147945  0.252757      pass
15  1.095375  0.784072  1.268596  1.459269  0.170914  0.397716      pass
16  0.499483  0.782548  0.884195  0.852359  0.091930  0.243954      pass
17  0.913054  1.110976  1.150233  1.174047  0.193578  0.356161      pass
18  0.944329  0.692297  0.874091  1.292803  0.165719  0.397374      pass
19  0.484682  0.487594  0.722899  0.694341  0.133109  0.235181      pass

BARINEL SCORES

       swap 1      cx 5      cx 3       h 0      cx 4    cx 2
sum  0.524083  0.521557  0.516527  0.513106  0.512787  0.4901

TARANTULA SCORES

       swap 1      cx 5      cx 3       h 0      cx 4    cx 2
sum  0.524083  0.521557  0.516527  0.513106  0.512787  0.4901

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_sx_inGap_2_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.38it/s]
100%|██████████| 10/10 [00:01<00:00,  9.18it/s]

        cx 5      cx 4      cx 3      cx 2       h 1    sxdg 0 pass/fail
0   0.920599  0.797187  0.923771  1.190340  0.302829  0.787378      fail
1   0.805017  0.604027  0.485857  0.618852  0.224110  0.577326      fail
2   0.952504  1.111423  1.375205  1.550773  0.350203  0.825476      fail
3   0.858081  0.812916  1.024440  1.143281  0.251862  0.643269      fail
4   1.054289  0.856820  1.228153  1.261264  0.311117  0.732045      fail
5   0.782147  0.748333  1.069181  1.371872  0.297237  0.793197      fail
6   0.982816  0.887227  1.229701  1.322839  0.340953  0.845845      fail
7   0.699228  0.473972  0.383614  0.835683  0.194372  0.657973      fail
8   0.990235  1.065993  1.086403  1.148917  0.268572  0.700579      fail
9   0.858042  0.644899  0.889882  1.242550  0.316455  0.874907      fail
10  0.750117  0.985387  1.473967  1.403747  0.394475  0.612881      pass
11  0.986615  0.911063  1.039275  1.098473  0.400411  0.589748      pass
12  0.648289  0.490117  0.713226  0.779815  0.223964  0.464597      pass
13  0.969763  1.018811  1.080400  1.147571  0.364272  0.625993      pass
14  0.864737  0.830480  0.827750  0.673563  0.251785  0.448101      pass
15  0.712643  0.595535  0.658356  0.714793  0.232837  0.461460      pass
16  0.712472  0.565428  0.743464  0.917287  0.270776  0.496991      pass
17  0.991692  0.843791  1.089456  1.359520  0.401571  0.801936      pass
18  0.598805  0.426254  0.461258  0.522876  0.144383  0.425744      pass
19  0.833646  0.444234  0.516933  0.503691  0.219437  0.431004      pass

BARINEL SCORES

       sxdg 0      cx 2      cx 3      cx 4      cx 5       h 1
sum  0.581255  0.561637  0.529839  0.529499  0.524575  0.495991

TARANTULA SCORES

       sxdg 0      cx 2      cx 3      cx 4      cx 5       h 1
sum  0.581255  0.561637  0.529839  0.529499  0.524575  0.495991

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_ry_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.85it/s]
100%|██████████| 10/10 [00:01<00:00,  9.71it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      ry 0 pass/fail
0   1.069770  0.898329  1.033915  1.207156  0.356726  0.831076      fail
1   1.173435  0.607481  0.815795  0.796015  0.294822  0.861294      fail
2   1.168338  0.974975  1.027385  0.786433  0.234549  0.835487      fail
3   1.033498  0.893983  1.128447  1.264585  0.310369  0.811771      fail
4   1.189510  0.814057  0.981309  0.701845  0.252360  0.924002      fail
5   1.039270  0.852179  1.006463  0.932006  0.238340  0.811351      fail
6   1.068528  1.100232  1.312794  1.728984  0.365137  0.867203      fail
7   0.926948  0.814162  1.155399  1.451153  0.328644  0.837690      fail
8   1.072954  1.285001  1.312140  1.378163  0.328679  0.944404      fail
9   1.053723  0.907034  1.112656  1.156898  0.327839  0.820621      fail
10  0.666927  0.614579  0.804000  0.880345  0.170894  0.616137      pass
11  0.843771  0.710346  0.878064  0.897441  0.254957  0.763422      pass
12  1.091350  0.447508  0.779466  0.763477  0.292419  0.813584      pass
13  0.934992  0.633938  0.634909  0.719756  0.224811  0.740902      pass
14  0.988251  0.833810  1.062242  1.083795  0.314536  0.711315      pass
15  0.715624  0.858773  0.958913  1.034663  0.221583  0.616018      pass
16  1.013356  1.116405  1.321682  1.337902  0.383859  0.852221      pass
17  1.073778  0.909487  0.759342  0.948205  0.217700  0.849294      pass
18  0.699232  0.423834  0.523355  0.697986  0.198780  0.447733      pass
19  0.739551  0.675832  1.038662  1.169887  0.304400  0.637088      pass

BARINEL SCORES

         cx 4      cx 3      cx 5      ry 0      cx 2       h 1
sum  0.558726  0.554097  0.551862  0.548009  0.544653  0.540339

TARANTULA SCORES

         cx 4      cx 3      cx 5      ry 0      cx 2       h 1
sum  0.558726  0.554097  0.551862  0.548009  0.544653  0.540339

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_ccx_inGap_3_.qasm

100%|██████████| 10/10 [00:02<00:00,  4.93it/s]
100%|██████████| 10/10 [00:01<00:00,  5.48it/s]

        cx 5      cx 4      cx 3     ccx 2      cx 1       h 0 pass/fail
0   1.165940  0.844200  0.779516  1.001917  0.613432  0.243877      fail
1   0.718830  0.887729  1.327721  0.786090  0.764410  0.223402      fail
2   0.934753  0.848581  0.945415  0.804275  0.633838  0.203244      fail
3   0.704005  0.408025  0.678903  0.690556  0.538716  0.148644      fail
4   1.223152  0.971578  1.290830  1.048010  0.844551  0.283419      fail
5   1.284488  1.359389  1.449708  1.180954  0.935701  0.309100      fail
6   0.664398  0.840975  0.954672  0.740833  0.489605  0.208964      fail
7   0.821897  0.761348  1.004690  0.870188  0.652546  0.203979      fail
8   1.048512  1.047079  1.333086  1.035246  0.841094  0.301730      fail
9   0.812995  0.726763  0.723338  0.797434  0.515893  0.208195      fail
10  0.847286  0.628363  0.826680  0.744004  0.477880  0.199044      pass
11  0.665179  0.261934  0.268856  0.504108  0.324383  0.146419      pass
12  0.523970  0.500950  0.641482  0.520264  0.457572  0.147167      pass
13  0.734959  0.654025  1.009869  0.750340  0.595947  0.179847      pass
14  1.187796  1.033109  1.467847  1.108892  1.017618  0.298771      pass
15  0.875947  0.522706  0.646845  0.847620  0.549208  0.218810      pass
16  1.017280  0.862219  1.112057  0.963486  0.739665  0.252776      pass
17  0.947728  0.641994  0.742324  0.728027  0.632964  0.218108      pass
18  0.731657  0.537431  0.547045  0.617177  0.346296  0.143321      pass
19  0.878685  0.845179  0.881719  0.751017  0.626891  0.212090      pass

BARINEL SCORES

         cx 4      cx 3     ccx 2      cx 1       h 0      cx 5
sum  0.572702  0.562878  0.543072  0.542124  0.536567  0.527221

TARANTULA SCORES

         cx 4      cx 3     ccx 2      cx 1       h 0      cx 5
sum  0.572702  0.562878  0.543072  0.542124  0.536567  0.527221

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_h_inGap_2_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.29it/s]
100%|██████████| 10/10 [00:01<00:00,  9.48it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       h 0 pass/fail
0   0.847792  0.804456  1.114884  1.083700  0.268271  0.414255      fail
1   0.963273  0.558071  0.788507  0.985374  0.273725  0.534075      fail
2   1.190951  0.775017  1.322110  1.763498  0.346064  0.724115      fail
3   0.861311  0.836570  1.207155  1.014808  0.247844  0.472057      fail
4   1.364036  1.075629  1.528276  1.770771  0.396911  0.698459      fail
5   0.865661  1.060833  1.109499  1.403443  0.350453  0.544193      fail
6   0.872793  1.021985  1.467349  1.911212  0.399164  0.725818      fail
7   0.758204  0.719954  0.845056  1.202783  0.264854  0.500807      fail
8   1.000803  0.492871  0.916856  1.190644  0.233745  0.568303      fail
9   0.834325  0.570407  0.823683  0.754300  0.150621  0.428298      fail
10  0.665813  0.224709  0.414031  0.377850  0.135210  0.230170      pass
11  0.542790  0.623704  0.579493  0.689456  0.168309  0.402509      pass
12  0.999094  0.500819  0.705746  0.710536  0.245106  0.370602      pass
13  0.882010  0.676592  1.255112  1.428187  0.410098  0.581094      pass
14  0.541775  0.765429  0.733223  0.915629  0.256754  0.348651      pass
15  1.059899  0.647724  0.768075  0.582627  0.258633  0.337798      pass
16  0.874166  0.388260  0.626529  0.674158  0.214024  0.446107      pass
17  0.967556  1.211128  1.386583  1.327695  0.335696  0.528431      pass
18  1.039803  1.002077  1.263672  1.428839  0.449015  0.551163      pass
19  0.834357  0.711770  0.728007  0.698205  0.152406  0.417491      pass

BARINEL SCORES

         cx 2       h 0      cx 3      cx 4      cx 5      h 1
sum  0.596911  0.571066  0.567987  0.539664  0.532057  0.52757

TARANTULA SCORES

         cx 2       h 0      cx 3      cx 4      cx 5      h 1
sum  0.596911  0.571066  0.567987  0.539664  0.532057  0.52757

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_ccx_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  5.33it/s]
100%|██████████| 10/10 [00:02<00:00,  4.98it/s]

        cx 5     ccx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.007201  0.832185  0.617438  0.673258  0.820429  0.239304      fail
1   1.066019  0.955523  0.515994  0.821832  0.854789  0.240424      fail
2   0.986565  0.880430  0.408431  0.640428  0.750698  0.208358      fail
3   1.334295  1.103340  0.739222  1.147869  1.230362  0.317686      fail
4   1.342220  0.912622  0.526974  0.782440  0.865631  0.251791      fail
5   1.179328  0.768859  0.572945  0.686681  0.830400  0.227831      fail
6   1.080946  1.012789  0.563064  0.764004  1.028852  0.289570      fail
7   1.026325  0.965316  0.749754  0.781898  0.997538  0.326794      fail
8   1.024619  0.904316  0.625331  0.814270  0.969058  0.270176      fail
9   0.926541  0.860899  0.374126  0.466510  0.561477  0.183505      fail
10  0.486063  0.498480  0.224787  0.345866  0.474141  0.125388      pass
11  0.951996  0.805973  0.602665  0.708636  0.749247  0.218344      pass
12  0.735675  0.859409  0.636998  0.796560  0.802239  0.209661      pass
13  0.922936  0.768244  0.495860  0.734911  0.876612  0.255367      pass
14  0.771349  0.759343  0.357212  0.462357  0.591637  0.192748      pass
15  0.784279  0.999485  0.577666  0.677604  0.851829  0.224952      pass
16  0.657062  0.598593  0.341357  0.386180  0.494894  0.155898      pass
17  0.952153  0.875093  0.485172  0.653338  0.769597  0.241677      pass
18  0.749086  0.849917  0.598044  0.709418  0.767884  0.219088      pass
19  0.860675  0.838772  0.647993  0.837336  0.972789  0.264207      pass

BARINEL SCORES

         cx 5       h 0     cx 1      cx 2     ccx 4      cx 3
sum  0.582322  0.548052  0.54792  0.545603  0.539384  0.534027

TARANTULA SCORES

         cx 5       h 0     cx 1      cx 2     ccx 4      cx 3
sum  0.582322  0.548052  0.54792  0.545603  0.539384  0.534027

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_y_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.16it/s]
100%|██████████| 10/10 [00:01<00:00,  9.83it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       y 0 pass/fail
0   0.845565  0.961816  0.720396  0.799635  0.196026  0.244146      fail
1   0.976263  0.832750  1.090004  1.090668  0.217374  0.206888      fail
2   0.673775  0.589523  0.614655  0.670396  0.222745  0.195106      fail
3   0.953768  0.959144  0.731672  1.037392  0.249825  0.275776      fail
4   0.979467  1.300411  1.646855  1.738693  0.437733  0.316162      fail
5   1.061538  1.143508  1.538201  1.593785  0.427683  0.292355      fail
6   1.017903  0.922793  1.170776  1.157720  0.245601  0.279062      fail
7   1.049319  0.879152  1.031902  1.127895  0.315679  0.239588      fail
8   0.964120  1.106095  1.314919  1.419325  0.364288  0.294270      fail
9   1.058626  1.175777  1.319939  1.189159  0.261849  0.269265      fail
10  1.058454  0.703400  1.012903  0.604550  0.250728  0.172330      pass
11  0.957810  0.928830  1.354613  1.484924  0.395910  0.236667      pass
12  0.893790  0.890757  1.013563  0.828622  0.259972  0.176750      pass
13  1.024871  0.918113  1.056006  1.008544  0.314390  0.215029      pass
14  1.205347  1.302197  1.472668  1.340911  0.464382  0.314928      pass
15  0.839650  0.806415  1.091040  1.370472  0.330167  0.249811      pass
16  0.960552  1.068461  1.410436  1.708173  0.411905  0.289870      pass
17  0.338095  0.284348  0.361136  0.415697  0.110388  0.083313      pass
18  1.065047  0.737058  1.066944  1.392139  0.387248  0.209468      pass
19  0.754388  0.836740  0.936227  1.246530  0.333969  0.166717      pass

BARINEL SCORES

          y 0      cx 4      cx 5      cx 3     cx 2       h 1
sum  0.552642  0.538007  0.512912  0.509196  0.50913  0.474164

TARANTULA SCORES

          y 0      cx 4      cx 5      cx 3     cx 2       h 1
sum  0.552642  0.538007  0.512912  0.509196  0.50913  0.474164

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_h_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.95it/s]
100%|██████████| 10/10 [00:01<00:00,  9.40it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       h 0 pass/fail
0   0.837017  0.838037  1.024572  0.697688  0.207343  0.472819      fail
1   1.223971  1.034429  1.322706  1.291866  0.332681  0.586020      fail
2   0.915388  0.998608  1.108189  0.995655  0.325087  0.493604      fail
3   1.191635  0.903030  1.287941  1.560887  0.339886  0.583343      fail
4   1.203539  0.999876  1.191593  1.283017  0.296334  0.572760      fail
5   0.823584  0.967127  1.043040  1.221750  0.274773  0.522426      fail
6   1.018760  0.782194  1.186498  1.300852  0.294102  0.425244      fail
7   1.065590  1.014544  1.145061  0.689352  0.213343  0.564488      fail
8   0.963806  0.822048  0.926610  0.798352  0.228845  0.496097      fail
9   0.684735  0.827973  1.080693  1.054666  0.240888  0.453206      fail
10  0.900715  0.842021  0.770653  0.706068  0.282640  0.381781      pass
11  0.970361  1.179809  1.398058  1.715998  0.360604  0.562575      pass
12  0.963272  0.712596  1.301907  1.588316  0.328067  0.612270      pass
13  0.885100  0.339194  0.628879  0.786975  0.240052  0.372440      pass
14  0.965269  0.540822  0.883225  1.048806  0.236833  0.380401      pass
15  0.930035  1.002216  1.457407  1.478546  0.403481  0.663473      pass
16  0.873975  0.752642  1.066696  1.144696  0.355305  0.551965      pass
17  0.865763  0.690777  1.044670  1.177409  0.344790  0.429385      pass
18  0.696605  0.700604  0.658198  0.845217  0.293221  0.448181      pass
19  1.118391  1.210952  1.289816  1.586319  0.407747  0.586809      pass

BARINEL SCORES

         cx 4     cx 5      cx 3       h 0      cx 2      h 1
sum  0.535439  0.51986  0.518733  0.508895  0.474224  0.45842

TARANTULA SCORES

         cx 4     cx 5      cx 3       h 0      cx 2      h 1
sum  0.535439  0.51986  0.518733  0.508895  0.474224  0.45842

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_rxx_inGap_4_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.49it/s]
100%|██████████| 10/10 [00:00<00:00, 11.46it/s]

        cx 5      cx 4     rxx 3      cx 2      cx 1       h 0 pass/fail
0   1.012065  0.913216  1.184102  1.446581  1.550710  0.484672      fail
1   0.880449  0.786248  0.949444  1.268965  1.391639  0.398561      fail
2   0.788524  0.976997  0.832702  1.161498  1.223026  0.348717      fail
3   0.849685  0.474443  1.142259  0.868072  0.918568  0.306468      fail
4   0.903586  0.759625  0.991603  1.224843  1.352164  0.449389      fail
5   1.014319  0.582015  1.165230  0.964139  1.512618  0.455725      fail
6   1.046229  0.550707  1.116365  0.845067  1.048513  0.395828      fail
7   0.838072  0.494141  1.124743  0.658274  0.992950  0.353879      fail
8   1.016508  0.851465  1.237909  1.245994  1.532059  0.455846      fail
9   1.045059  0.791626  1.493303  1.179998  1.497018  0.426008      fail
10  0.803036  0.703562  0.639181  1.029196  1.084297  0.334690      pass
11  0.883767  0.915953  1.007130  1.139567  1.377455  0.421208      pass
12  0.840850  0.502904  1.034535  0.915667  1.123754  0.401888      pass
13  1.110115  1.216523  0.894570  1.451366  1.581341  0.544303      pass
14  0.767226  0.779226  0.829766  0.885122  0.905432  0.375218      pass
15  0.764063  0.445887  0.880859  0.845210  0.804531  0.364234      pass
16  0.924632  1.215185  0.859231  1.319820  1.396038  0.492332      pass
17  1.035796  1.326059  1.008175  1.448313  1.576914  0.438812      pass
18  0.582352  0.622743  0.635513  0.613665  0.753642  0.205033      pass
19  0.734343  0.676305  1.011853  1.124710  1.170035  0.408407      pass

BARINEL SCORES

        rxx 3      cx 5      cx 1       h 0      cx 2      cx 4
sum  0.560804  0.526577  0.525125  0.505518  0.502098  0.460735

TARANTULA SCORES

        rxx 3      cx 5      cx 1       h 0      cx 2      cx 4
sum  0.560804  0.526577  0.525125  0.505518  0.502098  0.460735

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_y_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.94it/s]
100%|██████████| 10/10 [00:01<00:00,  9.52it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       y 0 pass/fail
0   1.268294  0.866754  1.011482  1.119920  0.273725  0.307298      fail
1   0.961763  0.517520  0.649564  0.811738  0.227505  0.208744      fail
2   1.455661  1.204376  1.552082  1.722490  0.429476  0.365000      fail
3   1.039410  0.825320  0.936821  0.845405  0.174195  0.248601      fail
4   1.027554  0.646920  0.841237  0.843770  0.206584  0.233266      fail
5   1.141118  1.072643  1.494710  1.653072  0.443510  0.287482      fail
6   1.237381  1.144751  1.294547  1.439011  0.328603  0.323756      fail
7   0.994403  0.632234  0.935105  0.812355  0.210161  0.229300      fail
8   1.016112  0.669774  0.809729  0.760212  0.208470  0.251756      fail
9   1.118574  0.773333  0.831614  1.047220  0.214815  0.277740      fail
10  0.881718  0.931436  1.391164  1.497010  0.351462  0.221973      pass
11  0.983252  0.760057  0.947991  1.127555  0.356125  0.229153      pass
12  0.556724  0.357449  0.567210  0.413072  0.111709  0.132385      pass
13  0.990636  1.073530  1.202264  1.410551  0.357580  0.280901      pass
14  0.569846  0.528191  0.767856  0.757107  0.240101  0.129185      pass
15  0.489356  0.530561  0.749960  0.911198  0.262358  0.131078      pass
16  1.365073  1.047104  1.077628  1.536185  0.375314  0.320445      pass
17  0.997950  1.271767  1.376941  1.534813  0.419895  0.262851      pass
18  0.898474  1.013931  1.415220  1.328097  0.396605  0.196850      pass
19  0.898373  0.842682  0.973228  1.230576  0.393007  0.218669      pass

BARINEL SCORES

        cx 5       y 0      cx 4      cx 3      cx 2       h 1
sum  0.56608  0.562747  0.499908  0.497297  0.484848  0.454264

TARANTULA SCORES

        cx 5       y 0      cx 4      cx 3      cx 2       h 1
sum  0.56608  0.562747  0.499908  0.497297  0.484848  0.454264

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_cx_inGap_5_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.80it/s]
100%|██████████| 10/10 [00:00<00:00, 11.99it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.284114  0.115046  0.869029  0.568854  0.738700  0.232525      fail
1   1.298312  0.116134  0.875808  0.696364  0.782693  0.267141      fail
2   1.039652  0.092682  0.775794  0.631174  0.679389  0.224601      fail
3   0.949671  0.083597  0.673200  0.895833  1.090619  0.315978      fail
4   1.127861  0.101106  0.955240  0.830842  1.080560  0.260250      fail
5   1.153998  0.104321  0.804007  0.983153  1.159891  0.326119      fail
6   0.974934  0.086888  0.589267  0.584067  0.703995  0.235262      fail
7   1.139731  0.102551  0.957423  0.950683  1.174583  0.307274      fail
8   1.104858  0.100882  0.867249  0.620595  0.791228  0.253651      fail
9   1.085530  0.098497  0.787933  0.666581  0.837265  0.281858      fail
10  0.911646  0.081981  0.612681  0.606821  0.856587  0.254473      pass
11  0.448236  0.039285  0.454879  0.450506  0.615766  0.199547      pass
12  0.643345  0.056714  0.579026  0.614522  0.785720  0.231869      pass
13  0.979904  0.087350  0.839870  0.959510  1.366666  0.309506      pass
14  0.660593  0.059385  0.723264  0.521641  0.629561  0.163187      pass
15  1.045153  0.093215  0.817092  0.669733  0.913959  0.218943      pass
16  1.090781  0.097665  0.784104  0.874654  1.030147  0.335568      pass
17  1.365764  0.120953  0.685562  0.817347  0.963558  0.321085      pass
18  0.872491  0.078592  0.690177  0.345037  0.455154  0.212925      pass
19  1.031026  0.093171  0.713580  0.775014  0.961799  0.261555      pass

BARINEL SCORES

         cx 4      cx 5     cx 3      cx 2       h 0      cx 1
sum  0.553423  0.552201  0.54167  0.528208  0.518798  0.513055

TARANTULA SCORES

         cx 4      cx 5     cx 3      cx 2       h 0      cx 1
sum  0.553423  0.552201  0.54167  0.528208  0.518798  0.513055

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_h_inGap_10_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.88it/s]
100%|██████████| 10/10 [00:00<00:00, 11.60it/s]

         h 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.761632  0.758486  0.733477  0.841272  1.433246  0.437585      fail
1   0.539434  0.979845  1.130563  1.141476  1.446088  0.410540      fail
2   0.662011  1.220095  1.113986  1.341495  2.116628  0.599459      fail
3   0.678366  1.032793  0.823248  0.856904  1.137142  0.367088      fail
4   0.607894  0.857498  0.944523  1.140477  1.494009  0.450715      fail
5   0.598095  0.968665  0.929620  1.047700  1.528164  0.458516      fail
6   0.560941  1.169011  0.811437  0.933321  1.127635  0.354777      fail
7   0.611907  1.340917  0.923447  1.278480  1.857175  0.546301      fail
8   0.554074  1.083290  0.925228  1.329698  1.930928  0.535655      fail
9   0.636597  1.008941  1.130886  1.531916  1.777612  0.540603      fail
10  0.421488  0.948467  1.044842  1.035695  1.884624  0.508678      pass
11  0.422733  0.643110  0.885647  1.079403  1.294983  0.396648      pass
12  0.638925  0.839036  0.936426  1.127680  1.449251  0.442379      pass
13  0.428191  0.674967  0.723146  0.969699  1.467632  0.422322      pass
14  0.562318  0.917430  1.005114  1.456274  1.771550  0.532800      pass
15  0.542785  0.782907  0.575172  0.833400  1.350190  0.373028      pass
16  0.312145  0.693264  0.589815  0.672874  1.160374  0.349488      pass
17  0.658966  1.147832  0.667479  0.707534  1.225815  0.395746      pass
18  0.347067  0.863210  0.738539  1.022757  1.362389  0.388361      pass
19  0.322809  1.112465  0.999301  1.107199  1.699910  0.445800      pass

BARINEL SCORES

         h 5      cx 4      cx 3     cx 2       h 0      cx 1
sum  0.57147  0.547181  0.536892  0.53333  0.524898  0.519366

TARANTULA SCORES

         h 5      cx 4      cx 3     cx 2       h 0      cx 1
sum  0.57147  0.547181  0.536892  0.53333  0.524898  0.519366

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_sx_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.46it/s]
100%|██████████| 10/10 [00:00<00:00, 11.36it/s]

      sxdg 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.046611  1.315267  1.232183  1.379487  1.521990  0.409634      fail
1   0.871982  1.075899  0.758288  0.812387  0.857584  0.250612      fail
2   0.995690  1.234886  0.964714  0.939794  1.297732  0.336513      fail
3   1.426338  1.742649  1.257476  1.317020  1.655023  0.506136      fail
4   1.204284  1.416418  1.217714  1.390659  1.592197  0.411237      fail
5   0.975117  1.154998  0.814293  0.880887  0.988472  0.292367      fail
6   0.920534  1.192897  0.844369  1.216965  1.367519  0.299290      fail
7   0.771117  0.967063  0.809442  1.006622  1.160677  0.246015      fail
8   0.871136  1.030999  0.663621  0.609521  0.771434  0.273423      fail
9   1.133271  1.400824  0.899529  1.090557  1.139580  0.376658      fail
10  0.672603  0.754187  0.937774  0.903093  1.121869  0.274785      pass
11  0.885329  1.004876  0.835197  0.695684  0.942827  0.306645      pass
12  0.887527  1.151087  1.067422  1.204988  1.189011  0.303814      pass
13  0.974863  1.153368  0.947154  1.108964  1.181035  0.375507      pass
14  1.107083  1.414433  1.060127  0.982575  1.191028  0.406322      pass
15  0.781330  0.957206  0.931606  1.296754  1.392579  0.412278      pass
16  0.648222  0.820905  0.376593  0.422632  0.587114  0.293950      pass
17  0.988429  1.264181  0.920416  1.217606  1.269078  0.392600      pass
18  0.690328  0.818288  0.744511  0.895050  0.767823  0.301704      pass
19  0.753055  0.892755  0.669024  0.644143  0.771384  0.335189      pass

BARINEL SCORES

         cx 4    sxdg 5      cx 1      cx 2      cx 3       h 0
sum  0.550534  0.549108  0.542574  0.531786  0.527068  0.499933

TARANTULA SCORES

         cx 4    sxdg 5      cx 1      cx 2      cx 3       h 0
sum  0.550534  0.549108  0.542574  0.531786  0.527068  0.499933

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ccx_inGap_8_.qasm

100%|██████████| 10/10 [00:03<00:00,  3.21it/s]
100%|██████████| 10/10 [00:03<00:00,  3.31it/s]

       ccx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.801550  1.128466  1.201622  1.191296  0.921399  0.320290      fail
1   1.492314  0.975650  0.962559  0.776986  0.659305  0.225677      fail
2   1.298580  0.602463  0.780561  0.677363  0.515588  0.221495      fail
3   1.290126  0.614613  0.874213  0.762424  0.692196  0.262367      fail
4   1.315250  0.875449  0.717144  0.477297  0.433851  0.200356      fail
5   1.229706  0.833269  0.832597  0.810551  0.724740  0.239630      fail
6   1.323409  0.956492  1.225206  1.042690  0.877923  0.283168      fail
7   1.527664  0.664012  1.093184  1.082359  0.859055  0.295922      fail
8   1.435178  0.942576  0.984897  0.830620  0.748979  0.262204      fail
9   1.632137  0.781537  0.960831  0.847998  0.743101  0.252543      fail
10  0.821443  0.553993  0.626758  0.649827  0.467323  0.171162      pass
11  1.641214  0.824803  1.144727  0.994071  0.944000  0.311015      pass
12  1.384570  0.862321  0.951481  0.764922  0.755296  0.274297      pass
13  1.507568  0.749959  1.048218  0.728484  0.741085  0.256653      pass
14  1.514630  0.928493  1.018254  0.763015  0.744803  0.209218      pass
15  1.102053  0.767172  0.774047  0.610934  0.485886  0.176813      pass
16  1.607414  0.938201  1.112686  1.042122  0.869656  0.314216      pass
17  0.969564  0.588062  0.727143  0.431371  0.375724  0.158753      pass
18  1.574522  0.925043  0.995355  0.732001  0.823899  0.289717      pass
19  1.455456  0.974021  0.973101  0.595028  0.702943  0.240330      pass

BARINEL SCORES

         cx 2       h 0     ccx 5      cx 1     cx 4      cx 3
sum  0.537562  0.516259  0.513742  0.509424  0.50796  0.506868

TARANTULA SCORES

         cx 2       h 0     ccx 5      cx 1     cx 4      cx 3
sum  0.537562  0.516259  0.513742  0.509424  0.50796  0.506868

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ccx_inGap_9_.qasm

100%|██████████| 10/10 [00:02<00:00,  3.44it/s]
100%|██████████| 10/10 [00:02<00:00,  3.56it/s]

       ccx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.784773  0.913181  0.898438  1.210616  1.082686  0.330469      fail
1   1.464498  0.669596  0.393756  0.574604  0.402552  0.177536      fail
2   1.653379  0.991808  0.827597  0.954607  0.611092  0.275227      fail
3   1.406615  0.907285  0.638548  0.715282  0.428378  0.217251      fail
4   1.632636  1.176111  1.032829  1.274283  1.053828  0.314454      fail
5   1.758213  1.077009  0.807511  1.089238  0.790124  0.310785      fail
6   1.441715  0.651639  0.491623  0.609562  0.374157  0.196326      fail
7   1.856043  1.250205  0.892932  1.175553  0.941386  0.348570      fail
8   1.816586  0.819488  0.847376  1.144347  0.943015  0.333077      fail
9   1.572686  0.850953  0.896767  1.102729  0.883751  0.276044      fail
10  1.688095  0.890090  0.698450  0.976332  0.711397  0.271589      pass
11  1.781147  1.237369  1.028656  1.260779  1.062768  0.358756      pass
12  1.479957  0.875402  0.443607  0.652885  0.488955  0.242266      pass
13  1.637605  0.895779  0.606559  0.815230  0.518033  0.252737      pass
14  2.004003  1.270610  1.034913  1.200786  0.953924  0.380356      pass
15  1.314535  0.790285  0.552910  0.872367  0.745204  0.266325      pass
16  1.605172  0.907037  0.853837  1.064354  0.917448  0.312225      pass
17  1.607267  0.835565  0.701331  1.009037  0.841319  0.286259      pass
18  1.471551  0.915829  0.707543  0.888342  0.769400  0.270855      pass
19  1.400035  0.636425  0.615016  0.759292  0.659373  0.239575      pass

BARINEL SCORES

         cx 3     cx 2     ccx 5      cx 4      cx 1       h 0
sum  0.516184  0.50908  0.506143  0.501425  0.494833  0.491061

TARANTULA SCORES

         cx 3     cx 2     ccx 5      cx 4      cx 1       h 0
sum  0.516184  0.50908  0.506143  0.501425  0.494833  0.491061

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cx_inGap_10_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.32it/s]
100%|██████████| 10/10 [00:00<00:00, 10.03it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.020596  0.968142  0.503244  0.559469  0.693272  0.170384      fail
1   0.931692  0.782889  0.435297  0.379683  0.441845  0.153828      fail
2   1.306652  0.626432  0.510449  0.639116  0.512401  0.150648      fail
3   1.184872  0.961177  1.044833  0.832814  0.847140  0.321734      fail
4   1.103785  0.870430  1.085088  1.011258  0.999162  0.233407      fail
5   0.789935  1.028812  0.929823  0.831326  0.834499  0.278898      fail
6   0.973141  0.950850  0.925195  0.852259  0.827484  0.258095      fail
7   1.207861  1.072620  0.962896  0.937550  0.796636  0.264124      fail
8   0.848127  0.684363  0.256231  0.409578  0.578058  0.185238      fail
9   1.023182  0.748043  0.858882  0.752114  0.675511  0.202483      fail
10  0.383115  0.308758  0.509581  0.380256  0.322176  0.121465      pass
11  0.847155  0.890675  0.852251  0.550301  0.383102  0.217453      pass
12  0.752838  0.228252  0.565650  0.537979  0.525020  0.201841      pass
13  0.852429  0.761608  0.805234  0.769119  0.933196  0.278349      pass
14  0.671357  0.625517  0.515358  0.388024  0.481165  0.154371      pass
15  0.774728  0.988110  1.070332  1.070150  0.992186  0.246836      pass
16  0.729616  0.484760  0.614961  0.617964  0.717596  0.256693      pass
17  0.840233  0.774994  0.690049  0.790227  0.909330  0.245610      pass
18  0.952402  0.693825  0.695243  0.675702  0.436067  0.197224      pass
19  0.399162  0.231531  0.207107  0.306934  0.369994  0.092558      pass

BARINEL SCORES

         cx 4      cx 5      cx 1      cx 2      cx 3       h 0
sum  0.592146  0.590571  0.542791  0.542075  0.535126  0.524395

TARANTULA SCORES

         cx 4      cx 5      cx 1      cx 2      cx 3       h 0
sum  0.592146  0.590571  0.542791  0.542075  0.535126  0.524395

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_swap_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  7.61it/s]
100%|██████████| 10/10 [00:01<00:00,  8.87it/s]

        cx 5    swap 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.754807  0.625015  0.826421  0.759146  0.941873  0.318419      fail
1   0.872113  0.451434  0.939325  0.785367  1.212218  0.362944      fail
2   1.083227  0.477963  1.018572  1.007011  1.046597  0.360885      fail
3   1.051023  0.402344  1.006116  0.835050  0.944183  0.294852      fail
4   0.870411  0.443182  0.996070  0.847144  0.821443  0.291037      fail
5   0.972754  0.540072  1.110065  0.751074  0.733635  0.278668      fail
6   0.963459  0.563351  1.306665  1.009241  0.957294  0.319433      fail
7   1.002415  0.479985  0.948303  0.924875  1.118351  0.295781      fail
8   0.830435  0.491322  0.612240  0.630818  0.694281  0.257890      fail
9   0.949963  0.511732  1.027560  0.938442  1.290580  0.338278      fail
10  0.872276  0.341972  1.087680  0.559825  0.698033  0.193502      pass
11  0.506103  0.296664  0.429080  0.491066  0.366930  0.222759      pass
12  0.890739  0.287991  0.605131  0.817308  1.133136  0.339356      pass
13  0.806527  0.394568  0.676253  0.965753  1.213192  0.227099      pass
14  0.829514  0.307133  0.617907  0.637587  0.830136  0.258964      pass
15  0.564348  0.402851  0.352960  0.550870  0.617572  0.165773      pass
16  0.762416  0.276077  0.589656  0.634950  0.842117  0.219579      pass
17  1.073618  0.321541  0.789973  0.907209  0.978762  0.216827      pass
18  0.591570  0.310283  0.726415  0.473381  0.613745  0.216211      pass
19  0.692256  0.317700  1.096378  0.480104  0.374532  0.174493      pass

BARINEL SCORES

       swap 4      cx 3       h 0      cx 2      cx 1      cx 5
sum  0.604912  0.584112  0.582539  0.565643  0.560025  0.551985

TARANTULA SCORES

       swap 4      cx 3       h 0      cx 2      cx 1      cx 5
sum  0.604912  0.584112  0.582539  0.565643  0.560025  0.551985

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_x_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.94it/s]
100%|██████████| 10/10 [00:00<00:00, 12.38it/s]

         x 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.606009  1.382902  0.875193  0.999536  1.089405  0.303873      fail
1   0.334549  0.864352  0.905265  1.038797  1.250947  0.282168      fail
2   0.419464  0.947494  0.433973  0.455979  0.487557  0.171909      fail
3   0.538800  1.273885  0.934256  1.317925  1.436726  0.362737      fail
4   0.507666  1.181921  0.939394  0.965874  0.823987  0.255233      fail
5   0.448162  1.092178  0.979009  1.228710  1.524878  0.371782      fail
6   0.534470  1.235163  1.098639  1.207807  1.274239  0.293698      fail
7   0.409088  0.971151  0.854993  0.982875  1.251726  0.305795      fail
8   0.403159  0.925006  0.671019  0.774225  0.633420  0.179980      fail
9   0.367904  0.867518  0.951318  1.313115  1.278003  0.291262      fail
10  0.349222  0.856029  0.884725  0.878410  1.062426  0.323674      pass
11  0.373049  0.934861  1.055760  1.203843  1.283308  0.413208      pass
12  0.262019  0.614123  0.561824  0.616796  0.825342  0.212510      pass
13  0.401962  0.946458  0.837388  1.098463  1.326204  0.413831      pass
14  0.435204  1.050987  0.754061  1.080011  1.413080  0.308294      pass
15  0.345117  0.818159  0.656704  0.878900  1.123674  0.345474      pass
16  0.311763  0.676507  0.526741  0.523271  0.780733  0.212387      pass
17  0.469465  1.145007  1.511132  1.754979  2.103666  0.472398      pass
18  0.431537  1.016521  0.831516  0.860541  0.955163  0.155907      pass
19  0.403538  0.943549  1.290214  1.294288  1.230077  0.311654      pass

BARINEL SCORES

          x 5      cx 4      cx 2      cx 3      cx 1       h 0
sum  0.547078  0.544049  0.502328  0.492394  0.477266  0.470699

TARANTULA SCORES

          x 5      cx 4      cx 2      cx 3      cx 1       h 0
sum  0.547078  0.544049  0.502328  0.492394  0.477266  0.470699

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ry_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.13it/s]
100%|██████████| 10/10 [00:01<00:00,  9.55it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      ry 0 pass/fail
0   1.032367  1.039401  1.304299  1.424835  0.310580  0.826536      fail
1   0.871639  0.789342  0.921609  0.829810  0.267621  0.615130      fail
2   0.736035  0.726310  0.817269  0.806895  0.181344  0.642115      fail
3   1.035386  0.989920  1.054476  0.817561  0.210158  0.712571      fail
4   1.024347  1.172936  1.397223  1.273241  0.389810  0.824241      fail
5   1.018756  0.958810  1.040434  0.884532  0.200996  0.689630      fail
6   1.039396  1.161296  1.388470  1.291627  0.380216  0.881650      fail
7   0.930608  1.149027  1.182278  1.268508  0.300901  0.759030      fail
8   0.712205  0.702908  0.960012  1.130439  0.245152  0.652590      fail
9   1.302837  1.490307  1.743803  1.894834  0.402277  1.063500      fail
10  0.441814  0.394170  0.308968  0.279765  0.113933  0.269222      pass
11  0.687052  0.402646  0.461634  0.563648  0.175314  0.363660      pass
12  0.818571  0.625995  0.793932  0.973346  0.350155  0.490927      pass
13  0.891851  0.854488  0.941248  0.673517  0.251489  0.766113      pass
14  1.037488  0.751627  0.935028  0.922611  0.229570  0.662820      pass
15  0.724158  0.808247  1.037084  1.210596  0.371768  0.611809      pass
16  0.923209  0.702422  0.864911  0.923530  0.357256  0.695511      pass
17  0.717920  0.762917  0.680802  0.992397  0.287870  0.479696      pass
18  0.668620  0.464851  0.753904  1.050589  0.259042  0.426958      pass
19  0.618464  0.503439  0.782576  0.793586  0.211989  0.619068      pass

BARINEL SCORES

         cx 4    cx 3      ry 0      cx 2     cx 5       h 1
sum  0.618821  0.6097  0.587384  0.580944  0.56309  0.525527

TARANTULA SCORES

         cx 4    cx 3      ry 0      cx 2     cx 5       h 1
sum  0.618821  0.6097  0.587384  0.580944  0.56309  0.525527

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_h_inGap_1_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.95it/s]
100%|██████████| 10/10 [00:01<00:00, 10.00it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       h 0 pass/fail
0   0.948072  1.079619  1.280289  1.440149  0.401081  0.355159      fail
1   0.842001  0.894684  0.887129  1.078183  0.392911  0.329108      fail
2   0.798450  0.920339  1.204081  1.480444  0.424736  0.400133      fail
3   0.947323  0.915104  0.971045  1.049009  0.360205  0.310660      fail
4   0.968474  0.732868  0.906303  0.732859  0.222627  0.156543      fail
5   0.879946  0.965552  1.071716  1.422270  0.365974  0.355365      fail
6   0.727595  0.449986  0.484231  0.629322  0.256351  0.136714      fail
7   1.091861  0.914961  1.229649  1.372717  0.410468  0.346234      fail
8   0.780006  0.909445  1.137390  1.308652  0.419634  0.350903      fail
9   1.021861  0.869159  1.185888  1.260245  0.370877  0.329650      fail
10  0.840447  0.761110  1.002805  1.061577  0.293999  0.297786      pass
11  0.776266  0.580299  0.616941  0.657050  0.160349  0.083806      pass
12  0.437221  0.550150  0.551517  0.656069  0.155126  0.119128      pass
13  0.821548  0.344077  0.382545  0.508430  0.206529  0.101997      pass
14  0.908223  0.570358  0.720780  0.825135  0.259959  0.177024      pass
15  0.882870  0.814824  0.788900  1.096196  0.314693  0.303010      pass
16  0.636935  0.531074  0.729210  0.653248  0.163444  0.142275      pass
17  0.716856  0.509793  0.467512  0.474086  0.196151  0.074022      pass
18  1.007828  0.705326  1.045002  1.295948  0.380575  0.345488      pass
19  0.859087  1.101106  1.351684  1.524037  0.399858  0.396698      pass

BARINEL SCORES

          h 0       h 1      cx 3      cx 2     cx 4    cx 5
sum  0.600674  0.588878  0.574962  0.573617  0.57221  0.5331

TARANTULA SCORES

          h 0       h 1      cx 3      cx 2     cx 4    cx 5
sum  0.600674  0.588878  0.574962  0.573617  0.57221  0.5331

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_h_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.73it/s]
100%|██████████| 10/10 [00:00<00:00, 12.06it/s]

         h 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.599927  0.940244  1.664660  1.107119  1.561758  0.646989      fail
1   0.735745  1.278632  2.024513  1.361595  1.770856  0.651483      fail
2   0.556372  1.024791  1.853251  1.630655  1.724629  0.676818      fail
3   0.654821  1.260238  2.024364  1.849101  1.859191  0.684274      fail
4   0.591874  0.926211  1.790331  1.134981  1.060327  0.453653      fail
5   0.563371  1.061040  1.857882  1.893078  2.200863  0.782994      fail
6   0.543236  0.565603  1.332113  0.890188  1.145677  0.508844      fail
7   0.654695  1.373132  2.180349  1.718035  1.715722  0.679578      fail
8   0.630339  1.275383  1.965181  1.260961  1.318688  0.626270      fail
9   0.603588  1.149518  1.881486  1.570947  1.591066  0.687362      fail
10  0.354986  0.620847  1.571844  1.349876  1.576076  0.413550      pass
11  0.644964  1.396695  2.070901  1.684663  1.576800  0.641552      pass
12  0.532957  0.672343  1.293009  1.166874  1.291083  0.470331      pass
13  0.616129  1.396197  1.986812  1.677742  1.747342  0.611933      pass
14  0.253542  0.724809  1.162034  1.243031  1.239626  0.450023      pass
15  0.545508  0.714010  1.619733  1.117644  1.000255  0.428982      pass
16  0.655058  1.031446  1.845065  1.573562  1.615845  0.607498      pass
17  0.343094  0.718912  1.505332  1.522968  1.527403  0.291483      pass
18  0.450080  0.739209  1.576081  1.446151  1.486576  0.387272      pass
19  0.540506  1.038057  2.079993  1.697611  1.892291  0.632415      pass

BARINEL SCORES

          h 0       h 5      cx 4      cx 3      cx 1      cx 2
sum  0.564554  0.554068  0.545266  0.526404  0.516107  0.498902

TARANTULA SCORES

          h 0       h 5      cx 4      cx 3      cx 1      cx 2
sum  0.564554  0.554068  0.545266  0.526404  0.516107  0.498902

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rx_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.92it/s]
100%|██████████| 10/10 [00:01<00:00,  9.86it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      rx 0 pass/fail
0   0.947706  1.277407  1.529263  1.699013  0.369404  0.768169      fail
1   0.900492  1.007381  1.035143  0.821040  0.196149  0.694788      fail
2   0.887238  0.964619  1.214025  1.217947  0.289807  0.634391      fail
3   1.067659  0.837711  1.152399  1.523291  0.337358  0.739533      fail
4   0.800382  1.035751  1.101917  1.152791  0.262535  0.743524      fail
5   1.017341  1.086438  1.191429  1.397961  0.349196  0.844338      fail
6   0.915514  0.890117  0.788619  0.734913  0.196899  0.693098      fail
7   1.179900  1.178162  1.521162  1.373971  0.399121  0.756897      fail
8   0.914464  0.911144  0.950700  0.974454  0.249719  0.697030      fail
9   0.759144  0.882958  0.814615  0.867326  0.231294  0.652834      fail
10  1.048558  0.589614  0.857538  1.022448  0.262060  0.613378      pass
11  0.882770  1.017540  1.445434  1.349525  0.362366  0.749984      pass
12  0.497019  0.901366  0.967323  0.925953  0.234515  0.629447      pass
13  0.819133  0.968868  0.916450  1.101883  0.332791  0.587194      pass
14  0.615866  0.335399  0.346458  0.462786  0.169220  0.338727      pass
15  0.612801  0.608849  0.952716  0.885443  0.309539  0.449850      pass
16  1.037324  0.447878  0.601643  0.911942  0.283395  0.514673      pass
17  0.797322  0.584372  0.443099  0.624227  0.229976  0.481731      pass
18  0.941161  0.952659  1.393356  1.450322  0.327527  0.564046      pass
19  0.634921  0.467265  0.448454  0.544624  0.174211  0.292309      pass

BARINEL SCORES

         cx 4      rx 0      cx 3      cx 2      cx 5       h 1
sum  0.594358  0.580479  0.574391  0.559015  0.543497  0.517593

TARANTULA SCORES

         cx 4      rx 0      cx 3      cx 2      cx 5       h 1
sum  0.594358  0.580479  0.574391  0.559015  0.543497  0.517593

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_y_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.84it/s]
100%|██████████| 10/10 [00:00<00:00, 12.87it/s]

         y 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.469724  1.051119  0.795656  0.783881  0.868596  0.214400      fail
1   0.660229  1.119076  0.448321  0.695919  0.857717  0.259743      fail
2   0.394992  0.775642  0.709758  0.549564  0.444973  0.154862      fail
3   0.375401  0.898381  0.885935  1.189998  1.344882  0.291863      fail
4   0.443480  0.717414  0.710521  0.965512  1.219844  0.324568      fail
5   0.480503  0.586412  0.581489  0.681108  0.772504  0.238191      fail
6   0.348590  0.825387  0.954438  0.878016  1.085992  0.289979      fail
7   0.540978  1.170011  0.998358  1.194912  1.245779  0.362329      fail
8   0.580978  1.022371  1.205522  1.281598  1.497471  0.396820      fail
9   0.522780  1.005132  1.110917  1.410244  1.479974  0.471644      fail
10  0.348656  0.931093  1.373202  1.502256  1.653021  0.435991      pass
11  0.454899  0.812369  0.584049  0.686443  0.880980  0.304558      pass
12  0.261954  0.400652  0.553843  0.663366  0.580635  0.152755      pass
13  0.375612  0.579236  0.918068  1.081880  0.927616  0.212268      pass
14  0.322292  0.914469  0.919465  0.923377  1.258135  0.325859      pass
15  0.433660  0.769313  0.498168  0.644926  0.426745  0.164750      pass
16  0.392668  0.788363  0.268020  0.617154  0.761364  0.173115      pass
17  0.435919  0.783922  0.733518  1.010709  1.237567  0.414809      pass
18  0.451102  1.177549  0.612816  0.776546  0.844471  0.262189      pass
19  0.434484  0.654898  1.005825  1.162023  1.119765  0.438515      pass

BARINEL SCORES

         y 5      cx 4      cx 3      cx 1      cx 2       h 0
sum  0.55192  0.540013  0.529429  0.527488  0.515029  0.510153

TARANTULA SCORES

         y 5      cx 4      cx 3      cx 1      cx 2       h 0
sum  0.55192  0.540013  0.529429  0.527488  0.515029  0.510153

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rxx_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.49it/s]
100%|██████████| 10/10 [00:00<00:00, 10.88it/s]

        cx 5      cx 4      cx 3     rxx 2      cx 1       h 0 pass/fail
0   1.071550  0.859631  0.744029  0.269923  0.961290  0.262541      fail
1   1.041168  1.212201  1.522972  0.256389  1.576049  0.413608      fail
2   0.874441  0.981973  1.406793  0.203632  1.505812  0.289964      fail
3   1.073702  0.716157  0.876084  0.190543  0.924320  0.200423      fail
4   1.314687  1.241564  1.511455  0.320931  1.568664  0.400926      fail
5   0.919241  0.801718  0.899209  0.205620  0.872132  0.265227      fail
6   0.802669  0.634245  0.685200  0.258953  0.765998  0.260919      fail
7   1.140018  0.753576  0.968886  0.257266  0.920591  0.337144      fail
8   0.830210  0.707873  0.705276  0.239615  0.479565  0.185760      fail
9   0.757950  0.670354  0.786278  0.226245  0.638821  0.173906      fail
10  0.848744  0.780965  0.782116  0.212414  0.789958  0.244649      pass
11  0.838072  0.690135  1.030293  0.138869  1.251269  0.346564      pass
12  0.856921  0.774833  1.110238  0.195170  0.823332  0.266516      pass
13  1.270110  1.211446  1.597671  0.217402  1.913699  0.439089      pass
14  0.953251  0.801874  0.911091  0.153355  1.105125  0.281457      pass
15  0.649691  0.242422  0.565177  0.100783  0.490525  0.149045      pass
16  0.425445  0.394427  0.533699  0.082877  0.848223  0.206686      pass
17  0.798448  0.723101  0.924443  0.180221  0.755561  0.304182      pass
18  0.860521  0.648588  0.888959  0.146219  0.965752  0.262472      pass
19  0.401923  0.408278  0.477935  0.092396  0.595422  0.116037      pass

BARINEL SCORES

       rxx 2      cx 4     cx 5      cx 3      cx 1       h 0
sum  0.61515  0.562379  0.55422  0.533933  0.517071  0.516064

TARANTULA SCORES

       rxx 2      cx 4     cx 5      cx 3      cx 1       h 0
sum  0.61515  0.562379  0.55422  0.533933  0.517071  0.516064

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_h_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.43it/s]
100%|██████████| 10/10 [00:01<00:00,  9.44it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       h 0 pass/fail
0   1.042770  0.838228  0.698032  0.674389  0.250055  0.549333      fail
1   1.267158  0.393003  0.778118  1.119783  0.338624  0.662971      fail
2   1.146498  0.654239  0.770646  1.059077  0.235756  0.579603      fail
3   1.069685  0.643512  0.854269  0.890728  0.197857  0.548830      fail
4   1.095243  1.175141  1.382697  1.561912  0.421920  0.600451      fail
5   1.148886  1.102979  1.303663  1.232518  0.301749  0.641637      fail
6   1.001527  1.188869  1.401420  1.496529  0.339489  0.524172      fail
7   0.821049  0.632928  0.650338  0.757400  0.166793  0.414865      fail
8   1.310928  1.124959  1.510699  1.491329  0.375095  0.745168      fail
9   0.872192  0.728732  0.915472  0.911588  0.240428  0.498975      fail
10  0.582968  0.385484  0.416057  0.440482  0.162998  0.347222      pass
11  0.548558  0.219480  0.506000  0.568017  0.182727  0.253806      pass
12  1.001830  0.868699  0.838388  1.311936  0.371770  0.543959      pass
13  1.083755  1.060040  1.471294  1.623856  0.441092  0.639717      pass
14  0.901853  1.044563  1.064933  1.165933  0.323536  0.524059      pass
15  0.536435  0.429783  0.741175  0.893574  0.213689  0.333876      pass
16  1.229534  0.871401  1.187137  1.606791  0.373913  0.734337      pass
17  0.935607  0.889909  1.126930  1.152385  0.291372  0.548375      pass
18  0.705830  0.840787  1.173987  1.410474  0.332453  0.446968      pass
19  0.916987  1.011094  1.398578  1.536942  0.377183  0.545982      pass

BARINEL SCORES

         cx 5       h 0      cx 4      cx 3      cx 2       h 1
sum  0.560683  0.539671  0.526744  0.508442  0.488755  0.482911

TARANTULA SCORES

         cx 5       h 0      cx 4      cx 3      cx 2       h 1
sum  0.560683  0.539671  0.526744  0.508442  0.488755  0.482911

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_y_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.41it/s]
100%|██████████| 10/10 [00:01<00:00,  9.66it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       y 0 pass/fail
0   1.070943  0.895880  1.102641  0.764198  0.234465  0.212517      fail
1   0.892791  0.928164  1.151709  1.236293  0.388478  0.242896      fail
2   0.846674  0.972955  1.131189  1.108071  0.251971  0.284339      fail
3   0.925143  1.089156  1.346901  1.379678  0.372903  0.280834      fail
4   1.181624  1.097325  1.593975  1.657240  0.378453  0.334795      fail
5   1.075212  1.198933  1.424971  1.495677  0.355877  0.279167      fail
6   0.856206  1.041787  1.295586  1.107653  0.281980  0.231681      fail
7   0.826805  1.016398  1.348134  1.376808  0.284922  0.283540      fail
8   0.881384  1.222256  1.344388  1.123974  0.245058  0.280474      fail
9   0.972233  0.835431  1.288569  1.345468  0.318430  0.289540      fail
10  0.717126  0.561349  0.613636  0.681184  0.177690  0.130146      pass
11  0.977329  0.907485  1.330284  1.232196  0.378432  0.250113      pass
12  0.878212  0.910131  1.328403  1.613618  0.359369  0.240335      pass
13  1.003852  0.949326  1.382795  1.540393  0.402620  0.271576      pass
14  0.998772  0.895668  1.196488  1.358159  0.380848  0.232090      pass
15  0.819496  0.739761  0.964771  1.077150  0.352803  0.183305      pass
16  0.668758  0.484259  0.592371  0.918005  0.291794  0.131631      pass
17  0.894871  0.794500  1.054567  1.161995  0.383713  0.242476      pass
18  1.104651  0.928084  1.188941  1.338836  0.415519  0.272698      pass
19  0.796590  0.499496  0.455599  0.794371  0.213672  0.159149      pass

BARINEL SCORES

         cx 4     cx 3       y 0    cx 5      cx 2       h 1
sum  0.573135  0.56311  0.562717  0.5182  0.518081  0.481147

TARANTULA SCORES

         cx 4     cx 3       y 0    cx 5      cx 2       h 1
sum  0.573135  0.56311  0.562717  0.5182  0.518081  0.481147

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_x_inGap_10_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.10it/s]
100%|██████████| 10/10 [00:00<00:00, 12.62it/s]

         x 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.504579  0.874317  0.684451  1.023185  1.085651  0.269953      fail
1   0.457777  0.865632  0.919570  1.187439  1.287857  0.316466      fail
2   0.448485  1.025237  0.793952  1.054495  1.138801  0.261351      fail
3   0.383980  1.094964  0.923547  1.201639  1.469272  0.337453      fail
4   0.459593  1.148458  1.082300  1.436825  1.533649  0.339117      fail
5   0.443609  0.614441  0.326192  0.450044  0.440294  0.172432      fail
6   0.492418  0.926200  1.075709  0.993445  1.012988  0.242811      fail
7   0.434949  0.809482  0.614044  0.736475  0.733970  0.167206      fail
8   0.512885  0.685334  0.822414  0.884634  0.855066  0.223202      fail
9   0.363669  0.995621  0.624508  0.753703  1.062562  0.230896      fail
10  0.473147  0.766784  1.044565  1.093298  1.026576  0.364766      pass
11  0.430427  0.723737  0.650932  0.878284  1.111108  0.291982      pass
12  0.213868  0.920245  0.716231  0.920156  0.998877  0.317102      pass
13  0.332266  0.890405  1.035267  1.204756  1.377638  0.394695      pass
14  0.275633  0.844498  0.988529  0.970438  1.213399  0.358823      pass
15  0.170335  0.847772  1.056566  1.014156  1.480314  0.367138      pass
16  0.455413  1.227135  1.237712  1.356550  1.608265  0.418529      pass
17  0.388941  0.892236  1.201291  1.393300  1.555964  0.351445      pass
18  0.276380  0.783691  0.593063  0.701364  1.209092  0.287270      pass
19  0.476689  1.018100  1.202281  1.562369  1.879023  0.437853      pass

BARINEL SCORES

          x 5      cx 4      cx 2      cx 3      cx 1       h 0
sum  0.563092  0.503483  0.467027  0.447146  0.441028  0.416371

TARANTULA SCORES

          x 5      cx 4      cx 2      cx 3      cx 1       h 0
sum  0.563092  0.503483  0.467027  0.447146  0.441028  0.416371

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rxx_inGap_7_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.32it/s]
100%|██████████| 10/10 [00:01<00:00,  9.57it/s]

       rxx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.722547  3.029956  1.932162  1.937587  1.429456  0.482748      fail
1   1.461504  2.845360  1.751913  2.160062  2.219350  0.600043      fail
2   1.520708  2.605758  1.866329  1.562203  2.058558  0.620950      fail
3   1.324209  2.439800  1.251798  1.551740  1.697654  0.424543      fail
4   1.335831  2.414454  1.487139  1.537412  1.851041  0.568587      fail
5   1.771823  2.752846  1.560590  1.438270  1.570569  0.638984      fail
6   1.361121  2.429268  1.843975  1.608482  1.555193  0.386562      fail
7   1.509886  2.689811  1.519290  1.589270  1.138297  0.495593      fail
8   1.640199  2.982972  1.836674  2.016207  2.207868  0.648101      fail
9   1.630532  2.952902  1.650302  2.213781  2.137931  0.549871      fail
10  0.717893  1.254483  0.902692  0.730890  0.593886  0.299441      pass
11  1.241792  2.688446  1.788570  2.232702  1.986565  0.559570      pass
12  1.159193  2.384976  1.716692  1.834381  1.904102  0.692702      pass
13  1.435186  2.664214  1.334517  1.912006  1.645596  0.610823      pass
14  1.293933  2.238829  1.173370  1.047354  0.916625  0.339701      pass
15  1.133485  2.301651  1.141346  1.425060  1.457533  0.461122      pass
16  1.603525  2.636564  1.615788  1.535573  1.800666  0.573152      pass
17  1.380784  2.684234  2.067217  1.665775  1.707808  0.691661      pass
18  0.570785  1.092713  0.883416  0.856633  1.130537  0.453348      pass
19  0.921772  1.536279  1.078151  0.755545  0.779291  0.343397      pass

BARINEL SCORES

        rxx 5      cx 1      cx 4      cx 2      cx 3       h 0
sum  0.571438  0.562024  0.558207  0.557244  0.549313  0.518727

TARANTULA SCORES

        rxx 5      cx 1      cx 4      cx 2      cx 3       h 0
sum  0.571438  0.562024  0.558207  0.557244  0.549313  0.518727

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rx_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.83it/s]
100%|██████████| 10/10 [00:00<00:00, 10.21it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      rx 0 pass/fail
0   1.305406  1.152882  1.209037  1.332516  0.388807  0.898763      fail
1   1.173340  1.035424  0.818495  0.906509  0.241219  0.819580      fail
2   0.808879  0.568781  0.609319  0.673765  0.175064  0.501352      fail
3   1.129047  0.839414  1.085710  1.000009  0.285428  0.838023      fail
4   0.957662  0.891813  0.967072  1.180757  0.223753  0.700649      fail
5   0.918424  0.554901  0.509631  0.570134  0.206481  0.605977      fail
6   0.965830  0.708600  1.027701  0.768639  0.222937  0.663635      fail
7   1.029080  0.521353  0.906664  0.768651  0.198748  0.765243      fail
8   1.079107  1.194593  1.095552  1.523428  0.374286  0.806868      fail
9   1.078209  0.810435  1.087134  1.267083  0.307225  0.872356      fail
10  0.598140  0.469499  0.555530  0.549849  0.202960  0.491940      pass
11  0.907361  0.700322  0.721739  0.924713  0.198228  0.742090      pass
12  0.859256  0.677189  0.527444  0.454916  0.202470  0.530661      pass
13  0.703301  0.869831  0.911774  0.975724  0.319432  0.524699      pass
14  0.858710  1.015711  1.306699  1.590262  0.406492  0.738936      pass
15  0.808443  0.518633  0.515290  0.791297  0.221834  0.540259      pass
16  0.832841  0.554761  0.498276  0.393992  0.242789  0.612721      pass
17  0.905101  0.687166  0.883384  0.879719  0.184950  0.584426      pass
18  0.573757  0.500403  0.585012  0.874712  0.263858  0.444222      pass
19  1.233107  1.331737  1.491530  1.674538  0.404121  0.956334      pass

BARINEL SCORES

         cx 5      rx 0      cx 3      cx 4      cx 2       h 1
sum  0.557809  0.547884  0.538111  0.530536  0.523081  0.497801

TARANTULA SCORES

         cx 5      rx 0      cx 3      cx 4      cx 2       h 1
sum  0.557809  0.547884  0.538111  0.530536  0.523081  0.497801

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_y_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.36it/s]
100%|██████████| 10/10 [00:00<00:00, 12.51it/s]

         y 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.480231  1.168898  1.028666  1.283231  1.435907  0.386183      fail
1   0.433742  1.001037  0.587123  0.850726  0.942408  0.276639      fail
2   0.476301  1.109944  1.104089  1.228357  1.339558  0.332232      fail
3   0.370546  0.848070  0.695755  0.839647  0.960131  0.208348      fail
4   0.613097  1.384607  0.671374  0.982999  0.980686  0.306904      fail
5   0.551822  1.274819  1.027514  1.198337  1.198001  0.288218      fail
6   0.441382  1.070569  0.904649  1.281882  1.450967  0.395987      fail
7   0.432484  1.029994  0.722871  0.887782  0.815224  0.254571      fail
8   0.426803  0.933068  0.765219  1.027451  0.966476  0.229689      fail
9   0.526494  1.213086  1.229883  1.489124  1.509276  0.482250      fail
10  0.312508  0.800025  1.073669  1.237580  1.337163  0.377933      pass
11  0.297788  0.716779  0.645368  0.915705  1.027342  0.279781      pass
12  0.458744  1.107924  0.661811  1.061790  1.370743  0.379308      pass
13  0.529412  1.175245  1.012479  1.158997  1.152552  0.358415      pass
14  0.449510  1.029308  0.805408  1.050475  1.208339  0.384136      pass
15  0.431872  0.988952  0.682092  0.939609  1.154409  0.240101      pass
16  0.451742  1.017707  0.415639  0.852670  0.947615  0.253144      pass
17  0.531263  1.277547  1.190611  1.392770  1.427800  0.377823      pass
18  0.210529  0.503597  0.535287  0.519248  0.670169  0.231450      pass
19  0.502977  1.125800  0.692522  0.987573  0.961137  0.272621      pass

BARINEL SCORES

          y 5      cx 4      cx 3      cx 2      cx 1       h 0
sum  0.532285  0.531073  0.531068  0.522494  0.507468  0.500499

TARANTULA SCORES

          y 5      cx 4      cx 3      cx 2      cx 1       h 0
sum  0.532285  0.531073  0.531068  0.522494  0.507468  0.500499

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ry_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.18it/s]
100%|██████████| 10/10 [00:00<00:00, 11.83it/s]

        ry 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.389262  1.004442  1.218170  1.524034  1.596014  0.375343      fail
1   0.399135  0.915945  0.598790  0.508975  0.367155  0.217737      fail
2   0.442450  1.056858  1.051464  1.101840  1.197648  0.312497      fail
3   0.396084  0.910318  1.063276  1.041435  0.920861  0.273031      fail
4   0.429053  0.980217  0.785023  1.184930  1.068069  0.265312      fail
5   0.438820  1.013296  0.378736  0.660956  0.797718  0.196560      fail
6   0.367505  0.876701  0.871318  1.109707  1.215492  0.273106      fail
7   0.460322  1.025197  0.953001  0.999082  1.120533  0.311290      fail
8   0.405867  0.958006  0.593636  0.858899  1.126939  0.264115      fail
9   0.507951  1.216214  0.800716  1.118118  1.353824  0.346620      fail
10  0.416137  0.972183  0.762342  1.108783  1.242048  0.350800      pass
11  0.434535  1.011626  0.940089  1.494095  1.843153  0.414675      pass
12  0.546089  1.268855  0.748940  1.020633  1.410482  0.343982      pass
13  0.461473  1.090786  0.863625  1.193793  1.256734  0.300873      pass
14  0.408618  0.926280  0.519048  0.474511  0.556553  0.243616      pass
15  0.395300  0.896882  0.860148  1.061814  0.874722  0.253721      pass
16  0.279691  0.683160  0.832510  1.298029  1.336292  0.413260      pass
17  0.337894  0.842896  0.830270  1.147598  1.464414  0.416135      pass
18  0.488640  1.150529  1.112290  1.529664  1.960185  0.452579      pass
19  0.250925  0.589586  0.377632  0.669440  0.604829  0.107664      pass

BARINEL SCORES

         cx 3      cx 4      ry 5      cx 2       h 0      cx 1
sum  0.514456  0.513523  0.513151  0.478907  0.462359  0.461714

TARANTULA SCORES

         cx 3      cx 4      ry 5      cx 2       h 0      cx 1
sum  0.514456  0.513523  0.513151  0.478907  0.462359  0.461714

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rxx_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.99it/s]
100%|██████████| 10/10 [00:00<00:00, 11.97it/s]

       rxx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.518885  0.934364  0.600046  0.479883  0.552316  0.194267      fail
1   0.386710  1.084072  0.973519  1.158177  1.441601  0.353048      fail
2   0.500751  0.945184  0.697111  0.752699  0.791865  0.209097      fail
3   0.458838  0.868169  0.551653  0.543860  0.751945  0.218713      fail
4   0.404605  0.935750  1.206973  1.453942  1.540742  0.376591      fail
5   0.424080  0.926118  0.490494  0.610889  0.601722  0.203970      fail
6   0.429116  0.982549  0.860832  1.042493  1.102349  0.329232      fail
7   0.447742  1.179805  0.874721  1.157397  1.577579  0.414216      fail
8   0.504680  0.929218  0.666718  0.606919  0.624337  0.192775      fail
9   0.467695  0.752729  1.000203  0.904058  0.978930  0.231526      fail
10  0.344691  0.508638  0.464040  0.421980  0.656613  0.135909      pass
11  0.414632  0.724420  0.695325  0.591398  0.970927  0.277161      pass
12  0.322197  0.846338  1.047132  1.507890  1.345172  0.373854      pass
13  0.247251  0.896261  0.599364  0.877873  1.310385  0.369401      pass
14  0.387306  0.684228  0.438482  0.629720  0.480464  0.227568      pass
15  0.289029  1.253184  1.006632  1.269554  1.104403  0.402628      pass
16  0.286021  0.827339  0.805043  1.021841  1.226394  0.362773      pass
17  0.288729  1.087682  0.762224  1.048245  1.199717  0.280294      pass
18  0.339296  1.052329  0.734273  1.206632  1.341445  0.375121      pass
19  0.291291  0.709787  0.464630  0.644173  0.572609  0.173568      pass

BARINEL SCORES

        rxx 5      cx 3     cx 4      cx 1      cx 2       h 0
sum  0.585939  0.530293  0.52614  0.493933  0.485806  0.477652

TARANTULA SCORES

        rxx 5      cx 3     cx 4      cx 1      cx 2       h 0
sum  0.585939  0.530293  0.52614  0.493933  0.485806  0.477652

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rx_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.92it/s]
100%|██████████| 10/10 [00:00<00:00, 11.88it/s]

        rx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.446636  1.029907  0.721396  0.927844  0.784950  0.219605      fail
1   0.481854  1.089413  0.864740  1.227558  1.117428  0.304227      fail
2   0.519012  1.172937  0.581383  0.558141  0.677521  0.236745      fail
3   0.428538  1.008702  0.792408  1.141451  1.225194  0.274339      fail
4   0.528737  1.289615  1.148350  1.323815  1.578048  0.355782      fail
5   0.491955  1.184688  0.985956  1.086932  1.224751  0.348521      fail
6   0.465016  1.133476  1.182510  1.313765  1.552728  0.366360      fail
7   0.356267  0.844048  0.768454  0.720282  0.835257  0.122846      fail
8   0.396844  0.879042  0.647970  0.647044  0.690346  0.208942      fail
9   0.490684  1.206579  1.229891  1.375406  1.325737  0.332203      fail
10  0.390410  0.928285  1.102180  1.378166  1.485760  0.430907      pass
11  0.210912  0.500859  0.384881  0.615419  0.736481  0.239304      pass
12  0.359248  0.854778  0.792272  1.098749  1.180865  0.351356      pass
13  0.245643  0.532683  0.584404  0.887891  0.945313  0.261088      pass
14  0.393237  0.912840  0.888365  0.955889  1.082951  0.273571      pass
15  0.337724  0.755136  0.955309  1.156495  1.233673  0.294387      pass
16  0.407797  0.935495  0.496461  0.676749  0.826238  0.204132      pass
17  0.408057  0.942536  0.583484  0.637012  0.830463  0.246407      pass
18  0.187991  0.406355  0.434410  0.476413  0.438506  0.151272      pass
19  0.227973  0.562559  0.674013  0.792440  1.080582  0.306851      pass

BARINEL SCORES

         cx 4      rx 5      cx 3      cx 2      cx 1       h 0
sum  0.596502  0.592388  0.564078  0.543348  0.528081  0.500931

TARANTULA SCORES

         cx 4      rx 5      cx 3      cx 2      cx 1       h 0
sum  0.596502  0.592388  0.564078  0.543348  0.528081  0.500931

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_h_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.18it/s]
100%|██████████| 10/10 [00:00<00:00, 10.22it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       h 0 pass/fail
0   0.773258  0.699936  0.659856  0.777877  0.253515  0.435485      fail
1   0.961173  1.085705  1.147919  1.103514  0.299108  0.559517      fail
2   0.856063  0.974254  1.026314  1.232313  0.306347  0.554125      fail
3   0.634873  0.890197  1.004577  0.976053  0.239928  0.410783      fail
4   1.063494  0.988689  1.336402  1.416478  0.352000  0.533112      fail
5   0.623520  0.710794  0.819961  1.068730  0.203600  0.467224      fail
6   0.766474  1.019217  1.048167  1.139151  0.274030  0.564476      fail
7   0.990824  1.083545  1.206927  1.183024  0.298933  0.559737      fail
8   1.104864  0.937140  1.057458  1.425828  0.321125  0.604270      fail
9   1.016344  1.015934  1.230062  1.173981  0.315447  0.492797      fail
10  0.780123  0.913460  1.242343  1.195812  0.243832  0.549337      pass
11  0.638484  0.459049  0.696331  0.698376  0.137387  0.347777      pass
12  0.996346  1.087827  1.026930  1.083082  0.375492  0.554864      pass
13  0.835363  0.434855  0.419911  0.563211  0.186548  0.325959      pass
14  0.502589  0.468302  0.449839  0.418908  0.140310  0.196238      pass
15  1.106360  0.851152  1.399348  1.555333  0.379043  0.464533      pass
16  1.217131  0.944507  1.178902  1.037199  0.284220  0.473871      pass
17  0.489646  0.275716  0.334850  0.537827  0.123660  0.234079      pass
18  0.561350  0.598036  0.796789  0.975981  0.228397  0.319109      pass
19  0.776480  0.698989  0.911174  1.311901  0.319227  0.449596      pass

BARINEL SCORES

         cx 4       h 0      cx 3      cx 2      h 1      cx 5
sum  0.582837  0.569593  0.554786  0.550763  0.54221  0.526566

TARANTULA SCORES

         cx 4       h 0      cx 3      cx 2      h 1      cx 5
sum  0.582837  0.569593  0.554786  0.550763  0.54221  0.526566

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_x_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.09it/s]
100%|██████████| 10/10 [00:00<00:00, 12.28it/s]

         x 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.458599  1.003002  1.004910  1.082985  1.230851  0.369191      fail
1   0.518846  0.968826  0.745640  1.008462  1.223536  0.377322      fail
2   0.429850  1.026026  1.005796  1.407000  1.417252  0.400556      fail
3   0.482721  1.357847  1.061896  1.398983  1.514369  0.387476      fail
4   0.526130  1.087244  0.445195  0.622235  0.832239  0.262641      fail
5   0.436570  0.922820  0.876931  0.656732  0.733485  0.168417      fail
6   0.531130  0.863406  0.551302  0.703329  1.122867  0.283237      fail
7   0.552585  1.100100  0.934569  0.828561  0.987938  0.257095      fail
8   0.447438  0.975886  0.435764  0.614450  0.674504  0.212449      fail
9   0.344156  0.953322  0.626302  0.714174  0.704852  0.184560      fail
10  0.220655  0.602020  0.776937  0.920812  0.848509  0.217242      pass
11  0.187562  0.597004  0.782263  0.972025  0.936905  0.230877      pass
12  0.357612  1.146508  0.781772  0.942963  1.196868  0.315420      pass
13  0.353326  1.000004  0.473956  0.759954  0.816960  0.159498      pass
14  0.314328  1.007883  0.925377  1.283471  1.419261  0.345842      pass
15  0.184107  0.930444  1.013921  1.392006  1.339087  0.348859      pass
16  0.453981  1.014852  0.590986  0.657512  0.834055  0.220153      pass
17  0.299051  0.743238  0.996943  0.883116  0.610627  0.211945      pass
18  0.367214  0.839157  1.056419  1.221597  0.982433  0.392017      pass
19  0.388339  1.094192  0.950360  1.296788  1.029418  0.336217      pass

BARINEL SCORES

          x 5      cx 4       h 0      cx 1      cx 3     cx 2
sum  0.601974  0.533357  0.510991  0.510456  0.479403  0.46661

TARANTULA SCORES

          x 5      cx 4       h 0      cx 1      cx 3     cx 2
sum  0.601974  0.533357  0.510991  0.510456  0.479403  0.46661

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rxx_inGap_9_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.24it/s]
100%|██████████| 10/10 [00:00<00:00, 10.48it/s]

       rxx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.876082  0.905466  0.761737  1.189363  0.943811  0.430439      fail
1   1.855836  0.981618  0.698115  1.392939  1.224509  0.528097      fail
2   1.737027  1.313157  1.105101  1.981080  1.831058  0.680748      fail
3   1.996589  1.517781  1.557190  1.881698  1.789373  0.667432      fail
4   1.910585  0.976514  1.084402  1.622912  1.471268  0.569146      fail
5   2.191008  1.406888  1.338117  2.016077  1.919962  0.739751      fail
6   2.385532  1.234714  1.198941  1.803158  1.700411  0.683233      fail
7   1.865838  1.259589  1.136631  1.662857  1.695714  0.665695      fail
8   2.033922  0.937733  0.929631  1.319654  1.144914  0.543147      fail
9   1.943466  1.307640  1.531331  1.887562  1.791779  0.679797      fail
10  2.377633  0.927568  1.083365  1.797829  1.765053  0.637928      pass
11  1.355600  0.910614  1.029689  1.558768  1.630880  0.558434      pass
12  1.645252  1.023068  0.943031  1.298972  1.241924  0.481789      pass
13  1.579330  1.496442  1.309803  1.791338  1.753601  0.656930      pass
14  2.459473  1.417098  1.394628  2.618273  2.169686  0.838122      pass
15  1.866694  0.894271  1.164655  1.835607  1.646659  0.609905      pass
16  2.312827  1.429751  1.372822  1.691416  1.326243  0.646752      pass
17  1.879435  0.971521  1.106011  1.657900  1.073901  0.514226      pass
18  1.608920  1.051928  1.001129  1.884107  1.626425  0.595301      pass
19  2.145462  1.015318  0.995146  1.608967  1.437269  0.522673      pass

BARINEL SCORES

         cx 4     rxx 5      h 0      cx 3      cx 1      cx 2
sum  0.515308  0.507242  0.50512  0.498701  0.497453  0.485712

TARANTULA SCORES

         cx 4     rxx 5      h 0      cx 3      cx 1      cx 2
sum  0.515308  0.507242  0.50512  0.498701  0.497453  0.485712

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cx_inGap_2_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.59it/s]
100%|██████████| 10/10 [00:01<00:00,  9.22it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.689453  0.565379  0.865030  1.011862  0.700895  0.262654      fail
1   0.842971  0.648554  0.946576  1.083368  0.730563  0.315462      fail
2   1.156849  0.964749  1.299649  1.367602  1.107091  0.338740      fail
3   1.414028  1.136278  1.269860  1.541945  1.121534  0.342775      fail
4   1.159066  1.029732  1.326563  1.472087  1.115589  0.294182      fail
5   0.728436  0.815484  1.104801  1.467735  1.069242  0.260506      fail
6   1.007207  0.909511  1.212745  1.576406  1.065093  0.251401      fail
7   0.813390  0.526798  0.683090  0.740673  0.562716  0.235433      fail
8   0.826235  1.132089  1.226258  1.399136  1.007033  0.275245      fail
9   1.166329  0.774775  1.176611  1.343027  0.849958  0.222392      fail
10  1.035284  1.137622  1.571499  1.443929  1.222586  0.238011      pass
11  1.042417  1.023177  1.251071  1.221324  0.951008  0.273468      pass
12  0.904067  0.957870  1.246059  1.163848  1.074478  0.292120      pass
13  1.100826  0.944536  0.932731  0.883490  0.811219  0.360628      pass
14  1.059625  1.136371  1.417962  1.617725  1.008671  0.183775      pass
15  0.984385  0.970883  0.830847  0.999360  0.680057  0.330307      pass
16  0.441700  0.388051  0.553816  0.688342  0.474923  0.137653      pass
17  0.915881  0.852366  1.107325  1.395944  1.122478  0.326886      pass
18  0.790399  0.650550  0.978303  1.238825  0.827045  0.215879      pass
19  0.344159  0.207822  0.239517  0.357557  0.162945  0.115155      pass

BARINEL SCORES

         cx 2      cx 5       h 0      cx 1      cx 3      cx 4
sum  0.541507  0.532167  0.530811  0.528143  0.523118  0.506979

TARANTULA SCORES

         cx 2      cx 5       h 0      cx 1      cx 3      cx 4
sum  0.541507  0.532167  0.530811  0.528143  0.523118  0.506979

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_sx_inGap_7_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.69it/s]
100%|██████████| 10/10 [00:00<00:00, 10.34it/s]

      sxdg 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.114024  1.752892  0.736976  1.377776  1.311051  0.412478      fail
1   1.205995  2.021798  1.562681  1.653824  2.023121  0.611973      fail
2   1.025656  1.888648  1.213861  1.733076  1.969458  0.562092      fail
3   1.076238  1.763798  1.142124  1.227465  1.208290  0.416239      fail
4   0.797501  1.300817  0.997009  1.103278  0.979565  0.211409      fail
5   1.016711  1.956843  1.468155  1.809929  1.915817  0.432650      fail
6   1.082722  1.701038  0.941098  0.998873  1.028622  0.410463      fail
7   1.290760  2.132583  1.404402  1.580343  1.708355  0.519079      fail
8   1.145969  1.907707  1.454409  1.513290  1.287872  0.528129      fail
9   0.935119  1.762475  1.401202  1.448594  1.285909  0.427675      fail
10  0.517633  1.070057  0.757047  0.977726  1.141538  0.345437      pass
11  0.879356  1.786371  1.169837  1.310701  1.625526  0.518817      pass
12  1.076245  2.134939  1.513616  1.521549  1.640311  0.566773      pass
13  0.686014  1.199668  0.675806  0.814829  0.817377  0.204678      pass
14  1.027226  1.904151  1.359459  1.507006  1.642768  0.698414      pass
15  0.755042  1.865355  1.357779  1.302138  1.354934  0.378627      pass
16  0.943095  1.778995  1.387201  1.394321  1.594001  0.591978      pass
17  0.846070  1.451342  0.828550  1.087314  1.329983  0.486629      pass
18  0.963004  1.635477  1.152724  0.882151  0.908792  0.384641      pass
19  1.111670  1.823244  0.856633  1.184827  1.023156  0.458709      pass

BARINEL SCORES

       sxdg 5      cx 2      cx 1      cx 3      cx 4       h 0
sum  0.548352  0.546613  0.529494  0.527015  0.522088  0.494408

TARANTULA SCORES

       sxdg 5      cx 2      cx 1      cx 3      cx 4       h 0
sum  0.548352  0.546613  0.529494  0.527015  0.522088  0.494408

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ry_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.28it/s]
100%|██████████| 10/10 [00:00<00:00, 11.61it/s]

        ry 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.158945  2.286127  1.421099  1.161382  1.388583  0.668301      fail
1   1.103685  2.278377  1.561998  1.346691  1.531763  0.644960      fail
2   0.985789  2.076684  1.064958  1.227911  1.265386  0.509124      fail
3   0.961599  2.298752  1.158908  1.436581  1.559650  0.599897      fail
4   1.297398  2.761308  1.594819  1.865131  1.790333  0.691924      fail
5   1.204882  2.656756  1.900456  1.734531  2.219545  0.739971      fail
6   1.087799  2.315077  1.722618  1.540919  1.479743  0.610248      fail
7   0.787742  1.930652  1.521134  1.599072  1.807148  0.676240      fail
8   1.091649  2.397789  1.500707  1.665901  1.962666  0.711643      fail
9   1.114193  2.346948  2.118956  1.840143  1.848646  0.731762      fail
10  0.776381  1.656716  0.837467  0.805455  0.744799  0.355296      pass
11  0.862280  2.155689  2.007085  1.501818  1.556555  0.501324      pass
12  0.755244  1.822374  1.134568  1.315085  1.183576  0.439730      pass
13  1.165844  2.159421  1.478564  1.131191  1.357589  0.499192      pass
14  1.024239  2.396861  1.816018  1.546857  1.663861  0.516451      pass
15  0.837955  1.681564  1.243529  0.738842  1.201431  0.405409      pass
16  1.154281  2.471869  1.515290  1.229988  1.568433  0.652910      pass
17  0.773010  1.888538  1.351023  1.023154  0.825227  0.424261      pass
18  0.823809  2.020848  1.533551  1.627467  1.327071  0.531260      pass
19  0.456159  1.169734  0.857436  1.098566  1.100978  0.374131      pass

BARINEL SCORES

          h 0      cx 1      cx 2     ry 5      cx 4      cx 3
sum  0.583485  0.573579  0.561958  0.55572  0.545881  0.530523

TARANTULA SCORES

          h 0      cx 1      cx 2     ry 5      cx 4      cx 3
sum  0.583485  0.573579  0.561958  0.55572  0.545881  0.530523

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rx_inGap_8_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.11it/s]
100%|██████████| 10/10 [00:00<00:00, 10.75it/s]

        rx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.650121  1.215924  1.760031  1.502090  1.649278  0.489711      fail
1   0.772373  0.994346  1.374437  0.938178  0.843991  0.431958      fail
2   0.568417  1.141153  1.505713  1.765088  1.817147  0.493788      fail
3   0.664302  1.009391  1.347770  1.111643  1.319117  0.501615      fail
4   0.516669  0.984500  1.309107  1.293941  1.720665  0.434213      fail
5   0.738377  1.069645  1.596420  1.341875  0.907658  0.525733      fail
6   0.586499  1.195254  1.848441  1.801811  1.807064  0.459526      fail
7   0.564642  1.330078  1.726805  1.816884  1.702829  0.630304      fail
8   0.671397  1.102538  1.278096  1.031288  0.756554  0.417961      fail
9   0.610753  0.955476  1.685703  1.542704  1.330550  0.392610      fail
10  0.489122  1.007272  1.473827  1.642382  1.588965  0.595139      pass
11  0.541914  1.125778  1.392303  1.550939  1.648990  0.647509      pass
12  0.579505  1.063837  1.631093  1.899503  1.984224  0.824535      pass
13  0.477802  0.847684  1.396031  1.274463  0.968963  0.317101      pass
14  0.471727  0.933886  1.226467  1.163758  0.756802  0.417571      pass
15  0.324500  0.881644  1.247147  1.305735  0.973178  0.475421      pass
16  0.578615  0.970950  1.466490  1.654790  1.673611  0.632089      pass
17  0.649883  0.828347  1.366108  0.999830  0.816769  0.392476      pass
18  0.527139  1.129246  1.799375  1.392447  1.382135  0.569580      pass
19  0.444049  0.601884  1.112820  1.254657  1.111372  0.496780      pass

BARINEL SCORES

         rx 5      cx 4      cx 3      cx 1      cx 2       h 0
sum  0.555098  0.539428  0.522354  0.517748  0.500124  0.470885

TARANTULA SCORES

         rx 5      cx 4      cx 3      cx 1      cx 2       h 0
sum  0.555098  0.539428  0.522354  0.517748  0.500124  0.470885

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ccx_inGap_7_.qasm

100%|██████████| 10/10 [00:02<00:00,  3.39it/s]
100%|██████████| 10/10 [00:02<00:00,  3.77it/s]

       ccx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.287181  1.127722  0.608217  0.622909  0.752091  0.230441      fail
1   1.379004  1.092141  0.954430  0.807513  0.909625  0.263258      fail
2   1.160085  1.042121  0.836554  0.663439  0.758244  0.245127      fail
3   1.487020  1.090175  0.903558  0.843222  1.032751  0.288174      fail
4   1.381935  1.263572  1.090150  0.965261  1.107234  0.319687      fail
5   1.115554  0.939312  0.485102  0.518706  0.725196  0.235552      fail
6   1.023254  0.914949  0.801305  0.572309  0.746536  0.238042      fail
7   1.347008  1.209035  1.034990  0.977070  1.236472  0.336103      fail
8   1.084989  0.981318  0.573726  0.553938  0.850083  0.242162      fail
9   1.438207  1.280652  0.905705  0.966256  1.127643  0.297358      fail
10  1.349520  1.139418  0.808243  0.815926  0.940110  0.306444      pass
11  0.972452  0.822448  0.378831  0.382970  0.441887  0.151467      pass
12  1.476755  1.347058  1.040854  0.898286  1.262773  0.335489      pass
13  1.070185  0.828110  0.775797  0.675788  0.840095  0.246725      pass
14  1.151537  1.220235  0.754309  0.733535  0.805978  0.252900      pass
15  0.968108  0.873312  0.570604  0.476413  0.598235  0.216945      pass
16  1.287529  1.320714  1.002067  0.868566  1.058541  0.308167      pass
17  1.711049  1.650242  1.294678  1.218880  1.388344  0.396026      pass
18  1.331791  0.930242  0.529419  0.552567  0.778084  0.220943      pass
19  0.865984  0.850515  0.419271  0.535959  0.768561  0.216246      pass

BARINEL SCORES

        cx 3      cx 2     ccx 5      cx 1       h 0      cx 4
sum  0.51965  0.511322  0.510433  0.510019  0.504166  0.499058

TARANTULA SCORES

        cx 3      cx 2     ccx 5      cx 1       h 0      cx 4
sum  0.51965  0.511322  0.510433  0.510019  0.504166  0.499058

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_sx_inGap_10_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.18it/s]
100%|██████████| 10/10 [00:00<00:00, 11.20it/s]

      sxdg 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.026632  1.379904  1.286763  1.284216  1.751729  0.654620      fail
1   0.848538  0.671496  0.847876  0.732625  0.988921  0.422467      fail
2   1.242130  0.877179  0.653024  0.816822  0.913197  0.466960      fail
3   1.078805  1.081273  1.255997  1.287737  1.839575  0.655150      fail
4   1.370594  0.999375  0.850860  0.906837  1.049486  0.523531      fail
5   1.499660  1.451477  1.011267  0.769660  1.199872  0.610278      fail
6   0.903986  0.745520  0.843453  0.878999  1.079118  0.438165      fail
7   1.043704  1.441516  0.905352  0.997442  1.080820  0.492009      fail
8   0.966570  1.237106  1.068437  1.352328  1.491664  0.608398      fail
9   0.921522  1.137949  0.829461  1.169742  1.565722  0.575547      fail
10  0.786836  0.985475  0.731221  1.136886  1.321686  0.465832      pass
11  0.866012  0.908114  0.907580  0.913542  1.383600  0.473129      pass
12  1.169569  1.311519  1.209390  1.020269  1.087133  0.528831      pass
13  0.673463  0.879206  0.610804  0.677371  0.769276  0.290442      pass
14  0.880838  1.012957  0.898225  1.249655  1.323331  0.550145      pass
15  1.107515  0.979557  0.673936  0.753294  0.875886  0.420077      pass
16  0.387917  0.739223  0.601065  0.788987  1.092484  0.322567      pass
17  0.868945  1.008769  0.987264  1.033153  1.390651  0.521441      pass
18  0.749002  1.222763  1.061687  1.185731  1.709031  0.517705      pass
19  1.165228  1.217309  0.766593  0.957842  1.302005  0.483878      pass

BARINEL SCORES

       sxdg 5       h 0      cx 3      cx 4     cx 1      cx 2
sum  0.557441  0.543562  0.530686  0.517801  0.51398  0.512044

TARANTULA SCORES

       sxdg 5       h 0      cx 3      cx 4     cx 1      cx 2
sum  0.557441  0.543562  0.530686  0.517801  0.51398  0.512044

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cx_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.89it/s]
100%|██████████| 10/10 [00:00<00:00, 12.31it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.131035  0.099172  0.714506  0.798421  0.909930  0.305132      fail
1   0.994630  0.089908  0.718620  0.659663  0.871320  0.239631      fail
2   1.210185  0.106807  0.853749  1.028602  1.216237  0.319312      fail
3   1.258567  0.111663  0.831591  1.051613  1.177557  0.340066      fail
4   1.158562  0.102688  0.631226  0.600391  0.628372  0.262637      fail
5   1.037978  0.093173  0.784450  0.958752  1.197507  0.324686      fail
6   0.955413  0.086121  0.899017  0.725270  1.052587  0.282724      fail
7   0.822714  0.074392  0.714730  0.363949  0.465101  0.235870      fail
8   1.137822  0.101932  0.662390  0.756197  1.015631  0.265067      fail
9   1.253726  0.110934  0.926823  0.962463  1.255821  0.300427      fail
10  0.683793  0.060589  0.570135  0.318200  0.510752  0.165817      pass
11  0.635088  0.057978  0.662458  0.438415  0.483037  0.228720      pass
12  0.651631  0.058444  0.410094  0.449304  0.660404  0.180687      pass
13  0.970704  0.088575  0.863204  0.459366  0.768561  0.214429      pass
14  1.123039  0.101077  0.884374  0.952072  1.221192  0.299396      pass
15  0.897806  0.080079  0.734226  0.458519  0.455532  0.193525      pass
16  0.618750  0.056230  0.407139  0.368935  0.311702  0.129695      pass
17  0.858154  0.076531  0.581214  0.609866  0.634409  0.180242      pass
18  1.102713  0.098834  0.623046  0.631303  0.795534  0.205795      pass
19  0.760070  0.066985  0.485177  0.526327  0.744983  0.209075      pass

BARINEL SCORES

         cx 2      cx 1       h 0      cx 5      cx 4      cx 3
sum  0.602649  0.597824  0.588898  0.569018  0.567205  0.554306

TARANTULA SCORES

         cx 2      cx 1       h 0      cx 5      cx 4      cx 3
sum  0.602649  0.597824  0.588898  0.569018  0.567205  0.554306

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_h_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.00it/s]
100%|██████████| 10/10 [00:00<00:00, 11.56it/s]

         h 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.672001  2.335678  1.911286  2.033112  2.460050  0.837870      fail
1   0.611715  2.267044  1.287737  1.544717  1.563022  0.527635      fail
2   0.732862  2.549947  1.095335  1.408185  1.608831  0.637998      fail
3   0.548882  2.322562  1.610405  1.972590  1.925967  0.752160      fail
4   0.723744  2.704203  1.783696  1.602663  1.161577  0.553549      fail
5   0.512833  2.072793  1.440058  1.182582  1.489792  0.671160      fail
6   0.559455  2.331532  1.455191  1.431088  1.361135  0.588658      fail
7   0.470137  2.260401  1.381355  1.403551  1.705511  0.555923      fail
8   0.654836  2.373080  1.424173  1.278380  1.509645  0.556608      fail
9   0.635801  2.380858  1.292178  1.166667  1.239833  0.580106      fail
10  0.447099  1.941314  1.772291  1.406672  2.019074  0.598132      pass
11  0.731272  2.595670  1.597645  1.178769  1.134124  0.653937      pass
12  0.222358  1.428329  0.728066  1.177485  1.600809  0.422043      pass
13  0.528326  2.010080  1.327889  1.543073  1.815587  0.579649      pass
14  0.517939  2.034766  1.428602  1.280460  1.352517  0.393279      pass
15  0.705365  2.586793  1.707086  1.743766  2.022424  0.731090      pass
16  0.568435  2.186294  1.095086  1.224646  1.451054  0.435554      pass
17  0.579194  2.134178  2.007672  1.634262  1.728610  0.698261      pass
18  0.574792  2.279107  1.164125  1.229267  1.836523  0.381893      pass
19  0.383329  1.407758  0.583469  0.886140  0.828611  0.275710      pass

BARINEL SCORES

          h 0       h 5      cx 4      cx 2      cx 3     cx 1
sum  0.547769  0.537967  0.533865  0.530341  0.522594  0.50371

TARANTULA SCORES

          h 0       h 5      cx 4      cx 2      cx 3     cx 1
sum  0.547769  0.537967  0.533865  0.530341  0.522594  0.50371

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_sx_inGap_9_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.17it/s]
100%|██████████| 10/10 [00:00<00:00, 11.04it/s]

      sxdg 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.255116  1.208397  1.072972  1.325059  1.429054  0.558548      fail
1   1.137153  0.987252  0.789102  1.269621  1.255387  0.420550      fail
2   0.887186  1.097941  0.685533  1.001116  1.024963  0.271765      fail
3   1.049279  1.098638  0.993231  1.253111  1.269128  0.553118      fail
4   1.431506  1.393210  1.139018  1.879955  2.214604  0.647190      fail
5   0.798831  1.137930  1.040397  1.595861  1.887986  0.426925      fail
6   1.220124  1.035617  0.905421  1.467193  1.528843  0.462068      fail
7   1.129339  1.087611  1.403398  2.082899  2.490881  0.670860      fail
8   0.916549  0.984174  0.811327  1.242122  1.424921  0.422597      fail
9   1.233936  0.867932  0.761858  1.182007  1.237766  0.435367      fail
10  0.794915  1.018008  1.058738  1.248493  1.245023  0.421278      pass
11  0.980965  0.885270  0.903663  1.202322  1.491203  0.614833      pass
12  0.634300  0.782845  0.800484  1.027454  0.934850  0.292191      pass
13  1.064079  1.161822  0.849975  1.449149  1.845299  0.629965      pass
14  0.711298  0.551915  0.422039  0.884234  0.855267  0.252037      pass
15  1.043732  1.123869  1.392232  1.800692  1.986172  0.750327      pass
16  1.038438  1.571195  1.105505  1.898343  2.078594  0.649756      pass
17  0.975934  0.969379  0.937603  1.259994  1.411889  0.477815      pass
18  0.885454  0.715429  0.750977  1.183110  1.380135  0.536834      pass
19  0.798396  0.714019  0.687301  1.170269  1.568068  0.464173      pass

BARINEL SCORES

       sxdg 5      cx 4      cx 2      cx 3      cx 1       h 0
sum  0.553324  0.534448  0.521421  0.518739  0.515822  0.488943

TARANTULA SCORES

       sxdg 5      cx 4      cx 2      cx 3      cx 1       h 0
sum  0.553324  0.534448  0.521421  0.518739  0.515822  0.488943

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_sx_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.74it/s]
100%|██████████| 10/10 [00:01<00:00,  9.22it/s]

        cx 5      cx 4      cx 3      cx 2       h 1    sxdg 0 pass/fail
0   1.031919  0.540950  0.885702  0.884928  0.184424  0.761902      fail
1   0.892172  1.166184  1.248997  1.178111  0.311303  0.682355      fail
2   1.107453  1.117419  1.369306  1.535864  0.334366  0.833112      fail
3   0.969325  0.832305  1.178528  1.278399  0.299029  0.762903      fail
4   0.976956  0.923936  1.142011  1.194900  0.258418  0.719955      fail
5   1.188398  1.197169  1.132798  1.575359  0.338027  0.900375      fail
6   0.892273  0.801171  0.814112  0.965374  0.253296  0.605254      fail
7   1.071829  0.946662  1.120459  1.028675  0.284571  0.841641      fail
8   0.981459  0.942889  1.273367  1.448114  0.331271  0.783245      fail
9   1.069667  1.103395  1.320640  1.337689  0.314990  0.867850      fail
10  0.486611  0.497298  0.445282  0.453508  0.163956  0.339065      pass
11  0.844777  1.103732  1.063579  1.081975  0.283119  0.621925      pass
12  0.777923  1.026335  1.001082  1.243000  0.303567  0.610499      pass
13  0.737466  0.434023  0.577624  0.784627  0.258449  0.499402      pass
14  1.284661  1.111673  1.162173  1.300567  0.457816  1.017649      pass
15  0.845923  0.798840  0.781983  0.837171  0.246672  0.599027      pass
16  0.900851  0.467076  0.787338  0.750383  0.243540  0.578086      pass
17  1.036277  0.792232  0.868392  0.802926  0.228180  0.701409      pass
18  0.509941  0.555627  0.692305  0.830780  0.242910  0.394606      pass
19  0.634310  0.954063  1.522622  1.401770  0.403713  0.571943      pass

BARINEL SCORES

         cx 2    sxdg 0      cx 3      cx 5      cx 4       h 1
sum  0.567096  0.566643  0.563358  0.558188  0.552885  0.506773

TARANTULA SCORES

         cx 2    sxdg 0      cx 3      cx 5      cx 4       h 1
sum  0.567096  0.566643  0.563358  0.558188  0.552885  0.506773

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_cswap_inGap_5_.qasm

100%|██████████| 10/10 [00:02<00:00,  3.62it/s]
100%|██████████| 10/10 [00:02<00:00,  3.63it/s]

        cx 5   cswap 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.092465  1.116758  0.869328  0.929372  1.092276  0.355518      fail
1   1.087345  0.954396  0.864380  1.091748  1.267093  0.337640      fail
2   0.962404  1.213528  1.022414  1.197331  1.265432  0.412474      fail
3   1.004009  0.942361  0.834980  0.900758  1.083192  0.312324      fail
4   0.791593  1.115530  0.882648  1.072826  1.090678  0.303905      fail
5   0.750548  0.953023  0.766615  0.671262  0.853775  0.233887      fail
6   0.923515  0.994093  0.993597  0.958545  1.050344  0.300564      fail
7   1.062947  1.103208  0.987599  1.067643  1.172664  0.329292      fail
8   0.665151  0.859701  0.831043  0.891325  0.988154  0.271889      fail
9   0.871161  1.234102  0.674081  0.692712  0.874339  0.279335      fail
10  0.568214  0.937826  0.612917  0.716176  0.616914  0.200654      pass
11  1.034695  1.229268  0.939177  1.025183  1.213234  0.354248      pass
12  0.915047  1.008392  0.661748  0.696382  0.726081  0.299358      pass
13  1.311878  1.191398  0.921036  1.109918  1.242628  0.393472      pass
14  0.774893  1.070027  0.662639  0.670149  0.753470  0.256697      pass
15  0.660408  1.212513  0.739218  0.844313  0.870133  0.326155      pass
16  0.510117  0.757490  0.516490  0.575623  0.638898  0.211244      pass
17  0.873678  0.894737  0.845779  0.935328  0.854641  0.287001      pass
18  1.032454  1.342086  0.827736  1.005808  0.805986  0.337440      pass
19  0.871282  0.872269  0.891384  1.059992  1.075670  0.339204      pass

BARINEL SCORES

        cx 1      cx 3      cx 2      cx 5       h 0   cswap 4
sum  0.54966  0.533912  0.523041  0.518534  0.510693  0.499302

TARANTULA SCORES

        cx 1      cx 3      cx 2      cx 5       h 0   cswap 4
sum  0.54966  0.533912  0.523041  0.518534  0.510693  0.499302

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_ry_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.93it/s]
100%|██████████| 10/10 [00:00<00:00, 12.38it/s]

        ry 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.247536  1.071122  1.939943  1.423474  1.540333  0.585193      fail
1   1.129843  1.129107  2.112130  1.727575  1.521225  0.613779      fail
2   0.892080  1.285427  1.722342  1.240863  1.613006  0.638240      fail
3   1.022090  0.890095  1.795156  1.087331  1.355908  0.653596      fail
4   0.878177  1.287100  1.640944  1.480517  2.033914  0.631608      fail
5   0.714112  0.959947  1.462803  1.183686  1.463871  0.558045      fail
6   1.121799  1.171402  1.961314  1.555628  1.919527  0.725499      fail
7   0.976840  0.925830  1.429254  0.870711  1.316018  0.489873      fail
8   1.089808  0.636314  1.659831  1.477453  1.434505  0.473551      fail
9   0.996809  1.022460  1.818758  1.531737  1.790708  0.702612      fail
10  0.926299  1.063650  1.831409  1.689919  2.061082  0.566639      pass
11  0.520219  0.891160  1.664736  1.156636  1.134611  0.435292      pass
12  0.976921  1.326459  1.877674  1.376646  1.751644  0.554639      pass
13  0.709460  1.071726  1.441356  1.490452  1.897581  0.463697      pass
14  0.986845  1.454908  1.846213  1.469166  1.981252  0.653067      pass
15  0.783258  0.944876  1.888993  1.757473  1.929065  0.558310      pass
16  0.778901  1.031584  1.696039  1.424456  1.255797  0.489731      pass
17  0.364895  0.487376  0.903249  0.613007  0.669848  0.212938      pass
18  0.670761  0.802449  1.634073  1.528016  1.691026  0.523619      pass
19  0.910627  0.657821  1.431825  1.075364  1.205152  0.418392      pass

BARINEL SCORES

         ry 5       h 0      cx 3      cx 4      cx 1     cx 2
sum  0.568963  0.554605  0.519653  0.516081  0.506525  0.49996

TARANTULA SCORES

         ry 5       h 0      cx 3      cx 4      cx 1     cx 2
sum  0.568963  0.554605  0.519653  0.516081  0.506525  0.49996

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cx_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.81it/s]
100%|██████████| 10/10 [00:00<00:00, 11.04it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.069148  0.844132  0.577039  0.571956  0.518272  0.212419      fail
1   0.846854  1.030692  0.517391  0.448752  0.603453  0.138363      fail
2   1.078447  1.463501  0.832525  1.004665  1.251717  0.337968      fail
3   0.708516  0.897041  0.540000  0.835317  1.056922  0.278632      fail
4   0.814472  0.886192  0.481881  0.768636  0.807668  0.225855      fail
5   0.906944  1.250875  0.602110  0.519065  0.772879  0.245131      fail
6   0.849952  0.576715  0.496877  0.832729  1.107108  0.345698      fail
7   1.111040  0.844631  0.510018  0.757786  0.725586  0.213643      fail
8   0.738771  1.030936  0.553294  0.918284  1.238973  0.297855      fail
9   0.956633  1.230941  0.445968  0.674994  0.646369  0.220241      fail
10  0.641686  0.617205  0.329167  0.355501  0.609868  0.191449      pass
11  0.732020  0.516397  0.385406  0.390380  0.416577  0.152540      pass
12  0.881315  0.669157  0.566691  0.586290  0.711259  0.218478      pass
13  0.950168  0.971625  0.662050  0.726859  0.843586  0.227539      pass
14  0.888314  1.243619  0.676758  0.610532  1.024121  0.321373      pass
15  0.936418  0.874578  0.484343  0.587025  0.485874  0.204486      pass
16  0.633169  0.917584  0.476024  0.491696  0.544509  0.193096      pass
17  0.754245  0.925909  0.417219  0.314512  0.495556  0.141736      pass
18  0.798645  0.805893  0.418378  0.299946  0.437437  0.197591      pass
19  0.784226  0.501353  0.465068  0.713362  0.921639  0.210678      pass

BARINEL SCORES

        cx 2      cx 1      cx 4      h 0      cx 3      cx 5
sum  0.59091  0.573542  0.555593  0.54993  0.532381  0.531631

TARANTULA SCORES

        cx 2      cx 1      cx 4      h 0      cx 3      cx 5
sum  0.59091  0.573542  0.555593  0.54993  0.532381  0.531631

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_x_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.51it/s]
100%|██████████| 10/10 [00:01<00:00,  9.76it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       x 0 pass/fail
0   0.776378  0.922426  1.268317  1.491141  0.364032  0.266405      fail
1   1.070529  0.861085  1.091755  1.166972  0.302803  0.201758      fail
2   0.794906  1.016207  1.412194  1.311806  0.287936  0.251421      fail
3   0.734217  0.856055  1.135255  0.833865  0.231867  0.246851      fail
4   0.935780  1.129209  1.347626  1.117861  0.292556  0.263501      fail
5   1.135280  1.133909  1.603213  1.678477  0.359762  0.309781      fail
6   1.025792  1.120234  1.777679  1.790134  0.448862  0.357935      fail
7   1.017700  1.113249  1.192450  1.155294  0.283722  0.297299      fail
8   1.134433  1.116014  1.404912  1.225740  0.332886  0.257691      fail
9   1.056365  1.048369  1.393895  1.710089  0.439294  0.326824      fail
10  1.002730  0.986833  1.184078  1.084920  0.331790  0.270452      pass
11  1.108935  1.116146  1.251260  1.388041  0.345208  0.253164      pass
12  0.614472  0.548458  0.589842  0.754814  0.282984  0.156101      pass
13  0.757792  0.692961  0.951554  1.168302  0.366959  0.184433      pass
14  0.329440  0.491604  0.388126  0.384230  0.172024  0.115627      pass
15  0.887613  0.868750  0.913143  0.926141  0.266445  0.178427      pass
16  1.236317  0.945906  1.075927  1.440024  0.400820  0.226964      pass
17  0.635510  0.462170  0.761208  0.729519  0.183072  0.128875      pass
18  1.130313  1.018081  1.230425  1.499596  0.343243  0.257370      pass
19  0.883738  0.738196  1.225408  1.200328  0.326991  0.258793      pass

BARINEL SCORES

         cx 3       x 0      cx 4      cx 2      cx 5       h 1
sum  0.587427  0.577891  0.567295  0.560386  0.529957  0.525473

TARANTULA SCORES

         cx 3       x 0      cx 4      cx 2      cx 5       h 1
sum  0.587427  0.577891  0.567295  0.560386  0.529957  0.525473

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_rxx_inGap_6_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.74it/s]
100%|██████████| 10/10 [00:00<00:00, 10.28it/s]

       rxx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.419552  0.868415  0.852400  1.152964  1.356014  0.295696      fail
1   0.367010  1.011733  0.748968  0.951401  0.760592  0.208633      fail
2   0.481622  1.364498  0.941547  0.944911  0.818586  0.240318      fail
3   0.402913  1.120454  0.929237  0.889583  0.958417  0.192543      fail
4   0.404282  0.771763  0.831167  0.745286  0.737200  0.202053      fail
5   0.390118  0.985857  0.907428  1.101694  1.367364  0.401667      fail
6   0.342933  0.812329  0.682766  0.831100  0.820638  0.164288      fail
7   0.391844  0.678186  0.804095  0.778361  0.519677  0.184717      fail
8   0.344371  0.626332  0.555751  0.661422  0.575375  0.127603      fail
9   0.425127  1.011031  0.675270  0.794094  1.044970  0.305449      fail
10  0.311747  1.154991  0.893526  1.153802  1.313748  0.400720      pass
11  0.252217  0.609595  0.416351  0.587744  0.622576  0.274295      pass
12  0.451088  0.806187  0.900475  0.766329  1.027596  0.293267      pass
13  0.347602  0.798559  0.787619  0.970444  1.012501  0.348916      pass
14  0.458566  0.909138  0.960647  0.858385  1.344094  0.365037      pass
15  0.205940  0.744698  0.429829  0.782638  1.127599  0.286251      pass
16  0.356742  0.857088  0.686324  0.958199  1.355407  0.399560      pass
17  0.351782  0.805943  0.890584  1.026811  1.186500  0.398729      pass
18  0.289075  1.193872  0.692511  1.005579  0.699602  0.218113      pass
19  0.297202  0.778255  0.516102  0.670288  0.529268  0.233193      pass

BARINEL SCORES

        rxx 5      cx 3      cx 4      cx 2      cx 1       h 0
sum  0.544421  0.524985  0.516536  0.502002  0.467148  0.419229

TARANTULA SCORES

        rxx 5      cx 3      cx 4      cx 2      cx 1       h 0
sum  0.544421  0.524985  0.516536  0.502002  0.467148  0.419229

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rxx_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.00it/s]
100%|██████████| 10/10 [00:00<00:00, 11.73it/s]

        cx 5     rxx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.002029  0.394438  0.786890  0.962800  1.375100  0.398482      fail
1   0.835830  0.376505  0.861811  0.959862  1.146814  0.316538      fail
2   1.010284  0.372227  0.547103  0.837694  0.990076  0.200642      fail
3   0.814004  0.340350  1.011202  1.071957  1.202340  0.354863      fail
4   1.090250  0.381684  0.976862  1.311469  1.530906  0.397629      fail
5   0.734221  0.346077  0.367979  0.641350  0.681811  0.184947      fail
6   1.249298  0.417513  1.053331  1.448205  1.571562  0.368119      fail
7   0.910485  0.360648  0.793390  0.994291  1.056043  0.275698      fail
8   0.944022  0.385898  0.728532  0.943620  1.136536  0.263224      fail
9   0.746637  0.347505  0.490896  0.764581  0.904276  0.249919      fail
10  1.083780  0.315412  0.705171  0.855042  1.277647  0.394460      pass
11  0.963628  0.302258  0.899053  0.610255  0.950031  0.312305      pass
12  0.806840  0.322879  0.611892  0.968590  0.955571  0.260908      pass
13  0.474277  0.291876  0.402895  0.425365  0.671809  0.227259      pass
14  1.256599  0.362457  0.912844  1.127565  1.089029  0.336757      pass
15  0.526031  0.288452  0.708511  0.702602  0.662890  0.190867      pass
16  0.692965  0.203103  0.494367  0.695410  0.930800  0.225469      pass
17  0.727872  0.174339  0.847250  0.849698  0.934356  0.247564      pass
18  0.761388  0.309050  0.482541  0.648539  0.670172  0.254289      pass
19  0.934435  0.386529  0.521950  0.782112  1.043351  0.305356      pass

BARINEL SCORES

         cx 2      cx 1     rxx 4     cx 3      cx 5     h 0
sum  0.564503  0.557981  0.557379  0.53631  0.531576  0.5221

TARANTULA SCORES

         cx 2      cx 1     rxx 4     cx 3      cx 5     h 0
sum  0.564503  0.557981  0.557379  0.53631  0.531576  0.5221

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_ccx_inGap_6_.qasm

100%|██████████| 10/10 [00:02<00:00,  4.21it/s]
100%|██████████| 10/10 [00:02<00:00,  4.05it/s]

       ccx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.157283  0.733143  0.562274  0.731404  0.819863  0.241874      fail
1   1.527079  0.803738  0.613401  0.940929  1.060294  0.278870      fail
2   1.311547  0.788620  0.603670  0.666085  0.847513  0.258476      fail
3   1.448828  0.763308  0.558017  0.658192  0.754762  0.230036      fail
4   1.211049  0.922236  0.615813  0.826183  0.976906  0.277452      fail
5   1.213943  0.717453  0.620866  0.705840  0.816184  0.231986      fail
6   1.039165  0.853478  0.440907  0.721721  0.918715  0.268028      fail
7   1.374002  0.961231  0.675414  0.899110  1.012694  0.298458      fail
8   1.564021  0.735617  0.617974  0.963819  1.042200  0.274328      fail
9   1.175048  0.842480  0.655280  0.897284  0.991493  0.265030      fail
10  1.018393  0.518293  0.329328  0.412354  0.551171  0.163785      pass
11  1.291211  0.516156  0.426652  0.474406  0.594053  0.197088      pass
12  0.789257  0.548067  0.316350  0.456671  0.603053  0.182877      pass
13  1.427881  0.534990  0.661600  0.657709  0.836250  0.250421      pass
14  1.417902  0.604863  0.625635  0.802889  0.890390  0.253148      pass
15  1.005786  0.497912  0.413309  0.640942  0.781681  0.233228      pass
16  1.317068  0.586177  0.475040  0.504113  0.540741  0.158005      pass
17  1.320873  0.665747  0.675617  0.837182  0.943196  0.276137      pass
18  1.222473  0.611967  0.615729  0.745933  0.965276  0.284925      pass
19  1.257552  0.808149  0.569508  0.671271  0.790588  0.236807      pass

BARINEL SCORES

         cx 4      cx 2      cx 1       h 0      cx 3     ccx 5
sum  0.579529  0.563567  0.552107  0.539922  0.538603  0.519003

TARANTULA SCORES

         cx 4      cx 2      cx 1       h 0      cx 3     ccx 5
sum  0.579529  0.563567  0.552107  0.539922  0.538603  0.519003

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rx_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.06it/s]
100%|██████████| 10/10 [00:01<00:00,  9.26it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      rx 0 pass/fail
0   0.842256  0.964269  1.157113  1.092347  0.267808  0.547494      fail
1   0.858049  1.256031  1.339463  1.474277  0.383183  0.506650      fail
2   0.880358  1.021328  1.527971  1.493103  0.329919  0.639090      fail
3   0.745420  0.836311  1.135648  0.886206  0.198247  0.410169      fail
4   0.915601  1.011234  1.102919  0.844970  0.211636  0.484912      fail
5   1.099654  0.986334  1.259351  1.363629  0.348218  0.521998      fail
6   0.928851  0.656542  1.185737  1.079990  0.285411  0.489862      fail
7   1.113953  0.911806  1.088026  1.071447  0.262540  0.428360      fail
8   0.858183  1.011171  1.325592  1.332014  0.365391  0.505746      fail
9   0.922952  0.705076  1.105945  0.893988  0.251868  0.468348      fail
10  1.096503  1.211329  1.413987  1.604936  0.383527  0.629305      pass
11  0.743370  0.426187  0.595032  0.864712  0.264701  0.281431      pass
12  1.139113  0.830911  0.947701  0.792443  0.266433  0.409466      pass
13  0.681857  0.852490  1.000776  1.318446  0.415628  0.455425      pass
14  0.987372  1.098525  1.077895  1.283287  0.370304  0.479448      pass
15  0.695638  0.618728  0.959056  0.792966  0.202851  0.371668      pass
16  1.079516  0.798570  0.978601  0.905630  0.241005  0.399249      pass
17  0.768246  1.050288  1.161291  1.569447  0.377967  0.408878      pass
18  0.747446  0.696421  0.870549  0.821257  0.251521  0.428997      pass
19  1.064413  0.907693  1.342500  1.391201  0.327321  0.513557      pass

BARINEL SCORES

         cx 3      rx 0      cx 4      cx 5      cx 2       h 1
sum  0.541647  0.533326  0.524339  0.504453  0.504101  0.483595

TARANTULA SCORES

         cx 3      rx 0      cx 4      cx 5      cx 2       h 1
sum  0.541647  0.533326  0.524339  0.504453  0.504101  0.483595

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_y_inGap_2_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.20it/s]
100%|██████████| 10/10 [00:01<00:00,  9.50it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       y 0 pass/fail
0   0.891492  0.558358  0.779341  0.834328  0.192818  0.218719      fail
1   0.884757  0.815945  0.898663  0.772143  0.182678  0.207482      fail
2   0.985489  0.602537  0.867113  1.127129  0.269559  0.243293      fail
3   0.839797  0.943265  1.193254  1.407179  0.396189  0.252061      fail
4   0.863202  0.583670  0.936388  1.233704  0.201717  0.261586      fail
5   0.874822  1.026547  1.051916  1.103163  0.273017  0.231042      fail
6   1.101189  0.680863  1.134765  1.337618  0.329646  0.269499      fail
7   0.961077  1.130847  1.463672  1.770507  0.387532  0.324573      fail
8   0.855156  0.868142  1.179082  1.658260  0.301164  0.312225      fail
9   1.133776  1.010428  1.553939  1.797364  0.416607  0.320852      fail
10  0.615965  0.354008  0.409934  0.518092  0.208470  0.131119      pass
11  1.130938  0.870160  0.980979  1.015129  0.282162  0.240257      pass
12  0.861574  0.831674  0.741660  0.794370  0.278674  0.187051      pass
13  1.040148  0.760655  1.006211  0.965128  0.306268  0.207373      pass
14  0.700926  0.622840  0.607745  0.868964  0.263695  0.212638      pass
15  1.041596  1.232377  1.353790  1.568338  0.424047  0.281710      pass
16  0.808556  0.922303  1.007367  0.710596  0.164939  0.187529      pass
17  0.848175  0.979122  1.159900  1.275902  0.231703  0.291756      pass
18  0.732928  0.597947  0.536959  0.572091  0.227263  0.164871      pass
19  0.921884  0.898768  1.088464  1.413429  0.437811  0.220353      pass

BARINEL SCORES

         cx 2      cx 3       y 0      cx 5       h 1      cx 4
sum  0.573414  0.554261  0.554204  0.519014  0.510898  0.504627

TARANTULA SCORES

         cx 2      cx 3       y 0      cx 5       h 1      cx 4
sum  0.573414  0.554261  0.554204  0.519014  0.510898  0.504627

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_sx_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  7.78it/s]
100%|██████████| 10/10 [00:00<00:00, 10.24it/s]

        cx 5      cx 4      cx 3      cx 2       h 1    sxdg 0 pass/fail
0   0.489993  0.729844  0.819322  0.901531  0.210394  0.595975      fail
1   1.233242  1.013115  1.406361  1.393201  0.373569  0.766436      fail
2   0.935762  1.047890  1.127516  1.253118  0.429532  0.830666      fail
3   0.740579  1.027300  0.928902  0.963678  0.272191  0.747727      fail
4   1.032056  0.608703  0.829581  1.156216  0.245052  0.650599      fail
5   0.902694  0.735512  0.711725  0.724727  0.248986  0.653062      fail
6   0.847990  1.005251  1.283499  1.376606  0.269912  0.646145      fail
7   0.953237  1.073747  1.237346  1.312605  0.328350  0.729375      fail
8   0.711486  0.813195  0.582542  0.722896  0.199306  0.667037      fail
9   1.128253  0.886825  1.185438  1.176940  0.274701  0.790862      fail
10  0.707189  0.832355  1.109839  1.139907  0.287236  0.568119      pass
11  0.996910  0.466715  0.666920  0.733649  0.289320  0.564233      pass
12  0.870122  0.935501  1.152506  1.033354  0.278780  0.622404      pass
13  0.827025  0.940394  1.088366  0.929730  0.298937  0.640770      pass
14  1.079068  0.748043  0.847563  0.907415  0.228107  0.630053      pass
15  0.498004  0.480837  0.397548  0.348408  0.152939  0.371815      pass
16  0.770340  0.962111  1.052902  0.986137  0.286741  0.679775      pass
17  0.892199  0.805225  0.855518  1.002664  0.291682  0.617565      pass
18  1.077670  0.606468  1.025895  1.363160  0.376438  0.644902      pass
19  0.578424  0.546982  0.692419  0.853953  0.283023  0.480733      pass

BARINEL SCORES

         cx 4    sxdg 0      cx 2      cx 3      cx 5       h 1
sum  0.549697  0.548747  0.541498  0.532175  0.519637  0.507003

TARANTULA SCORES

         cx 4    sxdg 0      cx 2      cx 3      cx 5       h 1
sum  0.549697  0.548747  0.541498  0.532175  0.519637  0.507003

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_swap_inGap_4_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.79it/s]
100%|██████████| 10/10 [00:00<00:00, 10.93it/s]

        cx 5      cx 4    swap 3      cx 2      cx 1       h 0 pass/fail
0   1.081688  0.735683  0.189413  1.148163  0.960893  0.277371      fail
1   0.830162  1.108200  0.175062  1.152219  1.341103  0.318658      fail
2   0.801258  0.513927  0.187513  0.860296  1.009240  0.233580      fail
3   0.957132  0.620457  0.223303  0.882079  0.668960  0.235567      fail
4   0.710163  0.540909  0.137627  0.616165  0.626500  0.150554      fail
5   0.787896  0.640523  0.214043  0.748622  0.811543  0.228545      fail
6   1.135529  0.885198  0.184651  1.016844  1.104879  0.394079      fail
7   1.003608  1.074585  0.157530  1.130951  1.534687  0.364533      fail
8   0.936771  0.855602  0.181503  1.235743  1.338501  0.372691      fail
9   0.835242  0.855479  0.231259  0.802341  0.718376  0.304357      fail
10  0.800711  0.712516  0.168832  0.636689  0.755072  0.255170      pass
11  0.774002  0.783783  0.122234  0.699383  0.851633  0.262712      pass
12  1.072997  1.117181  0.156941  0.972774  1.129892  0.244949      pass
13  1.148479  0.755911  0.113939  1.031268  1.105239  0.393507      pass
14  0.644566  0.594758  0.204056  0.926027  0.708628  0.241042      pass
15  0.745105  0.892200  0.128958  1.048039  1.019501  0.218698      pass
16  0.988255  0.493674  0.076329  0.922828  0.893356  0.252706      pass
17  1.021974  0.576815  0.115814  0.876554  0.766214  0.175978      pass
18  0.876983  0.927044  0.102823  0.917998  0.770443  0.243593      pass
19  1.133803  1.089714  0.148086  1.079410  1.103787  0.324821      pass

BARINEL SCORES

       swap 3      cx 1       h 0      cx 2      cx 5      cx 4
sum  0.584457  0.526301  0.524281  0.512897  0.496516  0.496417

TARANTULA SCORES

       swap 3      cx 1       h 0      cx 2      cx 5      cx 4
sum  0.584457  0.526301  0.524281  0.512897  0.496516  0.496417

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_rxx_inGap_2_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.09it/s]
100%|██████████| 10/10 [00:00<00:00, 11.16it/s]

        cx 5      cx 4      cx 3      cx 2     rxx 1       h 0 pass/fail
0   0.797952  0.672889  0.815685  0.950858  1.051559  0.470530      fail
1   0.758583  0.561272  0.530427  0.689253  0.849456  0.348106      fail
2   0.878667  0.765057  0.925727  1.259536  0.926831  0.519896      fail
3   0.785366  0.577199  1.057530  1.185482  0.929281  0.488625      fail
4   1.098646  0.954367  1.103117  0.956896  1.190395  0.497194      fail
5   0.993438  0.796819  1.121924  1.457941  1.051131  0.582698      fail
6   1.187318  1.157411  1.363478  1.927746  1.070853  0.681684      fail
7   1.078806  0.916126  1.255502  1.461505  0.866838  0.547338      fail
8   0.975634  1.000249  1.143799  1.125524  1.040972  0.503629      fail
9   0.801696  0.730252  0.777622  0.909308  0.959430  0.417321      fail
10  0.628764  0.627238  0.610416  0.795250  0.667019  0.359901      pass
11  0.710324  0.655809  0.966659  0.953606  0.692028  0.381176      pass
12  0.451546  0.513962  0.478425  0.441410  0.748500  0.262657      pass
13  0.827851  0.414863  0.632509  0.889884  0.601791  0.352764      pass
14  0.985924  0.543846  0.650733  0.949292  0.666298  0.387534      pass
15  0.939544  0.894578  0.994285  1.219753  0.711859  0.460229      pass
16  0.537107  0.612615  0.805644  0.628866  0.609501  0.282137      pass
17  0.742427  1.195139  1.470373  1.895936  0.746269  0.617981      pass
18  0.932462  0.792481  0.980547  1.009034  1.014490  0.445302      pass
19  0.964060  1.267618  1.369544  1.407013  1.008854  0.563428      pass

BARINEL SCORES

        rxx 1       h 0      cx 5      cx 2      cx 3      cx 4
sum  0.570967  0.551467  0.547906  0.539206  0.529802  0.519601

TARANTULA SCORES

        rxx 1       h 0      cx 5      cx 2      cx 3      cx 4
sum  0.570967  0.551467  0.547906  0.539206  0.529802  0.519601

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_rx_inGap_10_.qasm

100%|██████████| 10/10 [00:00<00:00, 12.08it/s]
100%|██████████| 10/10 [00:00<00:00, 13.93it/s]

        rx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.938316  1.089111  0.856872  0.956962  1.172901  0.495849      fail
1   1.088962  1.385394  1.040075  1.432684  1.791681  0.653387      fail
2   1.038852  1.056210  1.030329  1.321308  1.581138  0.641273      fail
3   1.268074  1.234438  1.077758  1.520400  2.035654  0.726391      fail
4   1.102543  1.079419  0.648170  0.609628  0.912596  0.391892      fail
5   1.005843  1.198323  0.785471  0.923512  1.039349  0.483268      fail
6   1.020043  1.160644  0.859860  0.938360  1.491346  0.525895      fail
7   1.311881  0.938217  0.716065  0.743185  1.203786  0.475790      fail
8   0.960312  1.048515  0.841475  1.114654  1.323925  0.515257      fail
9   0.998864  1.168456  0.566656  0.764669  1.144875  0.475742      fail
10  1.227556  1.184195  0.993075  1.170052  1.183264  0.541434      pass
11  1.101010  0.970485  0.680467  0.457508  0.778884  0.347289      pass
12  0.858205  0.829465  0.972136  1.125531  1.607000  0.491438      pass
13  0.836792  0.826030  0.920810  0.971018  1.281845  0.445537      pass
14  0.589132  0.775606  0.742811  0.622692  1.042053  0.337823      pass
15  1.006137  1.256648  1.126692  1.326716  1.941361  0.619198      pass
16  0.828309  0.675305  0.678244  0.731960  0.666787  0.329959      pass
17  0.753571  0.652019  0.714684  0.781295  0.782520  0.355386      pass
18  1.046498  1.416646  0.871799  1.037323  1.556981  0.601860      pass
19  0.774255  0.620967  0.752807  0.824738  1.156432  0.376813      pass

BARINEL SCORES

         cx 4       h 0      rx 5      cx 1      cx 2      cx 3
sum  0.552304  0.547704  0.543336  0.533084  0.532944  0.499088

TARANTULA SCORES

         cx 4       h 0      rx 5      cx 1      cx 2      cx 3
sum  0.552304  0.547704  0.543336  0.533084  0.532944  0.499088

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ry_inGap_4_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.47it/s]
100%|██████████| 10/10 [00:00<00:00, 11.39it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      ry 0 pass/fail
0   1.130967  0.819637  1.051141  0.861138  0.196234  0.233878      fail
1   0.881935  0.788655  1.121149  1.204384  0.260301  0.235510      fail
2   0.654034  0.640788  0.752705  1.112213  0.214079  0.238498      fail
3   0.697591  0.857007  1.070878  1.082465  0.256986  0.264889      fail
4   1.075714  0.820313  0.926589  1.150663  0.276519  0.257438      fail
5   0.772967  0.893912  0.934664  1.034603  0.225854  0.261669      fail
6   0.828856  1.027886  1.374881  1.810635  0.416466  0.301567      fail
7   0.963475  0.978532  0.917648  0.970004  0.269965  0.227150      fail
8   0.953218  0.973413  0.887398  1.061917  0.270793  0.259717      fail
9   0.912136  0.716396  0.836370  0.942481  0.176502  0.230334      fail
10  0.897251  1.078823  1.300239  1.298727  0.291882  0.291489      pass
11  0.748060  0.817055  1.028897  1.011130  0.300029  0.197120      pass
12  0.936209  0.612516  0.916570  1.118843  0.328307  0.169623      pass
13  0.575522  0.905024  1.100928  1.134179  0.261325  0.213730      pass
14  0.888859  0.771654  0.952738  1.126427  0.367202  0.165014      pass
15  0.694748  0.259944  0.497644  0.751807  0.239678  0.099396      pass
16  0.876608  0.624013  0.694942  1.299391  0.310508  0.160499      pass
17  1.060541  0.952359  1.206209  1.585451  0.352468  0.236147      pass
18  0.809018  0.386321  0.444632  0.798686  0.252787  0.170575      pass
19  0.881952  0.645756  0.571193  0.610929  0.207373  0.195146      pass

BARINEL SCORES

         ry 0      cx 4      cx 3      cx 5      cx 2       h 1
sum  0.569387  0.546984  0.531189  0.514563  0.511266  0.468234

TARANTULA SCORES

         ry 0      cx 4      cx 3      cx 5      cx 2       h 1
sum  0.569387  0.546984  0.531189  0.514563  0.511266  0.468234

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_rx_inGap_2_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.84it/s]
100%|██████████| 10/10 [00:00<00:00, 12.24it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      rx 0 pass/fail
0   0.958257  0.788920  0.778000  1.042558  0.245944  0.237849      fail
1   1.050393  1.095182  1.431506  1.705740  0.391680  0.317937      fail
2   1.023689  0.973155  1.093214  1.163350  0.290736  0.228061      fail
3   0.933790  1.162599  1.397462  1.567254  0.312196  0.279756      fail
4   0.846184  0.558417  0.735349  0.857248  0.233390  0.231498      fail
5   0.934863  1.039677  1.150130  1.259317  0.351328  0.241612      fail
6   1.016865  0.978769  1.177248  1.507421  0.358799  0.271261      fail
7   1.024375  1.061846  1.098491  1.482776  0.304498  0.269405      fail
8   0.994927  0.581669  0.888466  0.993274  0.180034  0.268392      fail
9   0.508770  0.493728  0.683703  0.969423  0.164834  0.226357      fail
10  0.605872  0.506758  0.598534  0.828438  0.216892  0.182555      pass
11  0.701661  0.536277  0.731035  0.626935  0.255424  0.153206      pass
12  0.834575  1.035318  1.317789  1.298210  0.330708  0.212291      pass
13  0.988630  0.497558  0.794965  1.215907  0.288862  0.235240      pass
14  0.516643  1.116990  1.260191  1.144450  0.237349  0.216730      pass
15  0.600606  0.429096  0.610396  0.513657  0.170397  0.125681      pass
16  0.918603  1.474473  1.560302  2.027706  0.456659  0.316679      pass
17  0.998702  0.573546  0.617776  0.765444  0.291505  0.166871      pass
18  0.624041  0.717213  0.944111  0.957387  0.277608  0.182063      pass
19  0.804020  0.737809  0.667778  0.825128  0.239355  0.137630      pass

BARINEL SCORES

         rx 0      cx 2      cx 5      cx 3      cx 4       h 1
sum  0.571447  0.551537  0.550302  0.534057  0.533893  0.506134

TARANTULA SCORES

         rx 0      cx 2      cx 5      cx 3      cx 4       h 1
sum  0.571447  0.551537  0.550302  0.534057  0.533893  0.506134

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_cswap_inGap_4_.qasm

100%|██████████| 10/10 [00:02<00:00,  4.56it/s]
100%|██████████| 10/10 [00:02<00:00,  4.82it/s]

        cx 5      cx 4   cswap 3      cx 2      cx 1       h 0 pass/fail
0   1.072329  0.755793  0.603476  0.780900  0.862442  0.314797      fail
1   1.127279  0.852488  0.878701  0.926342  1.012355  0.353845      fail
2   0.786852  0.915684  0.677017  0.833374  0.897251  0.312833      fail
3   0.916495  0.889276  0.596247  0.777901  0.892396  0.305508      fail
4   1.162562  1.151319  0.710763  0.946080  0.957455  0.337418      fail
5   1.066915  1.043767  0.794086  0.965595  1.002759  0.321051      fail
6   1.133977  1.037247  0.593819  0.925329  1.000121  0.324681      fail
7   0.994880  0.743554  0.728438  0.856694  0.935076  0.291678      fail
8   1.344956  1.144572  0.890757  1.029987  1.285360  0.440498      fail
9   0.709205  0.809924  0.732695  0.774042  0.922079  0.269910      fail
10  0.955913  0.854129  0.651568  0.783911  0.912862  0.263170      pass
11  0.731362  0.652246  0.588154  0.607824  0.602465  0.227208      pass
12  0.667817  0.731789  0.476720  0.753572  0.728348  0.241061      pass
13  0.652836  0.744364  0.786022  0.691043  0.879703  0.285058      pass
14  0.938748  0.461861  0.789883  0.601451  0.713411  0.265338      pass
15  0.966716  0.778435  0.641982  0.798862  0.891558  0.273433      pass
16  0.886793  0.996546  0.854573  0.932141  1.253573  0.382473      pass
17  1.053738  0.932143  0.874926  0.946092  1.016992  0.319533      pass
18  0.489733  0.346240  0.503698  0.432202  0.592955  0.203207      pass
19  0.725802  0.590101  0.701007  0.605419  0.806839  0.262531      pass

BARINEL SCORES

         cx 4      cx 5      cx 2       h 0      cx 1   cswap 3
sum  0.568642  0.561083  0.552093  0.545803  0.537669  0.511988

TARANTULA SCORES

         cx 4      cx 5      cx 2       h 0      cx 1   cswap 3
sum  0.568642  0.561083  0.552093  0.545803  0.537669  0.511988

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_ry_inGap_2_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.05it/s]
100%|██████████| 10/10 [00:00<00:00, 11.49it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      ry 0 pass/fail
0   0.828449  0.711907  0.859398  1.156951  0.279504  0.249658      fail
1   0.933121  0.789899  0.973011  1.315630  0.270333  0.265397      fail
2   1.175893  1.105211  1.458429  1.461741  0.325667  0.283106      fail
3   0.838988  1.018634  1.258172  1.382798  0.302123  0.247840      fail
4   1.177701  0.648394  0.833326  0.968251  0.248163  0.282657      fail
5   1.176684  0.876082  1.185002  1.143809  0.291710  0.274915      fail
6   1.062700  0.939113  0.989659  1.208692  0.299732  0.244636      fail
7   0.717349  0.413743  0.400448  0.838400  0.171912  0.221310      fail
8   1.094225  0.632979  0.899496  1.148985  0.271269  0.291289      fail
9   0.895148  0.949674  1.223201  1.450507  0.331056  0.289510      fail
10  0.745174  0.667893  0.935991  1.114035  0.259271  0.225266      pass
11  0.873468  0.789116  1.032547  1.314239  0.338213  0.207700      pass
12  1.133204  0.917882  1.188874  1.262453  0.319736  0.232623      pass
13  0.746547  0.311822  0.365566  0.544362  0.157980  0.166822      pass
14  1.092258  1.111597  1.321621  1.377546  0.321037  0.229271      pass
15  0.835306  0.481784  0.779880  0.966617  0.236581  0.216880      pass
16  1.076474  1.079012  1.069780  1.307123  0.376400  0.250445      pass
17  0.952646  0.731997  0.822968  1.095369  0.322604  0.223047      pass
18  1.043860  1.207932  1.399412  1.406909  0.403444  0.232849      pass
19  0.867134  0.850813  0.924000  0.599623  0.315926  0.130397      pass

BARINEL SCORES

         ry 0      cx 2      cx 5      cx 3      cx 4       h 1
sum  0.556133  0.523575  0.513863  0.506011  0.498022  0.477774

TARANTULA SCORES

         ry 0      cx 2      cx 5      cx 3      cx 4       h 1
sum  0.556133  0.523575  0.513863  0.506011  0.498022  0.477774

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_rxx_inGap_10_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.83it/s]
100%|██████████| 10/10 [00:00<00:00, 12.77it/s]

       rxx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.763887  1.392684  1.279328  1.736436  1.649522  0.706598      fail
1   1.914556  0.919486  1.172911  1.967633  1.806057  0.737462      fail
2   1.674040  1.306331  1.284883  2.129602  1.773539  0.773636      fail
3   1.726361  1.646323  1.433626  2.081380  2.147110  0.802002      fail
4   1.859237  1.350735  1.138200  1.943737  1.659791  0.676827      fail
5   1.443547  1.185325  1.107874  1.453088  1.335037  0.577199      fail
6   1.724420  0.723503  0.815460  1.364974  0.993787  0.432228      fail
7   1.449155  1.282797  1.063422  1.586841  1.199387  0.589539      fail
8   1.929710  1.021681  1.022300  1.802890  1.267385  0.621653      fail
9   1.859304  1.339381  1.467244  1.968871  1.759930  0.761334      fail
10  1.544196  1.369448  1.121852  2.025023  1.851004  0.629334      pass
11  1.738391  1.224894  1.153563  1.612959  1.299377  0.620643      pass
12  1.706094  0.993547  1.112091  1.943399  1.736102  0.699901      pass
13  1.201689  1.215288  1.171795  1.762144  1.796777  0.583234      pass
14  0.869258  0.810169  0.383532  0.803636  0.768366  0.316177      pass
15  1.431198  1.331770  0.531131  1.381538  1.016203  0.445937      pass
16  1.100256  1.082825  1.082801  1.551978  1.653496  0.611122      pass
17  1.054558  0.965626  0.818746  1.295389  1.154140  0.439443      pass
18  0.949973  0.973148  0.638723  1.295003  1.035001  0.436430      pass
19  1.306539  1.061972  1.166338  1.459757  1.454973  0.555978      pass

BARINEL SCORES

        rxx 5      cx 3       h 0      cx 2      cx 1      cx 4
sum  0.573431  0.562117  0.555768  0.543789  0.531102  0.524563

TARANTULA SCORES

        rxx 5      cx 3       h 0      cx 2      cx 1      cx 4
sum  0.573431  0.562117  0.555768  0.543789  0.531102  0.524563

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rxx_inGap_1_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.61it/s]
100%|██████████| 10/10 [00:00<00:00, 11.86it/s]

        cx 5      cx 4      cx 3      cx 2       h 1     rxx 0 pass/fail
0   1.031313  0.870261  1.135764  1.134551  0.282784  1.006735      fail
1   0.811440  0.535783  0.636224  0.662644  0.166849  0.591354      fail
2   1.077478  0.881668  0.900865  0.989692  0.313139  0.941040      fail
3   1.051904  0.974331  1.187535  1.416557  0.302860  1.290619      fail
4   0.976999  0.518935  0.820774  1.050846  0.196038  0.860839      fail
5   1.005815  0.944680  1.021386  1.296592  0.273389  1.168101      fail
6   0.979245  0.892858  0.718805  0.826731  0.218202  0.792108      fail
7   0.884429  0.903075  1.031336  1.030089  0.231972  1.027191      fail
8   1.112156  1.269510  1.308173  1.515179  0.333965  1.364267      fail
9   0.644697  0.674364  0.761732  0.695397  0.148466  0.713724      fail
10  0.980830  0.795434  0.739555  0.735130  0.241634  0.527956      pass
11  0.836362  0.975444  1.106257  1.148265  0.355262  0.862835      pass
12  0.829740  0.687282  0.556250  0.462731  0.235679  0.375481      pass
13  0.925184  0.828121  0.847104  0.970840  0.356527  0.793286      pass
14  0.806152  0.731097  1.076231  1.144917  0.321338  0.885595      pass
15  0.594201  0.392779  0.362190  0.551120  0.303425  0.448071      pass
16  1.028692  1.024698  1.341238  1.514925  0.374602  1.220624      pass
17  0.516737  0.584169  0.417460  0.647108  0.229748  0.483701      pass
18  0.805743  0.633084  0.632187  0.654769  0.151054  0.699474      pass
19  0.525561  0.409297  0.566900  0.511876  0.152765  0.468294      pass

BARINEL SCORES

        rxx 0      cx 2      cx 3      cx 5      cx 4       h 1
sum  0.590509  0.560037  0.554672  0.549535  0.545214  0.475493

TARANTULA SCORES

        rxx 0      cx 2      cx 3      cx 5      cx 4       h 1
sum  0.590509  0.560037  0.554672  0.549535  0.545214  0.475493

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_swap_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.93it/s]
100%|██████████| 10/10 [00:00<00:00, 10.93it/s]

        cx 5      cx 4      cx 3    swap 2      cx 1       h 0 pass/fail
0   0.784639  0.366430  0.727205  0.170056  0.806183  0.216871      fail
1   0.952163  0.910363  1.032670  0.096011  1.257732  0.344411      fail
2   1.085505  0.758906  0.908164  0.234652  1.219764  0.285752      fail
3   0.877842  1.053090  0.764204  0.125954  0.823666  0.199714      fail
4   0.881681  0.714754  0.783579  0.145426  0.823536  0.189869      fail
5   0.816452  0.909069  1.176014  0.195878  1.232775  0.375565      fail
6   1.077146  0.956820  1.154991  0.142393  1.342726  0.367876      fail
7   0.828444  0.849138  0.533326  0.197365  0.888688  0.213292      fail
8   1.150441  0.744299  0.859057  0.190520  1.114327  0.266445      fail
9   0.739472  0.681809  0.515336  0.134670  0.527245  0.175375      fail
10  0.591058  0.816665  0.896121  0.134365  1.008807  0.156545      pass
11  0.878597  0.783728  1.037000  0.084072  1.203180  0.301449      pass
12  0.583166  0.849691  0.809227  0.129649  0.860706  0.201205      pass
13  0.911973  0.918682  1.448772  0.165460  1.278441  0.338330      pass
14  0.898792  0.801480  1.175846  0.127708  1.015425  0.186240      pass
15  0.868294  0.911340  0.879943  0.105691  0.999578  0.243884      pass
16  0.982745  0.837293  0.876724  0.152898  0.893148  0.185746      pass
17  1.131832  1.138184  1.432225  0.110393  1.140894  0.275518      pass
18  0.737386  0.634807  0.893002  0.110950  0.850913  0.178912      pass
19  0.758427  0.715275  0.795561  0.108687  0.915791  0.264573      pass

BARINEL SCORES

       swap 2       h 0      cx 5      cx 1      cx 4     cx 3
sum  0.570395  0.530474  0.524279  0.496777  0.485859  0.45214

TARANTULA SCORES

       swap 2       h 0      cx 5      cx 1      cx 4     cx 3
sum  0.570395  0.530474  0.524279  0.496777  0.485859  0.45214

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_cswap_inGap_3_.qasm

100%|██████████| 10/10 [00:02<00:00,  4.94it/s]
100%|██████████| 10/10 [00:01<00:00,  5.37it/s]

        cx 5      cx 4      cx 3   cswap 2      cx 1       h 0 pass/fail
0   0.921128  0.962890  1.202728  0.725835  0.993202  0.284079      fail
1   0.938596  0.842225  0.880202  0.728615  0.755103  0.281105      fail
2   1.095374  0.862697  1.220505  0.836917  1.082276  0.338196      fail
3   1.200069  0.829208  0.961362  0.769551  0.851871  0.278574      fail
4   0.624701  0.544998  0.689630  0.470072  0.648245  0.189028      fail
5   1.060043  0.861140  1.154569  0.780337  0.911678  0.290911      fail
6   1.079858  0.656179  0.821363  0.698534  0.819026  0.260896      fail
7   1.136960  1.177994  1.351140  0.911784  1.060229  0.342219      fail
8   0.843635  1.095629  1.164516  0.781158  0.996996  0.301134      fail
9   0.813227  0.656477  0.506522  0.732272  0.596827  0.257580      fail
10  0.688795  0.827404  0.960172  0.727083  0.955095  0.307482      pass
11  1.066079  0.979800  0.985158  0.850786  0.929904  0.289791      pass
12  0.695235  0.465802  0.498401  0.673993  0.704442  0.206372      pass
13  0.476541  0.368490  0.205880  0.423146  0.324535  0.146510      pass
14  0.806695  1.022194  1.225628  0.823459  1.003403  0.291626      pass
15  0.863819  0.409892  0.429060  0.680661  0.573522  0.227365      pass
16  0.726227  0.977913  1.302419  0.652185  0.923182  0.291238      pass
17  0.658738  0.603853  0.726443  0.679776  0.761907  0.240735      pass
18  0.587138  0.468650  0.648103  0.573619  0.602989  0.204339      pass
19  0.801427  0.367618  0.722703  0.600208  0.653755  0.259933      pass

BARINEL SCORES

         cx 5      cx 4      cx 3      cx 1       h 0   cswap 2
sum  0.568569  0.566678  0.563675  0.539717  0.533875  0.526564

TARANTULA SCORES

         cx 5      cx 4      cx 3      cx 1       h 0   cswap 2
sum  0.568569  0.566678  0.563675  0.539717  0.533875  0.526564

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_sx_inGap_3_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.09it/s]
100%|██████████| 10/10 [00:00<00:00, 11.65it/s]

        cx 5      cx 4      cx 3      cx 2       h 1    sxdg 0 pass/fail
0   1.160157  1.376435  1.538714  1.442204  0.384738  0.937508      fail
1   1.226252  1.122732  1.461354  1.404920  0.368010  0.917888      fail
2   0.901041  0.865803  1.243739  1.547423  0.346777  0.750562      fail
3   0.560776  0.451935  0.699022  0.685959  0.148699  0.534359      fail
4   0.786649  0.682917  0.723905  0.512115  0.214143  0.586573      fail
5   0.945930  1.288841  1.542290  1.364114  0.402439  0.864473      fail
6   0.646850  0.786030  1.276109  1.311669  0.297602  0.637150      fail
7   0.833645  1.278408  1.296686  1.222279  0.301969  0.736256      fail
8   1.023445  1.028754  1.135548  1.074297  0.335001  0.720214      fail
9   0.855559  1.040561  1.413716  1.313825  0.312576  0.778850      fail
10  0.825478  0.705503  0.842005  0.765991  0.225137  0.432612      pass
11  0.609873  0.441708  0.669128  0.650502  0.249508  0.485294      pass
12  0.926576  0.660955  0.847878  0.930587  0.291775  0.578056      pass
13  1.003108  0.854455  1.061991  1.079782  0.263063  0.580279      pass
14  0.996249  1.044511  1.283331  1.371021  0.322524  0.678257      pass
15  0.897057  0.839128  1.248002  1.515804  0.434900  0.820645      pass
16  0.422451  0.781105  0.824695  0.817804  0.235718  0.550066      pass
17  0.795240  0.634262  0.611420  0.653716  0.231932  0.409151      pass
18  0.752503  0.853930  1.085007  1.198315  0.392104  0.586424      pass
19  0.861570  0.607974  0.753609  0.642705  0.220262  0.465564      pass

BARINEL SCORES

         cx 4      cx 3    sxdg 0      cx 2      cx 5       h 1
sum  0.572031  0.571992  0.571933  0.552373  0.524961  0.520491

TARANTULA SCORES

         cx 4      cx 3    sxdg 0      cx 2      cx 5       h 1
sum  0.572031  0.571992  0.571933  0.552373  0.524961  0.520491

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_rx_inGap_9_.qasm

100%|██████████| 10/10 [00:00<00:00, 12.88it/s]
100%|██████████| 10/10 [00:00<00:00, 13.03it/s]

        rx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.703515  1.272266  0.776632  1.200195  1.337307  0.557009      fail
1   0.749361  1.118213  0.740207  1.248881  1.425792  0.507566      fail
2   0.674368  1.272575  1.079925  1.910691  2.072623  0.609923      fail
3   0.542784  1.259413  0.791250  1.218051  1.289969  0.405622      fail
4   0.696590  0.929830  0.833921  1.388544  1.453939  0.513136      fail
5   0.536240  1.203010  1.285675  1.700140  1.740895  0.489448      fail
6   0.607461  0.703655  0.921878  1.321038  1.385892  0.465992      fail
7   0.569535  0.603931  0.542178  0.888958  1.061861  0.277733      fail
8   0.671209  1.174393  1.078819  1.422356  1.437046  0.501622      fail
9   0.571584  0.999976  1.037223  1.397091  1.557911  0.552321      fail
10  0.611835  1.043224  0.950912  1.233254  1.136973  0.471140      pass
11  0.359297  0.731494  0.610537  1.065638  1.473538  0.406166      pass
12  0.693205  1.296830  0.898166  1.241614  1.013975  0.494818      pass
13  0.565600  0.934315  0.874891  1.382414  1.381194  0.581248      pass
14  0.716344  1.292741  0.736053  1.272486  1.337122  0.467468      pass
15  0.486658  1.086392  1.266082  1.640859  1.630478  0.498354      pass
16  0.488862  0.904352  1.223749  1.323116  1.165391  0.389378      pass
17  0.492829  1.128172  0.829814  1.385441  1.444033  0.493217      pass
18  0.551686  1.070976  0.734128  1.459065  1.968036  0.625311      pass
19  0.662091  1.108696  0.950216  1.542642  1.896660  0.631789      pass

BARINEL SCORES

         rx 5      cx 1      cx 2      cx 3      cx 4      h 0
sum  0.529045  0.505406  0.502742  0.500362  0.498582  0.49102

TARANTULA SCORES

         rx 5      cx 1      cx 2      cx 3      cx 4      h 0
sum  0.529045  0.505406  0.502742  0.500362  0.498582  0.49102

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rx_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.99it/s]
100%|██████████| 10/10 [00:00<00:00, 12.24it/s]

        rx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.802531  1.551949  0.896775  1.439867  1.402059  0.350598      fail
1   1.336714  2.127129  1.367623  1.360821  1.240152  0.463241      fail
2   0.965615  1.762246  1.017115  0.894342  0.986013  0.321033      fail
3   0.697791  1.439349  1.001452  0.957484  0.642547  0.249660      fail
4   1.020833  1.647750  1.063656  1.515110  1.561768  0.432798      fail
5   0.940549  1.740139  1.496429  1.869041  1.881018  0.470896      fail
6   0.941654  1.984607  1.292004  1.674969  1.998651  0.450666      fail
7   1.113544  1.767155  1.133873  1.062033  0.988780  0.396277      fail
8   0.857295  1.642647  1.550805  1.788216  1.539075  0.426851      fail
9   1.208449  1.939670  1.141986  1.326268  1.535851  0.519763      fail
10  0.922619  1.942645  1.259788  1.224987  1.463749  0.433000      pass
11  0.918126  1.602619  1.195248  1.103381  1.458711  0.477233      pass
12  0.476881  1.490951  1.662441  1.803259  1.870517  0.512207      pass
13  0.912109  1.750094  1.107726  0.954945  0.993413  0.401792      pass
14  0.889490  1.643736  0.937001  0.915078  0.848301  0.353663      pass
15  0.744711  1.412611  0.929770  1.154347  1.309705  0.492223      pass
16  1.197328  2.140337  1.289842  1.325242  2.034520  0.666190      pass
17  0.658641  1.795492  1.741337  1.518815  1.705971  0.688057      pass
18  0.496362  1.264158  1.222629  1.321328  1.346715  0.326553      pass
19  0.687535  1.468502  1.043166  1.284254  1.136847  0.438411      pass

BARINEL SCORES

         rx 5      cx 2      cx 4      cx 1      cx 3       h 0
sum  0.555686  0.524204  0.515998  0.492977  0.491228  0.460121

TARANTULA SCORES

         rx 5      cx 2      cx 4      cx 1      cx 3       h 0
sum  0.555686  0.524204  0.515998  0.492977  0.491228  0.460121

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cx_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.19it/s]
100%|██████████| 10/10 [00:00<00:00, 12.61it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.072152  0.664736  0.323686  0.827230  0.958324  0.244777      fail
1   0.878158  0.831865  0.353371  0.809109  1.027978  0.292213      fail
2   0.931227  0.743972  0.441781  0.775620  0.745740  0.215107      fail
3   1.111868  0.883217  0.455177  0.803842  0.684423  0.280052      fail
4   0.990386  0.956867  0.349203  0.661289  0.885124  0.279057      fail
5   1.198104  0.583524  0.256302  0.858269  0.823337  0.291414      fail
6   1.137343  0.624288  0.275123  0.801415  0.928608  0.231545      fail
7   0.923713  0.577775  0.275421  0.717901  0.883045  0.266981      fail
8   1.172562  1.072593  0.346760  0.827510  1.070418  0.310883      fail
9   1.338072  0.869737  0.396210  0.808841  0.945045  0.304805      fail
10  0.630889  0.353764  0.475494  0.704853  0.729303  0.207441      pass
11  0.551904  0.510755  0.384322  0.618742  0.806722  0.181622      pass
12  1.250820  1.064776  0.267851  0.797014  1.021567  0.299490      pass
13  1.064724  0.585244  0.523960  1.059120  0.951850  0.287390      pass
14  0.814176  0.871367  0.442690  0.736382  0.659018  0.262711      pass
15  0.799416  0.921036  0.431110  0.619009  0.825664  0.232835      pass
16  0.925656  0.979480  0.574490  0.969527  1.002500  0.304607      pass
17  0.889263  0.606048  0.468993  0.921348  1.168244  0.274744      pass
18  1.123547  0.756734  0.155226  0.539111  0.534732  0.153160      pass
19  0.599275  0.821963  0.507892  0.801711  0.721939  0.170573      pass

BARINEL SCORES

         cx 5       h 0      cx 1      cx 4      cx 2      cx 3
sum  0.554216  0.533612  0.515268  0.511041  0.503966  0.450747

TARANTULA SCORES

         cx 5       h 0      cx 1      cx 4      cx 2      cx 3
sum  0.554216  0.533612  0.515268  0.511041  0.503966  0.450747

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_x_inGap_2_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.76it/s]
100%|██████████| 10/10 [00:00<00:00, 12.08it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       x 0 pass/fail
0   1.091566  0.816818  1.062806  1.215716  0.268525  0.291514      fail
1   0.779555  1.214546  1.550697  1.722094  0.349494  0.295220      fail
2   1.057597  1.178321  1.458231  1.722529  0.439236  0.304084      fail
3   0.947112  1.114763  1.368681  1.418968  0.353975  0.241858      fail
4   0.885297  0.607742  0.731370  0.903964  0.260270  0.185030      fail
5   0.878626  0.807803  1.123338  1.236505  0.284719  0.242288      fail
6   1.089187  0.809968  1.176883  1.662682  0.341210  0.325396      fail
7   0.829303  0.706972  0.851988  0.968309  0.260370  0.232926      fail
8   1.107401  1.231172  1.508397  1.433658  0.323464  0.278284      fail
9   0.944626  0.839748  1.210926  1.433273  0.372631  0.256993      fail
10  0.880431  1.109107  1.514952  1.399822  0.410247  0.210240      pass
11  0.838584  0.848422  1.076702  1.175770  0.319460  0.216216      pass
12  0.930321  1.311802  1.518072  1.431698  0.381002  0.249176      pass
13  1.044843  1.011365  1.071793  1.158545  0.291086  0.214715      pass
14  0.622074  0.627224  1.023873  1.075515  0.308547  0.185736      pass
15  0.914836  0.648878  0.931165  1.063008  0.380150  0.172725      pass
16  0.945902  0.882952  1.093451  1.143486  0.349810  0.197628      pass
17  0.874369  0.898379  1.121653  1.433715  0.435014  0.215895      pass
18  1.028003  0.724102  0.915642  0.808833  0.191919  0.198408      pass
19  0.790530  0.694294  0.918177  1.275784  0.333738  0.251708      pass

BARINEL SCORES

          x 0      cx 2      cx 5      cx 3      cx 4       h 1
sum  0.556771  0.534098  0.520032  0.518465  0.515796  0.488949

TARANTULA SCORES

          x 0      cx 2      cx 5      cx 3      cx 4       h 1
sum  0.556771  0.534098  0.520032  0.518465  0.515796  0.488949

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_sx_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.64it/s]
100%|██████████| 10/10 [00:00<00:00, 13.38it/s]

      sxdg 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.116589  1.166258  1.637508  1.599557  1.412385  0.500614      fail
1   0.967850  1.278989  1.695788  1.693546  1.609246  0.560733      fail
2   0.971326  0.850464  1.320857  1.212290  1.470073  0.415420      fail
3   1.015679  1.201734  1.742988  1.876984  1.598404  0.436723      fail
4   1.157613  1.033885  1.548433  1.371544  1.597625  0.583135      fail
5   0.937971  0.784780  1.187149  1.128055  0.934397  0.384918      fail
6   1.173694  1.204145  1.494247  1.535177  1.551713  0.567609      fail
7   1.036724  1.025250  1.344507  1.146413  1.137899  0.401260      fail
8   0.877581  0.837516  1.130610  1.082916  0.942790  0.278202      fail
9   1.014947  1.060098  1.733758  1.769631  1.209882  0.467720      fail
10  0.903676  1.142088  1.449791  1.058365  1.176425  0.550709      pass
11  0.920329  1.056069  1.546409  1.531504  1.317138  0.616607      pass
12  0.873124  0.891344  1.414298  1.311163  1.402691  0.640618      pass
13  0.989399  0.642289  1.299085  1.205892  1.282485  0.477835      pass
14  1.202935  1.046414  1.532379  1.462913  1.085772  0.354658      pass
15  0.734649  0.730926  1.054394  1.006694  1.028248  0.308657      pass
16  1.102542  1.383333  1.963699  1.983916  1.332815  0.597009      pass
17  0.799128  0.825720  1.287877  1.267074  1.186726  0.414357      pass
18  1.174956  1.268448  1.985367  2.315484  2.185555  0.705049      pass
19  0.867513  0.859520  1.039956  1.167976  1.139352  0.478770      pass

BARINEL SCORES

       sxdg 5      cx 4     cx 1      cx 3     cx 2       h 0
sum  0.517686  0.514711  0.50615  0.504464  0.50183  0.471874

TARANTULA SCORES

       sxdg 5      cx 4     cx 1      cx 3     cx 2       h 0
sum  0.517686  0.514711  0.50615  0.504464  0.50183  0.471874

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_y_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 13.22it/s]
100%|██████████| 10/10 [00:00<00:00, 14.70it/s]

         y 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.437226  1.025750  1.128569  1.359596  1.166408  0.305609      fail
1   0.451313  1.032808  0.706961  1.029015  1.279269  0.312948      fail
2   0.502411  0.766437  0.548812  0.610922  0.571102  0.191941      fail
3   0.475920  1.005815  0.883935  0.932640  0.932921  0.272831      fail
4   0.394712  1.039172  1.186571  1.244151  1.141123  0.317521      fail
5   0.273257  0.864295  1.259490  1.458328  1.340936  0.298009      fail
6   0.487939  1.007896  0.940618  1.151040  1.340693  0.407166      fail
7   0.569057  0.836540  0.741693  0.474680  0.608625  0.220659      fail
8   0.519850  1.392918  1.116037  1.270502  1.560125  0.396401      fail
9   0.546468  0.993086  1.038071  1.447510  1.378447  0.369735      fail
10  0.266865  0.590697  0.636847  0.876482  0.932470  0.299549      pass
11  0.400011  1.098579  1.090149  1.415791  1.503744  0.402148      pass
12  0.311857  0.832629  0.721645  0.909636  0.757362  0.187603      pass
13  0.297691  0.739062  0.551962  0.749468  0.877778  0.242346      pass
14  0.336862  0.635589  0.523992  0.443993  0.605373  0.189247      pass
15  0.297332  0.699661  0.780261  0.931473  1.075304  0.271872      pass
16  0.300458  1.045052  1.048872  1.506247  1.504578  0.466858      pass
17  0.486828  0.931765  1.188599  1.045774  1.238288  0.402870      pass
18  0.438067  0.983499  0.586304  0.466296  0.628545  0.243127      pass
19  0.484839  0.876572  0.716701  0.917186  0.899408  0.309965      pass

BARINEL SCORES

          y 5      cx 3      cx 2      cx 4      cx 1       h 0
sum  0.562649  0.549017  0.542391  0.541625  0.530381  0.506322

TARANTULA SCORES

          y 5      cx 3      cx 2      cx 4      cx 1       h 0
sum  0.562649  0.549017  0.542391  0.541625  0.530381  0.506322

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cx_inGap_9_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.34it/s]
100%|██████████| 10/10 [00:00<00:00, 11.26it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.522807  0.911996  0.945051  0.933083  0.687675  0.341540      fail
1   1.322083  0.855688  1.100416  1.007925  0.717498  0.296985      fail
2   1.582480  1.030179  1.231633  1.205990  0.900177  0.347192      fail
3   1.484989  1.025853  0.808137  0.875977  0.384988  0.212902      fail
4   1.241180  0.985896  1.033007  1.235038  0.765217  0.307354      fail
5   1.411301  0.909461  1.082203  1.232358  0.858302  0.315345      fail
6   1.196302  0.659481  0.923602  0.667273  0.364774  0.230872      fail
7   1.715997  0.906352  1.159353  1.223486  0.468971  0.253056      fail
8   1.108939  1.088773  0.689608  0.776833  0.458560  0.232517      fail
9   1.219122  1.194169  0.822093  0.949272  0.449382  0.181567      fail
10  0.783398  0.787698  0.768692  0.953838  0.684205  0.257126      pass
11  1.453319  0.768150  0.878210  0.631849  0.398275  0.262418      pass
12  1.035012  0.541698  0.780190  0.782377  0.518036  0.227302      pass
13  0.932204  0.632349  0.771291  0.780373  0.649718  0.265021      pass
14  0.901988  0.687100  0.522066  0.692010  0.347849  0.173248      pass
15  0.928378  0.523670  0.662318  0.604939  0.355748  0.164749      pass
16  1.052799  0.598310  0.954071  1.037720  0.897798  0.303482      pass
17  1.151594  0.673752  0.639083  1.035744  0.543894  0.197877      pass
18  0.805667  0.414260  0.420819  0.553885  0.483547  0.195267      pass
19  0.942090  0.591969  0.780595  0.976232  0.702089  0.261228      pass

BARINEL SCORES

         cx 4      cx 5      cx 3      cx 2      h 0      cx 1
sum  0.606066  0.580254  0.577118  0.556682  0.54094  0.520383

TARANTULA SCORES

         cx 4      cx 5      cx 3      cx 2      h 0      cx 1
sum  0.606066  0.580254  0.577118  0.556682  0.54094  0.520383

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ry_inGap_9_.qasm

100%|██████████| 10/10 [00:00<00:00, 13.16it/s]
100%|██████████| 10/10 [00:00<00:00, 13.70it/s]

        ry 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.471167  0.637143  0.580284  1.154245  0.951570  0.418359      fail
1   0.687658  0.901886  1.062599  1.749486  1.821281  0.628337      fail
2   0.660120  1.099788  0.979833  1.908636  1.681050  0.685493      fail
3   0.713029  0.759546  0.908648  1.710855  1.687078  0.543142      fail
4   0.707700  1.119899  0.800960  1.438325  1.267885  0.613681      fail
5   0.807489  0.695438  0.926185  1.645245  1.610863  0.655058      fail
6   0.668806  1.196674  1.088005  1.809562  1.497110  0.672049      fail
7   0.635585  1.075762  0.979705  1.645263  1.518424  0.668308      fail
8   0.690566  1.132702  0.850146  1.567888  1.451001  0.645524      fail
9   0.482564  1.156734  1.082253  1.675244  1.912098  0.736136      fail
10  0.372220  0.763889  0.439056  0.824717  1.100655  0.426451      pass
11  0.454349  0.954150  0.828749  1.555244  1.551267  0.467238      pass
12  0.411255  0.737144  0.479126  1.054905  1.153697  0.350137      pass
13  0.601212  1.106485  0.731077  1.379228  1.237697  0.540388      pass
14  0.540033  0.914755  0.783093  1.438574  1.546133  0.569890      pass
15  0.512831  0.532498  0.387283  0.939054  0.851307  0.337969      pass
16  0.699138  1.271086  1.129096  1.927436  1.855563  0.682232      pass
17  0.554187  1.407575  0.959435  1.812706  1.924369  0.567048      pass
18  0.330481  0.691275  0.481068  0.845149  0.916586  0.296868      pass
19  0.388853  1.003333  0.824550  1.421333  1.616104  0.389894      pass

BARINEL SCORES

          h 0      ry 5      cx 3      cx 2      cx 1      cx 4
sum  0.575176  0.572881  0.567973  0.552645  0.528214  0.510267

TARANTULA SCORES

          h 0      ry 5      cx 3      cx 2      cx 1      cx 4
sum  0.575176  0.572881  0.567973  0.552645  0.528214  0.510267

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cx_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.78it/s]
100%|██████████| 10/10 [00:00<00:00, 11.38it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.838209  0.626925  0.735300  0.395243  0.646590  0.196360      fail
1   1.749222  0.996581  1.006702  0.519626  0.844752  0.365527      fail
2   0.965564  0.922403  0.761866  0.719385  0.923119  0.231049      fail
3   1.173368  0.771630  0.793120  0.567618  0.996639  0.280414      fail
4   1.301750  0.818600  0.919905  0.505066  0.803598  0.253365      fail
5   1.180857  0.838941  0.818847  0.391281  0.551519  0.145318      fail
6   0.856362  0.775915  1.085188  0.739364  0.846225  0.237938      fail
7   0.961190  0.466594  0.639325  0.480868  0.616073  0.224131      fail
8   1.449872  0.814846  1.043181  0.556767  0.883613  0.293913      fail
9   1.280618  0.585693  0.877386  0.495567  0.579155  0.226991      fail
10  1.163750  1.065871  0.886742  0.547927  0.912521  0.254752      pass
11  0.940813  0.344839  0.544525  0.323372  0.412142  0.197974      pass
12  1.058496  0.667127  0.750401  0.564842  0.799844  0.208398      pass
13  0.786611  0.787029  0.977070  0.542061  0.846366  0.217975      pass
14  1.318148  0.797761  0.695388  0.598168  0.778835  0.305719      pass
15  0.907905  0.621684  0.613393  0.659032  0.921339  0.230048      pass
16  1.100134  0.731836  0.740372  0.529781  0.487006  0.190777      pass
17  0.844600  0.737092  0.516938  0.616222  0.769431  0.241507      pass
18  0.689228  0.877113  0.938552  0.676062  0.754772  0.240203      pass
19  0.948926  0.802186  0.552552  0.508193  0.621292  0.237784      pass

BARINEL SCORES

         cx 5      cx 3       h 0      cx 1      cx 4      cx 2
sum  0.546441  0.546075  0.513584  0.512929  0.506165  0.491091

TARANTULA SCORES

         cx 5      cx 3       h 0      cx 1      cx 4      cx 2
sum  0.546441  0.546075  0.513584  0.512929  0.506165  0.491091

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_h_inGap_9_.qasm

100%|██████████| 10/10 [00:00<00:00, 13.35it/s]
100%|██████████| 10/10 [00:00<00:00, 14.03it/s]

         h 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.549448  0.954932  0.757261  1.351883  1.270183  0.697536      fail
1   0.602908  1.027717  1.199486  1.814647  1.883770  0.614269      fail
2   0.758358  0.946809  0.491397  1.199652  0.889057  0.586230      fail
3   0.637180  0.997803  1.164092  1.835080  1.472941  0.600360      fail
4   0.732717  1.122724  1.018124  1.913167  2.195822  0.770200      fail
5   0.555337  1.318369  0.889857  1.604159  1.206808  0.664801      fail
6   0.601065  1.098517  0.859444  1.673925  1.437002  0.525147      fail
7   0.739912  1.141947  1.043013  1.772905  1.820988  0.689308      fail
8   0.453184  0.749354  0.321996  0.901607  0.597507  0.415543      fail
9   0.572267  0.824262  0.736648  1.580310  1.315633  0.477553      fail
10  0.535692  1.213597  1.380416  2.277211  2.168636  0.654748      pass
11  0.298357  1.062908  0.820510  1.151986  1.244182  0.363066      pass
12  0.518794  1.006720  0.830726  1.600567  1.736938  0.551916      pass
13  0.372547  0.988168  0.974881  1.447724  1.569512  0.499767      pass
14  0.582017  0.641814  0.976231  1.586963  1.585421  0.415847      pass
15  0.548779  0.831995  0.703541  1.504303  1.427876  0.433723      pass
16  0.519520  1.318011  1.094803  1.923183  1.716743  0.432532      pass
17  0.370344  0.711674  0.493115  0.991087  0.958984  0.328141      pass
18  0.285465  0.791901  0.740977  1.321846  1.438802  0.248240      pass
19  0.325781  0.654192  0.870012  1.412339  1.375022  0.437208      pass

BARINEL SCORES

          h 5       h 0      cx 4      cx 2      cx 3      cx 1
sum  0.587365  0.580518  0.524775  0.506968  0.488371  0.480683

TARANTULA SCORES

          h 5       h 0      cx 4      cx 2      cx 3      cx 1
sum  0.587365  0.580518  0.524775  0.506968  0.488371  0.480683

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_h_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 17.61it/s]
100%|██████████| 10/10 [00:00<00:00, 18.89it/s]

         h 5  cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.718970   0.0  0.486443  0.857540  0.954225  0.326798      fail
1   0.666584   0.0  0.522290  0.660391  0.751641  0.309268      fail
2   0.693344   0.0  0.736576  0.429912  0.672633  0.268042      fail
3   0.675573   0.0  0.528718  0.329352  0.360096  0.194473      fail
4   0.632275   0.0  0.585104  0.382320  0.512282  0.200417      fail
5   0.615886   0.0  0.435172  0.451835  0.615779  0.278998      fail
6   0.715935   0.0  0.787746  0.418084  0.706332  0.278108      fail
7   0.675551   0.0  0.541523  0.468466  0.571984  0.282522      fail
8   0.642469   0.0  0.506596  0.622830  0.691721  0.267070      fail
9   0.609738   0.0  0.516667  0.537469  0.789627  0.351225      fail
10  0.607004   0.0  0.865988  0.629830  0.781074  0.286980      pass
11  0.421326   0.0  0.524320  0.538758  0.589453  0.241317      pass
12  0.485232   0.0  0.538272  0.398429  0.448125  0.158517      pass
13  0.412320   0.0  0.488402  0.616583  0.458203  0.195861      pass
14  0.425356   0.0  0.331406  0.483721  0.427204  0.168698      pass
15  0.442803   0.0  0.520113  0.590603  0.642107  0.234688      pass
16  0.664707   0.0  0.852042  0.593655  0.884150  0.369748      pass
17  0.567389   0.0  0.503494  0.431800  0.407830  0.251083      pass
18  0.518220   0.0  0.374363  0.401689  0.633995  0.231157      pass
19  0.270395   0.0  0.618485  0.621384  0.763357  0.158000      pass

BARINEL SCORES

          h 5       h 0      cx 1     cx 3      cx 2  cx 4
sum  0.579904  0.545604  0.523331  0.50133  0.492917   NaN

TARANTULA SCORES

          h 5       h 0      cx 1     cx 3      cx 2  cx 4
sum  0.579904  0.545604  0.523331  0.50133  0.492917   NaN

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_x_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 12.20it/s]
100%|██████████| 10/10 [00:00<00:00, 13.92it/s]

         x 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.416492  0.691499  0.930356  1.006876  0.766826  0.230477      fail
1   0.479308  1.025820  0.676525  0.901838  1.292272  0.369240      fail
2   0.520468  1.077861  0.989962  0.940387  0.973081  0.230671      fail
3   0.403512  1.060198  0.598932  0.684731  0.777846  0.159702      fail
4   0.419270  0.846452  0.603560  0.839906  0.626452  0.167803      fail
5   0.364392  0.904524  0.771182  1.060564  1.126696  0.319924      fail
6   0.538963  0.941053  0.560466  0.882074  0.789353  0.221813      fail
7   0.405130  0.976026  0.846475  1.108428  1.134088  0.326104      fail
8   0.377278  0.875203  0.750633  1.238779  1.433584  0.319884      fail
9   0.401607  0.832942  0.790044  0.839169  0.771450  0.143091      fail
10  0.294907  0.786349  0.781225  1.013344  1.137459  0.323644      pass
11  0.362560  0.589595  0.614222  0.747530  1.020865  0.263427      pass
12  0.404004  0.895247  0.633560  0.349888  0.726150  0.222073      pass
13  0.251951  0.869340  0.958980  1.110510  1.413359  0.322855      pass
14  0.238969  1.068658  0.910628  0.967475  0.806938  0.283067      pass
15  0.406453  0.911383  0.714199  0.853920  0.833743  0.265438      pass
16  0.405980  1.062348  1.008692  1.268848  1.501064  0.361078      pass
17  0.342613  0.941531  1.223508  1.401789  1.479023  0.442304      pass
18  0.426139  0.796040  0.788975  0.741171  0.672525  0.197979      pass
19  0.431547  1.159601  0.828527  1.049276  0.894227  0.360216      pass

BARINEL SCORES

          x 5      cx 4      cx 2      cx 1      cx 3       h 0
sum  0.548235  0.504136  0.499974  0.480331  0.470452  0.449973

TARANTULA SCORES

          x 5      cx 4      cx 2      cx 1      cx 3       h 0
sum  0.548235  0.504136  0.499974  0.480331  0.470452  0.449973

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ry_inGap_10_.qasm

100%|██████████| 10/10 [00:00<00:00, 12.93it/s]
100%|██████████| 10/10 [00:00<00:00, 14.87it/s]

        ry 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.410553  0.823128  0.618406  0.622886  0.822871  0.194480      fail
1   0.405434  1.019112  0.638972  1.142711  1.139903  0.296439      fail
2   0.468990  0.802546  0.923493  1.127754  1.438169  0.285454      fail
3   0.359138  0.913783  0.948625  1.308667  1.486064  0.301698      fail
4   0.445945  1.173570  0.863845  1.300038  1.243114  0.312775      fail
5   0.465342  1.183868  0.781699  1.007631  1.318132  0.371230      fail
6   0.406067  0.831460  0.373215  0.719165  0.902456  0.182330      fail
7   0.397307  0.674895  0.601317  0.758214  0.904748  0.202182      fail
8   0.458377  1.053379  1.340751  1.409180  1.501309  0.359425      fail
9   0.475268  1.420959  0.893186  1.163343  1.268746  0.344816      fail
10  0.409977  0.905074  0.788297  1.145511  1.163379  0.299732      pass
11  0.502839  0.602983  0.448871  0.588148  0.701702  0.144987      pass
12  0.310018  0.675874  0.686936  0.808813  1.037900  0.254491      pass
13  0.495543  0.952744  1.383675  1.618606  1.950468  0.457928      pass
14  0.291503  1.108315  1.197544  1.525737  1.632165  0.393269      pass
15  0.457880  0.913604  0.551621  0.739333  0.618307  0.242595      pass
16  0.408425  0.730886  0.771917  0.972698  1.044015  0.278739      pass
17  0.355826  0.687628  0.729413  0.843051  1.235860  0.306077      pass
18  0.162526  0.835020  0.938074  1.220875  1.310299  0.325279      pass
19  0.270234  1.115921  0.935072  1.363024  1.347296  0.382434      pass

BARINEL SCORES

         ry 5      cx 4     cx 1      cx 2      cx 3       h 0
sum  0.539439  0.537142  0.49967  0.493776  0.486357  0.480232

TARANTULA SCORES

         ry 5      cx 4     cx 1      cx 2      cx 3       h 0
sum  0.539439  0.537142  0.49967  0.493776  0.486357  0.480232

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ccx_inGap_10_.qasm

100%|██████████| 10/10 [00:02<00:00,  4.44it/s]
100%|██████████| 10/10 [00:02<00:00,  4.16it/s]

       ccx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.540760  1.030364  0.813148  0.659556  0.874820  0.272452      fail
1   1.558060  0.977451  0.794761  0.632869  0.909981  0.316272      fail
2   1.832920  1.461059  1.209527  1.027482  1.332788  0.393890      fail
3   1.427864  1.292733  0.971412  0.801422  1.090322  0.341253      fail
4   1.667231  1.074801  0.952109  0.838680  1.234138  0.347137      fail
5   1.614065  0.756970  0.803695  0.701344  0.782411  0.272055      fail
6   1.321502  0.902554  0.667764  0.609585  0.884937  0.266215      fail
7   1.290637  0.807531  0.513654  0.419444  0.615027  0.206367      fail
8   1.454044  0.993320  0.774407  0.694318  0.917485  0.266516      fail
9   1.535283  0.856446  0.566717  0.523481  0.757366  0.240565      fail
10  1.608391  1.071703  0.792014  0.794407  1.132169  0.355818      pass
11  1.581853  1.123819  0.711013  0.748704  1.053119  0.343837      pass
12  1.305244  0.766934  0.486558  0.401527  0.573009  0.215076      pass
13  1.574799  1.116968  1.006775  0.932113  1.229945  0.416100      pass
14  1.301194  0.590682  0.509536  0.572048  0.704028  0.218401      pass
15  1.433094  0.764815  0.675853  0.682389  0.995054  0.291124      pass
16  1.697232  1.074556  0.739113  0.778779  1.177717  0.352243      pass
17  1.265226  0.985378  0.856726  0.747850  0.957977  0.277977      pass
18  1.561700  0.891257  0.742689  0.683443  1.065663  0.325664      pass
19  1.218191  0.831505  0.688530  0.685731  0.811090  0.258971      pass

BARINEL SCORES

         cx 3     cx 4     ccx 5      cx 2      cx 1       h 0
sum  0.528096  0.52415  0.511673  0.495737  0.492133  0.488918

TARANTULA SCORES

         cx 3     cx 4     ccx 5      cx 2      cx 1       h 0
sum  0.528096  0.52415  0.511673  0.495737  0.492133  0.488918

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ccx_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  5.50it/s]
100%|██████████| 10/10 [00:01<00:00,  6.12it/s]

        cx 5      cx 4     ccx 3      cx 2      cx 1       h 0 pass/fail
0   0.972545  1.325727  0.921364  0.875752  0.970294  0.287850      fail
1   1.054588  1.112397  0.944750  0.847386  0.960486  0.254321      fail
2   1.118360  0.749619  0.847255  0.558360  0.836584  0.234746      fail
3   0.881167  1.234424  0.857931  0.826856  0.862841  0.287051      fail
4   0.927125  0.562585  0.884356  0.511928  0.694318  0.231510      fail
5   0.894569  1.020606  0.805440  0.723692  0.822670  0.269889      fail
6   1.091648  1.076002  0.859124  0.740731  0.897027  0.288069      fail
7   1.032423  1.040836  0.943158  0.747588  0.901839  0.281133      fail
8   1.294522  0.968456  1.004008  0.821688  0.913522  0.264614      fail
9   0.947307  1.119717  0.894622  0.736046  0.876247  0.276220      fail
10  0.386925  0.251546  0.382458  0.267288  0.332331  0.117166      pass
11  0.909263  0.644302  0.844012  0.542135  0.786140  0.240988      pass
12  0.601062  0.428137  0.653112  0.340544  0.491001  0.159854      pass
13  0.773622  0.366771  0.745521  0.438870  0.506823  0.214443      pass
14  1.199680  1.079873  0.982952  0.849947  0.947761  0.280827      pass
15  0.582428  0.686060  0.609987  0.432744  0.636584  0.186837      pass
16  0.957141  0.773173  0.747886  0.667711  0.867261  0.267143      pass
17  0.857317  0.963374  0.824386  0.706269  0.754525  0.234591      pass
18  0.706174  0.714261  0.838966  0.561785  0.594701  0.233044      pass
19  0.438813  0.612777  0.550498  0.440802  0.529100  0.160648      pass

BARINEL SCORES

        cx 4      cx 2      cx 5      cx 1      h 0     ccx 3
sum  0.61028  0.584741  0.579477  0.575405  0.56077  0.555206

TARANTULA SCORES

        cx 4      cx 2      cx 5      cx 1      h 0     ccx 3
sum  0.61028  0.584741  0.579477  0.575405  0.56077  0.555206

ERROR GATE LOCATION:
3

,Program,path_to_mutant,exam_score
0,AddGate_ccx_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,1.0
1,AddGate_ccx_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.5
2,AddGate_ry_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
3,AddGate_x_inGap_7_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
4,AddGate_h_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
...,...,...,...
84,AddGate_x_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
85,AddGate_cx_inGap_3_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
86,AddGate_x_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
87,AddGate_y_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
88,AddGate_y_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.333333

,Program,path_to_mutant,exam_score
0,AddGate_ccx_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,1.0
1,AddGate_ccx_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.5
2,AddGate_ry_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
3,AddGate_x_inGap_7_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
4,AddGate_h_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
...,...,...,...
84,AddGate_x_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
85,AddGate_cx_inGap_3_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
86,AddGate_x_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
87,AddGate_y_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
88,AddGate_y_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.333333