<h1 style="text-align: center;">HEISENBERG-BASED FAULT LOCALIZATION (HBFL)</h1>

<h2 style="text-align: center;">Download Initial Dependencies</h2>

In [50]:
import numpy as np
import pandas as pd
import json
import math
from tqdm import tqdm
from qiskit.quantum_info import SparsePauliOp, Operator, Pauli, Clifford
import qiskit.qasm2 as q2
from qiskit import QuantumCircuit
from IPython.display import display

from heisenbergUtilities import *

In [51]:
# from qiskit_aer import AerSimulator
# simulator = AerSimulator()

# print(simulator.available_devices())

<h3>Download MQT Benchmark circuits.</h3>

We'll run this experiment on 11 different quantum circuits, including DJ, GHZ, GraphState, Grover No-Ancilla, QAOA, QFT, QGAN, QPE Exact, QPE Inexact, RealAmpRandom, and VQE.

<h3>Generate mutants.</h3>

We'll start with mutants that add an unnecessary gate, then add mutants that replace a certain gate later. Missing code in SBFL is still a more recent topic even in classical programs.

The mutants were downloaded from QMutBench, choosing specifically mutants that added a gate at any location with 0-10% survival scores

<h2 style="text-align: center;">CONTROL PANEL</h2>

In [52]:
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------GENERAL PARAMETERS---------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
ALG_NAME = "grover-noancilla"
ORIGINAL_QASM = f"{ALG_NAME}_5_qubits.qasm"                                                 #| The original algorithm QASM circuit file name.                           
ORIGINAL_QASM_FOLDER = "SBFL_circuits/MQTBench/"                                            #| The folder containing the original QASM circuit file.                    
QASM_MUTANT_FOLDER = f"SBFL_circuits/QMutBenchMutants/Mutants_{ALG_NAME}_5_qubits/"         #| The folder containing all mutants related to the original QASM circuit.  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------SB-QOPS PARAMETERS---------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
RUNS = 10                                                                                   #| Number of times SB-QOPS will run to find a failing or passing test case.            
SHOTS = 20000                                                                               #| Number of shots for SB-QOPS to use to create the compact program specification.     
EPOCH = 80                                                                                  #| Number of epochs SB-QOPS will run to navigate the search space of test cases.       
SBQOPS_TOL = 0.1                                                                            #| Tolerance value SB-QOPS uses to determine if a test case is failing or passing.     
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#---------------------------------------------------------------------HEISENBERG SBFL PARAMETERS-----------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
LAMBDA_WEIGHT = 1                                                                           #| The amount to weigh the "weight difference" in the heuristic            #
LAMBDA_COMP = 1                                                                             #| The amount to weigh the "composition difference" in the heuristic       #
LAMBDA_SUPPORT = 1                                                                          #| The amount to weigh the "support overlap" in the heuristic              #
LAMBDA_DIAMETER = 1                                                                         #| The amount to weigh the "diameter difference" in the heuristic          #
LAMBDA_PHASE = 1                                                                            #| The amount to weigh the "phase" in the heuristic                        #
CUSTOM_WEIGHT = 0.25                                                                        #| The amount of weight the "dstar boost" has in the custom heuristic (WIP)#
ATOL = 1e-4                                                                                 #| The tolerance value used to prune negligible magnitudes during Pauli propagation.   
MAX_TERMS = 10                                                                             #| The maximum number of terms to keep during Pauli propagation. If None, use all.     
SEARCH_STEP = 1                                                                             #| The search step size used during Pauli propagation. If None, pauli-prop uses 4.     
VERBOSE = 1                                                                                 #| A boolean value to determine if the program should print out detailed information.  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#

Generate the linked list of all gates found in a given circuit

In [53]:
"""
LinkedListNode: A class that holds information related to a gate in a quantum circuit. 

PROPERTIES:
    - value (String): The name of the quantum gate
    - depth (int): The depth of the gate in the circuit
    - count (Int): The probability that the gate will meaningfully change the Pauli string.
    - next (LinkedListNode): The next gate in the circuit

"""

class LinkedListNode:
    def __init__(self, name="Initial", depth=0, count=0,  next=None):
        self.value = name
        self.depth = depth
        self.next = next
        self.count = count

class LinkedList:
    def __init__(self):
        self.head = None

    def append(self, name, depth):
        new_node = LinkedListNode(name, depth)
        if not self.head:
            self.head = new_node
            return
        last_node = self.head
        while last_node.next:
            last_node = last_node.next
        last_node.next = new_node

    def mark(self, depth):
        current_node = self.head
        while current_node:
            if current_node.depth == depth:
                current_node.count += 1
                return
            current_node = current_node.next

    def reset(self):
        current_node = self.head
        while current_node:
            current_node.count = 0
            current_node = current_node.next

<h3>Load correct circuit</h3>
Here we want to load the correct version of the circuit from MQT. We use this both to generate a PS_compact from/for SB-QOPS and to check results from SBFL.

In [54]:
correct_circuit = load_program(ORIGINAL_QASM, ORIGINAL_QASM_FOLDER).copy()
correct_list = LinkedList()
correct_list = construct_list(correct_list, correct_circuit, inverse=False)

<h2 style="text-align: center;"> SB-QOPS </h2>

This is where we will use SB-QOPS on a provided circuit and its mutants

For a single mutant, it took about 2 minutes to generate a 20 test suite (10 fail, 10 pass) on an RTX 4090 SUPER. It can only be run on a Linux environment since the AER Simulator does not support Windows

Expect this cell to take up to a few hours, BUT this cell should only need to be run once per algorithm with mutants under test. After it saves to the csv file at the end, this cell can be commented out as to not accidentally run it again. 

In the future if we want to test this methodology on higher qubit circuits or other algorithms, we'll likely either want to reduce the number of tests in the suite or the number of mutants we're analyzing

In [55]:
# import QOPS as qops
# from QOPS_test import get_compact_program_specification_Z
# from pathlib import Path

# ga_result = pd.DataFrame(columns=['Program',"path_to_mutant",'catch_avg','avg_fitness','failing_testcases', 'passing_testcases'])
# program_history = {}

# #program_specification = The compact program specification. SB-QOPS needs this to generate failing test cases.
# # In a public-use environment, this would be provided by the user.
# program_specification = get_compact_program_specification_Z(correct_circuit, shots=SHOTS)

# #mutants = A python list of qiskit QuantumCircuit variables with a mutation in them
# mutants = []
# mutants_names = []
# root = Path(QASM_MUTANT_FOLDER)
# for qasm_mutant in root.rglob("*.qasm"):
#     mutants.append(load_program(qasm_mutant.name, QASM_MUTANT_FOLDER))
#     mutants_names.append(qasm_mutant.name)

# for mutant_index,mutant in enumerate(mutants):
#     tester = qops.Circuit_Tester(CUT=mutant)
#     tester.set_applicable_families_Z(program_specification)
#     mutants_per_run = []
#     fitness_per_run = []
#     failing_testcases_per_run = []
#     history_per_run = []

#     print("NOW RUNNING TO FIND FAILING TESTS")
#     #For a predefined number of attempts, try to find a set of failing test cases (output is above predefined tolerance)
#     for runs in range(RUNS):
#         killed = 0
#         pauli = {}
#         fitness = 0
#         for i in range(len(tester.applicable_families)):
#             best_function,testcase, history = tester.run_mealoneplusone(i, EPOCH)
#             if best_function > SBQOPS_TOL:
#                 killed = 1
#                 pauli = testcase
#                 fitness = best_function
#                 break
#         mutants_per_run.append(killed)
#         failing_testcases_per_run.append(pauli)
#         fitness_per_run.append(fitness)
#         history_per_run.append(history)

#     avg_score = np.mean(mutants_per_run)
#     avg_fitness = np.mean(fitness_per_run)

#     #Here is our new, modified algorithm from the SB-QOPS method that attempts to find passing test cases as well. We'll need them for SBFL
#     passing_testcases_per_run = []

#     print("NOW RUNNING TO FIND PASSING TESTS")
#     for runs in range(RUNS):
#         pauli = {}
#         fitness = 0
#         for i in range(len(tester.applicable_families)):
#             best_function, testcase, history = tester.run_reverse_mealoneplusone(i,EPOCH)
#             if best_function < SBQOPS_TOL:
#                 pauli = testcase
#                 break
#         passing_testcases_per_run.append(pauli)

#     #Replace static program file with "program_name" when ready to test fully
#     """
#     ga_result: A pandas dataframe with the following columns
#         Program: Name of the mutant quantum circuit file
#         Path_To_Mutant: Path to the mutant file
#         Catch_Avg: The average number of times the mutant was identified by SB-QOPS
#         Avg_Fitness: The average fitness of the search algorithm used. Higher usually indicates higher Catch_Avg
#         Failing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a failing test case
#         Passing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a passing test case
#     """
#     ga_result = pd.concat([pd.DataFrame([[mutants_names[mutant_index],QASM_MUTANT_FOLDER,avg_score,avg_fitness,json.dumps(failing_testcases_per_run), json.dumps(passing_testcases_per_run)]],columns=ga_result.columns),ga_result],ignore_index=True)
#     ga_result.to_csv(f'realamprandom_ga_result', index=False)

ga_result is a slightly altered pandas Dataframe with similar structure found in SB-QOPS. The differences are changing the column "Program" to be the name of the mutant file instead of the original quantum circuit, changing "Mutant" to be the path to the mutant file instead of being an arbitrary index value, and adding a passing_testcases column that returns Pauli strings and coefficients that generate passing tests.

Now we want to run SBFL using Heisenberg evolution trees on each circuit placed in ga_result

Evolution analysis can vary widely in runtime. Some of the simplest circuits take seconds to analyze and only took upwards of 3-4 minutes to get results on the whole dataset (GHZ was the fastest taking 3 minutes to run). Other, more complex algorithms can take upwards of 6-10 minutes PER MUTANT (RealAmpRandom took longest so far with 14 hours).

The runtime of this code segment is directly tied to the depth of the circuit being analyzed and the number of 2-branching gates such as rotation or phase gates that exist in the circuit.

This is something to note in the final paper. Regardless of accuracy this methodology takes a long time to run. If results are promising, then we'll want to look into the tradeoffs between EXAM and hyperparameters to speed this up. Primarily the atol, max_terms, and search_step parameters in the evolve_pauli_exact method in HeisenbergUtilities.py

<h2 style="text-align: center;">HEISENBERG EVOLUTIONS (PAULI PROPAGATION)</h2>

In [ ]:
from heisenbergTree import *

LAMBDAS = [LAMBDA_WEIGHT, LAMBDA_COMP, LAMBDA_SUPPORT, LAMBDA_DIAMETER, LAMBDA_PHASE]
ga_result = pd.read_csv(f'{ALG_NAME}_ga_result.csv')
custom_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','best_exam_score', 'worst_exam_score', 'avg_exam_score'])
barinel_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','best_exam_score', 'worst_exam_score', 'avg_exam_score'])
dstar_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','best_exam_score', 'worst_exam_score', 'avg_exam_score'])
mutant_num = 0

#For each mutant of a circuit, run the SBFL implementation
for mutant, path in zip(ga_result.loc[:,"Program"], ga_result.loc[:,"path_to_mutant"]):
    print("Now evolving the following mutant: ", mutant)

    #Extract the raw test cases found for each mutant
    raw_failing_testcases = format_test_case(ga_result, mutant, mutant_num, "failing_testcases")
    raw_passing_testcases = format_test_case(ga_result, mutant, mutant_num, "passing_testcases")

    circuit_inverse = load_program(mutant,path).copy().inverse()  # Invert to track backward evolution of the operator
    forward_mutant = load_program(mutant, path).copy()

    #Create the linked list of operations in the inverse circuit
    operation_list = LinkedList()
    operation_list = construct_list(operation_list, circuit_inverse, True)

    forward_list = LinkedList()
    forward_list = construct_list(forward_list, forward_mutant, False)

    #Create list of nodes in linked list. Somewhere down the road remove the linked list implementation. It's unnecessary and giving me a headache
    node_list = []
    node = operation_list.head
    while node:
        node_list.append(node)
        node = node.next

    #Perform Pauli propagation (Heisenberg evolution) for all test cases. Returns a dataframe with all counts for all operations
    global_frame_fail = heisenberg_evolve(circuit_inverse, 
                                          operation_list, 
                                          raw_failing_testcases, 
                                          "fail", 
                                          LAMBDAS,
                                          atol = ATOL, 
                                          max_terms = MAX_TERMS, 
                                          search_step = SEARCH_STEP)
    
    global_frame_pass = heisenberg_evolve(circuit_inverse, 
                                          operation_list, 
                                          raw_passing_testcases, 
                                          "pass", 
                                          LAMBDAS,
                                          atol = ATOL, 
                                          max_terms = MAX_TERMS, 
                                          search_step = SEARCH_STEP)

    global_frame = pd.concat([global_frame_fail, global_frame_pass], ignore_index=True)

    global_frame = global_frame.drop(["Initial"],axis=1)
    if VERBOSE:
        display(global_frame)

    custom_scores = custom_sbfl(global_frame, CUSTOM_WEIGHT)
    barinel_scores = barinel(global_frame)
    dstar_scores = dstar(global_frame)

    if VERBOSE:
        print("BARINEL SCORES")
        display(barinel_scores)
        print("custom SCORES")
        display(custom_scores)
        print("DSTAR SCORES")
        display(dstar_scores)
    
    # Here is where analysis of the methodology begins. 
    # We first extract the position of the erroneous gate by comparing it to the original MQT gate
    # NOTE: This method is intended for single-added gates for now. Other types of mutants will require other methods later
    error_gate_location = find_erroneous_gate(forward_mutant, correct_circuit)

    if VERBOSE:
        print("ERROR GATE LOCATION:")
        print(error_gate_location)

    #Calculate best, worst, and average EXAM for Barinel, custom, and DStar
    barinel_best_exam, barinel_worst_exam, barinel_average_exam = calc_exams(barinel_scores, error_gate_location, circuit_inverse)
    custom_best_exam, custom_worst_exam, custom_average_exam = calc_exams(custom_scores, error_gate_location, circuit_inverse)
    dstar_best_exam, dstar_worst_exam, dstar_average_exam = calc_exams(dstar_scores, error_gate_location, circuit_inverse)

    # Here we store the results from the HBFL analysis for both barinel and custom into a csv file for later analysis.
    barinel_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,barinel_best_exam, barinel_worst_exam, barinel_average_exam]],columns=barinel_sbfl_result.columns),barinel_sbfl_result],ignore_index=True)
    barinel_sbfl_result.to_csv(f'{ALG_NAME}_barinel_sbfl_result.csv', index=False)

    custom_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,custom_best_exam, custom_worst_exam, custom_average_exam]],columns=custom_sbfl_result.columns),custom_sbfl_result],ignore_index=True)
    custom_sbfl_result.to_csv(f'{ALG_NAME}_custom_sbfl_result.csv', index=False)

    dstar_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,dstar_best_exam, dstar_worst_exam, dstar_average_exam]],columns=dstar_sbfl_result.columns),dstar_sbfl_result],ignore_index=True)
    dstar_sbfl_result.to_csv(f'{ALG_NAME}_dstar_sbfl_result.csv', index=False)

    mutant_num += 1

if VERBOSE:
    display(barinel_sbfl_result)
    display(custom_sbfl_result)

Now evolving the following mutant:  AddGate_y_inGap_23_.qasm

100%|██████████| 10/10 [02:27<00:00, 14.76s/it]
100%|██████████| 10/10 [02:44<00:00, 16.47s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.564263,0.446167,0.131218,0.060957,0.527522,0.046646,0.006571,0.180482,0.037244,0.006842,...,44.936519,5.758298,44.221057,0.752262,198.434333,45.575314,18.664398,17.389742,16.955843,fail
1,0.587430,0.526702,0.135839,0.048355,0.401857,0.081262,0.006178,0.247035,0.052201,0.007032,...,92.511962,10.768734,92.412759,1.390915,285.160845,67.358304,35.348113,40.146891,45.709839,fail
2,0.437101,0.427538,0.106293,0.030136,0.258565,0.055897,0.005765,0.131813,0.057972,0.010589,...,94.167435,11.292250,93.302462,1.479639,371.627366,82.495012,38.086065,39.463144,42.091602,fail
3,0.465425,0.619328,0.098629,0.029215,0.220489,0.070279,0.004766,0.104657,0.084661,0.013837,...,156.342861,20.799314,156.669558,2.555742,297.829683,112.949341,54.312734,58.297575,63.927850,fail
4,0.557856,0.540699,0.134450,0.054499,0.313443,0.102617,0.008731,0.255448,0.085741,0.014641,...,141.938335,16.998155,140.970988,2.212921,518.578134,118.565308,56.302309,59.642960,64.690165,fail
5,0.510556,0.442460,0.103797,0.039686,0.188367,0.084574,0.008003,0.323125,0.036097,0.007339,...,48.409675,6.203358,47.638915,0.810405,213.771379,49.097843,20.106974,18.733800,18.266365,fail
6,0.497304,0.569769,0.116958,0.042980,0.326659,0.059617,0.006778,0.228044,0.038634,0.007288,...,52.181940,7.082599,51.659528,0.894140,172.861558,48.829157,20.059765,18.792722,18.435063,fail
7,0.384769,0.547052,0.129164,0.038100,0.393918,0.062688,0.004682,0.232281,0.025040,0.004083,...,37.598939,5.908411,37.849812,0.686129,7.462450,26.854935,11.170917,10.691475,10.731133,fail
8,0.422214,0.608763,0.118871,0.029501,0.188781,0.078436,0.007298,0.281429,0.051233,0.006812,...,95.734603,10.647003,95.537490,1.400174,330.267047,69.873716,37.615940,43.370031,49.847273,fail
9,0.466539,0.557231,0.100221,0.035706,0.262839,0.068131,0.005660,0.172747,0.048860,0.009215,...,74.605701,9.116716,73.781006,1.193537,304.142928,68.217510,30.399890,30.601218,31.906162,fail
10,0.421840,0.529991,0.101474,0.036888,0.296478,0.053353,0.006309,0.263516,0.016973,0.002569,...,23.693509,3.723270,23.851600,0.432374,4.702569,16.923021,7.039513,6.737386,6.762377,pass
11,0.387489,0.451521,0.099061,0.035013,0.273953,0.058922,0.005591,0.086301,0.073237,0.012763,...,130.796563,18.111390,131.050429,2.201249,218.440518,96.876661,44.478069,46.126979,49.329295,pass
12,0.347926,0.352323,0.096609,0.034484,0.355787,0.030164,0.003150,0.044325,0.043724,0.008886,...,58.601185,7.509328,57.668161,0.981016,258.775880,59.434231,24.340022,22.677758,22.111916,pass
13,0.420884,0.649833,0.097563,0.019353,0.206987,0.054504,0.003950,0.000868,0.090224,0.015560,...,167.720419,22.257267,167.865967,2.746209,348.071625,124.488636,59.038406,62.700515,68.220930,pass
14,0.427488,0.475983,0.074952,0.032936,0.330795,0.027831,0.001595,0.013541,0.043736,0.006199,...,76.908913,9.425403,76.916345,1.193630,203.587431,55.836812,28.399759,31.638996,35.577899,pass
15,0.309934,0.549983,0.071929,0.018383,0.150058,0.051574,0.003136,0.119325,0.032227,0.006043,...,56.060722,8.809551,56.434778,1.023031,11.126652,40.041211,16.656046,15.941190,16.000320,pass
16,0.361212,0.412584,0.111302,0.030496,0.300294,0.056244,0.004471,0.010619,0.093425,0.016268,...,166.736317,22.064633,166.652671,2.735084,377.861764,127.457155,59.553514,62.511397,67.420454,pass
17,0.580481,0.409725,0.102447,0.058014,0.281740,0.087809,0.010246,0.213781,0.090879,0.017826,...,147.635078,20.943948,147.240385,2.559586,309.494943,122.365670,51.784194,50.049811,50.539385,pass
18,0.346806,0.397598,0.074222,0.033127,0.282096,0.035697,0.003154,0.169348,0.004439,0.000035,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,pass
19,0.152068,0.398589,0.064868,0.015565,0.090326,0.057144,0.003927,0.027866,0.080977,0.013968,...,153.455621,20.896075,153.867700,2.546477,258.288687,110.699908,52.306594,55.455057,60.284031,pass

[[1.20044034 1.17170241 1.15564598 1.48989549 1.71137933 1.44501509
  1.35514061 1.49798529 1.65625089 1.66982931 1.70978091 1.64417078
  1.69228721 1.70012477 1.71771323 1.6899486  1.76694562 1.71453211
  1.81429749 1.72748469 1.74915499 1.72612312 1.73658039 1.73699631
  1.75748492 1.72919535 1.75637323 1.75902081 1.72772836 1.7582735
  1.72702555 2.05199242 1.76343158 1.72995755 2.05030506 1.75084022
  2.05664652 1.76064396 1.73154639 2.04890904 1.75568159 2.06215251
  1.76026907 2.06350105 1.75451581 2.05855548 1.76545883 2.0594201
  1.76007289 2.0477739  1.80561434 2.04498635 1.73691119 2.0513424
  1.81271339 2.05137914 1.74173122 2.00662749 1.868231   2.00119309
  1.88380039 1.92554698 1.72272794 1.74931939 1.77715508 1.72537097
  1.77422471 1.88415347 1.73257935 1.78679869 1.82437365 1.73199766
  1.87730129 1.73971385 1.777249   1.7327345  1.8693521  1.73972737
  1.81827829 1.73334163 1.86721029 1.73792409 1.76289378 1.73058457
  1.75601494 1.74563029 1.76521163 1.73142823 1.75684386 1.76665465
  1.72992176 1.76632579 1.74114812 2.047154   1.77220375 1.73498434
  2.04379105 1.76100356 2.04402469 1.7693456  1.73435946 2.03395619
  1.75987961 2.04979564 1.7690893  2.05147458 1.76107366 2.04559452
  1.76964891 2.04677462 1.76240082 2.0363587  1.81266735 2.03455866
  1.74333752 2.03968954 1.81668935 2.04052776 1.74478667 2.00087519
  1.86875851 1.99628839 1.88336998 1.91804199 1.72337084 1.75111569
  1.77717754 1.725975   1.7738702  1.8838149  1.73627343 1.78472426
  1.82748162 1.73241608 1.87735823 1.74098844 1.77501739 1.73300062
  1.86942012 1.74027663 1.82005143 1.73342884 1.86697717 1.7375127
  1.76164851 1.73050982 1.75482715 1.74514408 1.76321742 1.73128963
  1.75487432 1.7647402  1.72983137 1.76443096 1.74103562 2.03662423
  1.76966479 1.72579388 1.73470433 2.03322376 1.75945046 2.03361565
  1.76739011 1.73404151 2.0236454  1.75835007 2.0371111  1.7672094
  2.03874093 1.75933103 2.03431938 1.76767623 2.03548817 1.7605152
  2.02669176 1.81109817 2.02506799 1.74224861 2.03004946 1.81588945
  2.03097059 1.74342374 1.9929489  1.86471429 1.98894058 1.87843373
  1.91071172 1.92056321 1.71879505 1.7481546  1.76914063 1.78425458]]
BARINEL SCORES

,u 184,p 185,cx 186,x 4,cx 189,u 191,p 188,u 187,u 190,cx 127,...,cp 136,cp 152,cp 138,cp 148,cp 140,cp 150,cp 157,cp 155,cp 142,cp 160
sum,0.694358,0.585952,0.580475,0.575662,0.567882,0.565745,0.565577,0.545472,0.533165,0.493928,...,0.431496,0.431426,0.431364,0.431272,0.431248,0.431014,0.430668,0.430601,0.430535,0.428573

custom SCORES

,u 184,x 4,cx 186,p 185,u 187,p 188,u 191,cx 189,cx 127,cx 65,...,cp 138,cp 152,cp 155,cp 140,cp 157,cp 142,cp 132,cp 134,cp 160,cp 130
sum,0.954393,0.852061,0.790174,0.784463,0.77885,0.776239,0.73553,0.731949,0.713375,0.712515,...,0.652583,0.652414,0.652,0.651722,0.651418,0.650944,0.650827,0.648692,0.648431,0.648098

DSTAR SCORES

,x 4,cx 18,cx 22,cx 26,cx 10,cx 38,cx 14,cx 31,cx 40,cx 20,...,p 174,p 178,p 163,p 182,p 176,p 170,p 185,p 180,cp 130,p 168
sum,3644.728508,3102.070711,2170.833641,2142.949857,1783.858483,1593.526891,1560.427438,1516.755851,1509.928897,1460.705173,...,0.00301,0.001467,0.001376,0.000761,0.000546,0.00043,0.000413,0.000216,0.000165,0.000108

ERROR GATE LOCATION:
34
Now evolving the following mutant:  AddGate_y_inGap_114_.qasm

100%|██████████| 10/10 [03:01<00:00, 18.18s/it]
100%|██████████| 10/10 [03:08<00:00, 18.82s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.514360,0.602279,0.135567,0.045387,0.407098,0.074453,0.006174,0.038023,0.111512,0.020943,...,190.930922,25.759041,190.447084,3.192812,458.857765,153.965962,68.795952,69.663848,73.082747,fail
1,0.387578,0.318694,0.156080,0.050793,0.530373,0.063335,0.005328,0.210142,0.049386,0.007365,...,78.056735,9.054120,77.590471,1.188241,290.574725,63.238512,31.164384,33.905966,37.483062,fail
2,0.496071,0.466932,0.106372,0.052806,0.353594,0.062940,0.007288,0.284864,0.030316,0.005071,...,39.619764,4.874989,39.154367,0.638020,163.428827,36.790070,16.188424,16.120236,16.660210,fail
3,0.435807,0.603927,0.105241,0.029628,0.217718,0.058043,0.006527,0.165434,0.058409,0.010674,...,93.266322,11.229285,92.372700,1.471113,370.644451,82.463005,37.781360,38.909603,41.306969,fail
4,0.485333,0.443708,0.095745,0.047518,0.273415,0.076923,0.007363,0.266769,0.048550,0.008426,...,81.620612,12.334089,82.071677,1.450652,51.029854,58.464638,25.276462,25.016155,25.815739,fail
5,0.415767,0.548011,0.097577,0.028536,0.278242,0.046930,0.004062,0.177056,0.018755,0.002143,...,29.848653,3.319580,29.787195,0.436554,102.972447,21.785605,11.728101,13.522143,15.541653,fail
6,0.424008,0.365744,0.138719,0.046418,0.453336,0.061892,0.005118,0.178726,0.048519,0.008817,...,69.015291,8.494986,68.202106,1.111774,284.857024,64.137243,28.203311,28.068630,28.995336,fail
7,0.222072,0.513585,0.084055,0.022216,0.288594,0.028256,0.002347,0.042306,0.039065,0.005906,...,69.145517,8.354645,69.015710,1.068922,205.905356,52.173926,26.166688,28.857717,32.220516,fail
8,0.431400,0.574459,0.061557,0.021172,0.215230,0.032163,0.001494,0.119845,0.007396,0.000808,...,8.999286,1.165431,9.012045,0.144603,19.394776,6.512319,3.192650,3.472471,3.842675,fail
9,0.619861,0.641141,0.087021,0.062561,0.285106,0.075894,0.010032,0.213922,0.077693,0.015202,...,123.995110,18.270122,123.875963,2.199566,201.281489,101.129142,41.793170,39.557955,39.240062,fail
10,0.297128,0.383066,0.134295,0.031900,0.330977,0.082488,0.004194,0.169899,0.069405,0.010528,...,126.809256,15.969870,126.903071,2.001929,305.307977,91.919143,45.931194,50.591553,56.463945,pass
11,0.464955,0.440874,0.140608,0.044183,0.258761,0.104091,0.010324,0.228036,0.114422,0.020866,...,199.846482,26.339219,199.352535,3.286813,507.780230,159.144843,72.864901,75.233022,80.118693,pass
12,0.558797,0.504212,0.101192,0.042349,0.212078,0.088699,0.007535,0.261912,0.056002,0.010527,...,92.085798,14.062118,92.381945,1.659196,77.687063,69.997653,29.025039,27.630854,27.577103,pass
13,0.578513,0.557901,0.109539,0.049371,0.475979,0.031579,0.004887,0.196477,0.005677,0.000074,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,pass
14,0.202438,0.388876,0.086453,0.024252,0.262229,0.038907,0.003541,0.207328,0.005348,0.000344,...,4.606565,0.512313,4.597080,0.067374,15.891816,3.362189,1.810007,2.086883,2.398555,pass
15,0.402316,0.423963,0.090039,0.036079,0.144212,0.084659,0.007990,0.169174,0.084518,0.016866,...,140.646803,19.826505,140.247097,2.428471,303.735022,116.611804,49.595068,48.143731,48.793777,pass
16,0.224312,0.284177,0.097106,0.027212,0.277546,0.055988,0.003455,0.155877,0.034365,0.004826,...,61.830839,6.954937,61.639254,0.914119,217.784674,46.446879,24.398519,27.704615,31.529493,pass
17,0.543633,0.623292,0.102246,0.042447,0.173012,0.092518,0.009012,0.219968,0.093321,0.018049,...,155.887002,21.646204,155.479639,2.661211,347.477796,127.692712,55.322933,54.589668,56.089895,pass
18,0.451254,0.391251,0.155873,0.053836,0.293747,0.133907,0.010952,0.255981,0.130597,0.023606,...,226.481462,29.399107,225.759147,3.692841,617.092318,181.814372,83.775917,86.896948,92.849575,pass
19,0.506294,0.621370,0.136496,0.046887,0.317016,0.094604,0.007921,0.165621,0.103250,0.018451,...,178.591268,23.554655,178.211744,2.935883,445.146234,141.216022,64.881658,67.182955,71.705916,pass

[[1.39852213 1.26246711 1.46151602 1.53698528 1.60587428 1.32436266
  1.80003103 1.67854701 2.27760525 2.45360114 2.30223655 2.40640243
  2.263624   2.27371696 2.41404978 2.29957383 2.43399797 2.38747918
  2.39988491 2.39071005 2.38855301 2.36418012 2.38078551 2.38245929
  2.36104618 2.35731657 2.38994218 2.36001251 2.35693377 2.39263542
  2.35778113 2.39372246 2.53711048 2.35145387 2.39061225 2.52899759
  2.36660639 2.52835101 2.35476342 2.38891806 2.52604201 2.36090692
  2.52592114 2.35528668 2.5246983  2.36228701 2.52422191 2.34894669
  2.52303456 2.35564609 2.52988361 2.40700739 2.52732029 2.38333262
  2.52598691 2.40359858 2.52547297 2.37773381 2.52958346 2.44020284
  2.52300044 2.4413854  2.51857709 2.39894881 2.36853312 2.33460445
  2.39599727 2.33853741 2.41997467 2.38787108 2.32278418 2.38336278
  2.38853852 2.40241668 2.37972029 2.33468863 2.38770161 2.39853689
  2.37970339 2.37694729 2.38701114 2.39664399 2.38178058 2.35241927
  2.39013724 2.36091217 2.37286034 2.34957823 2.38918193 2.35990526
  2.34775661 2.39088443 2.3481441  2.37805347 2.51696404 2.34091166
  2.38513812 2.51487736 2.3546408  2.51595379 2.34444049 2.38584531
  2.51369439 2.35594444 2.51573006 2.34473811 2.5148261  2.35451682
  2.51537285 2.34403033 2.5154466  2.35289101 2.51653285 2.39832857
  2.5159376  2.37590912 2.51752496 2.39787052 2.51790154 2.37420734
  2.50964011 2.43499166 2.50847366 2.43795093 2.47885733 2.3982227
  2.36641781 2.33462428 2.39531328 2.33899937 2.41847854 2.38365629
  2.32544585 2.38264575 2.38807102 2.40295104 2.37826472 2.33749843
  2.38740714 2.3991079  2.37908497 2.37784125 2.38692031 2.39746141
  2.38227128 2.35396621 2.39022704 2.36236586 2.37344489 2.35204055
  2.38934476 2.36230226 2.35012612 2.39098915 2.35048724 2.37818922
  2.51240598 2.34407079 2.38546457 2.51052365 2.35654529 2.51147499
  2.34686625 2.38620967 2.50930174 2.35781784 2.51116186 2.34706603
  2.51042763 2.35665062 2.5110161  2.34647545 2.51114668 2.35520122
  2.5121391  2.3983518  2.51161831 2.37720696 2.51326748 2.39818653
  2.51367394 2.375828   2.50531496 2.43379678 2.504372   2.43685144
  2.47461516 2.13526823 2.40323823 2.3699002  2.34483627 2.32607616]]
BARINEL SCORES

,u 187,u 190,u 191,p 188,cx 189,u 184,p 185,x 4,cx 186,cx 183,...,cp 87,cp 159,cp 137,cp 135,cp 85,cp 154,cp 145,cp 143,cp 149,cp 147
sum,0.546059,0.523692,0.511696,0.505288,0.480666,0.455305,0.443934,0.430923,0.418383,0.412641,...,0.392034,0.392024,0.392012,0.392008,0.391981,0.391854,0.391786,0.391758,0.391683,0.391636

custom SCORES

,u 187,p 188,u 191,u 190,x 4,p 180,p 182,cx 189,p 175,p 177,...,cx 114,cx 56,cx 118,cx 110,u 121,u 59,cx 181,h 0,cx 176,cx 186
sum,0.765284,0.699443,0.6906,0.688977,0.660957,0.657906,0.657358,0.656291,0.653765,0.651693,...,0.636498,0.636484,0.636436,0.636434,0.636358,0.636184,0.635914,0.635648,0.634515,0.556906

DSTAR SCORES

,cx 18,x 4,cx 22,cx 26,cx 10,cx 14,cx 37,cx 31,cx 39,cx 20,...,p 173,p 177,p 162,p 182,p 175,p 169,p 185,p 180,cp 129,p 167
sum,1974.880388,1621.534077,1385.585675,1370.672853,1174.912324,1030.326851,1006.654328,967.995184,953.203709,916.928584,...,0.002591,0.001302,0.00116,0.00072,0.000496,0.000362,0.000308,0.000209,0.000165,0.000089

ERROR GATE LOCATION:
178
Now evolving the following mutant:  AddGate_cx_inGap_95_.qasm

100%|██████████| 10/10 [02:27<00:00, 14.75s/it]
100%|██████████| 10/10 [04:00<00:00, 24.04s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.611834,0.599260,0.117839,0.042161,0.211050,0.101978,0.009456,0.286437,0.088487,0.014563,...,204.728262,27.236117,205.159032,3.346338,390.075649,147.909844,71.125579,76.344348,83.719144,fail
1,0.515077,0.548224,0.102433,0.041335,0.253247,0.069219,0.008145,0.108868,0.097769,0.019030,...,205.904034,28.157615,205.234267,3.482793,496.356845,169.698606,74.160008,73.692866,76.144501,fail
2,0.502771,0.570888,0.117324,0.033496,0.217756,0.092524,0.005529,0.189037,0.080051,0.013872,...,168.465881,19.855918,167.206029,2.603500,645.046256,141.759925,67.678078,71.954009,78.241361,fail
3,0.606552,0.514831,0.123649,0.056545,0.349778,0.086004,0.008479,0.198432,0.080996,0.016031,...,159.927584,23.315003,159.580320,2.823677,296.083431,133.034298,54.929810,51.910064,51.406180,fail
4,0.468577,0.527549,0.104962,0.038457,0.253296,0.074256,0.006846,0.152908,0.081373,0.013218,...,186.116602,24.760107,186.508211,3.042125,354.614226,134.463494,64.659617,69.403953,76.108313,fail
5,0.499801,0.577114,0.097996,0.032024,0.312947,0.046728,0.003303,0.177307,0.016876,0.002298,...,30.380512,4.065116,30.420695,0.499710,59.798848,22.419745,10.601096,11.236692,12.210011,fail
6,0.393495,0.651472,0.092733,0.028230,0.453142,0.002631,0.000300,0.015506,0.004113,0.000050,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,fail
7,0.508279,0.659709,0.105006,0.037429,0.283879,0.064150,0.005513,0.207972,0.037959,0.007682,...,63.103120,8.086884,62.099460,1.056276,278.665074,64.003113,26.211437,24.420514,23.810467,fail
8,0.253202,0.377075,0.114690,0.033947,0.364555,0.053504,0.004479,0.175232,0.034680,0.006323,...,72.620078,11.412053,73.105136,1.325098,14.418099,51.870932,21.577257,20.650603,20.726786,fail
9,0.514498,0.678084,0.095009,0.034140,0.350286,0.036100,0.003270,0.088034,0.038315,0.007659,...,63.103120,8.086884,62.099460,1.056276,278.665074,64.003113,26.211437,24.420514,23.810467,fail
10,0.388008,0.401712,0.094874,0.038518,0.343420,0.045185,0.004858,0.096160,0.049346,0.009543,...,93.467255,11.624331,92.432217,1.512988,372.057779,86.110815,37.807506,37.587076,38.799033,pass
11,0.533947,0.576091,0.124599,0.049113,0.316766,0.089096,0.007883,0.188145,0.100897,0.017240,...,222.888641,29.515839,222.854998,3.654160,494.749030,169.173912,79.331480,83.509645,90.263448,pass
12,0.405261,0.443898,0.124812,0.035346,0.291339,0.079205,0.005618,0.145244,0.087814,0.014681,...,192.289422,23.447184,191.531537,3.009231,613.453120,152.513983,73.817342,79.372280,87.054367,pass
13,0.193192,0.311386,0.107582,0.021895,0.200174,0.065578,0.004577,0.075547,0.078763,0.013854,...,168.465881,19.855918,167.206029,2.603500,645.046256,141.759925,67.678078,71.954009,78.241361,pass
14,0.419779,0.468563,0.090985,0.033757,0.207970,0.072493,0.005530,0.147157,0.071129,0.012297,...,152.962538,18.534416,152.121255,2.394380,523.690851,125.032538,59.696062,63.521538,69.135081,pass
15,0.389176,0.342999,0.079586,0.037854,0.305631,0.045162,0.004790,0.031697,0.071026,0.014426,...,144.851987,21.208084,144.608242,2.562229,254.954492,119.553580,49.381222,46.695092,46.272294,pass
16,0.415272,0.436200,0.133075,0.032405,0.172149,0.102466,0.008610,0.219643,0.101907,0.018234,...,220.140055,27.279741,218.974292,3.496873,719.684544,180.925281,84.886791,89.179723,96.164508,pass
17,0.456158,0.440282,0.113743,0.037466,0.385148,0.046188,0.004456,0.043341,0.069992,0.012356,...,152.889815,21.545339,153.213432,2.604449,234.718280,113.901277,51.368950,52.535554,55.593637,pass
18,0.456846,0.494979,0.088772,0.039843,0.196886,0.067786,0.007422,0.235519,0.049146,0.009098,...,93.396108,11.625918,92.492375,1.506800,354.744843,83.858651,37.322222,37.549033,39.141998,pass
19,0.439044,0.366446,0.135318,0.048304,0.378227,0.086623,0.006803,0.124279,0.094651,0.017906,...,195.993131,26.720455,195.398869,3.306020,470.806141,160.559621,70.562235,70.459469,73.093417,pass

[[1.25527956 1.1887443  1.15382797 1.49684094 1.48574098 1.62620397
  1.70926672 1.7905332  1.74395374 1.88928862 1.74691667 1.86867571
  1.77155954 1.84275849 1.75187678 1.86371051 1.77199893 1.82539347
  1.78604561 1.80767316 1.76859451 1.80444893 1.7746841  1.78582706
  1.76550568 1.80680259 1.7694356  1.76350701 1.80967408 1.76768122
  1.8107352  1.83163792 1.76367044 1.80632858 1.82378035 1.77448403
  1.82129571 1.76658298 1.76265698 1.80256258 1.81909645 1.76931532
  1.81555886 1.76594195 1.8149236  1.77095813 1.81506479 1.76050829
  1.8148941  1.76360809 1.82467155 1.77482449 1.82301088 1.77719726
  1.81999476 1.7827892  1.81952976 1.7709224  1.83680321 1.78876536
  1.83132458 1.78490827 1.84565193 1.81754298 1.77438747 1.75458173
  1.81347721 1.81179715 1.82357038 1.80131506 1.86332365 1.83234293
  1.80299178 1.85045521 1.79018104 1.79447497 1.80182448 1.85016205
  1.79046781 1.83728523 1.80089957 1.85110316 1.79343031 1.77225914
  1.80530429 1.79251328 1.78129325 1.77391233 1.80398492 1.79231386
  1.76358313 1.80638949 1.75949657 1.78886994 1.81225723 1.77053944
  1.79839982 1.81117263 1.7566315  1.81223217 1.7658592  1.79963647
  1.81291323 1.76150208 1.81026238 1.76094602 1.80884797 1.7590477
  1.81116418 1.75719938 1.81089736 1.75866931 1.81511186 1.78847106
  1.8150351  1.76626904 1.8151215  1.79367964 1.81526354 1.76448135
  1.81861587 1.78363859 1.81881792 1.78480647 1.8124124  1.81705793
  1.7730112  1.74918328 1.81301195 1.81480029 1.82448334 1.79679412
  1.86560938 1.83569563 1.80206085 1.84906084 1.78797896 1.79683952
  1.80113724 1.84828891 1.78919167 1.83708975 1.80045992 1.84896141
  1.79327874 1.77680267 1.80521241 1.79452292 1.78125109 1.77625156
  1.80398072 1.79329127 1.7664624  1.80646168 1.76220588 1.78891415
  1.81081712 1.77198356 1.79857821 1.80990508 1.75687804 1.81076497
  1.76756061 1.80007551 1.81152399 1.76154578 1.80939495 1.7620626
  1.80815222 1.75943156 1.81008294 1.75862025 1.80986683 1.75921834
  1.81351511 1.78657788 1.81346768 1.7666107  1.81366534 1.79207512
  1.81380628 1.76523023 1.81665861 1.78372399 1.81690519 1.78245631
  1.81057943 2.29250051 1.82635978 1.77775957 1.80043173 1.87636523]]
BARINEL SCORES

,u 190,u 184,u 191,u 187,p 188,cx 189,p 185,cx 186,cp 160,cp 133,...,u 62,cx 126,cx 54,u 124,cx 64,cx 116,h 0,u 59,u 121,x 4
sum,0.571177,0.550405,0.54333,0.521567,0.50217,0.494987,0.477449,0.472609,0.427508,0.426665,...,0.400516,0.400448,0.400432,0.400382,0.400355,0.400002,0.398395,0.398378,0.397992,0.375282

custom SCORES

,u 184,u 190,u 187,u 191,p 188,p 185,cx 186,cx 189,cp 160,cp 133,...,cx 144,cx 24,cx 99,cx 91,cx 20,cx 96,cx 86,cx 82,cx 126,cx 64
sum,0.796785,0.740922,0.715295,0.713838,0.690087,0.681471,0.664749,0.63777,0.623268,0.62259,...,0.579051,0.579008,0.578976,0.578818,0.578581,0.578562,0.578437,0.577959,0.576102,0.575428

DSTAR SCORES

,cx 18,cx 22,cx 26,cx 10,x 4,cx 14,cx 37,cx 31,cx 39,cx 20,...,p 174,p 178,p 163,p 182,p 176,p 170,p 185,p 180,cp 129,p 168
sum,2816.83672,1980.629826,1960.783233,1720.164824,1686.663744,1510.701612,1431.79678,1385.542216,1355.994111,1297.494338,...,0.003496,0.001772,0.001558,0.001001,0.000682,0.000484,0.000304,0.000286,0.000253,0.000118

ERROR GATE LOCATION:
154
Now evolving the following mutant:  AddGate_x_inGap_36_.qasm

100%|██████████| 10/10 [03:25<00:00, 20.51s/it]
100%|██████████| 10/10 [02:17<00:00, 13.72s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.376941,0.462444,0.104315,0.029682,0.223514,0.069950,0.004714,0.057464,0.091128,0.016033,...,155.443083,19.120332,154.565844,2.459364,521.258489,128.211036,60.314667,63.483113,68.544562,fail
1,0.438960,0.483699,0.144692,0.047689,0.354857,0.099855,0.006897,0.185062,0.090696,0.014661,...,163.637913,21.969765,164.017863,2.690767,297.572618,118.151619,56.429905,60.283518,65.886562,fail
2,0.408233,0.535118,0.118293,0.030362,0.251855,0.080693,0.005882,0.150852,0.079734,0.015280,...,133.503137,17.649761,132.855367,2.214953,376.941907,111.868013,49.671701,49.983645,52.154840,fail
3,0.364838,0.501008,0.118805,0.046056,0.372986,0.073399,0.006397,0.343522,0.004775,0.000052,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,fail
4,0.309867,0.464871,0.083789,0.029548,0.120393,0.075277,0.006206,0.209493,0.054650,0.009170,...,92.238843,10.808552,91.598288,1.417799,349.611548,76.565654,36.971577,39.639611,43.367049,fail
5,0.463899,0.551427,0.139054,0.043787,0.317427,0.088713,0.007368,0.201854,0.088658,0.015232,...,147.753942,17.424340,146.637355,2.284927,566.336747,124.504061,59.369829,63.066057,68.532141,fail
6,0.561418,0.546664,0.099361,0.046191,0.219669,0.091163,0.008426,0.108890,0.119992,0.021875,...,209.362981,27.593468,208.845513,3.443328,531.960241,166.723169,76.334659,78.815547,83.933868,fail
7,0.373908,0.377797,0.127610,0.042285,0.294597,0.078884,0.008508,0.264196,0.059712,0.011041,...,95.759275,13.086737,95.437181,1.619618,232.374558,79.053046,34.530507,34.298519,35.426441,fail
8,0.472135,0.608995,0.119542,0.030760,0.262639,0.071915,0.005445,0.234224,0.037072,0.006487,...,56.967774,7.186603,56.560816,0.920920,193.492244,48.956917,22.134692,22.580309,23.806036,fail
9,0.348934,0.319879,0.141488,0.046193,0.244646,0.120678,0.010072,0.253036,0.113386,0.021132,...,194.425695,26.147708,193.934662,3.243926,470.914100,156.516689,70.169115,71.247063,74.902412,fail
10,0.333536,0.445781,0.095865,0.024653,0.252073,0.043480,0.003309,0.111753,0.045060,0.005845,...,82.058231,9.126003,81.889277,1.200149,283.086041,59.891756,32.242234,37.174312,42.726234,pass
11,0.316871,0.321923,0.138121,0.045162,0.468953,0.073839,0.003779,0.095952,0.077077,0.011997,...,139.933366,18.032232,140.114750,2.241426,307.912785,101.293001,49.830462,54.323469,60.209705,pass
12,0.403209,0.576756,0.138522,0.028165,0.335007,0.062225,0.004473,0.140939,0.055237,0.007212,...,101.366050,11.273297,101.157342,1.482537,349.694521,73.983934,39.828642,45.921209,52.779466,pass
13,0.489371,0.629418,0.088036,0.033668,0.189407,0.065796,0.006498,0.121640,0.086078,0.014676,...,150.548464,17.575677,149.556693,2.305878,566.878222,123.865501,60.256573,64.954047,71.337408,pass
14,0.413309,0.434461,0.121461,0.042059,0.380621,0.059327,0.005668,0.172851,0.054033,0.008503,...,95.443054,12.707682,95.644446,1.561021,181.090005,68.949001,33.135023,35.551371,38.973610,pass
15,0.442241,0.455637,0.088072,0.035763,0.195194,0.065458,0.006856,0.145140,0.074296,0.012425,...,136.217743,18.561124,136.585877,2.261401,228.401668,98.260642,46.405194,49.180422,53.449065,pass
16,0.491103,0.391490,0.109403,0.048355,0.303396,0.067590,0.008282,0.276632,0.041754,0.008459,...,55.671126,7.133862,54.784753,0.931966,245.837086,56.462519,23.123020,21.543870,21.006320,pass
17,0.575999,0.560688,0.099694,0.041667,0.397826,0.045525,0.003413,0.145006,0.024443,0.004389,...,28.723712,3.680741,28.266385,0.480851,126.840504,29.132034,11.930403,11.115635,10.838284,pass
18,0.303950,0.369084,0.149067,0.039742,0.351364,0.094549,0.006696,0.188360,0.081747,0.013273,...,149.991537,19.918402,150.298128,2.449081,288.275733,108.373079,52.181318,56.061310,61.514996,pass
19,0.356459,0.420904,0.113678,0.036559,0.395328,0.045390,0.003360,0.038808,0.070192,0.010956,...,120.286884,13.878505,119.629009,1.821849,443.554667,96.207746,47.926762,52.538638,58.389248,pass

[[1.36295194 1.25516663 1.20884408 1.21483303 1.40084303 1.41886266
  1.44056389 1.71026122 1.62195015 1.67034503 1.62608657 1.65937528
  1.61121629 1.65544185 1.6278817  1.66212156 1.65197058 1.64980016
  1.65852309 1.64536786 1.63690585 1.64328286 1.64711628 1.63745841
  1.63340291 1.6457578  1.63676181 1.63312016 1.64663405 1.63287622
  1.64697589 1.73215778 1.62981678 1.64581744 1.72828745 1.63699445
  1.72833109 1.63129612 1.64518121 1.72688515 1.6342513  1.72748381
  1.63154914 1.72699274 1.63476377 1.72651774 1.6285751  1.72603812
  1.63206448 1.72856778 1.66122069 1.72726999 1.64655442 1.72697281
  1.66015798 1.72673133 1.64428017 1.72640035 1.6791053  1.72310812
  1.68048208 1.71729301 1.64877731 1.6378526  1.6215313  1.64770134
  1.62768894 1.67124966 1.64477732 1.62243257 1.65225995 1.64507535
  1.66338328 1.64194206 1.62481612 1.64477086 1.66128359 1.64192445
  1.64920906 1.64452011 1.66036048 1.64269456 1.63285937 1.64563512
  1.63838175 1.63947901 1.63145911 1.64528957 1.63786277 1.62995563
  1.64588836 1.62993058 1.64124172 1.72265505 1.6267708  1.64383564
  1.72154197 1.63294576 1.72204072 1.62834364 1.64404462 1.72051209
  1.63285987 1.72222918 1.62823432 1.72190496 1.6324367  1.72185668
  1.62766187 1.72194931 1.63153726 1.72191836 1.65790273 1.7215582
  1.64402082 1.7225352  1.65794175 1.72274798 1.64331893 1.71700577
  1.6768651  1.71624485 1.67896339 1.69887033 1.64844211 1.6370915
  1.62231346 1.64739771 1.62820018 1.67058982 1.64323036 1.62397193
  1.65214259 1.64496614 1.66361264 1.64155441 1.62644823 1.64758736
  1.64472915 1.66152866 1.64183356 1.6496886  1.6445555  1.66069176
  1.6430282  1.63391501 1.64570884 1.63926775 1.63985322 1.63288035
  1.6453943  1.6391681  1.63134824 1.64594655 1.63130394 1.64134137
  1.72006405 1.62849913 1.64401044 1.71904242 1.63405694 1.7194917
  1.62971081 1.64419268 1.71800619 1.63398281 1.71952688 1.62951386
  1.71927804 1.63366102 1.71932006 1.62901838 1.71943804 1.6328294
  1.71944234 1.65782137 1.71912483 1.64475211 1.72012215 1.65802966
  1.7203525  1.64416664 1.71464603 1.67612052 1.71401556 1.67821149
  1.6965885  1.59961235 1.64982569 1.63834068 1.63045043 1.62488109]]
BARINEL SCORES

,u 184,cx 186,p 180,p 182,p 185,p 176,cp 130,p 178,cp 134,cp 132,...,u 125,u 63,u 60,u 122,h 0,u 190,cx 189,p 188,u 191,u 187
sum,0.582932,0.577134,0.574893,0.57264,0.57191,0.564203,0.559684,0.558903,0.555652,0.554137,...,0.52891,0.52858,0.523665,0.523663,0.522945,0.512992,0.511764,0.510908,0.499581,0.44887

custom SCORES

,u 184,p 180,p 182,cp 130,p 176,cp 134,cp 160,cp 132,cp 142,p 178,...,u 125,u 63,u 60,u 122,h 0,u 190,u 191,cx 189,p 188,u 187
sum,0.832174,0.813384,0.811766,0.79997,0.798646,0.795471,0.793791,0.792846,0.790607,0.790211,...,0.744135,0.743738,0.736269,0.736065,0.735376,0.673965,0.669807,0.666425,0.666075,0.606069

DSTAR SCORES

,cx 18,x 4,cx 22,cx 26,cx 10,cx 14,cx 37,cx 31,cx 39,cx 20,...,p 174,p 178,p 163,p 182,p 176,p 170,p 185,p 180,cp 130,p 168
sum,5422.342039,4134.778112,3806.136617,3769.037265,3252.715149,2854.837785,2753.456779,2656.653875,2605.807706,2504.355896,...,0.006449,0.003186,0.002926,0.001699,0.0012,0.00091,0.000486,0.000478,0.000396,0.000226

ERROR GATE LOCATION:
54
Now evolving the following mutant:  AddGate_x_inGap_96_.qasm

100%|██████████| 10/10 [02:42<00:00, 16.25s/it]
100%|██████████| 10/10 [02:09<00:00, 12.90s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.612474,0.586958,0.092760,0.043814,0.289093,0.069816,0.006042,0.188346,0.051463,0.009031,...,88.364763,13.239215,88.831424,1.561523,63.317551,63.334237,27.602851,27.501895,28.532885,fail
1,0.519900,0.677361,0.112404,0.027749,0.177279,0.079105,0.007169,0.181749,0.073667,0.014445,...,123.020580,16.965713,122.599180,2.094476,292.330214,102.130588,44.165210,43.491272,44.604322,fail
2,0.617327,0.678110,0.137364,0.044659,0.296411,0.096661,0.007391,0.208195,0.082216,0.014248,...,134.103131,15.906182,133.014651,2.085276,519.243923,114.540758,54.006167,56.881919,61.424411,fail
3,0.483808,0.522010,0.093100,0.035646,0.411523,0.033292,0.001432,0.116021,0.004580,0.000076,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,fail
4,0.271166,0.529101,0.068287,0.022277,0.133697,0.054253,0.004783,0.087791,0.057386,0.011520,...,96.904375,14.039094,96.805579,1.698304,169.201709,78.439358,33.026750,31.803165,32.024787,fail
5,0.603469,0.726571,0.119115,0.044609,0.341376,0.074987,0.006162,0.096377,0.083882,0.016821,...,133.669988,19.390839,133.304048,2.355338,261.317910,112.172984,46.297046,43.723296,43.268016,fail
6,0.412374,0.544859,0.105340,0.027982,0.277491,0.053579,0.004053,0.096368,0.061910,0.010586,...,103.178227,12.158036,102.406343,1.594394,394.932881,86.781753,41.445927,44.077083,47.937838,fail
7,0.515556,0.573995,0.065561,0.038160,0.213770,0.050935,0.005050,0.143263,0.045852,0.009394,...,64.508807,8.522642,63.681401,1.093241,247.591144,62.774808,25.748759,24.056916,23.528687,fail
8,0.619690,0.623734,0.055058,0.041664,0.191610,0.053052,0.007026,0.185941,0.042257,0.007858,...,73.330782,11.412146,73.798916,1.329409,22.431444,52.414149,22.019231,21.260667,21.499375,fail
9,0.499754,0.737219,0.048729,0.022330,0.154398,0.034347,0.003912,0.035497,0.051260,0.010011,...,92.713264,14.569242,93.331877,1.691890,18.401265,66.220184,27.545781,26.363551,26.461341,fail
10,0.324698,0.387730,0.105439,0.038429,0.363825,0.040244,0.004321,0.143353,0.035903,0.004494,...,62.538728,6.955166,62.409964,0.914665,215.747289,45.645077,24.572651,28.331517,32.562783,pass
11,0.596785,0.518560,0.129523,0.052938,0.313281,0.095339,0.009560,0.239544,0.083490,0.016843,...,133.669988,19.390839,133.304048,2.355338,261.317910,112.172984,46.297046,43.723296,43.268016,pass
12,0.436775,0.429884,0.118361,0.047590,0.335831,0.086912,0.006543,0.205567,0.070654,0.013087,...,115.596431,16.178915,115.428396,1.978431,234.733810,92.780647,40.387125,40.037473,41.304474,pass
13,0.244497,0.311548,0.070071,0.018446,0.167106,0.042829,0.002987,0.173679,0.008854,0.000899,...,12.529106,1.393409,12.503309,0.183245,43.223148,9.144606,4.922923,5.675980,6.523679,pass
14,0.375377,0.385825,0.079273,0.023790,0.293101,0.030901,0.001716,0.117238,0.003059,0.000041,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,pass
15,0.394288,0.509054,0.105275,0.043408,0.352290,0.051791,0.005948,0.125743,0.054251,0.010985,...,78.724291,10.718084,77.961801,1.350656,256.000153,73.325601,30.128941,28.235142,27.707717,pass
16,0.465311,0.482521,0.140578,0.046425,0.365807,0.084562,0.008479,0.320317,0.042871,0.007654,...,70.908056,11.142706,71.381178,1.293975,14.073477,50.645876,21.067296,20.163115,20.237905,pass
17,0.457780,0.557927,0.089510,0.033897,0.192781,0.069171,0.006290,0.278222,0.017520,0.003199,...,21.530268,2.803502,21.222181,0.362745,88.596359,21.375523,8.760960,8.174225,7.982786,pass
18,0.414394,0.474582,0.130636,0.040854,0.201485,0.110942,0.009383,0.341557,0.073591,0.012655,...,123.332408,14.535795,122.407386,1.906193,472.241242,103.781621,49.545536,52.675563,57.277275,pass
19,0.514912,0.518906,0.069708,0.037502,0.234229,0.048467,0.004268,0.138605,0.045598,0.005878,...,82.058231,9.126003,81.889277,1.200149,283.086041,59.891756,32.242234,37.174312,42.726234,pass

[[1.2019947  1.18907894 1.53015261 1.28001921 1.65493077 1.61094349
  1.39395858 1.55422082 1.5128304  1.61757344 1.49827816 1.64090327
  1.57991888 1.55261705 1.52102721 1.57807403 1.60016943 1.54107086
  1.55504943 1.59144594 1.68884158 1.59362489 1.63219157 1.64674036
  1.72182682 1.59566194 1.72137095 1.72793279 1.58863928 1.72304331
  1.58545723 1.56510864 1.74623681 1.59765771 1.55247159 1.69009386
  1.54345369 1.54903192 1.73338107 1.60431916 1.54831473 1.71124245
  1.54294525 1.73168446 1.54036137 1.7057604  1.54148608 1.75540222
  1.53926677 1.73160175 1.5548781  1.55941659 1.55188306 1.63433132
  1.54723548 1.57275955 1.54633319 1.65536665 1.57014233 1.47886753
  1.56178287 1.474043   1.58372852 1.56724658 1.68333648 1.80973359
  1.57815702 1.80710703 1.52435475 1.6086305  1.87573683 1.64883016
  1.60624723 1.58627154 1.63995882 1.81891545 1.6094029  1.59929934
  1.63999513 1.67210291 1.61201161 1.60593921 1.63207712 1.75011238
  1.60018195 1.72247407 1.66655309 1.760678   1.60377728 1.72611062
  1.76576511 1.59733427 1.76371036 1.64613029 1.53403489 1.79200767
  1.61909648 1.53191959 1.73909503 1.53360716 1.77824296 1.61629815
  1.5338754  1.73229724 1.53094318 1.77639736 1.52877318 1.73831926
  1.53202256 1.77841621 1.53167535 1.74404809 1.53759835 1.59184406
  1.53733174 1.6635148  1.5379129  1.59408619 1.5382008  1.66995301
  1.54035157 1.4704224  1.5402656  1.46820458 1.52320499 1.56976181
  1.69168383 1.81190172 1.58056801 1.80618371 1.52958145 1.6245647
  1.86600169 1.65200608 1.60815595 1.58433383 1.64590826 1.80891856
  1.61067249 1.59721628 1.64270467 1.66899003 1.61252046 1.60289884
  1.63058582 1.74519635 1.59994273 1.71760849 1.66469225 1.7520994
  1.60327377 1.71765431 1.75756612 1.59698951 1.75560011 1.64573373
  1.53068189 1.78059636 1.61799472 1.52891906 1.7325542  1.53034032
  1.76964105 1.61495613 1.53072638 1.7259661  1.52842298 1.76805807
  1.52654856 1.73094054 1.529298   1.76968767 1.52904718 1.73595027
  1.53419876 1.59153475 1.53398623 1.65912475 1.53472399 1.5928225
  1.535028   1.66428643 1.53642434 1.47399459 1.53647868 1.4684727
  1.51919558 2.61088228 1.55034368 1.67795156 1.78223965 1.86540637]]
BARINEL SCORES

,cp 160,cp 133,cp 129,cp 141,cp 131,cp 157,cp 139,cp 154,cp 151,cp 137,...,u 59,h 0,u 121,x 4,p 188,cx 186,p 185,u 187,cx 189,u 184
sum,0.583416,0.582996,0.58287,0.581858,0.581656,0.58158,0.581359,0.581252,0.580952,0.580862,...,0.541043,0.540806,0.540609,0.51552,0.476515,0.475765,0.471221,0.468615,0.463675,0.391295

custom SCORES

,x 4,p 180,cp 129,p 182,cp 133,cp 160,cp 131,cp 141,cp 157,cp 139,...,cx 177,cx 181,u 190,u 191,cx 186,u 187,cx 189,p 185,p 188,u 184
sum,0.852011,0.815551,0.813648,0.812582,0.811843,0.811693,0.808761,0.808037,0.807301,0.80691,...,0.76445,0.763582,0.746346,0.714766,0.667372,0.662496,0.641048,0.635437,0.629002,0.543335

DSTAR SCORES

,cx 18,cx 22,cx 26,cx 10,cx 14,x 4,cx 37,cx 31,cx 39,cx 20,...,p 178,p 163,p 182,p 176,p 170,p 180,p 185,cp 129,p 168,x 155
sum,3890.936881,2735.324389,2713.437259,2402.548098,2112.218749,2104.926785,1958.889541,1907.066346,1852.406762,1770.724095,...,0.001804,0.001514,0.001073,0.000707,0.000468,0.000309,0.000279,0.00026,0.000111,0.000053

ERROR GATE LOCATION:
155
Now evolving the following mutant:  AddGate_z_inGap_58_.qasm

100%|██████████| 10/10 [02:53<00:00, 17.31s/it]
100%|██████████| 10/10 [02:52<00:00, 17.27s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.549437,0.648246,0.116440,0.047115,0.467725,0.042417,0.005032,0.114480,0.040210,0.008076,...,53.020120,6.794154,52.175955,0.887586,234.130558,53.773828,22.021924,20.517972,20.006019,fail
1,0.542403,0.525741,0.099102,0.044151,0.232954,0.072887,0.007798,0.200100,0.072241,0.012051,...,122.844984,14.352537,122.026640,1.882942,463.195502,101.258314,49.183025,52.958159,58.116251,fail
2,0.411866,0.467846,0.104874,0.036080,0.134576,0.100651,0.008109,0.149573,0.113611,0.020869,...,199.846482,26.339219,199.352535,3.286813,507.780230,159.144843,72.864901,75.233022,80.118693,fail
3,0.445628,0.476655,0.094569,0.034036,0.336591,0.038902,0.002993,0.180171,0.009035,0.000808,...,7.226939,1.135663,7.275160,0.131882,1.434367,5.161821,2.147176,2.055022,2.062644,fail
4,0.530667,0.386173,0.160179,0.054808,0.411386,0.098991,0.009422,0.266362,0.092854,0.015507,...,164.216556,21.773496,164.289895,2.690349,350.442705,123.008420,58.066000,61.444788,66.674495,fail
5,0.485090,0.408991,0.140287,0.049834,0.500626,0.061936,0.004659,0.045200,0.091384,0.014576,...,164.160004,21.839279,164.503036,2.683529,312.721167,118.596808,57.028371,61.212454,67.124242,fail
6,0.386470,0.721324,0.085316,0.020549,0.124193,0.059931,0.004845,0.186020,0.050199,0.007263,...,91.536146,10.340531,91.216288,1.358815,324.939388,69.504405,36.178889,40.842119,46.302525,fail
7,0.405081,0.378062,0.154096,0.046779,0.426455,0.089827,0.007728,0.234351,0.063091,0.012376,...,103.901585,15.576228,104.009606,1.856999,129.864177,81.981408,33.932730,32.203382,32.035540,fail
8,0.524760,0.484148,0.112918,0.044302,0.422221,0.036404,0.004955,0.118444,0.040078,0.007821,...,52.685105,6.716096,51.875039,0.877589,230.646601,52.844034,21.836231,20.525356,20.177064,fail
9,0.509932,0.520629,0.150663,0.043599,0.401446,0.081146,0.005691,0.168676,0.075438,0.012676,...,123.332408,14.535795,122.407386,1.906193,472.241242,103.781621,49.545536,52.675563,57.277275,fail
10,0.339892,0.369691,0.064149,0.025263,0.210927,0.030360,0.003582,0.165139,0.003045,0.000016,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,pass
11,0.515574,0.455184,0.156194,0.051301,0.442076,0.096104,0.007573,0.210144,0.094470,0.015351,...,172.800005,22.988715,173.161091,2.824767,329.180176,124.838746,60.029864,64.434162,70.657097,pass
12,0.412250,0.398172,0.148229,0.041822,0.252396,0.117474,0.009469,0.343460,0.080182,0.013875,...,135.078351,15.920157,134.065232,2.087735,517.216598,113.665584,54.264158,57.692284,62.732253,pass
13,0.517866,0.549690,0.105470,0.040495,0.272474,0.074798,0.006633,0.056733,0.113308,0.020201,...,201.392644,26.283814,201.011122,3.284243,509.082228,157.653082,73.409737,76.804390,82.615014,pass
14,0.485999,0.247037,0.096620,0.053358,0.428161,0.038376,0.005600,0.136575,0.038717,0.007502,...,50.503352,6.430748,49.732750,0.840345,220.682872,50.534322,20.922391,19.703567,19.402701,pass
15,0.392743,0.622607,0.071517,0.023427,0.203070,0.031422,0.003402,0.079665,0.034616,0.007166,...,47.448743,6.080222,46.693283,0.794318,209.528019,48.123251,19.707851,18.361935,17.903778,pass
16,0.300881,0.207872,0.113923,0.040717,0.242654,0.078336,0.007777,0.186912,0.080641,0.014230,...,133.318328,15.875238,132.242174,2.078242,512.548364,113.948793,53.580279,56.319495,60.727192,pass
17,0.467645,0.584316,0.090733,0.033573,0.285454,0.046665,0.004810,0.094751,0.053623,0.010460,...,80.934301,9.993078,79.955293,1.307651,335.821085,75.734479,33.115126,32.795186,33.740364,pass
18,0.341247,0.274233,0.067019,0.033169,0.263258,0.037994,0.003418,0.040052,0.052886,0.009154,...,93.667176,13.191112,93.940721,1.591543,134.483808,68.456421,31.222835,32.232441,34.358806,pass
19,0.407221,0.497453,0.066859,0.033274,0.178248,0.055680,0.004979,0.216568,0.020457,0.003707,...,28.734664,4.129531,28.625721,0.504299,61.826559,24.515503,10.110805,9.536609,9.424385,pass

[[1.14673087 1.43752673 1.31461929 1.30106562 1.44765897 1.47346407
  1.53871872 1.60133324 1.75287675 1.86289286 1.79798025 1.84337189
  1.77947149 1.83964828 1.798632   1.85158573 1.82009253 1.83092814
  1.82469209 1.82250424 1.80631128 1.8196714  1.81632155 1.80847647
  1.80139442 1.82252339 1.80206034 1.8008042  1.82407245 1.80151284
  1.82471511 1.91028583 1.79774332 1.8225942  1.90459152 1.80689637
  1.90395396 1.799774   1.82145127 1.90258687 1.80342994 1.9020809
  1.80007294 1.90118234 1.80431118 1.90099931 1.79626311 1.90016005
  1.80016031 1.90529244 1.82986129 1.90359969 1.81652054 1.90246429
  1.82752022 1.90209674 1.81296499 1.90640312 1.84978316 1.90195982
  1.85016329 1.90125102 1.82813948 1.80805353 1.78776506 1.82615629
  1.78890841 1.83631832 1.82072692 1.7791573  1.81454441 1.82114935
  1.82533692 1.81531258 1.78693508 1.82059466 1.82307296 1.81530549
  1.81068789 1.82013737 1.82193245 1.81666225 1.79752476 1.82221885
  1.80213501 1.81083288 1.79584953 1.82158349 1.80154656 1.79495377
  1.82272269 1.79524531 1.81425507 1.8963254  1.7908766  1.81890076
  1.82603373 1.89498883 1.79914247 1.89572444 1.79299542 1.819385
  1.89447564 1.80013811 1.89539183 1.79324387 1.89471689 1.79920471
  1.89527502 1.79289142 1.8952895  1.79826983 1.89636172 1.82417759
  1.8960059  1.81164855 1.89694471 1.82380033 1.89717928 1.81058021
  1.8926933  1.84637273 1.89202908 1.84793485 1.87412717 1.8276777
  1.80668977 1.78756696 1.82571837 1.78909883 1.8353702  1.81794739
  1.78062374 1.81403465 1.82081734 1.82567196 1.81431184 1.78850403
  1.82037601 1.82342988 1.81485444 1.81120557 1.82005261 1.82244984
  1.81692998 1.79834994 1.82226351 1.80294216 1.81115769 1.7972393
  1.82167499 1.802926   1.79628484 1.822785   1.79656371 1.81432644
  1.89350592 1.7926816  1.8190962  1.89231479 1.80021944 1.89295715
  1.79437293 1.81962022 1.89176647 1.80119113 1.892635   1.79457638
  1.89208069 1.80041916 1.89261998 1.79428773 1.8926741  1.79959415
  1.89362638 1.8242266  1.89331725 1.81239797 1.89430129 1.82401739
  1.89455335 1.81153694 1.88995678 1.84569596 1.88942989 1.84734231
  1.87147417 1.67728385 1.83123912 1.80893833 1.79268019 1.78083192]]
BARINEL SCORES

,u 187,cx 189,u 190,cp 85,cp 148,cp 87,cp 144,cp 150,cp 146,cp 81,...,p 188,p 174,h 3,p 178,p 176,p 180,p 182,u 184,p 185,x 4
sum,0.55447,0.55405,0.543991,0.537137,0.537104,0.537045,0.537043,0.537008,0.536966,0.53696,...,0.528115,0.527911,0.527812,0.526919,0.525856,0.524342,0.524248,0.520884,0.516832,0.516818

custom SCORES

,cp 148,cp 150,cp 160,cp 155,cp 144,cp 146,cp 157,cp 138,cp 136,cp 142,...,cx 179,u 187,u 190,cx 189,x 4,u 184,cx 186,p 185,p 188,u 191
sum,0.792387,0.792365,0.792273,0.792204,0.79216,0.79216,0.791951,0.791903,0.791889,0.79187,...,0.763143,0.755142,0.739492,0.736142,0.73353,0.729411,0.72442,0.715646,0.699893,0.68708

DSTAR SCORES

,cx 18,cx 22,x 4,cx 26,cx 10,cx 14,cx 37,cx 31,cx 39,cx 20,...,p 174,p 178,p 163,p 182,p 176,p 170,p 185,p 180,cp 130,p 168
sum,4621.158421,3243.989262,3226.737043,3203.157962,2766.866796,2424.174026,2368.193526,2272.782632,2245.840499,2152.675402,...,0.004775,0.002349,0.002174,0.001242,0.000881,0.000676,0.000373,0.00035,0.000295,0.000169

ERROR GATE LOCATION:
95
Now evolving the following mutant:  AddGate_z_inGap_59_.qasm

100%|██████████| 10/10 [02:01<00:00, 12.17s/it]
100%|██████████| 10/10 [02:35<00:00, 15.53s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.446500,0.705041,0.122191,0.023980,0.202404,0.079748,0.005298,0.267297,0.041125,0.005328,...,74.922733,8.332437,74.768470,1.095788,258.469863,54.683778,29.438561,33.941763,39.010910,fail
1,0.497036,0.428101,0.116179,0.055222,0.496840,0.043537,0.005184,0.176670,0.033937,0.006374,...,41.718458,5.345926,41.054233,0.698390,184.223758,42.311507,17.327775,16.144402,15.741576,fail
2,0.487301,0.547929,0.126849,0.039573,0.296799,0.078419,0.007255,0.357798,0.014641,0.002379,...,15.521670,1.988992,15.274540,0.259841,68.541853,15.742319,6.446931,6.006648,5.856773,fail
3,0.482314,0.398625,0.160882,0.054122,0.460067,0.085569,0.007111,0.285607,0.044040,0.008442,...,55.671126,7.133862,54.784753,0.931966,245.837086,56.462519,23.123020,21.543870,21.006320,fail
4,0.387526,0.489788,0.137724,0.038115,0.268466,0.099694,0.007455,0.254385,0.081716,0.013211,...,149.236368,19.853890,149.548215,2.439572,284.291970,107.815280,51.843974,55.647685,61.022038,fail
5,0.472038,0.539075,0.117100,0.039394,0.421737,0.049618,0.003672,0.091072,0.044570,0.009020,...,62.841719,8.407440,62.117539,1.070451,225.915928,60.065952,24.655026,23.063464,22.587683,fail
6,0.449029,0.520618,0.100165,0.046359,0.324318,0.070611,0.006409,0.237439,0.035712,0.006780,...,54.377438,7.972252,54.294007,0.962528,94.090881,44.763628,18.491358,17.489569,17.335378,fail
7,0.437155,0.456953,0.168163,0.049614,0.374342,0.126463,0.008658,0.308975,0.094450,0.015337,...,172.800005,22.988715,173.161091,2.824767,329.180176,124.838746,60.029864,64.434162,70.657097,fail
8,0.474465,0.417048,0.093319,0.044616,0.348824,0.055407,0.004499,0.211530,0.013651,0.002043,...,13.119797,1.681209,12.910909,0.219633,57.935465,13.306301,5.449312,5.077160,4.950477,fail
9,0.279735,0.542789,0.121131,0.023584,0.253171,0.075633,0.003291,0.193068,0.048752,0.006489,...,90.695940,10.086635,90.509201,1.326481,312.884571,66.196152,35.636153,41.087397,47.223733,fail
10,0.454424,0.648831,0.125016,0.042700,0.193752,0.104520,0.009759,0.195870,0.125850,0.022933,...,219.831130,28.973141,219.287789,3.615495,558.558253,175.059328,80.151392,82.756324,88.130562,pass
11,0.318103,0.417755,0.073182,0.025627,0.317234,0.012987,0.001645,0.070241,0.007103,0.000881,...,5.573685,0.714228,5.484943,0.093307,24.612733,5.652918,2.315032,2.156931,2.103112,pass
12,0.370311,0.396346,0.094767,0.032092,0.334325,0.041301,0.003916,0.058297,0.053638,0.010364,...,91.888960,14.155946,92.280994,1.662091,59.504542,68.566587,28.457871,27.133368,27.125487,pass
13,0.486830,0.414489,0.132839,0.047808,0.341421,0.083027,0.008529,0.239214,0.073258,0.014442,...,119.006854,17.630913,118.967128,2.116060,179.253942,96.069975,39.721297,37.627577,37.357850,pass
14,0.356674,0.338351,0.128429,0.037931,0.290001,0.086823,0.005892,0.095885,0.102612,0.018185,...,178.210514,23.145910,177.747966,2.902058,471.563856,141.303143,65.544241,68.352802,73.337607,pass
15,0.340982,0.518562,0.087834,0.037513,0.392064,0.017093,0.003207,0.127282,0.004977,0.000022,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,pass
16,0.560116,0.617702,0.090304,0.038746,0.252060,0.071931,0.005734,0.196423,0.044749,0.007933,...,76.387739,11.610524,76.822661,1.362949,43.001153,54.693489,23.515751,23.165536,23.816409,pass
17,0.451939,0.463238,0.143415,0.038308,0.437854,0.063168,0.004978,0.233293,0.015498,0.002492,...,16.202199,2.076197,15.944234,0.271234,71.546988,16.432522,6.729589,6.270002,6.113556,pass
18,0.529691,0.653700,0.148132,0.044019,0.345102,0.095367,0.007396,0.145439,0.104274,0.018663,...,178.997922,23.283242,178.444318,2.922013,483.289455,143.540555,66.084162,68.504373,73.164798,pass
19,0.490501,0.597476,0.101291,0.033500,0.237514,0.065175,0.006159,0.219262,0.036863,0.007675,...,50.610115,6.485329,49.804321,0.847241,223.488260,51.329563,21.020928,19.585337,19.096654,pass

[[1.12627436 1.39723613 1.33071897 1.33199414 1.44138313 1.65376639
  1.47166055 1.50093257 2.0868493  2.0339565  2.21564504 1.99487467
  2.07992295 2.10361124 2.2363376  2.0811687  2.2811262  2.13262163
  2.32872144 2.15913817 2.22041273 2.15643828 2.25245668 2.17910082
  2.21138608 2.16259881 2.25575308 2.21501287 2.15957675 2.20342307
  2.1581145  2.49354759 2.1990884  2.16442029 2.4978452  2.20556994
  2.50490548 2.19869038 2.1676429  2.4984734  2.20286899 2.51234718
  2.19929151 2.51468818 2.20079088 2.50989268 2.19676502 2.5116193
  2.20626912 2.49456766 2.3155327  2.49347926 2.24307861 2.50107515
  2.32540858 2.50151904 2.24821974 2.45183397 2.36404414 2.45084552
  2.38019466 2.37412674 2.14812391 2.20586499 2.18528906 2.15381337
  2.26576726 2.39382507 2.16977476 2.29549076 2.35006877 2.16959534
  2.39698091 2.18699576 2.24443044 2.17114322 2.39060941 2.18680838
  2.34701547 2.172424   2.38939002 2.18338578 2.24767033 2.16620074
  2.27954483 2.19953766 2.2452122  2.16802053 2.27827586 2.23249883
  2.16444469 2.2288653  2.18815522 2.50323831 2.22989573 2.17579428
  2.50121861 2.23095225 2.50069443 2.23000044 2.15562553 2.17358193
  2.491782   2.21855739 2.5068769  2.2255698  2.50927442 2.22256868
  2.50274804 2.22084651 2.50392717 2.21939975 2.4922738  2.32846278
  2.49081652 2.25888085 2.49504536 2.33316697 2.4956515  2.2601576
  2.45994474 2.36785116 2.45593446 2.38187429 2.39298277 2.14816801
  2.20953595 2.19940582 2.15407321 2.27135239 2.39437084 2.17722331
  2.30229056 2.35391328 2.17162517 2.39672317 2.1922476  2.25155246
  2.17293658 2.39034423 2.19044115 2.34846536 2.17389814 2.38865008
  2.1854547  2.25439735 2.16681975 2.28389929 2.20158034 2.25116565
  2.16858884 2.28258283 2.23868505 2.16463348 2.23490607 2.18886825
  2.49548719 2.23585837 2.17626769 2.49326322 2.23572901 2.49299991
  2.23528327 2.17321073 2.48409239 2.22378916 2.49687873 2.23003468
  2.49910368 2.22752877 2.49406131 2.22576595 2.49519176 2.22416081
  2.48528116 2.3267176  2.4839485  2.26157244 2.48799737 2.33210014
  2.48867301 2.2623031  2.45461885 2.36419158 2.4510483  2.37720529
  2.38791767 1.5968988  2.12967739 2.20339998 2.26532979 2.31365263]]
BARINEL SCORES

,u 184,cx 186,cx 189,u 187,p 188,p 185,u 191,u 190,x 4,u 122,...,cp 138,cp 152,cp 155,cp 140,cp 157,cp 132,cp 142,cp 130,cp 134,cp 160
sum,0.601214,0.543847,0.528987,0.523196,0.522916,0.506977,0.503051,0.498987,0.493601,0.466014,...,0.41891,0.418792,0.418424,0.41827,0.418002,0.417815,0.417645,0.416125,0.416121,0.415667

custom SCORES

,u 184,cx 186,h 0,u 59,u 122,u 62,u 125,cx 54,cx 117,cx 113,...,u 190,cp 134,p 174,h 3,cp 130,p 178,p 176,u 191,p 182,p 180
sum,0.826809,0.768695,0.735215,0.733484,0.733447,0.722166,0.721392,0.719365,0.719337,0.718896,...,0.673288,0.671186,0.670983,0.670944,0.663109,0.659945,0.65051,0.644694,0.635468,0.630396

DSTAR SCORES

,cx 18,x 4,cx 22,cx 26,cx 10,cx 37,cx 14,cx 31,cx 39,cx 20,...,p 174,p 178,p 163,p 182,p 176,p 185,p 170,p 180,cp 130,p 168
sum,2296.617787,1999.818483,1609.718411,1587.189364,1346.541441,1183.25287,1177.920585,1128.144797,1122.706256,1079.816028,...,0.00218,0.001069,0.000992,0.000563,0.000399,0.000344,0.00031,0.000161,0.000133,0.000078

ERROR GATE LOCATION:
91
Now evolving the following mutant:  AddGate_cx_inGap_91_.qasm

100%|██████████| 10/10 [02:45<00:00, 16.53s/it]
100%|██████████| 10/10 [03:09<00:00, 18.97s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.389206,0.614007,0.107589,0.031593,0.432776,0.031746,0.001086,0.103340,0.004698,0.000045,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,fail
1,0.525092,0.617382,0.074957,0.041891,0.249522,0.046112,0.006656,0.172039,0.037467,0.007677,...,63.099777,8.086422,62.095963,1.056223,278.664458,64.000149,26.210160,24.419478,23.809809,fail
2,0.515142,0.535140,0.109965,0.046033,0.358131,0.061756,0.005875,0.109372,0.071422,0.012915,...,144.896029,18.269244,143.978503,2.335939,478.058998,122.537295,55.927077,57.499544,60.995118,fail
3,0.420380,0.575562,0.103663,0.034563,0.237583,0.068979,0.006182,0.012124,0.114177,0.021775,...,246.426311,33.346071,245.803145,4.129179,587.911700,199.043467,88.660657,89.548198,93.753929,fail
4,0.347703,0.562334,0.106768,0.021230,0.357297,0.029988,0.001102,0.003417,0.048645,0.006483,...,113.125294,12.581330,112.894836,1.654383,390.279690,82.568764,44.450170,51.249956,58.905483,fail
5,0.416993,0.591930,0.076836,0.024852,0.156971,0.056312,0.004047,0.043282,0.082788,0.014552,...,176.878783,20.847327,175.555654,2.733509,677.296609,148.840490,71.058837,75.548884,82.150998,fail
6,0.482783,0.516479,0.127821,0.038254,0.123039,0.126974,0.010277,0.276963,0.119112,0.021841,...,261.073797,34.409433,260.432329,4.293355,663.421712,207.907828,95.193913,98.288058,104.672712,fail
7,0.388712,0.586414,0.103997,0.033306,0.228563,0.066730,0.006722,0.234343,0.043669,0.008428,...,79.929433,9.911681,78.929388,1.296544,334.075446,75.503718,32.761429,32.225113,32.966523,fail
8,0.438927,0.573782,0.115155,0.034536,0.315716,0.066228,0.004610,0.171627,0.057088,0.008166,...,124.204541,14.096969,123.719372,1.851798,444.673927,95.414637,49.179198,55.164065,62.275117,fail
9,0.448927,0.628158,0.093979,0.036991,0.212086,0.077888,0.005882,0.221543,0.063269,0.009556,...,144.924116,18.073377,144.999978,2.273654,361.557507,105.113839,52.866112,58.474941,65.445923,fail
10,0.413215,0.404890,0.091284,0.037550,0.113824,0.093629,0.008752,0.164410,0.107769,0.019365,...,239.069395,31.312045,238.614877,3.908176,599.882918,187.559348,87.006004,90.766450,97.425040,pass
11,0.270068,0.347648,0.147448,0.040739,0.385323,0.082396,0.006422,0.263946,0.045772,0.009372,...,77.121949,9.883404,75.895065,1.290939,340.589893,78.222405,32.034640,29.846028,29.100877,pass
12,0.459405,0.445663,0.099182,0.046037,0.216312,0.086585,0.008042,0.311969,0.040577,0.006144,...,84.843120,11.464714,85.055289,1.400790,149.090725,61.236550,29.105683,30.986851,33.785652,pass
13,0.334403,0.239493,0.068342,0.029723,0.190358,0.046166,0.005290,0.177479,0.029599,0.005772,...,55.199523,7.847855,54.924231,0.964234,131.207227,47.980877,19.772554,18.622825,18.375282,pass
14,0.391352,0.489270,0.097320,0.039192,0.312701,0.044018,0.006235,0.154722,0.039103,0.008028,...,66.104528,8.471489,65.052913,1.106519,291.934194,67.047775,27.458263,25.582310,24.943609,pass
15,0.453042,0.480500,0.118873,0.037544,0.292048,0.074559,0.006135,0.135013,0.079335,0.013673,...,172.958372,22.153516,172.546705,2.787474,467.845879,135.658980,63.947460,67.503903,73.082914,pass
16,0.389078,0.374268,0.153055,0.057793,0.569934,0.061924,0.006624,0.209352,0.052789,0.009342,...,106.078656,16.562575,106.703388,1.930038,36.703134,76.883222,31.957259,30.545410,30.616677,pass
17,0.343221,0.386363,0.060158,0.025500,0.163462,0.046148,0.004516,0.015186,0.075412,0.014666,...,163.323092,22.774395,163.103991,2.786809,333.584078,130.568649,57.132684,56.890287,58.904464,pass
18,0.347236,0.323217,0.125935,0.035824,0.351999,0.063123,0.004525,0.101910,0.077355,0.013248,...,160.798894,18.952116,159.596049,2.485008,615.724190,135.309537,64.598943,68.680803,74.682726,pass
19,0.323053,0.164982,0.128120,0.040000,0.336321,0.076765,0.006724,0.235419,0.051182,0.008312,...,111.288947,14.420957,111.253662,1.797683,264.157096,83.869685,40.129867,42.868356,46.828318,pass

[[1.20052141 1.08280902 1.25224795 1.34108236 1.61986274 2.00682034
  1.95988221 2.05454346 1.85435506 1.95993624 1.9117864  1.95299432
  1.86921407 1.91092513 1.90794156 1.93196123 1.87463086 1.89246667
  1.89403342 1.87364898 1.8411375  1.87229623 1.86208554 1.85349069
  1.82915371 1.87194245 1.83131652 1.82730243 1.87464496 1.82840969
  1.87576232 2.07918399 1.82052967 1.87137358 2.06574316 1.83968664
  2.06456422 1.82472955 1.86902596 2.06108851 1.83235629 2.06040736
  1.82534365 2.05838374 1.83412143 2.05774791 1.81742741 1.81403439
  2.05642726 1.82410511 2.0668615  1.89272598 2.06296768 1.86091406
  2.06060944 1.88739312 2.05977691 1.85355979 2.06806758 1.9384304
  2.05715757 1.93910157 2.04092125 1.88233691 1.84043211 1.79934294
  1.87825659 1.80346477 1.90844447 1.86632019 1.78501209 1.85997711
  1.86827265 1.88472469 1.85603974 1.79902766 1.86711476 1.87936164
  1.85625323 1.8518871  1.86620082 1.87697816 1.85923792 1.82140908
  1.87045367 1.83180112 1.84751029 1.81784608 1.86915314 1.83072844
  1.8156427  1.87143372 1.81613313 1.85425048 2.04640533 1.80710055
  1.8637124  2.04328075 1.82419321 2.04500287 1.81142851 1.86467911
  2.0417583  1.82591163 2.04443006 1.8118555  2.042961   1.82407182
  2.04401742 1.81099328 2.04410606 1.82209127 2.04617039 1.87977582
  2.04528592 1.85108333 2.04760281 1.87912517 2.04817692 1.84891464
  2.03637319 1.92902059 2.03473268 1.9328848  1.99129283 1.88147143
  1.83922581 1.79954337 1.87749382 1.80484879 1.90593394 1.86177479
  1.78857672 1.85911324 1.86767436 1.88517446 1.85462278 1.80305378
  1.8667834  1.88017893 1.85570949 1.85300945 1.86613106 1.8780422
  1.85991442 1.82336086 1.87058056 1.83375918 1.84832289 1.82097044
  1.86939141 1.83368912 1.8186234  1.87161177 1.81908309 1.85455502
  2.03964151 1.81112548 1.86418724 2.03679621 1.82664169 2.03827879
  1.81458396 1.86519515 2.0351944  1.82828877 2.03767425 1.81484425
  2.03646677 1.82680116 2.03753538 1.81412398 2.03770134 1.82499762
  2.03955219 1.87984118 2.03878557 1.85278614 2.04121694 1.87956676
  2.04182721 1.85100358 2.0299397  1.92737248 2.02859668 1.93140432
  1.98540474 1.60651385 1.88847422 1.84374433 1.81203455 1.78935173]]
BARINEL SCORES

,u 190,x 4,u 121,h 0,u 59,cx 116,u 124,u 62,cx 54,cx 64,...,cp 157,cp 141,cp 133,cp 160,cx 186,cx 189,u 187,p 188,p 185,u 184
sum,0.613397,0.566152,0.545602,0.545319,0.545137,0.541621,0.541449,0.541329,0.541093,0.540261,...,0.504109,0.503905,0.502581,0.501926,0.483716,0.483655,0.476749,0.468184,0.453209,0.43242

custom SCORES

,x 4,h 0,u 121,u 59,u 62,u 124,cx 116,cx 54,h 1,cx 96,...,cx 183,p 182,p 180,cx 186,u 191,p 185,u 187,u 184,cx 189,p 188
sum,0.793535,0.789261,0.789079,0.788892,0.785584,0.78557,0.785218,0.784998,0.784443,0.783615,...,0.757406,0.756926,0.75261,0.726399,0.702227,0.675268,0.669816,0.654527,0.635069,0.625152

DSTAR SCORES

,cx 18,x 4,cx 22,cx 26,cx 10,cx 37,cx 14,cx 31,cx 39,cx 20,...,p 174,p 178,p 163,p 182,p 176,p 170,p 180,cp 129,p 185,p 168
sum,6076.785658,5484.631234,4259.45069,4200.346839,3551.00135,3132.503936,3106.595459,2985.288536,2971.897797,2861.286947,...,0.004908,0.002389,0.002259,0.001229,0.000887,0.000702,0.000342,0.000294,0.000273,0.000177

ERROR GATE LOCATION:
145
Now evolving the following mutant:  AddGate_y_inGap_124_.qasm

100%|██████████| 10/10 [02:16<00:00, 13.69s/it]
100%|██████████| 10/10 [02:33<00:00, 15.36s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,y 184,u 183,cx 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.374701,0.399518,0.117620,0.050892,0.280055,0.083139,0.010208,0.271055,0.348015,0.047938,...,65.236129,8.359550,64.197466,1.092089,288.075005,66.163494,27.095848,25.245380,24.615471,fail
1,0.584705,0.570513,0.099797,0.045804,0.399152,0.047477,0.004298,0.100681,0.132508,0.048727,...,86.161143,9.582303,85.983741,1.260157,297.240343,62.886344,33.854346,39.033028,44.862546,fail
2,0.523812,0.537483,0.116433,0.041381,0.393931,0.065314,0.004879,0.202933,0.254934,0.017784,...,25.112192,3.946206,25.279749,0.458263,4.984142,17.936312,7.461014,7.140797,7.167284,fail
3,0.296290,0.487294,0.118271,0.027556,0.298667,0.066786,0.003365,0.118767,0.145483,0.053101,...,96.465080,12.088297,96.525012,1.518143,236.508450,69.944275,35.065786,38.706373,43.260777,fail
4,0.303386,0.510970,0.076518,0.017422,0.271004,0.027722,0.001401,0.099787,0.122430,0.004342,...,4.943860,0.549825,4.933681,0.072307,17.055423,3.608370,1.942536,2.239685,2.574178,fail
5,0.533113,0.452450,0.153025,0.064093,0.401650,0.096892,0.011546,0.217193,0.279466,0.093368,...,148.522208,21.545376,148.115609,2.617042,290.353233,124.636648,51.441162,48.581441,48.075573,fail
6,0.391226,0.460921,0.136584,0.045074,0.445086,0.075250,0.004732,0.149777,0.189654,0.051726,...,91.612420,10.955105,91.569517,1.400352,261.782349,66.604339,34.397188,38.687572,43.774322,fail
7,0.452073,0.485600,0.120535,0.040144,0.399677,0.054525,0.004186,0.106976,0.132620,0.040606,...,55.212814,7.330919,54.533021,0.937595,206.614829,53.351908,21.889731,20.461303,20.022647,fail
8,0.396093,0.512745,0.121838,0.034804,0.264034,0.085421,0.005270,0.148580,0.182923,0.073338,...,123.332408,14.535795,122.407386,1.906193,472.241242,103.781621,49.545536,52.675563,57.277275,fail
9,0.527857,0.488186,0.093561,0.041199,0.266663,0.068622,0.006060,0.108574,0.139933,0.074509,...,136.314848,18.571924,136.682782,2.262821,228.736664,98.331516,46.443349,49.224413,53.499626,fail
10,0.393465,0.331134,0.099321,0.040788,0.337621,0.047214,0.005037,0.023480,0.030554,0.078717,...,123.863904,16.432441,123.057418,2.069400,373.101336,107.445621,46.697671,46.116263,47.379731,pass
11,0.600000,0.738329,0.104167,0.053697,0.366341,0.068800,0.006847,0.258383,0.331906,0.006152,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,pass
12,0.458828,0.560800,0.067572,0.039696,0.220478,0.053456,0.006808,0.160061,0.208906,0.034024,...,57.567603,9.046347,57.951712,1.050530,11.425730,41.117496,17.103751,16.369680,16.430400,pass
13,0.326486,0.217377,0.136095,0.048230,0.369788,0.077888,0.007882,0.100738,0.129965,0.096846,...,161.279385,21.840344,160.783819,2.708085,394.790745,131.766389,58.287745,58.521925,60.975118,pass
14,0.328172,0.364937,0.109329,0.036124,0.303416,0.052467,0.006079,0.124839,0.160158,0.044772,...,62.473917,8.193120,61.625336,1.055600,248.605600,61.422274,25.183944,23.512798,22.978820,pass
15,0.406632,0.611385,0.091039,0.032356,0.239962,0.048071,0.006771,0.153302,0.201617,0.029599,...,49.863403,7.835686,50.196108,0.909939,9.896639,35.614793,14.814777,14.178946,14.231540,pass
16,0.631465,0.582509,0.118751,0.051906,0.316469,0.077228,0.008879,0.221416,0.285875,0.044308,...,58.601185,7.509328,57.668161,0.981016,258.775880,59.434231,24.340022,22.677758,22.111916,pass
17,0.475124,0.460171,0.066311,0.038610,0.209678,0.063543,0.005881,0.186897,0.236873,0.030022,...,48.348285,7.291114,48.432101,0.866352,54.166758,37.702781,15.614254,14.832727,14.770530,pass
18,0.361805,0.639364,0.107209,0.021860,0.279011,0.052579,0.003818,0.001017,0.001220,0.087597,...,160.741709,21.096057,160.746132,2.617520,361.684063,120.923686,57.377851,60.934506,66.286973,pass
19,0.336604,0.270452,0.069959,0.036038,0.256714,0.037599,0.004499,0.002919,0.003861,0.069598,...,105.198767,14.248042,104.121841,1.801001,352.920682,98.754781,40.564732,37.993967,37.261670,pass

[[1.33395126 1.1629645  1.32583147 1.56948216 1.30145179 1.4436776
  2.06375745 1.77820057 1.805089   1.84727067 2.16927854 1.78680202
  2.20307733 1.80814706 1.96215798 1.76112329 2.04284282 1.69108877
  1.87460484 1.70397002 1.79441818 1.63720849 1.7904006  1.67848226
  1.71207727 1.61972614 1.78785049 1.61227006 1.62233153 1.79891886
  1.62228301 1.80372404 2.11002713 1.63285563 1.78456457 2.06884196
  1.64905824 2.05942021 1.62747046 1.77439888 2.05527504 1.62805372
  2.04131103 1.62665945 2.03360096 1.63548986 2.03597765 1.63710065
  2.02924612 1.62543683 2.07596096 1.71612798 2.06573306 1.68360237
  2.05242733 1.69297375 2.04961073 1.65614236 2.11596062 1.81025461
  2.08749115 1.80035877 2.14152142 1.83331822 1.65628166 1.66152208
  1.81586353 1.64580635 1.69845517 1.76776367 1.66688414 1.60173152
  1.77069017 1.64092285 1.71876719 1.65438818 1.76583841 1.63494688
  1.71886452 1.59656183 1.76183478 1.63321946 1.73045832 1.62589354
  1.78035946 1.60870537 1.67952092 1.63070594 1.77476669 1.61045815
  1.63507476 1.78503483 1.63487654 1.71088989 2.01030073 1.64626073
  1.75107874 2.00304633 1.62425112 2.00829172 1.64064373 1.75597718
  2.00689433 1.62357058 2.00136657 1.64068509 1.99508539 1.62540566
  2.00375956 1.64236082 2.00295187 1.62837435 2.01893632 1.66850119
  2.01770957 1.63923255 2.02065231 1.66238791 2.02173254 1.63118596
  2.01954144 1.78482155 2.01823959 1.78435987 1.94856967 1.83023823
  1.64444037 1.65981987 1.81277458 1.64442221 1.69177042 1.74368477
  1.66193314 1.60379141 1.76693786 1.64103274 1.70811637 1.64911723
  1.7630161  1.6350702  1.71309047 1.59792776 1.76014169 1.63316892
  1.73063504 1.62265522 1.78017837 1.60589032 1.68009518 1.62609734
  1.77493375 1.60613999 1.6305836  1.78530095 1.63044175 1.71081276
  1.99767067 1.64055015 1.7520051  1.99152969 1.6206548  1.99596186
  1.6361711  1.75781558 1.99494351 1.61996596 1.99086908 1.63646012
  1.98551382 1.62141708 1.99292831 1.63789529 1.99241882 1.62412631
  2.00628093 1.67016798 2.00526607 1.64211512 2.00864479 1.66464353
  2.00978707 1.63585988 2.00560267 1.78316571 2.00486819 1.78403542
  1.93497203 2.05002148 1.86792978 1.66402747 1.63590965 1.65958695]]
BARINEL SCORES

,y 184,u 183,cx 189,u 187,cx 186,h 0,u 121,u 59,x 4,u 62,...,cp 156,cp 141,cp 131,cp 159,cp 133,p 175,cp 129,p 185,p 181,p 179
sum,0.552817,0.547888,0.543416,0.541178,0.536921,0.532972,0.532274,0.532042,0.527263,0.524326,...,0.482582,0.482,0.480317,0.479512,0.478289,0.476428,0.474993,0.472323,0.466941,0.463709

custom SCORES

,y 184,x 4,u 183,h 0,u 121,u 59,u 62,cx 116,u 124,cx 54,...,p 167,cx 155,cx 146,cx 150,cx 178,u 187,p 185,p 188,u 191,u 190
sum,0.798572,0.797489,0.795135,0.754101,0.754084,0.753097,0.739879,0.739516,0.739507,0.73847,...,0.718559,0.718514,0.71819,0.718158,0.717457,0.717257,0.716013,0.703999,0.671699,0.653984

DSTAR SCORES

,cx 18,x 4,cx 22,cx 26,cx 10,cx 37,cx 14,cx 31,cx 39,cx 20,...,p 173,p 177,p 162,p 181,p 175,p 169,p 185,p 179,cp 129,p 167
sum,3308.216446,2556.91332,2319.665208,2284.90001,1949.94342,1709.142863,1705.006007,1628.347209,1623.096909,1557.322549,...,0.002825,0.001388,0.001284,0.000737,0.00052,0.0004,0.000311,0.000208,0.000175,0.0001

ERROR GATE LOCATION:
184
Now evolving the following mutant:  AddGate_cx_inGap_72_.qasm

100%|██████████| 10/10 [02:57<00:00, 17.77s/it]
100%|██████████| 10/10 [01:58<00:00, 11.89s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.420882,0.440644,0.126919,0.057835,0.515998,0.054902,0.005144,0.111431,0.072133,0.010975,...,151.815353,18.192955,152.232779,2.312669,434.404852,117.687763,56.787340,60.263070,64.954530,fail
1,0.500847,0.521095,0.107457,0.046068,0.415183,0.048493,0.005002,0.159013,0.041928,0.007349,...,80.999040,11.927329,81.550974,1.393185,63.960455,57.483330,25.274266,25.305853,26.356187,fail
2,0.520711,0.429887,0.131528,0.043965,0.409638,0.069786,0.005037,0.266411,0.019569,0.002751,...,30.107002,4.433338,30.312153,0.517841,23.773831,21.366311,9.394338,9.406079,9.796484,fail
3,0.575656,0.509318,0.147204,0.050311,0.464245,0.074931,0.005898,0.197803,0.056601,0.011063,...,100.033913,13.567081,100.265458,1.662918,263.984449,90.492539,38.075596,35.312231,33.297469,fail
4,0.397582,0.424254,0.116539,0.040147,0.302784,0.075872,0.006415,0.262599,0.038059,0.007629,...,64.959510,8.477571,64.995051,1.062084,219.466285,63.503954,26.475912,24.067836,22.015967,fail
5,0.554209,0.506510,0.160965,0.057808,0.417755,0.109453,0.010273,0.315015,0.094821,0.015340,...,212.290216,27.713835,213.358003,3.383367,384.222829,150.281889,72.024741,77.007636,84.236626,fail
6,0.493831,0.662441,0.118603,0.038236,0.269748,0.074623,0.007629,0.178672,0.077965,0.012636,...,175.370178,22.894038,176.252263,2.794955,317.401468,124.145908,59.498699,63.615003,69.586778,fail
7,0.460258,0.483728,0.137467,0.043854,0.372995,0.078797,0.006348,0.089714,0.107698,0.019750,...,227.653850,30.029888,228.535825,3.679173,496.670189,179.030740,81.244689,82.150695,85.165626,fail
8,0.565634,0.593058,0.091562,0.041230,0.206117,0.071776,0.007254,0.096093,0.103321,0.018374,...,221.232261,28.260540,221.968393,3.507775,546.840351,175.235645,80.799228,82.650004,86.414431,fail
9,0.554626,0.524637,0.131502,0.058405,0.328388,0.103575,0.010232,0.231487,0.113931,0.020517,...,243.482427,31.733143,244.405235,3.903998,547.494370,190.197409,87.207087,88.986334,92.998573,fail
10,0.313064,0.391224,0.129660,0.043683,0.422415,0.067014,0.005161,0.150654,0.062199,0.011733,...,126.389403,18.448073,127.187515,2.165814,125.743888,92.430442,40.399718,40.056035,41.230533,pass
11,0.523216,0.468820,0.159648,0.056727,0.370254,0.114864,0.008506,0.245125,0.107331,0.018202,...,224.382784,27.375553,224.899333,3.469019,665.623610,183.168919,85.459715,87.863126,91.948299,pass
12,0.279425,0.366336,0.105824,0.030952,0.240612,0.062946,0.006518,0.154623,0.060005,0.010894,...,129.075751,18.000245,129.813700,2.147201,175.312890,93.548293,42.436438,43.416218,45.860348,pass
13,0.475685,0.514767,0.079933,0.036087,0.209788,0.066415,0.005447,0.165208,0.054589,0.011065,...,105.468445,14.650657,105.846654,1.770438,223.215444,89.599398,38.099944,36.021296,34.883719,pass
14,0.269765,0.464651,0.087900,0.026955,0.265540,0.048224,0.003194,0.196983,0.003423,0.000034,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,pass
15,0.607836,0.614509,0.097558,0.036648,0.381148,0.037068,0.003681,0.193578,0.004153,0.000081,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,pass
16,0.410943,0.625298,0.039984,0.019309,0.182414,0.012554,0.002038,0.082843,0.001540,0.000042,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,pass
17,0.350913,0.313908,0.097038,0.043034,0.295449,0.063691,0.006123,0.250271,0.034996,0.004899,...,74.379966,9.234176,74.703258,1.149461,163.683831,52.603693,26.011336,28.414732,31.548203,pass
18,0.498835,0.372508,0.131224,0.051042,0.359249,0.078442,0.007712,0.231493,0.071780,0.011691,...,149.894145,18.169860,150.263531,2.305078,438.946555,120.127608,56.719462,58.987055,62.405983,pass
19,0.308541,0.405445,0.119018,0.027446,0.295621,0.060329,0.003570,0.256174,0.006835,0.000510,...,5.575442,0.820999,5.613433,0.095898,4.402618,3.956775,1.739714,1.741889,1.814187,pass

[[1.14121475 1.30003309 1.26769303 1.22223048 1.39351613 1.43599534
  1.48385267 1.65081587 1.56923996 1.62338774 1.59826695 1.59821385
  1.60513638 1.62077797 1.60246297 1.62365369 1.61809997 1.62364289
  1.61373863 1.62410148 1.62360405 1.62297521 1.62117546 1.62345697
  1.62545601 1.6242655  1.62342804 1.6255322  1.62443185 1.62595569
  1.62435204 1.59771615 1.62673101 1.62442854 1.59832377 1.62501633
  1.59810069 1.62640709 1.62451587 1.59853559 1.62568896 1.59801589
  1.62636697 1.59804893 1.62564588 1.59827955 1.62706302 1.59830205
  1.6260419  1.59837171 1.61656057 1.59862153 1.62184885 1.5984513
  1.61647995 1.59849226 1.62215486 1.60003638 1.6115523  1.60066126
  1.61078487 1.60401885 1.62438852 1.62484064 1.6289596  1.62443385
  1.62504254 1.61214923 1.62454026 1.62517856 1.61728724 1.62448376
  1.61358856 1.62458659 1.62634055 1.62449835 1.6142036  1.62459621
  1.58854772 1.6147573  1.62403088 1.61289667 1.62276477 1.62009369
  1.62408955 1.61787732 1.62304597 1.62044127 1.6240381  1.6181541
  1.6210451  1.62424946 1.62071548 1.62401335 1.60620716 1.6232353
  1.62385852 1.60650326 1.62123557 1.60642193 1.62284389 1.62417985
  1.60704016 1.62158953 1.60610243 1.62299333 1.60622232 1.62138173
  1.60652136 1.62312693 1.60656739 1.62134482 1.60695945 1.61635979
  1.60702224 1.61991609 1.60682817 1.6167465  1.60682672 1.61960139
  1.6084269  1.61371499 1.60854432 1.61378266 1.61179148 1.62501762
  1.62470332 1.62520608 1.62489653 1.62107382 1.61401026 1.62462551
  1.61806027 1.61630176 1.62397163 1.6142079  1.62336818 1.62156007
  1.62392917 1.6145804  1.62342682 1.61659679 1.62390102 1.61472897
  1.62286081 1.61968868 1.62412208 1.61784412 1.62324495 1.61998492
  1.624083   1.61810392 1.6205067  1.62429544 1.62025853 1.62423701
  1.60709154 1.6219174  1.62391448 1.60724806 1.6208767  1.60720538
  1.62175478 1.62426455 1.60769822 1.62120793 1.60696476 1.62203639
  1.60695847 1.62106849 1.60720281 1.62219448 1.60716494 1.62104805
  1.60748741 1.61706862 1.60754495 1.6197581  1.60732492 1.61715155
  1.6072864  1.61951933 1.6088061  1.61466518 1.60894327 1.6144335
  1.61202556 1.65996969 1.62641751 1.62462794 1.62157529 1.61786544]]
BARINEL SCORES

,h 0,u 59,u 122,cx 113,cx 119,cx 115,cx 48,cx 52,cx 121,cx 56,...,cx 181,cx 183,p 185,p 188,u 191,cx 186,u 187,cx 189,u 190,u 184
sum,0.649874,0.649857,0.649773,0.649707,0.649681,0.649677,0.64957,0.649567,0.649565,0.649564,...,0.641058,0.640869,0.571309,0.562358,0.555382,0.554836,0.550582,0.547887,0.528968,0.49756

custom SCORES

,x 4,u 122,cx 117,u 125,cx 127,cx 145,cx 159,u 59,h 0,cx 143,...,cx 181,cx 183,p 185,cx 186,u 187,p 188,cx 189,u 191,u 184,u 190
sum,0.915961,0.913772,0.913358,0.913287,0.913261,0.912871,0.912807,0.912734,0.912726,0.912709,...,0.897203,0.892289,0.783243,0.754021,0.742393,0.73419,0.721525,0.713835,0.702905,0.700887

DSTAR SCORES

,cx 18,cx 22,cx 26,x 4,cx 10,cx 14,cx 37,cx 31,cx 39,cx 20,...,p 174,p 178,p 163,p 182,p 176,p 170,p 185,p 180,cp 130,p 168
sum,9812.181033,6908.389596,6805.005275,6020.297463,5992.916945,5258.15325,4985.852871,4835.53757,4739.615467,4574.93615,...,0.005919,0.002938,0.002666,0.001586,0.001108,0.000827,0.000477,0.000452,0.000396,0.000204

ERROR GATE LOCATION:
113
Now evolving the following mutant:  AddGate_h_inGap_70_.qasm

100%|██████████| 10/10 [03:20<00:00, 20.03s/it]
100%|██████████| 10/10 [02:54<00:00, 17.42s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.350414,0.384595,0.133187,0.043550,0.283031,0.095596,0.009310,0.375328,0.039570,0.008134,...,32.696212,4.087781,31.336241,0.606542,137.419961,31.834872,12.978906,12.172136,11.928443,fail
1,0.503550,0.554236,0.109962,0.045899,0.384231,0.065834,0.004315,0.190715,0.035499,0.004560,...,35.325249,4.077786,34.367341,0.593708,99.701623,24.865381,12.756805,14.457523,16.430672,fail
2,0.374048,0.493523,0.144560,0.037883,0.295582,0.100577,0.007480,0.236431,0.078727,0.013291,...,81.952447,9.345413,79.220101,1.389422,295.084548,65.237506,31.304816,33.808796,37.157400,fail
3,0.440386,0.563675,0.083223,0.042249,0.261293,0.062341,0.006150,0.084791,0.082743,0.014669,...,86.811093,11.769805,84.756535,1.635415,151.305381,63.926248,28.683464,29.534047,31.384111,fail
4,0.595971,0.369816,0.136596,0.067780,0.490198,0.080146,0.008615,0.277977,0.051880,0.009463,...,42.797673,5.196765,41.133159,0.771564,171.439104,39.182109,16.779063,16.496712,16.854527,fail
5,0.478699,0.572746,0.103273,0.047487,0.262871,0.073742,0.008332,0.192649,0.078552,0.015782,...,74.338385,10.516616,72.281263,1.462573,149.907006,61.327995,25.061314,23.694353,23.443952,fail
6,0.727209,0.493428,0.131811,0.071790,0.290968,0.129708,0.012909,0.413203,0.085950,0.017021,...,79.546561,11.213141,77.309652,1.562365,165.948271,66.013528,26.968548,25.485100,25.202581,fail
7,0.537648,0.372867,0.181872,0.064579,0.476795,0.120762,0.009740,0.265180,0.109714,0.019948,...,109.306782,14.440428,106.297544,2.038164,252.831702,85.516888,37.812907,38.396408,40.337497,fail
8,0.568679,0.489866,0.161285,0.054848,0.329061,0.129493,0.010347,0.267013,0.127260,0.022974,...,132.102537,17.041142,128.438319,2.419713,322.526764,102.011286,46.190654,47.823259,50.998539,fail
9,0.485595,0.579181,0.082362,0.040893,0.231122,0.059291,0.007949,0.185585,0.054352,0.010798,...,54.083827,7.954350,52.855636,1.084215,67.372690,41.691268,17.093187,16.254617,16.182152,fail
10,0.536230,0.389517,0.117708,0.058845,0.425789,0.073040,0.008312,0.287007,0.045324,0.008076,...,44.263347,6.846068,43.555763,0.909673,8.921417,30.876084,12.725823,12.212398,12.274716,pass
11,0.533220,0.552533,0.131302,0.042150,0.299109,0.100950,0.007236,0.239695,0.084399,0.013907,...,93.869967,12.223642,91.718249,1.710117,172.231417,65.850499,31.294519,33.700540,37.017798,pass
12,0.627548,0.541736,0.135202,0.051627,0.476875,0.062621,0.005044,0.004313,0.109017,0.019195,...,110.873996,13.919256,107.623059,1.997493,304.157557,86.733580,39.696403,41.424535,44.427580,pass
13,0.228000,0.301013,0.093927,0.027865,0.263052,0.059966,0.003031,0.138251,0.040261,0.005274,...,44.504073,4.824435,43.208482,0.718110,146.511899,31.376940,16.658717,19.277867,22.198003,pass
14,0.398043,0.453498,0.102004,0.045633,0.299600,0.065863,0.006279,0.079941,0.092472,0.017767,...,90.985608,12.454333,88.509731,1.742537,192.516546,72.599814,30.954944,30.460209,31.199154,pass
15,0.496647,0.473105,0.089793,0.041653,0.339229,0.051244,0.004719,0.111853,0.049147,0.009548,...,46.571233,6.754722,45.429771,0.927317,71.040495,36.814652,15.074975,14.304162,14.207483,pass
16,0.347336,0.534640,0.099005,0.025461,0.335122,0.035646,0.003272,0.042388,0.044332,0.008431,...,46.476514,7.188371,45.733552,0.955157,9.367488,32.419888,13.362114,12.823018,12.888452,pass
17,0.341743,0.560884,0.116397,0.035604,0.258094,0.084742,0.006436,0.197775,0.066593,0.011213,...,69.985442,8.378573,67.874246,1.219236,212.575588,53.922764,25.644986,27.547496,30.172780,pass
18,0.500628,0.377908,0.069834,0.042036,0.262655,0.042885,0.005179,0.213355,0.009876,0.001070,...,4.175096,0.523622,4.000206,0.077690,17.637440,4.091590,1.659554,1.548300,1.509979,pass
19,0.361005,0.210119,0.172859,0.045267,0.343510,0.122217,0.008421,0.251930,0.110261,0.019435,...,117.005244,15.376708,114.048655,2.160148,242.246687,87.017263,39.727836,41.448693,44.474512,pass

[[1.43654726 1.18832326 1.43417203 1.38869368 1.48313366 1.41372844
  1.51610158 1.66020286 1.7099214  1.68132605 1.75153478 1.65930156
  1.71623058 1.72972902 1.76087468 1.71265595 1.81374955 1.75089249
  1.8162237  1.7716847  1.81506046 1.77007787 1.81252353 1.78786334
  1.81965625 1.77425004 1.83503268 1.82260545 1.77174937 1.81754413
  1.77063452 1.76861577 1.82133588 1.77556875 1.77724822 1.8106791
  1.78021758 1.81827678 1.77817533 1.77995766 1.81465567 1.78500052
  1.81809429 1.78689585 1.81269557 1.78563737 1.82261179 1.78722835
  1.82046803 1.77533446 1.81654554 1.77710823 1.8102729  1.78095038
  1.82325789 1.78157693 1.81700869 1.76067767 1.80565154 1.76587005
  1.81055734 1.74323285 1.76321026 1.80924149 1.83084382 1.76759881
  1.8583338  1.8345671  1.77990735 1.88454596 1.85068904 1.7792912
  1.85160247 1.79287407 1.8534697  1.78053414 1.85265713 1.7928206
  1.85531004 1.78156231 1.80267281 1.86558734 1.80846425 1.83513533
  1.77178201 1.84657892 1.78389562 1.83781863 1.77287839 1.84548629
  1.84206121 1.77095504 1.82494999 1.76813927 1.7816639  1.84319777
  1.77911386 1.79112201 1.8275678  1.78579418 1.83905935 1.78139065
  1.79532096 1.8151325  1.77386281 1.84906816 1.80107899 1.82010739
  1.78485774 1.840942   1.79785836 1.82251451 1.78476349 1.83018007
  1.78767827 1.82447981 1.78565399 1.83188464 1.78782724 1.82499296
  1.78312184 1.82031036 1.78103786 1.82116496 1.7811656  1.76610125
  1.81926997 1.84785036 1.76829776 1.85130524 1.84094446 1.78439943
  1.87783436 1.85373541 1.78083115 1.85524693 1.79492746 1.85611604
  1.78152291 1.85205227 1.7942329  1.85587657 1.78227532 1.85516483
  1.79074071 1.8400409  1.77665525 1.84421822 1.80210531 1.84085763
  1.77799432 1.84375515 1.83759525 1.77533977 1.83592732 1.79344621
  1.79073571 1.84176187 1.78402157 1.79167721 1.83104007 1.79060725
  1.83894045 1.78244675 1.78949245 1.82503869 1.79192817 1.83782655
  1.79430335 1.82743845 1.79133301 1.83602235 1.79187739 1.82762476
  1.78729799 1.82878504 1.78731256 1.82275403 1.78723881 1.83082564
  1.78719071 1.82409839 1.78226819 1.81220366 1.78174063 1.81411133
  1.78396485 1.77844044 1.75395537 1.80693638 1.85273178 1.88939547]]
BARINEL SCORES

,u 184,p 185,x 4,cx 186,p 188,p 180,p 182,p 176,p 178,cx 179,...,cp 19,cp 25,cp 146,cp 81,cp 23,cp 150,cp 144,cp 148,cp 85,u 187
sum,0.613721,0.595121,0.568374,0.56752,0.554023,0.546675,0.545345,0.541694,0.539341,0.538962,...,0.516662,0.516617,0.516327,0.516298,0.516293,0.51626,0.516132,0.516019,0.51585,0.50016

custom SCORES

,u 184,x 4,p 185,p 182,p 176,p 180,p 178,h 3,p 174,cx 127,...,cp 155,cp 146,cp 144,cp 150,cp 148,p 188,u 191,cx 189,u 187,u 190
sum,0.868446,0.821079,0.820687,0.774571,0.773628,0.77345,0.77257,0.772295,0.771834,0.771718,...,0.747011,0.74682,0.746743,0.746642,0.746537,0.746365,0.729409,0.718988,0.685611,0.682054

DSTAR SCORES

,cx 18,x 4,cx 22,cx 26,cx 10,cx 14,cx 37,cx 31,cx 39,cx 20,...,p 166,p 178,p 163,p 182,p 176,p 170,p 185,p 180,cp 130,p 168
sum,2867.441156,2370.891824,2009.918701,2007.154751,1700.04375,1493.122669,1473.600273,1408.234273,1393.151136,1380.610412,...,0.006284,0.003215,0.002785,0.001846,0.001245,0.000866,0.000721,0.000528,0.000423,0.000209

ERROR GATE LOCATION:
111
Now evolving the following mutant:  AddGate_x_inGap_32_.qasm

100%|██████████| 10/10 [03:11<00:00, 19.18s/it]
100%|██████████| 10/10 [02:45<00:00, 16.58s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.437495,0.489061,0.103953,0.034062,0.230804,0.084569,0.005541,0.157394,0.075931,0.014098,...,131.554024,17.794893,131.327489,2.199093,300.446734,104.404641,46.972962,47.850557,50.441390,fail
1,0.440938,0.513245,0.106019,0.038740,0.125672,0.101732,0.010442,0.267404,0.097957,0.018089,...,173.790924,23.675792,173.677592,2.911329,365.517833,135.251269,61.183578,62.632755,66.288207,fail
2,0.600760,0.579604,0.120530,0.053636,0.313301,0.074535,0.009152,0.223416,0.072638,0.012904,...,112.021576,13.505525,110.933429,1.769206,446.211688,99.349841,45.402933,46.663456,49.460242,fail
3,0.365781,0.539813,0.091830,0.027501,0.327412,0.034355,0.002797,0.108307,0.027127,0.005443,...,35.827347,4.591022,35.256919,0.599770,158.209313,36.336651,14.880900,13.864633,13.518690,fail
4,0.556270,0.544471,0.120493,0.050922,0.256990,0.098010,0.009939,0.246447,0.099417,0.017617,...,169.570629,21.581580,168.874672,2.734320,501.771230,137.520402,63.869727,66.623908,71.477645,fail
5,0.563754,0.527060,0.161022,0.051254,0.364970,0.116880,0.008432,0.229821,0.105705,0.017131,...,193.129417,25.693270,193.532984,3.157093,367.907255,139.525657,67.092201,72.014651,78.969697,fail
6,0.459202,0.509326,0.123432,0.037124,0.366765,0.065441,0.004907,0.151842,0.046739,0.008407,...,77.998862,12.256977,78.519296,1.423373,15.480824,55.710464,23.174025,22.179426,22.261696,fail
7,0.466862,0.520712,0.111841,0.051912,0.227578,0.108398,0.010011,0.297468,0.084164,0.015667,...,144.125284,19.870810,143.968341,2.437947,300.062146,113.916401,50.611318,51.048888,53.404226,fail
8,0.485384,0.558568,0.104713,0.041688,0.213888,0.084394,0.007786,0.264679,0.064506,0.010416,...,111.745754,13.601989,111.349997,1.744731,351.655563,87.765806,42.772152,46.222841,50.879034,fail
9,0.509062,0.604996,0.075732,0.035830,0.188424,0.064858,0.007366,0.251086,0.038945,0.007343,...,67.825097,10.658241,68.277648,1.237715,13.461586,48.443882,20.151326,19.286457,19.357996,fail
10,0.610401,0.425190,0.081931,0.053555,0.280076,0.064400,0.007786,0.142352,0.075072,0.014947,...,119.059644,17.312992,118.766115,2.100059,226.705174,99.481964,41.067074,38.797039,38.406887,pass
11,0.485615,0.554707,0.088653,0.040740,0.263034,0.065493,0.005523,0.179885,0.062655,0.009842,...,111.163050,13.659714,110.964169,1.738007,319.127054,84.371043,41.704799,45.547940,50.519533,pass
12,0.431516,0.441000,0.113161,0.042932,0.325146,0.064129,0.006637,0.251670,0.039863,0.005160,...,71.533184,7.955473,71.385900,1.046214,246.776534,52.209851,28.106744,32.406218,37.246033,pass
13,0.448188,0.593311,0.091628,0.027998,0.071992,0.090244,0.008346,0.390772,0.020709,0.003775,...,33.241732,5.094079,33.362539,0.599875,25.449012,25.083639,10.404893,9.911218,9.898405,pass
14,0.394695,0.407806,0.107596,0.039891,0.346662,0.060075,0.004510,0.160927,0.048150,0.006919,...,85.899156,10.493191,85.900995,1.330477,229.791991,62.375400,31.790448,35.462255,39.910887,pass
15,0.243693,0.359380,0.052886,0.023135,0.157593,0.035492,0.003113,0.120009,0.023860,0.004811,...,32.910240,4.175964,32.420035,0.545782,142.973746,32.685219,13.614621,12.896672,12.767285,pass
16,0.458706,0.520759,0.122340,0.041393,0.238042,0.088770,0.008469,0.266355,0.074829,0.012027,...,132.744075,16.871403,132.641379,2.118286,337.857317,100.078429,48.537576,52.341152,57.553762,pass
17,0.133540,0.376181,0.086955,0.016229,0.259818,0.026584,0.001428,0.072344,0.011443,0.001984,...,13.063664,1.674016,12.855670,0.218693,57.687591,13.249371,5.425997,5.055437,4.929297,pass
18,0.448934,0.389537,0.165742,0.049511,0.491920,0.084086,0.005901,0.281759,0.053725,0.006883,...,95.734603,10.647003,95.537490,1.400174,330.267047,69.873716,37.615940,43.370031,49.847273,pass
19,0.447816,0.503087,0.106254,0.036404,0.194288,0.082996,0.008312,0.186795,0.078050,0.016012,...,127.304750,18.467465,126.956236,2.243179,248.874200,106.831413,44.092425,41.641235,41.207634,pass

[[1.22967689 1.12309685 1.43825841 1.26898472 1.40211099 1.40283045
  1.36719525 1.35344208 1.48227248 1.42304195 1.5286036  1.41065548
  1.46090262 1.42494276 1.54190981 1.41968754 1.57003183 1.45645396
  1.59007401 1.48707082 1.55348829 1.48732697 1.55873069 1.51650309
  1.55519444 1.49010277 1.58422456 1.55901246 1.48602957 1.55010462
  1.48424624 1.56905728 1.55315437 1.49162415 1.58008404 1.54302477
  1.58526118 1.54964387 1.49547755 1.58340903 1.54670498 1.5925649
  1.54958432 1.59532184 1.54392271 1.59270591 1.55393665 1.5949839
  1.55416859 1.57707009 1.57948851 1.57889356 1.55290534 1.58517512
  1.5896298  1.5859992  1.56189711 1.54961876 1.57973306 1.55547237
  1.58944171 1.5098467  1.47271618 1.54144775 1.55982129 1.47938526
  1.61262163 1.62       1.49801895 1.64929905 1.62669571 1.49726393
  1.63979508 1.51764697 1.60141048 1.49912202 1.63934006 1.51753356
  1.63100984 1.50065834 1.64041083 1.5131887  1.58624736 1.49341606
  1.60013067 1.53289524 1.5873151  1.49557121 1.600241   1.58019643
  1.49150249 1.57727214 1.52003981 1.59565116 1.58506991 1.50475758
  1.5964261  1.57239049 1.59500292 1.58168877 1.50256129 1.59144102
  1.56246465 1.59926883 1.57828935 1.60174567 1.56665423 1.59692854
  1.57566628 1.59762532 1.56602087 1.58892009 1.59694198 1.58856373
  1.57105305 1.58973703 1.60062125 1.58975568 1.5736001  1.57465033
  1.58745198 1.57318266 1.59398125 1.56097726 1.47342614 1.54603843
  1.56975152 1.4802058  1.61608983 1.62187015 1.50715028 1.65143109
  1.63006616 1.49910428 1.63908015 1.52266878 1.60365215 1.50063638
  1.63858316 1.52063554 1.63111689 1.48102951 1.50176024 1.63907983
  1.51415003 1.5894302  1.4937572  1.60172646 1.53374991 1.58906301
  1.49580852 1.60087295 1.58220949 1.49153354 1.57921148 1.5204034
  1.59515684 1.58616098 1.50477425 1.59558882 1.57386775 1.59446233
  1.5830189  1.50196001 1.5908052  1.56429586 1.59731631 1.579145
  1.59951097 1.56804121 1.59561754 1.57672995 1.59622683 1.56710049
  1.58874461 1.59572248 1.58839329 1.5716478  1.58939282 1.59957653
  1.58942797 1.57350128 1.57545817 1.58616274 1.57405223 1.59192284
  1.56179037 1.77887379 1.45608448 1.53841986 1.60608044 1.65882224]]
BARINEL SCORES

,cp 160,cp 130,cp 134,cp 142,cp 132,cp 157,cp 140,cp 155,p 180,cp 152,...,u 122,x 4,p 185,cx 186,u 191,u 190,p 188,cx 189,u 184,u 187
sum,0.609492,0.609434,0.609301,0.608349,0.608323,0.608138,0.607991,0.607885,0.60784,0.607684,...,0.581604,0.565702,0.559929,0.557141,0.543522,0.540968,0.532023,0.523967,0.517055,0.498783

custom SCORES

,cp 148,cp 150,cp 144,cp 146,cp 155,cp 160,cp 138,cp 136,cp 157,cp 86,...,cx 183,cx 179,cx 186,p 185,cx 189,u 191,p 188,u 190,u 184,u 187
sum,0.849232,0.84915,0.848932,0.848884,0.848799,0.848574,0.848404,0.848401,0.848366,0.848292,...,0.813487,0.807714,0.752535,0.751313,0.712367,0.710611,0.700805,0.692857,0.692006,0.67362

DSTAR SCORES

,cx 18,cx 22,cx 26,cx 10,x 4,cx 14,cx 37,cx 31,cx 39,cx 20,...,p 174,p 178,p 163,p 182,p 176,p 170,p 185,p 180,cp 130,p 168
sum,6239.262543,4384.186672,4338.408662,3804.803122,3657.29695,3339.462915,3170.691928,3065.57427,3003.229866,2872.364108,...,0.00585,0.002919,0.002621,0.001603,0.00111,0.000814,0.00058,0.000451,0.000411,0.0002

ERROR GATE LOCATION:
50
Now evolving the following mutant:  AddGate_x_inGap_27_.qasm

100%|██████████| 10/10 [02:54<00:00, 17.46s/it]
100%|██████████| 10/10 [02:53<00:00, 17.40s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.517492,0.748706,0.050327,0.019144,0.094008,0.047679,0.003173,0.176179,0.005808,0.000720,...,4.769235,0.611144,4.693301,0.079840,21.060376,4.837032,1.980903,1.845621,1.799570,fail
1,0.386508,0.506706,0.120058,0.029922,0.285312,0.058199,0.005330,0.120922,0.067738,0.011639,...,113.465815,13.372932,112.614795,1.753698,434.461943,95.479091,45.581893,48.461518,52.695093,fail
2,0.577225,0.694000,0.124113,0.030799,0.154562,0.113544,0.008475,0.304244,0.079320,0.013221,...,149.236368,19.853890,149.548215,2.439572,284.291970,107.815280,51.843974,55.647685,61.022038,fail
3,0.440168,0.543446,0.138196,0.033150,0.336808,0.081083,0.003809,0.182159,0.060360,0.008674,...,108.276873,13.246079,108.282858,1.678603,288.289786,78.618347,40.031982,44.629734,50.209311,fail
4,0.515452,0.451433,0.123371,0.046607,0.244487,0.103977,0.008689,0.327689,0.065233,0.010432,...,112.126597,12.979052,111.478906,1.703510,415.864376,90.387559,44.731140,48.810308,54.071895,fail
5,0.496800,0.522545,0.069246,0.031681,0.222375,0.043867,0.004110,0.140030,0.033377,0.005971,...,55.230329,8.679061,55.598843,1.007878,10.961840,39.448104,16.409330,15.705062,15.763317,fail
6,0.514567,0.443885,0.159214,0.049516,0.499477,0.078333,0.005571,0.059187,0.107416,0.019027,...,182.580093,23.384724,181.883921,2.954577,526.644507,147.593568,68.377269,71.199678,76.289750,fail
7,0.329663,0.475452,0.146646,0.033537,0.195423,0.115792,0.008762,0.322529,0.082276,0.013901,...,150.907167,20.763430,151.353156,2.521098,238.823374,108.788586,50.990724,53.746840,58.184741,fail
8,0.448128,0.457539,0.122868,0.044411,0.340907,0.084949,0.006037,0.169627,0.077256,0.014668,...,127.930051,17.984411,127.733408,2.196950,257.429799,103.090310,44.617926,44.012321,45.219995,fail
9,0.574818,0.379094,0.111693,0.070980,0.386587,0.082134,0.010802,0.215581,0.089300,0.017746,...,140.705250,20.411409,140.320051,2.479303,275.071484,118.076825,48.733733,46.024523,45.545280,fail
10,0.335896,0.540436,0.094344,0.028324,0.271848,0.051568,0.003529,0.010984,0.082569,0.013770,...,152.780695,20.308071,153.036111,2.498906,299.943300,111.409992,53.316111,57.019285,62.359415,pass
11,0.472468,0.532667,0.094320,0.040218,0.408381,0.032357,0.003167,0.033116,0.045718,0.009387,...,61.856807,7.926513,60.871947,1.035517,273.152317,62.736133,25.692245,23.937634,23.340355,pass
12,0.383863,0.555245,0.122150,0.033605,0.210129,0.099272,0.006937,0.178246,0.091247,0.015151,...,168.271383,22.366124,168.548955,2.752356,330.876525,122.766632,58.736033,62.803494,68.675583,pass
13,0.494186,0.567680,0.119282,0.046301,0.279264,0.078897,0.007316,0.206221,0.065574,0.012321,...,98.853180,12.747309,97.982024,1.629787,343.737889,88.553938,38.567447,38.116722,39.170122,pass
14,0.434243,0.358415,0.085445,0.038945,0.216095,0.069670,0.006571,0.278553,0.027931,0.004911,...,45.292146,7.117345,45.594350,0.826520,8.989359,32.349786,13.456624,12.879083,12.926855,pass
15,0.301088,0.463805,0.114721,0.027185,0.234926,0.073549,0.006184,0.164879,0.078599,0.012771,...,147.762327,19.262499,147.995949,2.384294,309.466638,106.884814,52.156503,56.549680,62.444172,pass
16,0.413950,0.445516,0.107082,0.040154,0.345128,0.060573,0.005339,0.205073,0.047285,0.006201,...,86.161143,9.582303,85.983741,1.260157,297.240343,62.886344,33.854346,39.033028,44.862546,pass
17,0.459852,0.345592,0.109847,0.048916,0.271088,0.076314,0.008427,0.178336,0.091350,0.016479,...,147.905267,17.705721,146.571738,2.320191,581.955431,129.057987,59.779822,62.102622,66.370757,pass
18,0.302491,0.440651,0.069570,0.017718,0.202761,0.031623,0.002424,0.068664,0.033385,0.004498,...,62.823232,6.986807,62.693882,0.918826,216.728777,45.852728,24.684438,28.460404,32.710919,pass
19,0.426657,0.596925,0.083692,0.027305,0.212832,0.059342,0.004386,0.003096,0.098206,0.017150,...,181.273155,24.032209,181.343718,2.970013,388.290811,135.953231,64.136324,67.834980,73.581527,pass

[[1.20234604 1.4335321  1.36578503 1.82118038 1.80973561 1.43031761
  1.66807354 1.62371202 1.60782387 1.64026022 1.55410662 1.62986901
  1.59163495 1.64428178 1.55350686 1.64295006 1.62449622 1.64497362
  1.60195888 1.64871329 1.65006296 1.64581884 1.63724184 1.64575456
  1.65810818 1.65030655 1.64948588 1.65880055 1.65021286 1.6605273
  1.65020393 1.5231594  1.66448266 1.65080929 1.52659152 1.65560452
  1.52576451 1.66284432 1.65114911 1.52788354 1.65905841 1.52583641
  1.66250194 1.526067   1.65874164 1.52705849 1.66616393 1.52732325
  1.66109004 1.52666161 1.6157428  1.52803734 1.6404304  1.52753177
  1.6157293  1.52773239 1.64230543 1.53331044 1.59115781 1.53668184
  1.5878662  1.55073751 1.64959631 1.65466509 1.6756503  1.65010003
  1.6585038  1.59594373 1.65140197 1.66060302 1.62125924 1.65109126
  1.60384453 1.65244075 1.66440985 1.65124046 1.60681301 1.65248359
  1.62490816 1.65136252 1.60793393 1.65204722 1.65501737 1.65088436
  1.64494327 1.65363577 1.65688451 1.65104609 1.6456717  1.66015947
  1.65081776 1.66064451 1.65307911 1.53155955 1.66405662 1.65171098
  1.53287132 1.65701227 1.53243525 1.66227921 1.65175066 1.53489339
  1.65866034 1.53159252 1.6629607  1.53165701 1.658631   1.53239834
  1.66419975 1.53218169 1.66003509 1.5334515  1.61779059 1.53396233
  1.64128312 1.532548   1.61718772 1.53227372 1.6418984  1.54178243
  1.59306561 1.5429728  1.58925746 1.56742427 1.64996548 1.65505796
  1.6729579  1.65040736 1.65723188 1.596572   1.65221047 1.65803149
  1.62092312 1.65096303 1.60363301 1.65222349 1.66168121 1.65106594
  1.60658515 1.65213559 1.6242167  1.65114124 1.60767074 1.65141932
  1.65300396 1.65072581 1.64343098 1.65002596 1.65296485 1.65455714
  1.65085913 1.64370297 1.65782646 1.65072954 1.65834992 1.65287954
  1.53494113 1.66136652 1.65145741 1.53618901 1.65517606 1.53577259
  1.66008312 1.65163112 1.53819695 1.65675055 1.53532362 1.66096392
  1.53533203 1.65664223 1.53582903 1.66205667 1.53559159 1.6579925
  1.53664603 1.61808608 1.5371031  1.6401496  1.53568284 1.61722071
  1.53538282 1.64070324 1.54471197 1.59426881 1.5457282  1.59057923
  1.57032826 1.91305391 1.65068605 1.6544267  1.6554858  1.65558998]]
BARINEL SCORES

,u 184,cx 186,p 185,u 191,cx 189,p 188,u 190,u 187,p 180,cp 130,...,h 1,cx 65,cx 55,u 125,u 63,cx 117,u 60,h 0,u 122,x 4
sum,0.603276,0.561131,0.544016,0.543971,0.538149,0.527814,0.518664,0.50993,0.508984,0.508815,...,0.489387,0.489247,0.488752,0.488647,0.488612,0.488537,0.486568,0.486465,0.486369,0.47437

custom SCORES

,u 184,p 185,p 188,cx 186,u 187,cx 189,p 180,p 182,p 176,p 178,...,cx 117,cx 55,cx 111,cx 51,cx 113,u 125,u 63,u 122,u 60,h 0
sum,0.848162,0.77088,0.768125,0.76178,0.74064,0.721899,0.716379,0.715397,0.710562,0.70771,...,0.691819,0.691789,0.691754,0.691623,0.691595,0.691252,0.691047,0.688286,0.688255,0.687812

DSTAR SCORES

,cx 18,cx 22,cx 26,x 4,cx 10,cx 14,cx 37,cx 31,cx 39,cx 20,...,p 174,p 178,p 163,p 182,p 176,p 170,p 185,p 180,cp 130,p 168
sum,4030.262997,2832.114731,2800.160502,2476.310773,2445.068406,2145.029849,2056.313928,1983.009708,1948.891601,1865.001167,...,0.005054,0.002496,0.002296,0.001331,0.00094,0.000715,0.000417,0.000375,0.000345,0.000178

ERROR GATE LOCATION:
44
Now evolving the following mutant:  AddGate_cx_inGap_74_.qasm

100%|██████████| 10/10 [02:45<00:00, 16.59s/it]
100%|██████████| 10/10 [02:52<00:00, 17.30s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.470806,0.663929,0.076670,0.028392,0.177543,0.064490,0.005296,0.166291,0.040707,0.007646,...,83.537177,12.302420,84.055136,1.442035,65.687090,59.277210,26.042293,26.067780,27.143716,fail
1,0.416071,0.408158,0.102337,0.040570,0.245639,0.078754,0.006909,0.173393,0.070968,0.013989,...,138.914754,19.477708,139.432859,2.345386,250.459692,112.454273,48.438509,46.694678,46.319870,fail
2,0.413769,0.468598,0.139680,0.054605,0.382115,0.083423,0.009254,0.245615,0.078626,0.013744,...,158.559011,19.497804,158.781538,2.476475,478.417280,132.462707,60.852410,61.654772,63.612247,fail
3,0.412403,0.500761,0.137636,0.049224,0.299880,0.098515,0.009016,0.230435,0.087452,0.016426,...,177.920542,24.623793,178.663755,2.968972,301.367701,137.268991,60.864513,60.588544,62.153159,fail
4,0.586631,0.541009,0.131078,0.053551,0.336348,0.083881,0.008902,0.302712,0.044693,0.008879,...,73.695882,9.642042,73.676292,1.211972,250.403738,72.530952,30.096235,27.218869,24.743814,fail
5,0.604059,0.492292,0.139932,0.048934,0.355352,0.083707,0.007908,0.176907,0.085145,0.015978,...,167.538065,22.436844,168.023077,2.751100,375.493652,137.069545,60.529389,59.534251,60.035698,fail
6,0.539546,0.597331,0.108423,0.041899,0.160351,0.097564,0.009633,0.312559,0.061883,0.011535,...,120.717070,15.099000,120.832470,1.912196,376.551098,105.663424,47.125350,46.308995,46.312981,fail
7,0.343190,0.541248,0.089504,0.025676,0.265605,0.048771,0.002874,0.127171,0.035217,0.006045,...,69.947530,8.590108,70.048084,1.091302,210.507142,58.222462,26.809553,27.226598,28.155828,fail
8,0.453353,0.600390,0.065662,0.031047,0.267157,0.035479,0.002765,0.051475,0.039963,0.007338,...,79.905126,11.767533,80.400565,1.379337,62.831130,56.699940,24.910020,24.934398,25.963555,fail
9,0.471956,0.582830,0.107160,0.039021,0.366165,0.051347,0.003921,0.180114,0.027208,0.003279,...,56.175604,6.524075,56.335876,0.837044,150.934790,39.672147,20.359215,22.795031,25.729169,fail
10,0.540587,0.556350,0.136554,0.050660,0.303662,0.104204,0.009699,0.382889,0.048934,0.008875,...,96.727258,14.244908,97.326999,1.669724,76.058736,68.636769,30.154234,30.183745,31.429566,pass
11,0.267701,0.248178,0.054741,0.025056,0.173507,0.038440,0.003227,0.126188,0.025687,0.004516,...,49.363875,7.265612,49.669501,0.851814,39.069029,35.027700,15.395689,15.416484,16.057519,pass
12,0.352583,0.427007,0.105792,0.029414,0.273384,0.061678,0.004958,0.044175,0.090292,0.015806,...,199.146093,25.999928,199.900230,3.196462,401.790696,148.173781,69.326524,72.367939,77.382741,pass
13,0.417773,0.463518,0.104900,0.039418,0.201195,0.095377,0.007624,0.209656,0.081748,0.016843,...,161.901983,22.692602,162.453126,2.737612,310.139350,134.109335,57.237946,54.532484,53.364711,pass
14,0.261567,0.266679,0.094626,0.021928,0.164442,0.060109,0.004864,0.159708,0.056309,0.008699,...,127.041218,16.057339,127.543786,1.991834,261.785920,89.859861,43.921162,47.627506,52.615844,pass
15,0.421722,0.565494,0.077619,0.029017,0.134935,0.069205,0.006487,0.107412,0.091598,0.015315,...,209.438922,27.334920,210.360235,3.349184,378.896804,148.235624,71.003302,75.920073,83.052997,pass
16,0.297488,0.366764,0.091508,0.029107,0.305300,0.037363,0.003606,0.078466,0.046292,0.007194,...,100.955862,12.990464,101.379986,1.600313,193.981733,71.433895,34.528156,37.155140,40.828271,pass
17,0.348469,0.469892,0.107056,0.032682,0.312560,0.055254,0.003857,0.165357,0.040325,0.005139,...,89.230068,10.362926,89.484645,1.329572,239.746803,63.015760,32.338845,36.207926,40.868549,pass
18,0.483139,0.439096,0.115009,0.040004,0.329100,0.074165,0.005749,0.170869,0.061814,0.010796,...,132.483816,18.247009,133.169383,2.191093,181.322432,93.872328,43.358247,45.146422,48.450182,pass
19,0.492506,0.641364,0.098429,0.034529,0.162898,0.087952,0.007850,0.279101,0.055066,0.011307,...,107.925586,15.086791,108.277111,1.822917,213.152649,90.072783,38.392647,36.492567,35.600059,pass

[[1.28201808 1.23028521 1.27433481 1.32241328 1.33786565 1.35709156
  1.44908198 1.58927975 1.52925336 1.56649818 1.55349295 1.57261992
  1.49495776 1.5378977  1.55079199 1.54997732 1.53514993 1.52312046
  1.56258098 1.51018994 1.53265321 1.50872032 1.51673796 1.50631107
  1.55649366 1.50951155 1.55507486 1.56052597 1.5114266  1.55744009
  1.51231996 1.74788055 1.57341952 1.50919283 1.73960939 1.53469641
  1.74039438 1.56462744 1.50743361 1.73652415 1.54934438 1.73921
  1.56347116 1.73831031 1.54561684 1.73676745 1.57972134 1.73585437
  1.56324544 1.73992469 1.55833506 1.73691205 1.51379996 1.73696287
  1.55581696 1.73644865 1.50953701 1.731035   1.60929208 1.72350848
  1.61391924 1.70358137 1.51689767 1.53000446 1.61676128 1.51407704
  1.6132004  1.59005221 1.50632195 1.65846823 1.53437753 1.50716469
  1.5684194  1.50026032 1.62162964 1.50634591 1.81824774 1.59754242
  1.50911723 1.55301772 1.51278507 1.57237767 1.51626306 1.51701335
  1.51251803 1.53359288 1.50883688 1.51732606 1.51227142 1.53131993
  1.52113488 1.51191602 1.51928145 1.50602319 1.66161078 1.54739091
  1.51114663 1.65930127 1.51148244 1.65974478 1.539039   1.50957955
  1.65587119 1.51017819 1.66162273 1.53816957 1.66137202 1.51132812
  1.65888726 1.53822842 1.6591448  1.51291982 1.6574223  1.55469994
  1.6568377  1.52820643 1.65856997 1.55195667 1.65876483 1.52931822
  1.64690848 1.58530619 1.64586675 1.58541389 1.60966976 1.51158368
  1.50415143 1.55687732 1.51073147 1.53830636 1.57442964 1.5060763
  1.55181027 1.54612117 1.51243352 1.56622706 1.5106183  1.54751486
  1.51227891 1.56226944 1.51079713 1.54236295 1.51218461 1.56071066
  1.51585083 1.51941758 1.51260522 1.53355306 1.50894714 1.51682426
  1.51236927 1.53193804 1.51632997 1.51198049 1.5150682  1.50561491
  1.65497314 1.53569271 1.51131134 1.65335852 1.51405257 1.65400422
  1.53069163 1.50965152 1.65031791 1.5131163  1.65546831 1.53079987
  1.65515582 1.5133162  1.65380328 1.53093278 1.65406596 1.51291875
  1.65280721 1.55026513 1.65228261 1.52934423 1.65421705 1.54911113
  1.6546076  1.53018905 1.64314031 1.57883435 1.64200957 1.58074594
  1.61218582 1.89648446 1.50626281 1.49902445 1.52980429 1.55087504]]
BARINEL SCORES

,p 188,u 190,u 191,u 187,p 185,u 184,cx 189,x 4,cx 186,p 180,...,cp 157,cp 152,cp 138,cp 136,cp 155,cp 146,cp 150,cp 144,cp 148,cx 115
sum,0.554451,0.54838,0.54818,0.547456,0.534388,0.532902,0.526831,0.523524,0.514962,0.505116,...,0.460126,0.45985,0.459591,0.459507,0.459395,0.458597,0.458488,0.458343,0.458167,0.44781

custom SCORES

,x 4,u 184,p 188,u 187,p 185,u 191,u 190,p 180,p 182,cx 189,...,cx 58,cx 56,cx 52,cx 110,cx 48,cx 50,cx 121,cx 119,u 59,h 0
sum,0.771738,0.744635,0.737754,0.730562,0.727981,0.723875,0.717046,0.703704,0.697041,0.694671,...,0.64446,0.644327,0.644092,0.64409,0.643978,0.643875,0.643089,0.641927,0.640288,0.63968

DSTAR SCORES

,cx 18,x 4,cx 22,cx 26,cx 10,cx 14,cx 37,cx 31,cx 39,cx 20,...,p 166,p 178,p 163,p 182,p 176,p 170,p 185,p 180,cp 130,p 168
sum,3522.317179,2759.728476,2485.182842,2457.039475,2158.228096,1902.915246,1762.536601,1734.816997,1679.1836,1642.270475,...,0.003626,0.001877,0.001607,0.001088,0.000729,0.000499,0.000439,0.000315,0.00025,0.00012

ERROR GATE LOCATION:
115
Now evolving the following mutant:  AddGate_h_inGap_63_.qasm

100%|██████████| 10/10 [03:38<00:00, 21.89s/it]
100%|██████████| 9/9 [02:35<00:00, 17.28s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.334348,0.419438,0.125798,0.037563,0.393131,0.055256,0.003966,0.106710,0.045831,0.009248,...,64.613111,7.908431,64.002192,1.064179,281.925985,64.511247,26.399770,25.118679,24.752984,fail
1,0.460593,0.457744,0.117532,0.040984,0.247064,0.090402,0.008900,0.230782,0.070764,0.014279,...,122.507693,17.464211,123.255752,2.124876,206.478303,98.934399,40.835345,39.445933,39.554014,fail
2,0.336205,0.559268,0.155410,0.031253,0.297390,0.096293,0.005964,0.187053,0.087604,0.015290,...,155.767519,18.492388,155.349717,2.423387,542.124823,128.204448,60.929964,64.775798,69.747655,fail
3,0.483341,0.521510,0.093167,0.043206,0.273586,0.065430,0.006417,0.090011,0.087703,0.017704,...,148.822501,20.945022,149.522424,2.569563,286.765041,122.746652,50.616674,48.814944,48.858452,fail
4,0.438736,0.464168,0.124924,0.029730,0.191980,0.097744,0.007281,0.261199,0.072834,0.012222,...,142.081938,18.950222,143.114657,2.316013,245.502965,101.461704,48.430608,51.886734,56.316152,fail
5,0.465012,0.274058,0.153713,0.057016,0.396249,0.110914,0.009966,0.394739,0.055693,0.009681,...,100.564935,14.688100,101.764984,1.734946,77.895546,71.009159,31.188678,31.702445,33.173088,fail
6,0.416171,0.510695,0.104804,0.036490,0.235709,0.072660,0.006890,0.160590,0.078325,0.014837,...,137.267700,17.661730,137.349801,2.242113,382.502544,113.254574,50.553013,51.623187,54.012129,fail
7,0.477349,0.475865,0.152183,0.052831,0.433666,0.081530,0.007404,0.180329,0.093568,0.016074,...,162.964075,19.847479,162.776253,2.567824,520.239425,132.388221,62.320577,65.897195,70.707705,fail
8,0.436719,0.408488,0.136793,0.047520,0.382167,0.074906,0.007182,0.164265,0.087590,0.015159,...,154.008442,18.221859,153.564644,2.392018,541.785173,126.970948,60.417385,64.274851,69.238743,fail
9,0.585257,0.439106,0.104306,0.049125,0.309578,0.071845,0.008126,0.261735,0.052300,0.009236,...,87.101345,10.610380,86.885791,1.381708,294.440410,73.294256,33.679701,35.032022,37.132320,fail
10,0.392254,0.393680,0.105494,0.036173,0.123606,0.106498,0.009271,0.279959,0.083645,0.013840,...,164.250551,21.554488,165.314740,2.650926,310.307224,117.514963,56.841263,61.370783,66.951382,pass
11,0.315822,0.366410,0.111407,0.032244,0.272893,0.063380,0.005136,0.141699,0.068332,0.011298,...,125.583894,15.525128,125.768308,1.976955,348.717948,96.530131,46.675458,50.254405,54.647108,pass
12,0.358957,0.434187,0.130368,0.039465,0.313041,0.074553,0.007287,0.189118,0.074008,0.011181,...,142.769178,17.633235,143.288715,2.221520,352.591695,102.841655,52.078482,57.685982,63.975458,pass
13,0.512262,0.462127,0.096130,0.048285,0.366233,0.049453,0.005613,0.134060,0.046891,0.008424,...,74.819065,9.826778,74.905622,1.239587,197.981205,62.299433,27.172580,27.300319,28.213035,pass
14,0.466434,0.655956,0.064286,0.025003,0.243680,0.025044,0.002791,0.131058,0.002865,0.000049,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,pass
15,0.401807,0.483033,0.113670,0.028618,0.322207,0.060861,0.004313,0.048097,0.083439,0.013879,...,164.250551,21.554488,165.314740,2.650926,310.307224,117.514963,56.841263,61.370783,66.951382,pass
16,0.322969,0.565930,0.102523,0.020192,0.188673,0.062949,0.004725,0.178552,0.047810,0.006459,...,94.592118,10.451597,94.483380,1.379483,326.182885,68.915298,37.488716,43.069966,48.844293,pass
17,0.508346,0.442391,0.098925,0.039920,0.276214,0.061609,0.005721,0.180034,0.051550,0.009555,...,81.405021,9.793655,80.957024,1.297897,313.150109,72.981638,32.427353,32.912393,34.223459,pass
18,0.440222,0.549525,0.099176,0.037743,0.301673,0.057347,0.006709,0.183626,0.042580,0.008046,...,78.667206,12.098281,79.829777,1.402822,15.189376,55.163027,22.922900,22.402718,22.758926,pass

[[1.32000929 1.23449395 1.22501866 1.33929295 1.37213392 1.35760777
  1.38229519 1.93745319 1.2778852  1.32386926 1.26554844 1.34933018
  1.28096583 1.25669452 1.27446972 1.26832195 1.31787783 1.27813756
  1.30603055 1.29992373 1.34178677 1.30045745 1.32592758 1.32177745
  1.35248306 1.30214428 1.35777151 1.35509374 1.29914796 1.35201578
  1.29787797 1.32346868 1.3594445  1.30305247 1.30491803 1.34084313
  1.30099644 1.3550153  1.30581411 1.29873427 1.34787206 1.29312751
  1.35448452 1.28967362 1.34572426 1.29049459 1.36228562 1.28747969
  1.35529666 1.30798324 1.30717895 1.30323724 1.32563723 1.29757177
  1.31332101 1.29628997 1.33376004 1.32359114 1.27257738 1.31058895
  1.27375473 1.33035533 1.28998859 1.33851392 1.37913271 1.29466095
  1.38805288 1.30377481 1.3076297  1.41425362 1.34398026 1.30674626
  1.32723076 1.32092343 1.38935064 1.30807052 1.33119668 1.32091411
  1.35186102 1.30916432 1.33346343 1.31767734 1.36664365 1.30414761
  1.36107275 1.33185543 1.3699355  1.30566594 1.35219332 1.35169788
  1.35916952 1.30031907 1.37866325 1.3174062  1.27534742 1.36542818
  1.31216858 1.27768078 1.35961545 1.27656104 1.37480343 1.31334731
  1.27659709 1.36044214 1.27304196 1.37242484 1.27257202 1.35761905
  1.27254343 1.37358596 1.27355926 1.36333087 1.28069073 1.3192868
  1.28073931 1.33301274 1.28209331 1.32032947 1.28290343 1.33289201
  1.27272115 1.27253593 1.27371388 1.26881625 1.24267502 1.29097176
  1.34826242 1.36861681 1.29546513 1.38037987 1.2996037  1.31496301
  1.40688555 1.34058451 1.30898195 1.31906139 1.32636773 1.3782788
  1.3099102  1.32391787 1.32465642 1.34710275 1.31057215 1.32617213
  1.31733026 1.36770875 1.30545136 1.35833747 1.33651073 1.36827672
  1.30671335 1.35767661 1.36715224 1.30311688 1.36797507 1.32554927
  1.27162141 1.3683072  1.31192637 1.26969866 1.35816576 1.26998448
  1.36950202 1.3096757  1.26994655 1.3578423  1.26921192 1.36803787
  1.26955419 1.3564038  1.26985234 1.36972609 1.27007158 1.35855746
  1.27400725 1.31769234 1.27361751 1.33507275 1.27523289 1.31866107
  1.27583421 1.3358976  1.27193132 1.27744901 1.27101433 1.27409212
  1.23437993 1.60408085 1.2818682  1.33915696 1.37695528 1.40434268]]
BARINEL SCORES

,p 180,p 182,p 176,x 4,p 178,h 3,p 174,u 129,u 66,p 126,...,cx 113,cx 119,cx 115,cx 111,u 187,u 59,h 0,u 122,u 191,u 190
sum,0.620679,0.617801,0.609284,0.6085,0.604042,0.598178,0.598014,0.595451,0.595293,0.594276,...,0.569763,0.569216,0.569162,0.568932,0.567547,0.565971,0.565686,0.565168,0.543829,0.509968

custom SCORES

,u 184,x 4,p 180,p 182,p 176,p 178,cx 186,cp 130,h 3,p 174,...,cx 124,cx 48,cx 52,cx 56,cx 111,cx 115,cx 119,cx 189,u 191,u 190
sum,0.863183,0.85252,0.830055,0.822273,0.802477,0.793816,0.793708,0.791915,0.789874,0.7891,...,0.759662,0.759281,0.75926,0.758829,0.758595,0.758579,0.758086,0.756482,0.723294,0.667356

DSTAR SCORES

,cx 18,x 4,cx 22,cx 26,cx 10,cx 14,cx 37,cx 31,cx 39,cx 20,...,p 174,p 178,p 163,p 182,p 176,p 170,p 185,p 180,cp 130,p 168
sum,6398.579039,5228.876816,4479.161097,4419.547146,3847.071936,3363.261247,3218.942788,3115.90293,3052.860475,2955.755479,...,0.006261,0.003159,0.002783,0.001774,0.001212,0.000863,0.000517,0.000503,0.000407,0.00021

ERROR GATE LOCATION:
103
Now evolving the following mutant:  AddGate_ccx_inGap_93_.qasm

100%|██████████| 10/10 [02:32<00:00, 15.20s/it]
100%|██████████| 10/10 [02:23<00:00, 14.34s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.231680,0.397029,0.051445,0.020590,0.138027,0.033210,0.003960,0.188620,0.001870,0.000020,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,fail
1,0.477180,0.512839,0.110776,0.038308,0.364053,0.054675,0.004184,0.075147,0.071637,0.012379,...,82.346336,9.644757,81.856081,1.271521,316.024944,69.340006,33.153947,35.251355,38.200241,fail
2,0.429781,0.556666,0.079335,0.031591,0.330111,0.025853,0.002387,0.053965,0.033688,0.005016,...,38.816434,4.442320,38.665848,0.585153,142.313857,30.730455,15.502709,17.083357,18.982225,fail
3,0.523707,0.677845,0.065461,0.032419,0.253900,0.030005,0.004150,0.154686,0.013079,0.001886,...,11.859202,1.852862,11.985359,0.214728,2.276885,8.413954,3.499984,3.375711,3.406616,fail
4,0.462995,0.538634,0.130311,0.039706,0.342002,0.062927,0.006534,0.231539,0.044295,0.005521,...,54.135211,6.018434,54.062209,0.791887,187.153765,39.531042,21.407387,24.619244,28.133399,fail
5,0.524416,0.615043,0.092949,0.036768,0.197669,0.071773,0.007146,0.101971,0.099987,0.017999,...,119.519317,15.315301,119.386859,1.934057,333.257552,95.797768,44.434085,46.350173,49.581978,fail
6,0.354786,0.529954,0.076553,0.028852,0.210693,0.049893,0.004329,0.172353,0.032632,0.004272,...,41.483109,4.611848,41.427169,0.606813,143.413499,30.292124,16.404203,18.865406,21.558258,fail
7,0.420042,0.576264,0.085820,0.034864,0.191712,0.067001,0.007473,0.247135,0.042375,0.008033,...,50.926747,7.956710,51.468499,0.922103,9.777586,36.131883,15.029916,14.496253,14.628968,fail
8,0.585044,0.647499,0.095615,0.037612,0.249975,0.063426,0.005812,0.091325,0.081051,0.013982,...,94.169062,11.201975,93.703119,1.464599,342.495507,78.312098,37.368901,39.694659,42.993144,fail
9,0.390941,0.646591,0.052528,0.015179,0.119300,0.041912,0.002993,0.065430,0.038082,0.007546,...,47.036211,7.271708,47.480286,0.847749,19.313071,34.069375,14.171485,13.655655,13.764222,fail
10,0.435048,0.473041,0.149148,0.044868,0.333881,0.104060,0.008271,0.261799,0.078229,0.014964,...,90.204584,12.685986,90.412742,1.546211,168.760397,71.628163,30.999173,30.732505,31.641376,pass
11,0.396434,0.556000,0.055348,0.014615,0.012811,0.072758,0.004767,0.148138,0.051955,0.010345,...,65.836371,10.286165,66.536730,1.192063,12.640132,46.710074,19.430166,18.740265,18.911834,pass
12,0.505520,0.429609,0.111101,0.054735,0.389453,0.064407,0.007114,0.186578,0.064374,0.012220,...,69.848869,10.340829,70.148040,1.237225,93.134304,55.220373,22.850644,21.843617,21.832814,pass
13,0.483655,0.333501,0.107454,0.050824,0.282836,0.094018,0.007956,0.126824,0.122859,0.023310,...,144.800652,19.403259,144.805864,2.412076,350.146501,116.781269,52.142356,52.910675,55.450727,pass
14,0.514483,0.490236,0.109582,0.041542,0.273237,0.077142,0.007708,0.303646,0.028100,0.004940,...,31.170577,4.870039,31.502166,0.564389,5.984537,22.115131,9.199315,8.872677,8.953907,pass
15,0.513799,0.585593,0.088465,0.034507,0.341960,0.035623,0.002608,0.150556,0.014361,0.001330,...,12.708595,1.412867,12.691457,0.185901,43.935570,9.280171,5.025524,5.779528,6.604499,pass
16,0.364868,0.600773,0.123689,0.032261,0.185281,0.097999,0.007634,0.199931,0.094483,0.015664,...,123.040344,16.212797,123.548400,1.995419,241.774132,88.681283,43.014879,46.389619,50.873198,pass
17,0.422809,0.634851,0.097025,0.023723,0.274977,0.036570,0.004268,0.153261,0.018807,0.002324,...,22.653262,2.518456,22.622714,0.331371,78.315819,16.542045,8.958073,10.302097,11.772620,pass
18,0.223832,0.267473,0.087933,0.027873,0.201875,0.065912,0.004808,0.221903,0.035286,0.004975,...,45.020214,5.281916,45.033137,0.679922,135.583647,32.747606,17.186683,19.428900,21.968594,pass
19,0.410405,0.389261,0.083975,0.033937,0.365267,0.024945,0.002945,0.156811,0.003755,0.000056,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,pass

[[1.3294732  1.18954291 1.549858   1.25695028 1.51850642 1.43353151
  1.52608235 1.78801864 2.17980237 2.34807662 2.1576768  2.346106
  2.17943923 2.29377781 2.15210068 2.31694203 2.20573501 2.26851026
  2.19279654 2.24878614 2.20668611 2.24411397 2.21096492 2.21966578
  2.20407669 2.2486617  2.19127422 2.20246683 2.2518791  2.20708286
  2.25337974 2.26322934 2.203384   2.24839524 2.25384143 2.21364289
  2.25063112 2.20624142 2.24573834 2.25084572 2.20983787 2.24563353
  2.20643915 2.21268414 2.23909575 2.20730373 2.23860536 2.19474919
  2.23698651 2.20082651 2.25300876 2.2079431  2.24850673 2.21105099
  2.24461982 2.19983678 2.24257064 2.20561666 2.26997755 2.22100104
  2.25844457 2.21535863 2.28824252 2.25652959 2.20402788 2.19162857
  2.25182929 2.16744481 2.19190394 2.23862925 2.14508562 2.17650709
  2.23897714 2.17659337 2.22448762 2.17192765 2.2377343  2.17519174
  2.22476807 2.17154377 2.23677807 2.17368871 2.22901952 2.1823951
  2.2417116  2.17967624 2.21352338 2.1815891  2.24031014 2.17948298
  2.18460171 2.24359995 2.18548592 2.22323271 2.23540994 2.18143164
  2.23452695 2.2345387  2.19090523 2.23501088 2.18305537 2.23629097
  2.23635642 2.19466334 2.23402128 2.18514508 2.2329973  2.19322755
  2.23445854 2.18546945 2.23420445 2.19279936 2.23807901 2.1949832
  2.23810979 2.19888121 2.23803534 2.19239033 2.23811974 2.1972423
  2.24328785 2.21220466 2.24342867 2.21041701 2.24087467 2.25581059
  2.20534912 2.18719805 2.25120692 2.16686894 2.18911661 2.2324188
  2.14666292 2.17380944 2.23800015 2.17624367 2.22186776 2.17169906
  2.2370459  2.17494901 2.22339191 2.17146489 2.23638719 2.17417463
  2.22882512 2.18168901 2.24162892 2.1793315  2.21368621 2.18160757
  2.24029963 2.17979932 2.1845645  2.24349734 2.18544043 2.22316238
  2.23411294 2.18174611 2.2346938  2.23349325 2.19089035 2.23385977
  2.18320802 2.23671346 2.23528134 2.19469441 2.23334002 2.1854278
  2.23245309 2.19334661 2.23365208 2.18577405 2.23345453 2.19315039
  2.2369667  2.19530349 2.23697271 2.19902157 2.23694916 2.19285104
  2.23705276 2.1977375  2.24166757 2.21212601 2.24183505 2.21072272
  2.23885277 2.28936766 2.26676593 2.21095219 2.17206892 2.14409433]]
BARINEL SCORES

,x 4,u 190,u 191,u 121,u 59,h 0,cx 116,u 124,u 62,cx 64,...,cp 150,cp 139,cp 152,cp 155,cp 133,cp 157,cp 141,cp 160,cx 186,u 184
sum,0.569632,0.544844,0.50748,0.50504,0.503821,0.503527,0.500252,0.50001,0.499629,0.499578,...,0.445066,0.444916,0.444794,0.444206,0.443983,0.44391,0.443604,0.441343,0.42643,0.419907

custom SCORES

,x 4,u 121,u 59,h 0,cx 126,cx 64,cx 116,u 124,cx 54,cx 82,...,cp 157,cp 141,cp 160,u 191,u 187,p 185,cx 189,p 188,u 184,cx 186
sum,0.895657,0.775878,0.774205,0.773429,0.773149,0.772747,0.77188,0.770946,0.770786,0.770458,...,0.694035,0.693465,0.691058,0.67615,0.653798,0.631955,0.629044,0.615247,0.607607,0.579255

DSTAR SCORES

,cx 18,x 4,cx 22,cx 26,cx 10,cx 37,cx 14,cx 31,cx 39,cx 20,...,p 178,p 163,cp 133,p 182,p 176,p 170,p 185,p 180,p 168,cp 129
sum,1998.574669,1962.768378,1399.976076,1378.258233,1161.783695,1030.259651,1014.558126,979.490374,976.59038,943.13897,...,0.001151,0.001101,0.001038,0.000582,0.000424,0.000343,0.000238,0.000163,0.000087,0.00006

ERROR GATE LOCATION:
148
Now evolving the following mutant:  AddGate_z_inGap_62_.qasm

100%|██████████| 10/10 [03:03<00:00, 18.32s/it]
100%|██████████| 10/10 [02:34<00:00, 15.41s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.579399,0.601940,0.129821,0.041395,0.271542,0.077885,0.008464,0.182920,0.086287,0.014942,...,145.024875,17.724386,144.165141,2.286394,496.899511,119.988667,56.577006,59.644182,64.472029,fail
1,0.427188,0.488423,0.093888,0.039702,0.271200,0.070193,0.006889,0.233461,0.040651,0.007592,...,70.083596,11.013148,70.551217,1.278930,13.909842,50.057008,20.822343,19.928675,20.002596,fail
2,0.592569,0.667267,0.092433,0.037921,0.386651,0.023223,0.002845,0.022841,0.039161,0.007696,...,50.750387,6.503304,49.942360,0.849590,224.107686,51.471830,21.079190,19.639620,19.149583,fail
3,0.423793,0.419032,0.139445,0.044273,0.466819,0.051038,0.005102,0.216375,0.025819,0.004510,...,29.709849,3.807107,29.236821,0.497359,131.195167,30.132189,12.339995,11.497255,11.210382,fail
4,0.471262,0.462588,0.162945,0.048497,0.488258,0.067546,0.006586,0.118468,0.090122,0.015340,...,149.297125,17.595963,148.177362,2.307497,571.660451,125.630383,59.976175,63.765156,69.335648,fail
5,0.426052,0.528989,0.130014,0.038128,0.304581,0.077996,0.005377,0.131123,0.078123,0.013626,...,125.825617,14.985609,124.754180,1.964213,490.687997,108.499257,50.753775,53.132010,57.114459,fail
6,0.506947,0.572427,0.106472,0.042017,0.347968,0.054594,0.005993,0.164557,0.051939,0.009832,...,83.600412,12.597780,83.737944,1.497541,95.042088,65.291175,27.037769,25.681296,25.570243,fail
7,0.495214,0.627429,0.108674,0.036613,0.246386,0.077675,0.007374,0.136059,0.095140,0.018513,...,162.050550,22.331676,161.630496,2.751357,368.740918,132.191294,57.744708,57.381901,59.299142,fail
8,0.470221,0.417775,0.127093,0.037264,0.372144,0.063167,0.004819,0.009754,0.104765,0.018434,...,180.646729,22.697681,179.872752,2.888703,552.382383,146.208015,68.575422,72.059060,77.727379,fail
9,0.473114,0.576226,0.085193,0.048161,0.337605,0.048178,0.006250,0.151455,0.045043,0.008069,...,74.703472,11.719892,75.198261,1.361719,16.188573,53.363285,22.235072,21.313008,21.419699,fail
10,0.504208,0.584098,0.135258,0.045303,0.233428,0.104964,0.008710,0.348867,0.060444,0.009250,...,100.102948,11.585378,99.526261,1.520602,371.162014,80.663242,39.931985,43.583628,48.289649,pass
11,0.593067,0.534652,0.120090,0.059685,0.247544,0.106242,0.012078,0.313976,0.095692,0.018853,...,156.582577,22.177186,156.164687,2.711518,329.845388,129.665193,54.972235,53.217326,53.812316,pass
12,0.563253,0.440180,0.128451,0.050015,0.324004,0.080339,0.008360,0.162739,0.095029,0.016383,...,160.641262,20.349850,160.019307,2.580288,475.064356,129.369121,60.517657,63.478018,68.385661,pass
13,0.312859,0.483604,0.140482,0.027688,0.225502,0.090038,0.006745,0.169980,0.084741,0.014660,...,145.055417,17.052418,144.003188,2.236488,552.929571,121.328377,58.214380,62.123680,67.735130,pass
14,0.319584,0.482197,0.094721,0.023080,0.261128,0.047231,0.003883,0.237826,0.002509,0.000032,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,pass
15,0.225553,0.237634,0.111208,0.028620,0.251871,0.066378,0.004572,0.204505,0.039439,0.005188,...,69.772364,7.803008,69.593198,1.025878,243.176484,51.653005,27.472339,31.439373,35.962023,pass
16,0.356511,0.257500,0.085626,0.039703,0.260426,0.052310,0.006817,0.105725,0.066399,0.013863,...,104.091495,14.614319,103.428110,1.808891,274.129763,92.375442,38.032860,35.767111,35.233186,pass
17,0.306645,0.450678,0.085705,0.022242,0.277667,0.035689,0.001295,0.016724,0.051111,0.006849,...,95.734603,10.647003,95.537490,1.400174,330.267047,69.873716,37.615940,43.370031,49.847273,pass
18,0.315612,0.526440,0.081940,0.017638,0.212031,0.037936,0.002847,0.183023,0.002598,0.000007,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,pass
19,0.286311,0.317742,0.053848,0.027457,0.141707,0.045130,0.005457,0.182500,0.024423,0.004753,...,39.135128,5.811103,39.132362,0.696549,57.024966,31.455664,13.008362,12.326964,12.243146,pass

[[1.21783418 1.24441461 1.38561092 1.17151471 1.397757   1.27550333
  1.41774697 1.70781408 1.59446659 1.56158236 1.623499   1.5392523
  1.61610658 1.6224909  1.63632359 1.59800783 1.7145828  1.65107594
  1.70515068 1.67937528 1.73458629 1.67777879 1.72113262 1.70268204
  1.7454897  1.68285145 1.75761687 1.74918356 1.67934441 1.74420067
  1.67780983 1.61734979 1.75186987 1.68444345 1.60784702 1.73201893
  1.60662485 1.74687279 1.68796763 1.60452651 1.73951517 1.6032874
  1.74637991 1.60173704 1.73684378 1.6015585  1.75471001 1.60171817
  1.74824057 1.60909273 1.70892774 1.60633967 1.72004178 1.60424607
  1.71719715 1.60362173 1.72982334 1.61208911 1.67620002 1.604849
  1.6796791  1.6058554  1.66782777 1.72948856 1.77188781 1.67377045
  1.7928446  1.71564072 1.69029991 1.82619897 1.75513346 1.68929053
  1.7426786  1.70737648 1.79133137 1.69096888 1.74629034 1.70734156
  1.76358651 1.69235558 1.74868715 1.70328213 1.76648986 1.68595151
  1.76462792 1.72122315 1.76982403 1.6878812  1.76568169 1.76828277
  1.68433998 1.76652176 1.71013628 1.60808062 1.77740036 1.67503397
  1.69608858 1.61051278 1.7577536  1.60875914 1.77229051 1.69438448
  1.60924997 1.75181067 1.6110611  1.7703955  1.61316163 1.75519129
  1.6102701  1.76987017 1.61053752 1.756517   1.60522909 1.72594342
  1.60564229 1.73593659 1.60464896 1.72816184 1.60428718 1.73882944
  1.60512262 1.68505487 1.60556718 1.68526098 1.62899221 1.66887245
  1.73372398 1.77648961 1.6748234  1.79404576 1.7180312  1.69865756
  1.82459663 1.75748275 1.69059135 1.74179945 1.71112859 1.78959939
  1.69194956 1.74535454 1.70937803 1.76275301 1.69294601 1.74722598
  1.70323011 1.76645471 1.68601576 1.76394408 1.72103284 1.76819825
  1.68782562 1.76359996 1.76686914 1.68424921 1.76509776 1.71016695
  1.61232743 1.77476616 1.69576969 1.61439156 1.75654841 1.61290599
  1.77049902 1.69374735 1.61326811 1.75079683 1.61460513 1.76847666
  1.616399   1.75371209 1.61392058 1.76793087 1.61408891 1.75471736
  1.60947204 1.72533645 1.60981464 1.73492435 1.60867513 1.72734714
  1.6082918  1.7371696  1.6097783  1.68562074 1.6100324  1.68535925
  1.63357666 1.93075395 1.65612294 1.72672536 1.78345397 1.82758446]]
BARINEL SCORES

,u 187,p 180,p 182,cp 130,cp 134,cp 160,cp 132,cp 142,cp 157,cp 140,...,u 125,u 62,u 59,u 122,h 0,cx 189,x 4,p 185,cx 186,u 184
sum,0.589218,0.572116,0.568903,0.567684,0.566598,0.566357,0.565326,0.56483,0.564512,0.564373,...,0.538027,0.537877,0.534121,0.533926,0.533755,0.531322,0.529245,0.495574,0.47857,0.415142

custom SCORES

,cp 130,cp 160,u 187,cp 134,p 180,cp 132,cp 142,cp 157,cp 140,p 182,...,cx 179,cx 181,cx 177,u 191,u 190,cx 189,p 188,p 185,cx 186,u 184
sum,0.795589,0.795356,0.795114,0.794949,0.792274,0.792141,0.792046,0.791424,0.791016,0.791001,...,0.769785,0.769373,0.768415,0.733832,0.726506,0.715374,0.708515,0.671224,0.631174,0.592389

DSTAR SCORES

,cx 18,x 4,cx 22,cx 26,cx 10,cx 14,cx 37,cx 31,cx 39,cx 20,...,p 174,p 178,p 163,p 182,p 176,p 170,p 180,p 185,cp 130,p 168
sum,4714.844561,3316.093414,3310.569431,3279.599242,2849.143308,2501.553878,2388.897335,2309.983803,2260.369106,2169.290727,...,0.004938,0.002494,0.0022,0.001393,0.000954,0.000682,0.0004,0.000354,0.000315,0.000166

ERROR GATE LOCATION:
96
Now evolving the following mutant:  AddGate_y_inGap_59_.qasm

100%|██████████| 10/10 [02:43<00:00, 16.32s/it]
100%|██████████| 10/10 [02:44<00:00, 16.50s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.381823,0.446805,0.154864,0.036298,0.243222,0.114713,0.009079,0.368028,0.067012,0.010346,...,123.855598,15.694167,123.965529,1.962894,291.381773,89.745406,44.660534,49.059634,54.655643,fail
1,0.524922,0.415187,0.096610,0.049937,0.220840,0.094018,0.008817,0.285457,0.066051,0.013345,...,103.913278,14.925362,103.512857,1.823270,224.787457,88.741133,36.597496,34.516570,34.107677,fail
2,0.422694,0.407103,0.128575,0.046325,0.300814,0.088549,0.008860,0.274403,0.067869,0.012606,...,109.155152,14.471769,108.613036,1.815149,307.866838,91.796068,40.595828,40.712850,42.366112,fail
3,0.460524,0.546583,0.077246,0.031141,0.312519,0.026285,0.002367,0.149799,0.004265,0.000036,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,fail
4,0.402228,0.425823,0.165745,0.048211,0.332326,0.117520,0.008519,0.262795,0.101493,0.017722,...,171.465396,21.079552,170.493547,2.712038,576.060299,141.464007,66.562528,70.068831,75.662706,fail
5,0.278674,0.329298,0.121905,0.039791,0.210530,0.101678,0.008069,0.370788,0.048526,0.006444,...,88.808107,9.998255,88.648366,1.308460,297.765699,64.776931,34.640778,39.785707,45.618018,fail
6,0.609550,0.426725,0.168134,0.060846,0.470722,0.098210,0.009139,0.266807,0.082186,0.014016,...,134.159242,16.029766,133.188283,2.091002,499.050601,112.922707,53.461138,56.498008,61.168615,fail
7,0.431824,0.571229,0.094743,0.040201,0.278260,0.060917,0.006380,0.320298,0.006198,0.000437,...,3.694373,0.580545,3.719023,0.067417,0.733241,2.638695,1.097625,1.050516,1.054413,fail
8,0.406454,0.312410,0.142612,0.048828,0.397415,0.088167,0.007652,0.400118,0.015494,0.002084,...,18.887398,2.968023,19.013421,0.344669,3.748676,13.490270,5.611582,5.370740,5.390662,fail
9,0.429109,0.568487,0.076585,0.035962,0.285820,0.041829,0.004184,0.132417,0.028179,0.005781,...,37.801257,4.843964,37.199401,0.632814,166.925867,38.338622,15.700765,14.628506,14.263504,fail
10,0.372953,0.379202,0.158872,0.041226,0.251054,0.124060,0.010412,0.264400,0.112952,0.020905,...,196.122703,26.120967,195.632496,3.249682,486.283677,157.059501,71.132302,72.817389,77.039895,pass
11,0.427095,0.586880,0.103266,0.032864,0.211832,0.073750,0.005397,0.178551,0.065402,0.010620,...,111.591266,12.973597,110.900392,1.702437,417.103752,90.905208,44.592457,48.356823,53.335204,pass
12,0.441863,0.528346,0.121656,0.037642,0.337301,0.071917,0.005314,0.178572,0.061742,0.009229,...,113.171189,14.015187,113.209831,1.767918,289.261185,82.114098,41.486119,46.021461,51.606200,pass
13,0.489698,0.484062,0.090869,0.041098,0.240623,0.077675,0.005556,0.122904,0.093542,0.015466,...,170.153366,22.607286,170.400974,2.783861,339.187141,124.675369,59.517716,63.531792,69.385710,pass
14,0.411516,0.466412,0.091156,0.027859,0.214339,0.060551,0.004498,0.247331,0.003020,0.000054,...,0.118409,0.013169,0.118166,0.001732,0.408491,0.086423,0.046525,0.053642,0.061654,pass
15,0.438579,0.452014,0.101111,0.033379,0.311135,0.056857,0.004378,0.235228,0.012288,0.001451,...,15.747877,1.811158,15.666503,0.237790,57.738555,12.497933,6.266846,6.900972,7.693445,pass
16,0.475017,0.388926,0.155369,0.048434,0.412696,0.085859,0.006754,0.184875,0.082312,0.013869,...,135.078351,15.920157,134.065232,2.087735,517.216598,113.665584,54.264158,57.692284,62.732253,pass
17,0.477001,0.514411,0.115218,0.041645,0.275389,0.070878,0.008728,0.297909,0.040614,0.008429,...,55.671126,7.133862,54.784753,0.931966,245.837086,56.462519,23.123020,21.543870,21.006320,pass
18,0.451988,0.337429,0.117759,0.042953,0.360575,0.060032,0.005889,0.240374,0.028942,0.005420,...,35.624888,4.565078,35.057683,0.596380,157.315276,36.131314,14.796809,13.786284,13.442297,pass
19,0.309997,0.354337,0.073753,0.031507,0.220713,0.055817,0.004207,0.129156,0.052390,0.008421,...,95.683132,12.613255,95.861003,1.554977,190.492881,69.165425,33.482035,36.104954,39.719087,pass

[[1.40197305 1.28376129 1.37026295 1.39063182 1.54210471 1.41269204
  1.25078617 1.41338866 2.08286572 2.13985553 2.06424894 2.1221917
  2.0858732  2.17790398 2.07002335 2.16627836 2.19717168 2.18792791
  2.17129503 2.20283895 2.22496583 2.19744775 2.21118762 2.20353316
  2.23570237 2.20660011 2.23432147 2.23810508 2.20538966 2.2375259
  2.20499142 2.06116843 2.24312534 2.20805028 2.07002554 2.22947647
  2.07056363 2.24013293 2.20963959 2.07303748 2.23475684 2.07316683
  2.23970455 2.07443803 2.2335466  2.07500348 2.24534409 2.07615143
  2.23940673 2.06909895 2.1912704  2.07172616 2.21399834 2.07312948
  2.19438125 2.0737066  2.21901912 2.06941984 2.15955931 2.07631927
  2.15829219 2.08101795 2.20075073 2.22790256 2.25823565 2.20343692
  2.25349456 2.17844193 2.21076985 2.26652561 2.21258856 2.21015682
  2.19467276 2.21802269 2.25718169 2.21090898 2.19830033 2.21804056
  2.2184014  2.2115288  2.20004363 2.21618804 2.24164221 2.20872288
  2.23365463 2.224086   2.24418102 2.2095827  2.23456598 2.24597963
  2.20805359 2.24569587 2.21952636 2.08252845 2.25201253 2.2132084
  2.08468212 2.23993427 2.08357398 2.24892701 2.20369221 2.2125866
  2.0859151  2.23896574 2.0837954  2.24873661 2.08472222 2.24017057
  2.08416953 2.24943156 2.08409177 2.24165703 2.0829887  2.19922498
  2.08360513 2.22052586 2.08196025 2.19959025 2.08157029 2.22204342
  2.09014329 2.16450823 2.09134955 2.16156417 2.12155085 2.20142832
  2.22975197 2.25798476 2.20407029 2.25300245 2.1798346  2.21454985
  2.26413857 2.21318531 2.21056263 2.19418532 2.21927994 2.25462908
  2.21115784 2.19778131 2.2185567  2.21757981 2.21159396 2.1993063
  2.21571255 2.24017533 2.20863232 2.23230079 2.22352932 2.24192242
  2.20942543 2.23237646 2.24380017 2.20795443 2.24354059 2.21939334
  2.08723329 2.24915744 2.21290259 2.08916914 2.23817593 2.0881938
  2.24671762 2.21225628 2.09044023 2.23722472 2.08850765 2.24662462
  2.08925594 2.23820514 2.08866259 2.24721004 2.08852648 2.23954045
  2.08752605 2.19922417 2.08806369 2.21931734 2.08636081 2.19931262
  2.08594137 2.2205529  2.09458892 2.16567862 2.09556199 2.16265362
  2.12580237 2.43235791 2.19694    2.22670568 2.24801967 2.26340322]]
BARINEL SCORES

,u 184,p 185,p 188,cx 186,cx 189,u 187,u 191,u 190,cx 179,p 180,...,cx 50,cx 52,cx 56,cx 48,cx 115,cx 119,cx 111,u 122,u 59,h 0
sum,0.576535,0.544455,0.536104,0.530106,0.520796,0.518411,0.503014,0.497631,0.471195,0.469397,...,0.458602,0.458362,0.458346,0.458346,0.458337,0.458322,0.458302,0.45803,0.457963,0.457734

custom SCORES

,u 184,x 4,p 188,cx 127,cx 64,cx 145,cx 159,p 182,cx 154,cx 149,...,cp 142,cp 157,cp 144,cp 146,cp 155,cp 150,cp 148,cp 160,u 191,u 190
sum,0.780252,0.751301,0.722485,0.720972,0.72046,0.719824,0.719614,0.719499,0.719454,0.71941,...,0.698847,0.698786,0.698661,0.698655,0.698567,0.698455,0.69845,0.698404,0.679316,0.657341

DSTAR SCORES

,cx 18,x 4,cx 22,cx 26,cx 10,cx 14,cx 37,cx 31,cx 39,cx 20,...,p 174,p 178,p 163,p 182,p 185,p 176,p 170,p 180,cp 130,p 168
sum,2584.684522,2069.075323,1813.056917,1792.042904,1535.189815,1345.412765,1320.566243,1267.638171,1251.132538,1202.764354,...,0.002633,0.001287,0.001195,0.000679,0.000531,0.000482,0.000374,0.000191,0.000154,0.000094

ERROR GATE LOCATION:
91
Now evolving the following mutant:  AddGate_y_inGap_36_.qasm

100%|██████████| 10/10 [02:43<00:00, 16.38s/it]
100%|██████████| 10/10 [03:25<00:00, 20.52s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.535421,0.453539,0.168486,0.054742,0.448702,0.090790,0.008462,0.289900,0.058580,0.009725,...,89.595671,10.671067,88.832430,1.398689,349.422150,77.264627,36.140352,37.831811,40.665822,fail
1,0.437113,0.628458,0.133189,0.041602,0.388445,0.062835,0.006421,0.184882,0.057542,0.008281,...,103.232197,12.624656,103.237089,1.600059,275.161292,74.956933,38.175802,42.566134,47.891964,fail
2,0.493480,0.445459,0.152961,0.049066,0.296659,0.121726,0.009810,0.266357,0.115620,0.020876,...,199.846482,26.339219,199.352535,3.286813,507.780230,159.144843,72.864901,75.233022,80.118693,fail
3,0.460308,0.482335,0.104215,0.040503,0.165221,0.092991,0.009384,0.358338,0.040107,0.008432,...,55.671126,7.133862,54.784753,0.931966,245.837086,56.462519,23.123020,21.543870,21.006320,fail
4,0.396904,0.463214,0.148327,0.042819,0.357221,0.092938,0.006239,0.196325,0.079796,0.013644,...,129.219007,15.313397,128.181202,2.007646,499.563959,110.142835,52.021377,54.862793,59.301369,fail
5,0.427415,0.625815,0.067236,0.035697,0.092579,0.068044,0.008103,0.265291,0.043952,0.009140,...,61.355815,7.942199,60.441171,1.031285,259.322605,61.401718,25.158442,23.461053,22.898116,fail
6,0.378912,0.510203,0.097240,0.033591,0.255515,0.062457,0.006365,0.330564,0.002892,0.000044,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,fail
7,0.696408,0.563864,0.130741,0.059080,0.365450,0.093600,0.008629,0.206941,0.100161,0.016394,...,174.340589,22.272196,174.101408,2.796810,451.621542,133.539645,63.935340,68.295556,74.587137,fail
8,0.555572,0.583490,0.102535,0.043364,0.416070,0.042370,0.003472,0.112389,0.029372,0.004873,...,44.771341,7.035504,45.070070,0.817016,8.885992,31.977802,13.301889,12.730989,12.778212,fail
9,0.481933,0.421007,0.110302,0.042747,0.275987,0.074226,0.006403,0.145530,0.086310,0.015394,...,144.697567,18.226336,143.940848,2.324074,457.660373,119.566667,55.325362,57.518897,61.543919,fail
10,0.383117,0.537535,0.086250,0.025616,0.109290,0.073904,0.005472,0.161414,0.061713,0.011460,...,99.599220,12.159733,98.694385,1.583453,381.699569,87.707428,39.937097,40.938761,43.309500,pass
11,0.490366,0.536022,0.124453,0.036772,0.276719,0.074946,0.006467,0.098507,0.095915,0.016043,...,170.818391,21.677770,170.523816,2.730406,456.875871,131.447368,63.055784,67.438873,73.711619,pass
12,0.176452,0.181372,0.050795,0.024829,0.196693,0.032936,0.002004,0.092755,0.018055,0.002638,...,27.932591,3.234348,27.770380,0.424504,103.658679,22.534691,11.144660,12.155355,13.461304,pass
13,0.408828,0.366775,0.100231,0.041199,0.314205,0.059533,0.005876,0.190206,0.042078,0.008406,...,58.288477,7.755743,57.583632,0.990679,215.732074,56.153749,23.042038,21.542895,21.085879,pass
14,0.314721,0.559891,0.090803,0.024227,0.080697,0.082739,0.006950,0.186151,0.080813,0.014160,...,140.335943,16.908792,139.484462,2.192127,494.636702,115.740561,55.163899,58.612445,63.717954,pass
15,0.360722,0.485620,0.143948,0.038880,0.267510,0.100532,0.007645,0.226865,0.090843,0.015970,...,154.350443,19.189834,153.552931,2.456573,498.750403,126.649427,59.347699,62.295961,67.133644,pass
16,0.442223,0.554639,0.122306,0.035412,0.345517,0.071017,0.004536,0.289219,0.010113,0.001252,...,11.143791,1.751169,11.218146,0.203359,2.211764,7.959421,3.310901,3.168801,3.180555,pass
17,0.552842,0.512603,0.133622,0.052215,0.391435,0.075682,0.009125,0.262902,0.058546,0.010335,...,100.336177,15.139241,100.886289,1.781468,64.362614,71.878390,31.120424,30.836990,31.853342,pass
18,0.458133,0.415918,0.152928,0.052589,0.366880,0.103883,0.009759,0.298621,0.090110,0.014564,...,164.160004,21.839279,164.503036,2.683529,312.721167,118.596808,57.028371,61.212454,67.124242,pass
19,0.257305,0.371402,0.051403,0.018686,0.207076,0.022848,0.001102,0.003786,0.037384,0.005538,...,68.346530,7.849260,68.142549,1.024226,232.208823,51.675324,26.710285,30.026144,33.949292,pass

[[1.43191635 1.2138529  1.38644961 1.33300901 1.46546049 1.51782144
  1.33856306 1.52062483 1.88204592 1.95461525 1.9183966  1.93435652
  1.86366663 1.93735274 1.91659794 1.94642112 1.94601827 1.93060792
  1.96065548 1.92541248 1.9174894  1.92185481 1.93546378 1.91220373
  1.90963969 1.92602092 1.91880267 1.9096345  1.92725455 1.90832476
  1.92779631 2.09995204 1.90298261 1.92642191 2.09368292 1.91520759
  2.09436727 1.90535912 1.92563079 2.09130569 1.91052784 2.09360126
  1.90581832 2.09295146 1.9112017  2.09170961 1.90077258 2.09102162
  1.90722524 2.09387188 1.96406021 2.09152173 1.93390572 2.0916956
  1.9631122  2.09132062 1.93057424 2.08627448 1.99802709 2.08050325
  2.00171176 2.06372898 1.93002429 1.91665815 1.88844243 1.92870496
  1.90477542 1.98735204 1.92516239 1.89855513 1.95202909 1.92563722
  1.97444998 1.92186974 1.89840346 1.92525958 1.9704094  1.92182609
  1.94672187 1.9249491  1.96876731 1.92281886 1.9117925  1.92628839
  1.92338789 1.91882258 1.90930765 1.92586469 1.92243377 1.90584684
  1.92656571 1.90551957 1.92081319 2.08442504 1.90044603 1.92409186
  2.0823199  1.91061046 2.08313407 1.90301915 1.92426035 2.07969248
  1.90949204 2.08401774 1.90249235 2.08367412 1.90911667 2.08300142
  1.90118787 2.08326784 1.90739765 2.08216399 1.95961633 2.08141105
  1.93100193 2.08347891 1.96006901 2.08390113 1.92994935 2.0708037
  1.99458351 2.06913846 1.99929804 2.03391774 1.9294773  1.9157018
  1.89080852 1.92822693 1.90605366 1.98629172 1.92321179 1.901608
  1.95215137 1.92561793 1.97481156 1.92164851 1.90162584 1.92862937
  1.92533243 1.97079616 1.92196361 1.94763519 1.92512329 1.96925795
  1.92352918 1.91405437 1.92645812 1.92519331 1.91959695 1.9121041
  1.9260813  1.92492376 1.90861011 1.92667606 1.90823915 1.92103273
  2.07925264 1.90373417 1.92441587 2.07729064 1.91280579 2.07804175
  1.90566668 1.92447396 2.07468209 1.91174051 2.07845111 1.90493144
  2.07822202 1.91150961 2.07784111 1.9037868  2.0781462  1.90988403
  2.07726366 1.95933737 2.07659682 1.93242183 2.07867972 1.96012712
  2.07913774 1.93151662 2.06627411 1.99302427 2.06487474 1.99763748
  2.02960409 1.66198956 1.93029751 1.91726287 1.90925373 1.90399955]]
BARINEL SCORES

,u 184,u 191,p 188,p 185,u 187,cx 189,cx 186,u 190,x 4,p 180,...,cp 98,cp 23,cp 84,cp 82,cp 146,cp 150,cp 88,cp 144,cp 148,cp 86
sum,0.565527,0.558494,0.558456,0.554266,0.54502,0.53488,0.534652,0.533797,0.525128,0.517657,...,0.49828,0.498279,0.498259,0.498212,0.498197,0.498143,0.498097,0.498096,0.498013,0.497974

custom SCORES

,u 184,p 180,p 182,cp 130,p 176,cp 134,cp 160,cp 132,cp 142,p 178,...,u 125,x 4,u 63,u 60,u 122,h 0,p 185,cx 186,cx 189,u 190
sum,0.780515,0.76799,0.76746,0.763501,0.763023,0.761918,0.761318,0.760988,0.760186,0.760094,...,0.743343,0.743318,0.743189,0.740343,0.740274,0.739991,0.739746,0.737529,0.720276,0.695785

DSTAR SCORES

,cx 18,x 4,cx 22,cx 26,cx 10,cx 14,cx 37,cx 31,cx 39,cx 20,...,p 174,p 178,p 163,p 182,p 176,p 170,p 185,p 180,cp 130,p 168
sum,3926.310485,3366.413151,2753.33057,2722.884171,2323.116107,2036.341071,2003.109664,1923.191981,1896.863533,1826.280919,...,0.004299,0.002121,0.001947,0.001129,0.000797,0.000607,0.000534,0.000321,0.00025,0.000151

ERROR GATE LOCATION:
54
Now evolving the following mutant:  AddGate_y_inGap_76_.qasm

100%|██████████| 10/10 [02:51<00:00, 17.13s/it]
100%|██████████| 10/10 [02:34<00:00, 15.41s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.364259,0.628283,0.074472,0.022211,0.227276,0.041991,0.003426,0.091573,0.042184,0.008016,...,74.284630,11.673311,74.780281,1.355593,14.743642,53.057585,22.070500,21.123263,21.201615,fail
1,0.397453,0.533706,0.168292,0.038388,0.408572,0.083891,0.006449,0.181340,0.069697,0.012489,...,109.712444,13.193602,108.674183,1.728548,435.100468,96.738752,44.422604,45.832363,48.724622,fail
2,0.283969,0.581404,0.129944,0.023575,0.288884,0.075374,0.003804,0.167921,0.056306,0.008775,...,104.108950,13.254486,104.213233,1.654873,240.502675,75.415790,37.409832,41.008455,45.621665,fail
3,0.404166,0.474104,0.086033,0.033585,0.234417,0.057025,0.005752,0.194311,0.037943,0.007560,...,57.262661,8.079462,56.928771,0.997177,145.008017,50.405206,20.760084,19.535111,19.256109,fail
4,0.481458,0.490282,0.118500,0.042575,0.188070,0.109775,0.009352,0.223844,0.114266,0.020872,...,199.846482,26.339219,199.352535,3.286813,507.780230,159.144843,72.864901,75.233022,80.118693,fail
5,0.497310,0.529634,0.156219,0.051772,0.405453,0.103391,0.008184,0.299648,0.073146,0.011685,...,131.328004,17.471424,131.602429,2.146823,250.176934,94.877447,45.622697,48.969963,53.699394,fail
6,0.342544,0.329086,0.109395,0.039674,0.319868,0.069848,0.004674,0.159142,0.051561,0.008594,...,81.280745,9.631471,80.628679,1.262729,314.182553,69.266567,32.721066,34.513019,37.309022,fail
7,0.348727,0.587853,0.130673,0.034140,0.360231,0.058602,0.004528,0.054927,0.084305,0.014558,...,141.832269,16.716165,140.768493,2.192122,543.077428,119.348864,56.977366,60.576898,65.868866,fail
8,0.523669,0.571468,0.103295,0.032472,0.304655,0.042698,0.003609,0.096257,0.051378,0.006675,...,91.273885,10.385735,91.130597,1.353457,298.255094,66.538106,35.373378,40.486865,46.321777,fail
9,0.484091,0.644171,0.129401,0.035549,0.374759,0.067929,0.004024,0.152617,0.050826,0.007019,...,90.314262,10.751109,90.262697,1.376663,261.524697,65.677133,34.011496,38.318433,43.403814,fail
10,0.377805,0.420678,0.149113,0.041298,0.524367,0.043143,0.003850,0.206610,0.018725,0.001916,...,26.197185,2.913487,26.143246,0.383149,90.375545,19.120512,10.293370,11.867942,13.640400,pass
11,0.215943,0.275718,0.139867,0.034889,0.335860,0.073138,0.005439,0.105781,0.092078,0.016132,...,156.147357,19.231004,155.274817,2.472216,521.398270,128.714062,60.523912,63.683377,68.745569,pass
12,0.406877,0.453415,0.135231,0.033490,0.381988,0.060247,0.004256,0.211738,0.023323,0.002723,...,37.904263,4.215475,37.826219,0.554372,130.762843,27.665145,14.893303,17.171524,19.736063,pass
13,0.421549,0.477095,0.150048,0.038230,0.172641,0.132656,0.010503,0.299424,0.119496,0.021477,...,212.625546,27.626109,212.125818,3.461017,555.536847,167.735214,78.010501,81.525932,87.613288,pass
14,0.315429,0.466623,0.079195,0.024024,0.182383,0.056507,0.003948,0.176225,0.037807,0.005032,...,70.268804,7.814856,70.124123,1.027722,242.414650,51.287019,27.609944,31.833423,36.587693,pass
15,0.402093,0.425241,0.118278,0.043663,0.246359,0.096558,0.007565,0.143862,0.114929,0.020150,...,200.996642,26.199147,200.594997,3.275850,512.266683,157.602327,73.383568,76.771190,82.573109,pass
16,0.371523,0.615406,0.065204,0.035191,0.252845,0.034096,0.005401,0.214604,0.002970,0.000044,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,pass
17,0.316108,0.443205,0.087827,0.031865,0.207786,0.056864,0.005336,0.165456,0.041943,0.007431,...,64.681494,7.790092,64.059769,1.020541,257.185513,57.229985,26.205114,26.974890,28.626419,pass
18,0.402442,0.546069,0.109611,0.025616,0.292315,0.051444,0.003460,0.225133,0.003827,0.000043,...,0.316456,0.035194,0.315805,0.004628,1.091717,0.230972,0.124342,0.143362,0.164773,pass
19,0.358458,0.316082,0.161480,0.053483,0.441395,0.097012,0.007069,0.204873,0.092210,0.016294,...,150.936573,19.295810,150.197248,2.446831,457.810652,124.691722,57.132405,58.956619,62.731913,pass

[[1.2686869  1.19957629 1.39519725 1.4627221  1.31281351 1.54498712
  1.73818953 1.84787489 1.80910718 1.964535   1.83164609 1.95062633
  1.83003205 1.89683474 1.82636481 1.92460986 1.81925038 1.87261287
  1.8223491  1.8490199  1.80353244 1.84669315 1.81609374 1.82311826
  1.79584273 1.84729136 1.78748037 1.79347662 1.85073528 1.79725571
  1.85215275 1.94822159 1.7909853  1.8465316  1.93557358 1.80715861
  1.9327084  1.79495798 1.84357448 1.93138893 1.80104009 1.92720282
  1.79539623 1.92486698 1.80316866 1.92556768 1.78865784 1.92350795
  1.79406981 1.93774577 1.82804241 1.93457585 1.81769994 1.93053973
  1.82141091 1.9296874  1.80976579 1.94986926 1.85631458 1.94102974
  1.85354936 1.95740685 1.86099961 1.80927977 1.77487593 1.85581887
  1.76055144 1.82381393 1.84163863 1.73648168 1.79146987 1.8425062
  1.80217922 1.8273447  1.85568717 1.76119801 1.84108195 1.79920991
  1.82737117 1.78481568 1.83990774 1.79730169 1.83074836 1.78045632
  1.84534537 1.78258929 1.81598103 1.77779785 1.84370093 1.78173932
  1.7787275  1.84671894 1.78002935 1.82504079 1.91767883 1.77156931
  1.83675698 1.91545426 1.7869847  1.9170479  1.77554305 1.83818347
  1.91655625 1.79145873 1.91498523 1.77692519 1.91309327 1.7888463
  1.91568277 1.77723324 1.91544567 1.7877281  1.92023335 1.814338
  1.91984821 1.80499391 1.92077739 1.81262275 1.9211117  1.80268136
  1.92018417 1.84882839 1.91975689 1.84884005 1.8980533  1.86007432
  1.80588235 1.77159434 1.85489612 1.75977327 1.82187809 1.83458487
  1.73783017 1.78970996 1.84141377 1.8028692  1.82427388 1.76268578
  1.84026399 1.79994202 1.82571472 1.78549314 1.83942185 1.79843591
  1.83082432 1.78062739 1.84529819 1.78321554 1.81617374 1.77919538
  1.84375684 1.78345695 1.77996721 1.84680028 1.78127582 1.82502651
  1.91377542 1.77374585 1.83703666 1.91189123 1.78803765 1.91323686
  1.77705565 1.83872434 1.9128597  1.79237315 1.91171801 1.77852261
  1.91010864 1.79012366 1.91232244 1.77885802 1.91217615 1.78925556
  1.91632114 1.81480049 1.91600193 1.80586274 1.91706186 1.81326347
  1.91741514 1.80406072 1.91588635 1.84830085 1.91563556 1.84869507
  1.89389314 1.80403313 1.87125693 1.81150562 1.76770402 1.73595347]]
BARINEL SCORES

,u 190,cp 160,cp 155,cp 142,cp 157,cp 150,cp 148,cp 140,cp 138,cp 146,...,cx 64,cx 127,cx 179,x 4,u 187,cx 186,cx 189,p 188,p 185,u 184
sum,0.547426,0.546274,0.545922,0.545911,0.545894,0.545865,0.545823,0.545776,0.545773,0.545758,...,0.534595,0.534448,0.533083,0.520895,0.506036,0.503136,0.502159,0.494546,0.486326,0.453552

custom SCORES

,cp 160,cp 134,cp 130,cp 142,cp 157,cp 132,cp 140,cp 155,cp 152,cp 138,...,u 122,x 4,u 190,u 191,p 185,cx 186,cx 189,p 188,u 187,u 184
sum,0.812339,0.811467,0.810677,0.81037,0.810048,0.809759,0.809737,0.8097,0.809271,0.809182,...,0.767455,0.755823,0.711596,0.704628,0.697657,0.697471,0.677311,0.675392,0.672119,0.663079

DSTAR SCORES

,cx 18,cx 22,cx 26,x 4,cx 10,cx 14,cx 37,cx 31,cx 39,cx 20,...,p 174,p 178,p 163,p 182,p 176,p 170,p 180,p 185,cp 130,p 168
sum,4726.462443,3317.988928,3275.339679,3261.148078,2830.049473,2479.142717,2424.242598,2325.491266,2299.457623,2203.420633,...,0.004574,0.002213,0.002114,0.001119,0.000816,0.000658,0.000314,0.000288,0.000278,0.000166

ERROR GATE LOCATION:
117
Now evolving the following mutant:  AddGate_z_inGap_53_.qasm

100%|██████████| 10/10 [02:35<00:00, 15.54s/it]
100%|██████████| 10/10 [03:09<00:00, 18.92s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.503440,0.652811,0.108210,0.040420,0.378983,0.056491,0.004055,0.166475,0.050009,0.006821,...,88.123111,9.903174,87.857595,1.301679,309.867832,66.042852,34.761284,39.521327,45.014688,fail
1,0.522847,0.646439,0.093713,0.039167,0.228990,0.068777,0.006826,0.181575,0.056863,0.011702,...,87.808791,12.330841,87.251199,1.526066,230.871267,77.898612,32.072923,30.162995,29.713548,fail
2,0.567997,0.508878,0.098314,0.046781,0.187234,0.092748,0.010471,0.230647,0.090464,0.017841,...,152.583481,21.278807,152.182920,2.612895,336.081245,125.281574,54.024917,53.093095,54.369811,fail
3,0.495062,0.615611,0.079782,0.036303,0.286256,0.044420,0.005139,0.146109,0.039970,0.007391,...,68.225054,10.721091,68.680274,1.245014,13.540968,48.729550,20.270157,19.400187,19.472148,fail
4,0.521427,0.603373,0.112161,0.040725,0.342417,0.060212,0.006502,0.229660,0.035958,0.006318,...,58.561054,9.202461,58.951793,1.068659,11.622906,41.827066,17.398912,16.652173,16.713941,fail
5,0.428326,0.521491,0.135474,0.028666,0.219457,0.097985,0.007091,0.253913,0.069938,0.012284,...,118.189510,13.963834,117.275077,1.830975,454.499176,100.027979,47.524794,50.345710,54.599461,fail
6,0.403911,0.390041,0.111340,0.047184,0.439310,0.041885,0.005524,0.108413,0.052927,0.010194,...,77.486294,9.777754,76.596398,1.268202,305.681192,72.310672,31.240380,30.627020,31.249686,fail
7,0.572917,0.508947,0.086368,0.038071,0.231138,0.058558,0.006104,0.192918,0.043170,0.008874,...,58.601185,7.509328,57.668161,0.981016,258.775880,59.434231,24.340022,22.677758,22.111916,fail
8,0.480295,0.713660,0.100997,0.020809,0.207355,0.063052,0.002596,0.116553,0.050509,0.006992,...,92.764086,10.808353,92.666564,1.395516,285.210885,67.538382,35.423021,40.218583,45.781798,fail
9,0.406527,0.610686,0.105770,0.031397,0.384801,0.034607,0.001742,0.117402,0.019047,0.002041,...,28.231016,3.139677,28.172890,0.412895,97.391894,20.604943,11.092501,12.789315,14.699379,fail
10,0.447437,0.316606,0.106698,0.041599,0.217552,0.086433,0.007872,0.211666,0.084470,0.014252,...,146.265024,17.941243,145.642580,2.300497,467.098625,117.048282,56.139491,59.967055,65.458889,pass
11,0.480619,0.401353,0.153368,0.049610,0.363951,0.095036,0.008763,0.298815,0.059954,0.011703,...,89.177583,12.608060,88.678519,1.554230,221.982452,78.216780,32.222941,30.332598,29.910614,pass
12,0.516636,0.382565,0.117514,0.042945,0.378317,0.059426,0.004463,0.195029,0.039624,0.004994,...,65.889087,7.384244,65.707181,0.970721,230.528020,49.038926,25.963898,29.629015,33.829055,pass
13,0.322256,0.402791,0.056350,0.023549,0.188934,0.037451,0.002719,0.151345,0.009618,0.001664,...,11.118494,1.466380,10.973899,0.188294,43.044701,10.846004,4.448356,4.155383,4.063398,pass
14,0.516565,0.609860,0.105289,0.036999,0.342990,0.047743,0.004524,0.129072,0.045595,0.009375,...,61.856807,7.926513,60.871947,1.035517,273.152317,62.736133,25.692245,23.937634,23.340355,pass
15,0.576778,0.443819,0.149001,0.054723,0.382837,0.096271,0.009411,0.244749,0.095194,0.015332,...,172.800005,22.988715,173.161091,2.824767,329.180176,124.838746,60.029864,64.434162,70.657097,pass
16,0.532784,0.409179,0.096986,0.047180,0.279480,0.065450,0.007768,0.170280,0.072618,0.014661,...,113.497511,16.220875,112.996974,1.987218,257.314178,97.764850,40.303657,37.987136,37.510579,pass
17,0.418368,0.559145,0.077805,0.030414,0.196704,0.053453,0.006027,0.100248,0.061330,0.012278,...,98.236951,13.336258,97.628548,1.666410,277.772169,85.562297,36.492306,35.453979,35.933895,pass
18,0.448704,0.428755,0.130528,0.046125,0.415883,0.076337,0.004872,0.105209,0.094581,0.015365,...,172.800005,22.988715,173.161091,2.824767,329.180176,124.838746,60.029864,64.434162,70.657097,pass
19,0.444181,0.467434,0.108590,0.037397,0.349509,0.058985,0.004458,0.156231,0.040541,0.007458,...,68.450335,10.738360,68.892931,1.248182,16.222563,49.078008,20.411019,19.528415,19.593917,pass

[[1.16856345 1.23643016 1.312571   1.27688175 1.51176447 1.58363487
  1.86819235 1.45620524 1.77779038 1.97229809 1.81233269 1.95717148
  1.80706892 1.88167421 1.8084858  1.91980382 1.77822968 1.84712271
  1.79292895 1.8117439  1.74212049 1.80897524 1.76790796 1.77466405
  1.72723496 1.80884168 1.71758888 1.72312367 1.81398205 1.72834593
  1.81600801 2.01542359 1.71674764 1.80751771 1.99664157 1.74596988
  1.99329344 1.72373065 1.80302929 1.99027071 1.73492075 1.98581401
  1.72457589 1.98252608 1.73838439 1.98289705 1.71233714 1.9799468
  1.7230793  1.99950073 1.79620518 1.99445869 1.76898827 1.98933613
  1.78606703 1.98807585 1.75589694 2.01163052 1.85048808 1.99804506
  1.8480636  2.01135829 1.82908401 1.74966315 1.68623817 1.82138053
  1.6697762  1.79919542 1.80005188 1.64157613 1.73646324 1.8014741
  1.76157958 1.77825122 1.66841646 1.79930296 1.75546897 1.7782719
  1.72408761 1.79751026 1.75190239 1.78354789 1.70390784 1.80574825
  1.71168096 1.76044083 1.69880868 1.80325559 1.70999116 1.69893112
  1.80779466 1.70083154 1.77448547 1.9695555  1.68565305 1.79267621
  1.96575528 1.71355723 1.96819042 1.69287363 1.7947777  1.96611492
  1.7199836  1.96584079 1.69483216 1.96319958 1.71583842 1.81958681
  1.96633895 1.69481215 1.96613703 1.71345445 1.97196424 1.77417454
  1.97114697 1.74891707 1.97322303 1.77178682 1.97383575 1.74502
  1.96716238 1.83846719 1.96590909 1.8403822  1.92256824 1.82758247
  1.74421841 1.6820111  1.81990229 1.66900551 1.79590412 1.78921435
  1.63665472 1.73378388 1.79991978 1.76277433 1.77370754 1.67201004
  1.79817262 1.7567417  1.77592726 1.72549403 1.79689122 1.75383606
  1.78394496 1.70504306 1.80575147 1.71334851 1.76103377 1.70206264
  1.80342332 1.71362048 1.70192352 1.80795434 1.70381507 1.7745532
  1.96226956 1.69032994 1.79320714 1.95896662 1.71602803 1.96105651
  1.69625342 1.79563448 1.95916508 1.72225612 1.959218   1.6982602
  1.95699031 1.71872647 1.95976501 1.69834272 1.95969794 1.71676422
  1.9647966  1.77475525 1.96409984 1.75078125 1.96635832 1.77276894
  1.96701256 1.74771463 1.95965008 1.83708565 1.95873746 1.83950673
  1.91520264 1.97304382 1.84320049 1.75320811 1.68288707 1.63605471]]
BARINEL SCORES

,u 190,u 191,u 184,x 4,cx 189,u 187,p 185,cx 186,p 188,cx 127,...,cp 136,cp 138,cp 144,cp 146,cp 142,cp 157,cp 148,cp 150,cp 155,cp 160
sum,0.56624,0.510327,0.497294,0.485057,0.483601,0.482546,0.479348,0.47767,0.473709,0.462329,...,0.446533,0.446512,0.446488,0.446459,0.44642,0.446412,0.446352,0.446327,0.446324,0.446052

custom SCORES

,u 190,x 4,p 185,p 182,p 180,p 176,u 184,cp 130,p 178,cp 134,...,h 1,cx 54,cx 117,u 125,u 62,u 122,u 59,h 0,cx 189,p 188
sum,0.741269,0.724316,0.703226,0.68371,0.680993,0.678381,0.678334,0.674752,0.674406,0.672008,...,0.654005,0.653687,0.653678,0.652987,0.65272,0.650232,0.649281,0.648872,0.642291,0.624926

DSTAR SCORES

,cx 18,x 4,cx 22,cx 26,cx 10,cx 14,cx 37,cx 31,cx 39,cx 20,...,p 174,p 178,p 163,p 182,p 176,p 170,p 185,p 180,cp 130,p 168
sum,2638.371607,2161.011889,1850.680009,1830.050477,1567.397029,1374.0293,1346.06492,1293.173481,1274.864359,1226.141139,...,0.002924,0.001464,0.001309,0.00081,0.000558,0.000407,0.000312,0.00023,0.000185,0.0001

ERROR GATE LOCATION:
84
Now evolving the following mutant:  AddGate_x_inGap_26_.qasm

100%|██████████| 10/10 [03:08<00:00, 18.84s/it]
100%|██████████| 10/10 [02:34<00:00, 15.41s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.505236,0.583711,0.117110,0.047036,0.288499,0.094442,0.006985,0.200603,0.083166,0.013335,...,151.336987,20.012676,151.630283,2.464392,296.836142,109.373910,52.825453,56.874126,62.499120,fail
1,0.499451,0.577418,0.136645,0.045173,0.302002,0.096399,0.008155,0.197793,0.101352,0.017706,...,175.581453,22.347078,174.997991,2.825028,502.153429,140.066921,65.669308,69.014802,74.463310,fail
2,0.646477,0.563038,0.098934,0.052713,0.352209,0.058942,0.007789,0.170018,0.059850,0.011531,...,94.129900,13.880295,94.047769,1.670338,151.248429,76.660937,31.683416,29.992320,29.754937,fail
3,0.392037,0.605202,0.105050,0.016001,0.170654,0.059024,0.003832,0.085187,0.065404,0.010703,...,116.460446,13.464945,115.800630,1.767384,431.038468,93.616367,46.439171,50.758392,56.295346,fail
4,0.461925,0.579579,0.120128,0.041620,0.296084,0.083409,0.008138,0.208068,0.079295,0.013098,...,147.059178,19.611757,147.375508,2.407729,276.781061,106.226217,50.988515,54.661367,59.888415,fail
5,0.428310,0.650733,0.118514,0.031121,0.123759,0.105683,0.007312,0.240130,0.090009,0.015738,...,153.078781,18.483476,152.090046,2.397356,545.309580,127.381653,60.318786,63.774908,69.078739,fail
6,0.540306,0.423063,0.131941,0.054569,0.502105,0.056278,0.005618,0.185996,0.047294,0.006017,...,80.700892,9.240435,80.585183,1.201232,259.616683,58.810811,31.155294,35.584816,40.660057,fail
7,0.463984,0.504045,0.085420,0.048799,0.266163,0.067530,0.007475,0.248898,0.041260,0.007338,...,67.825097,10.658241,68.277648,1.237715,13.461586,48.443882,20.151326,19.286457,19.357996,fail
8,0.591737,0.515719,0.126547,0.057512,0.318578,0.094612,0.010668,0.269216,0.078932,0.015843,...,124.382527,17.931379,123.954619,2.185855,259.474581,105.539442,43.537674,41.082354,40.617277,fail
9,0.466707,0.515254,0.120588,0.039305,0.243054,0.091356,0.007128,0.177874,0.095679,0.016848,...,168.026653,22.200874,167.815334,2.759026,398.494148,130.501225,60.493641,63.094611,67.719583,fail
10,0.549124,0.524566,0.094792,0.036724,0.246800,0.069061,0.005584,0.155886,0.067883,0.010773,...,118.931430,13.704813,118.295137,1.799158,437.569145,94.833024,47.363773,52.014098,57.877797,pass
11,0.367667,0.526404,0.110897,0.037004,0.332161,0.071828,0.003521,0.148271,0.055941,0.008467,...,99.648002,12.748256,99.759547,1.588832,225.829006,72.163321,35.678134,39.024673,43.350726,pass
12,0.445672,0.549959,0.062586,0.028900,0.222682,0.028048,0.003561,0.005987,0.052889,0.011207,...,74.228168,9.511816,73.046337,1.242621,327.782781,75.283359,30.830694,28.725161,28.008426,pass
13,0.573834,0.703160,0.056913,0.032533,0.238557,0.028704,0.003027,0.150849,0.004457,0.000022,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,pass
14,0.339241,0.417021,0.104822,0.039194,0.132240,0.100189,0.009684,0.194675,0.114532,0.021702,...,197.170152,26.691082,196.668694,3.305135,469.865173,159.288804,70.919862,71.604453,74.945531,pass
15,0.347407,0.501451,0.078159,0.015097,0.115965,0.052931,0.003849,0.000486,0.089010,0.015575,...,159.604710,19.609357,158.923398,2.513191,508.478437,127.850961,61.220684,65.317426,71.238781,pass
16,0.583666,0.435118,0.129663,0.056358,0.388179,0.078789,0.008159,0.269345,0.045691,0.008989,...,60.510223,7.894292,59.656138,1.020272,246.797525,59.918831,24.560751,22.919896,22.387449,pass
17,0.358992,0.496561,0.083509,0.026120,0.229988,0.048398,0.004456,0.193461,0.022249,0.003538,...,33.759472,3.991514,33.495896,0.523360,129.988232,28.620634,13.578759,14.369340,15.571108,pass
18,0.374361,0.601916,0.093620,0.029355,0.307553,0.045741,0.003103,0.123509,0.032643,0.005901,...,54.439910,8.554852,54.803151,0.993454,10.804961,38.883550,16.174491,15.480302,15.537723,pass
19,0.473078,0.450782,0.100212,0.038664,0.377331,0.044519,0.003905,0.177261,0.021643,0.003977,...,28.294388,3.870577,28.034659,0.486397,89.336676,26.163944,10.753745,10.082988,9.900213,pass

[[1.29394565 1.17934254 1.17708507 1.32563222 1.7537079  1.30848375
  1.45929889 1.35708593 1.36548963 1.38160892 1.36507061 1.3726188
  1.38225803 1.39639597 1.36648154 1.39159449 1.39773863 1.40230504
  1.38448443 1.40821156 1.41660751 1.40731158 1.40603465 1.41149424
  1.42256505 1.40908932 1.41843097 1.42331741 1.40845841 1.42378148
  1.40818587 1.32679253 1.42734048 1.40948315 1.32584109 1.41901133
  1.32575754 1.42563118 1.41019319 1.3254849  1.42221928 1.32548871
  1.4253494  1.32533978 1.42166328 1.3252838  1.42879649 1.32513811
  1.42467196 1.32594382 1.39022575 1.32563267 1.40762531 1.32548259
  1.39131599 1.32542251 1.41013146 1.3258561  1.36996614 1.32505569
  1.36832181 1.32818981 1.40637553 1.41806016 1.43713259 1.40753306
  1.4286905  1.37834248 1.41066424 1.43415048 1.39982376 1.41032535
  1.38696517 1.41366427 1.43232479 1.41065242 1.38934858 1.41368714
  1.40326122 1.41092159 1.3903807  1.41285543 1.42310512 1.40973142
  1.41635352 1.41629652 1.42473813 1.41010196 1.41695907 1.42665866
  1.40946562 1.42674682 1.41444861 1.32440709 1.43034001 1.41165774
  1.324155   1.42327215 1.32428256 1.42854075 1.4114498  1.32446854
  1.4235674  1.32426567 1.42873957 1.32416186 1.42398674 1.32421653
  1.42947344 1.3242272  1.42506526 1.32433848 1.39379951 1.32426499
  1.41027596 1.32446143 1.39370142 1.32450739 1.41105204 1.32828799
  1.37239992 1.32911429 1.36997525 1.34813715 1.4067596  1.41887388
  1.43597996 1.40787779 1.42801672 1.37906248 1.41233045 1.43228828
  1.39990634 1.410422   1.38671529 1.41403138 1.43034159 1.41067499
  1.38908113 1.41373844 1.40270797 1.41086031 1.39002327 1.41244409
  1.42179891 1.40963834 1.41528827 1.41583861 1.40765947 1.42302583
  1.40997405 1.41542019 1.42496965 1.40939633 1.42508117 1.4143242
  1.32493884 1.42826569 1.4114509  1.32603281 1.42193022 1.3255542
  1.42689238 1.41128548 1.32715948 1.42220234 1.32550856 1.42720349
  1.32576906 1.42251056 1.325735   1.42784005 1.3256068  1.42351295
  1.32562312 1.39391049 1.32596498 1.4094115  1.32489197 1.39361589
  1.32464486 1.41006322 1.330834   1.3732515  1.33152145 1.37083986
  1.35065039 1.73974963 1.40541761 1.41753964 1.42555999 1.43106539]]
BARINEL SCORES

,cp 148,cp 144,cp 150,cp 86,cp 146,cp 88,cp 82,cp 98,cp 84,cp 155,...,p 182,cx 186,p 180,u 184,x 4,p 188,cx 189,u 191,u 187,u 190
sum,0.615133,0.614975,0.614972,0.614965,0.614851,0.614806,0.614632,0.614566,0.614562,0.614486,...,0.587052,0.587022,0.585545,0.582864,0.561636,0.560675,0.559176,0.530987,0.524901,0.514491

custom SCORES

,h 0,u 60,u 122,cx 119,cx 111,cx 57,cx 115,cx 49,cx 53,cx 51,...,p 176,p 182,p 180,u 184,cx 186,u 187,p 188,cx 189,u 191,u 190
sum,0.822314,0.821546,0.821295,0.821243,0.821241,0.821174,0.82115,0.82111,0.821076,0.820047,...,0.795375,0.789821,0.786477,0.780613,0.77905,0.755032,0.746488,0.723725,0.702754,0.666181

DSTAR SCORES

,cx 18,cx 22,cx 26,cx 10,x 4,cx 14,cx 37,cx 31,cx 39,cx 20,...,p 174,p 178,p 163,p 182,p 176,p 170,p 185,p 180,cp 130,p 168
sum,7017.672139,4930.735902,4865.119653,4254.694219,3999.488716,3727.567739,3601.612336,3460.590778,3418.35901,3264.03906,...,0.006311,0.003096,0.002874,0.001628,0.001158,0.000894,0.000532,0.000457,0.000422,0.000223

ERROR GATE LOCATION:
43
Now evolving the following mutant:  AddGate_p_inGap_105_.qasm

100%|██████████| 10/10 [02:18<00:00, 13.88s/it]
100%|██████████| 10/10 [02:36<00:00, 15.66s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.458849,0.331702,0.138876,0.044161,0.445315,0.065142,0.004690,0.158957,0.050050,0.009824,...,61.147139,8.151591,60.476274,1.039765,220.679642,58.489597,24.016983,22.486023,22.026075,fail
1,0.424784,0.710338,0.063733,0.022209,0.112299,0.040817,0.005702,0.241468,0.003995,0.000432,...,2.538326,0.324540,2.499737,0.042451,11.161091,2.570923,1.053256,0.982166,0.957796,fail
2,0.491708,0.633721,0.092788,0.031750,0.310077,0.044965,0.004232,0.232103,0.003460,0.000028,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,fail
3,0.585578,0.515964,0.130942,0.054040,0.326034,0.102835,0.008229,0.227529,0.097980,0.017461,...,148.545323,19.512555,148.233413,2.437967,380.809654,118.354630,54.259816,56.073602,59.723333,fail
4,0.491437,0.490797,0.125501,0.043142,0.111589,0.130453,0.011614,0.323587,0.114087,0.020862,...,177.843086,23.419436,177.491170,2.922936,450.520730,141.507095,64.805368,66.920963,71.237607,fail
5,0.360781,0.555962,0.111503,0.039777,0.271632,0.080011,0.005945,0.245442,0.042967,0.008893,...,52.261184,6.681902,51.466695,0.874017,229.793933,52.932337,21.685325,20.221660,19.719921,fail
6,0.381481,0.458054,0.134023,0.036481,0.275375,0.090293,0.007264,0.204777,0.088253,0.014567,...,145.979269,19.413573,146.346927,2.384913,277.268566,105.372084,50.684847,54.402482,59.627443,fail
7,0.640263,0.631252,0.115478,0.050838,0.380368,0.061637,0.006788,0.177482,0.057903,0.011549,...,76.073661,10.561610,75.564893,1.315168,213.856028,68.430959,28.172401,26.496421,26.084290,fail
8,0.450954,0.560013,0.137573,0.034813,0.253953,0.086126,0.007249,0.276116,0.061476,0.009026,...,96.750175,11.003633,96.382961,1.445436,346.285058,74.616183,38.317234,42.843463,48.233284,fail
9,0.499666,0.529090,0.063127,0.033241,0.319051,0.015085,0.002339,0.093567,0.004531,0.000027,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,fail
10,0.348056,0.438141,0.109259,0.026673,0.236082,0.068735,0.004439,0.160873,0.051643,0.009328,...,73.994581,8.859312,73.355360,1.161524,290.534314,64.657544,29.898779,31.010731,33.081002,pass
11,0.486838,0.486275,0.106788,0.038513,0.325831,0.048123,0.006640,0.101435,0.065513,0.013355,...,90.536415,12.761717,90.079980,1.575076,226.750723,79.457133,32.747429,30.857434,30.440180,pass
12,0.434414,0.494652,0.094176,0.033425,0.303096,0.042612,0.004101,0.120718,0.039142,0.008057,...,47.283929,6.045531,46.565105,0.790778,207.908797,47.891162,19.620056,18.295788,17.841833,pass
13,0.590989,0.337898,0.181192,0.064419,0.452784,0.117751,0.011046,0.297057,0.108602,0.017526,...,173.396362,22.740463,173.655192,2.813130,366.550126,127.249529,61.263663,65.762981,72.068096,pass
14,0.566204,0.509853,0.094016,0.053729,0.322315,0.073015,0.006286,0.031246,0.117340,0.021045,...,179.213087,23.421113,178.792619,2.932824,470.507682,143.181007,65.782577,68.085636,72.597522,pass
15,0.403155,0.408822,0.100646,0.032825,0.233699,0.079632,0.005013,0.156775,0.072579,0.012493,...,116.212626,16.160323,116.586505,1.956901,178.383205,84.676609,39.072845,40.697958,43.653425,pass
16,0.406560,0.534135,0.056914,0.019335,0.154218,0.032585,0.002144,0.065811,0.034128,0.005389,...,49.750979,5.797830,49.449458,0.760900,186.146963,40.756217,19.890230,21.478847,23.605198,pass
17,0.308290,0.298872,0.083055,0.034252,0.183224,0.056378,0.007487,0.239801,0.033587,0.006980,...,41.116935,5.257044,40.491863,0.687641,180.792347,41.644970,17.061115,15.909564,15.514817,pass
18,0.300842,0.422315,0.075540,0.023135,0.301930,0.022961,0.001201,0.088295,0.007171,0.000953,...,5.364560,0.685891,5.283007,0.089717,23.588126,5.433453,2.225978,2.075734,2.024231,pass
19,0.356082,0.449193,0.096276,0.035899,0.250677,0.064804,0.006586,0.337909,0.003212,0.000044,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,pass

[[1.33792291 1.31133859 1.24715347 1.3840336  1.58718293 1.81850686
  1.81317203 1.4836436  2.17432305 2.25122942 2.26061304 2.21183036
  2.22348122 2.2650153  2.27354642 2.26428654 2.310271   2.27390652
  2.32176615 2.27989365 2.29347725 2.2769172  2.30364653 2.28101573
  2.28071778 2.29268776 2.28239752 2.30234336 2.29211116 2.28103001
  2.28905422 2.2811121  2.37717459 2.28728164 2.28137419 2.37667522
  2.29089453 2.37861963 2.28835646 2.28228936 2.3767738  2.28882043
  2.38109012 2.28777735 2.38175382 2.28971596 2.37948786 2.28629843
  2.37987239 2.28967597 2.37675323 2.32181483 2.3764164  2.30082215
  2.37869772 2.32317101 2.37871759 2.30139841 2.36500357 2.33705615
  2.36457277 2.34111065 2.34502223 2.27833659 2.29031594 2.28303593
  2.27951483 2.3041154  2.34366564 2.28290199 2.31017272 2.32950572
  2.28296923 2.34315728 2.28669892 2.29827625 2.28327535 2.34132092
  2.28661667 2.32820603 2.28352878 2.34082626 2.2858921  2.3003482
  2.28222078 2.30933292 2.28941754 2.29951067 2.28260134 2.30891099
  2.29606558 2.28181463 2.29508995 2.28678073 2.37825033 2.29488929
  2.28418843 2.37755635 2.2960721  2.37755308 2.29510661 2.28365817
  2.37507895 2.29301478 2.37890461 2.29389618 2.37947827 2.29394221
  2.37794745 2.29262802 2.37826218 2.29296817 2.37543517 2.32464586
  2.37502936 2.30497798 2.37624564 2.32597931 2.37643255 2.30515726
  2.36654531 2.33757587 2.36550988 2.34143746 2.34694067 2.278286
  2.29129029 2.2865397  2.27952046 2.30536762 2.34358345 2.28440663
  2.31274687 2.33045229 2.28341711 2.34322975 2.28790055 2.30034006
  2.28369132 2.34129619 2.28749529 2.32869113 2.28389204 2.34073652
  2.28646956 2.30224123 2.28237125 2.31059933 2.28994245 2.30123391
  2.28274355 2.31024687 2.29781742 2.28185751 2.29686695 2.28696923
  2.37592412 2.29667516 2.28434597 2.37521324 2.29746595 2.37524682
  2.29666093 2.28359918 2.37277467 2.29451192 2.3760492  2.29524163
  2.37658456 2.29538581 2.37541939 2.29410681 2.37572382 2.29438925
  2.37330266 2.32422687 2.37293069 2.30578517 2.3740949  2.32573698
  2.37430255 2.30586736 2.36490314 2.33654144 2.36395584 2.34014563
  2.34535617 2.11474878 2.27403264 2.28998095 2.30422838 2.31584361]]
BARINEL SCORES

,u 184,u 190,cx 186,p 185,u 191,cx 189,p 188,u 187,x 4,cx 177,...,cp 137,cp 151,cp 154,cp 139,cp 131,cp 156,cp 141,cp 133,cp 129,cp 159
sum,0.576847,0.552911,0.541833,0.538274,0.532495,0.527395,0.518765,0.503756,0.499908,0.49921,...,0.492987,0.492983,0.492944,0.492929,0.492915,0.492914,0.49286,0.49283,0.492795,0.492691

custom SCORES

,u 184,cx 186,cp 85,cp 147,cp 87,cp 81,cp 23,cp 83,cp 149,cp 143,...,p 176,p 182,p 180,cx 183,x 4,u 190,u 191,u 187,p 188,cx 189
sum,0.790806,0.788164,0.786723,0.786664,0.786607,0.786526,0.786496,0.786486,0.78648,0.786476,...,0.773729,0.771008,0.766814,0.765796,0.764202,0.734174,0.710605,0.703644,0.698262,0.69183

DSTAR SCORES

,cx 18,x 4,cx 22,cx 26,cx 10,cx 14,cx 37,cx 31,cx 39,cx 20,...,p 178,p 167,p 162,p 165,p 182,p 176,p 170,p 185,p 180,cp 129
sum,2797.747626,2119.641469,1963.353164,1939.595328,1670.571265,1463.896469,1427.205149,1372.10559,1351.871018,1299.309355,...,0.001551,0.001485,0.001292,0.00129,0.000851,0.000589,0.000434,0.000408,0.000242,0.000157

ERROR GATE LOCATION:
168
Now evolving the following mutant:  AddGate_y_inGap_88_.qasm

100%|██████████| 10/10 [02:31<00:00, 15.15s/it]
100%|██████████| 10/10 [02:59<00:00, 17.91s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.528802,0.443241,0.157062,0.055821,0.463922,0.088842,0.007493,0.228641,0.086144,0.014606,...,141.832269,16.716165,140.768493,2.192122,543.077428,119.348864,56.977366,60.576898,65.868866,fail
1,0.477975,0.512291,0.101522,0.038853,0.265380,0.076446,0.005745,0.305592,0.019209,0.002181,...,29.975599,3.333698,29.913881,0.438410,103.410390,21.878260,11.777981,13.579653,15.607752,fail
2,0.502818,0.484455,0.108597,0.044089,0.344969,0.058556,0.006162,0.199514,0.041852,0.008461,...,55.671126,7.133862,54.784753,0.931966,245.837086,56.462519,23.123020,21.543870,21.006320,fail
3,0.591173,0.550926,0.147766,0.052636,0.336292,0.105788,0.008096,0.293107,0.081065,0.013797,...,131.027291,15.514503,129.985763,2.034093,505.802212,111.462646,52.731886,55.681989,60.242910,fail
4,0.564152,0.477318,0.066897,0.040236,0.412719,0.013774,0.000958,0.032449,0.016353,0.001647,...,22.116550,2.459664,22.071013,0.323467,76.298094,16.142184,8.690012,10.019318,11.515687,fail
5,0.510809,0.368198,0.149328,0.056090,0.420234,0.098051,0.007683,0.279188,0.071562,0.012115,...,115.067340,13.616606,114.159335,1.785312,443.728255,97.749204,46.298034,48.931293,52.973804,fail
6,0.436256,0.473444,0.103736,0.034094,0.332616,0.045106,0.004445,0.102290,0.050558,0.010194,...,74.932167,10.371183,74.338374,1.294404,219.035431,68.041457,27.986998,26.275624,25.836163,fail
7,0.442109,0.540626,0.112085,0.031180,0.281337,0.072628,0.004716,0.155944,0.058220,0.010695,...,101.034106,14.561765,101.246135,1.749680,140.023187,76.213113,33.478327,33.510851,34.869171,fail
8,0.365455,0.512983,0.160295,0.045400,0.241984,0.129875,0.011188,0.357075,0.099932,0.017745,...,173.369552,22.361390,172.841389,2.813154,475.935904,138.342573,64.252931,67.057114,71.982384,fail
9,0.441795,0.479807,0.115075,0.043624,0.451796,0.036517,0.004867,0.220981,0.005043,0.000058,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,fail
10,0.385274,0.513146,0.096773,0.024022,0.264814,0.042579,0.003769,0.119366,0.042305,0.005578,...,78.328312,8.711184,78.167037,1.145597,270.218493,57.169404,30.776678,35.484570,40.784133,pass
11,0.445230,0.382334,0.143703,0.045351,0.196650,0.138772,0.010695,0.293470,0.123566,0.022657,...,216.924007,28.516307,216.361269,3.562444,557.981262,172.982924,79.287664,81.929667,87.300838,pass
12,0.335532,0.404899,0.124972,0.038505,0.229931,0.094921,0.007932,0.211460,0.082379,0.016813,...,133.669988,19.390839,133.304048,2.355338,261.317910,112.172984,46.297046,43.723296,43.268016,pass
13,0.445051,0.580697,0.089359,0.022539,0.152321,0.067144,0.005607,0.150664,0.069428,0.011966,...,129.897882,17.858269,130.279028,2.168969,206.599293,93.647972,43.922001,46.317376,50.158428,pass
14,0.449903,0.477365,0.111715,0.035786,0.191500,0.094995,0.007194,0.198539,0.087992,0.014572,...,164.160004,21.839279,164.503036,2.683529,312.721167,118.596808,57.028371,61.212454,67.124242,pass
15,0.484218,0.480502,0.100379,0.043184,0.211361,0.090953,0.007200,0.243096,0.069827,0.012346,...,113.363314,13.505146,112.394905,1.770140,442.303652,97.816453,45.731909,47.854860,51.425627,pass
16,0.191071,0.370856,0.065497,0.013146,0.181391,0.023856,0.002156,0.010581,0.039791,0.007300,...,65.717352,7.864307,65.127056,1.030570,258.420155,57.297610,26.557814,27.604041,29.512835,pass
17,0.492746,0.491413,0.079334,0.044016,0.245451,0.062999,0.006833,0.069703,0.086897,0.017728,...,140.705250,20.411409,140.320051,2.479303,275.071484,118.076825,48.733733,46.024523,45.545280,pass
18,0.435286,0.303612,0.146505,0.055666,0.431598,0.083797,0.008260,0.200077,0.091856,0.016717,...,155.559669,21.462937,155.445361,2.630221,316.156776,122.063732,54.417819,55.053265,57.733753,pass
19,0.537602,0.429073,0.117772,0.050902,0.533077,0.034052,0.004080,0.064866,0.047556,0.008479,...,77.998862,12.256977,78.519296,1.423373,15.480824,55.710464,23.174025,22.179426,22.261696,pass

[[1.21607013 1.13750303 1.31135201 1.26893008 1.30636395 1.78993626
  1.82359407 1.64188821 1.88573276 1.93933106 1.99369126 1.90670182
  1.94078113 1.95398923 2.00880571 1.95315003 2.00942901 1.96292536
  2.03259627 1.96733533 1.9804355  1.96580372 1.99647672 1.97059543
  1.97447762 1.96771361 1.99011154 1.97513448 1.96748902 1.97144867
  1.96709797 2.13654062 1.9681048  1.96823115 2.13506307 1.97485763
  2.13754834 1.96893989 1.96884965 2.13416747 1.97220071 2.13942502
  1.96933014 2.13988765 1.97190945 2.13785347 1.96657638 2.1380704
  1.97177846 2.13415052 2.02550989 2.13275278 1.99277543 1.96582635
  2.13514521 2.02792265 2.13512741 1.99282181 2.11787087 2.05373546
  2.1150227  2.05997361 2.08496247 1.96535395 1.9755132  1.95849187
  1.96634558 1.98706886 2.05779364 1.96920203 1.99275034 2.03028327
  1.96934708 2.05321773 1.97251625 1.97859795 1.96961097 2.04966044
  1.97244768 2.02719041 1.96983024 2.04861243 1.97192562 1.98495774
  1.96869671 1.99853298 1.9746761  1.98326534 1.96901488 1.99778702
  1.9783671  1.96833628 1.97724028 1.97239955 2.13257808 1.97545414
  1.97039128 2.13102725 1.97988889 2.13123008 1.97653103 1.96986227
  2.12699632 1.97604677 2.13350417 1.97510673 2.13408142 1.97698796
  2.13179538 1.97328791 2.13227257 1.97542255 2.12824286 2.02732864
  2.12746678 1.99594349 2.12966785 2.02885266 2.13003954 1.99586273
  2.11346881 2.05336557 2.11153352 2.05942854 2.07754037 1.96514318
  1.97612207 1.96325711 1.96622084 1.98913505 2.05749994 1.97041881
  1.99589531 2.03142973 1.96988713 2.0532967  1.97384991 1.98186703
  1.9701249  2.04974781 1.97348848 2.02798508 1.97029938 2.04860672
  1.97277563 1.98773609 1.96893279 2.00048892 1.97554737 1.9860468
  1.96925645 2.00001135 1.98118932 1.96843212 1.98000248 1.97268232
  2.12792417 1.97842432 1.97065129 2.12637927 1.98209447 2.12663274
  1.97905545 1.96984907 2.12244894 1.97839211 2.12799035 1.97731999
  2.12856374 1.9793198  2.12686534 1.97568758 2.1273434  1.97773575
  2.12395171 2.0267172  2.12325349 1.99727436 2.12540102 2.02857434
  2.12580867 1.99710318 2.10987884 2.05164754 2.10819606 2.05736828
  2.07419805 1.97256897 1.96052395 1.9750895  1.98878308 2.00004926]]
BARINEL SCORES

,u 184,u 187,p 188,u 191,cx 189,u 190,cx 186,p 185,x 4,cx 126,...,cp 152,cp 146,cp 137,cp 140,cp 148,cp 150,cp 157,cp 142,cp 155,cp 160
sum,0.582021,0.573768,0.542266,0.536379,0.531839,0.522064,0.497093,0.490508,0.485614,0.423962,...,0.375922,0.375909,0.375851,0.375839,0.375654,0.375492,0.375377,0.375312,0.37526,0.373909

custom SCORES

,u 184,u 187,x 4,cx 186,p 188,p 185,cx 189,u 191,u 190,u 121,...,cp 135,cp 152,cp 137,cp 150,cp 133,cp 140,cp 155,cp 157,cp 142,cp 160
sum,0.820924,0.761156,0.72509,0.719535,0.714291,0.71413,0.706196,0.699448,0.670527,0.632584,...,0.576611,0.576492,0.576475,0.576326,0.576241,0.576232,0.575795,0.57574,0.575555,0.573626

DSTAR SCORES

,x 4,cx 18,cx 22,cx 26,cx 10,cx 37,cx 14,cx 31,cx 39,cx 20,...,p 174,p 178,p 163,p 182,p 176,p 170,p 185,p 180,cp 129,p 168
sum,2590.267201,2368.093073,1658.338918,1638.319212,1370.908629,1213.910344,1200.180562,1158.444611,1149.829704,1111.675586,...,0.003127,0.001545,0.00142,0.000826,0.000581,0.000444,0.000374,0.000235,0.000173,0.000111

ERROR GATE LOCATION:
138
Now evolving the following mutant:  AddGate_x_inGap_93_.qasm

100%|██████████| 10/10 [02:23<00:00, 14.37s/it]
100%|██████████| 10/10 [02:45<00:00, 16.55s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.382892,0.652823,0.083846,0.027105,0.174709,0.059773,0.005474,0.212480,0.023928,0.004763,...,31.522896,4.039437,31.021002,0.527711,139.201370,31.971011,13.093045,12.198877,11.894497,fail
1,0.555943,0.541206,0.121203,0.049999,0.351442,0.081100,0.006981,0.205839,0.068514,0.013616,...,108.858800,15.884675,108.633297,1.922991,199.278199,90.389265,37.324125,35.278214,34.941815,fail
2,0.436197,0.568474,0.101012,0.031040,0.242186,0.062168,0.005268,0.220599,0.043183,0.005588,...,78.328312,8.711184,78.167037,1.145597,270.218493,57.169404,30.776678,35.484570,40.784133,fail
3,0.312361,0.616656,0.077787,0.022450,0.177526,0.041582,0.004048,0.168614,0.026423,0.003728,...,45.879955,5.684146,45.896066,0.716905,117.101352,33.288515,16.813710,18.648631,20.909300,fail
4,0.401170,0.529609,0.112571,0.031175,0.321280,0.047145,0.004621,0.054844,0.071345,0.012862,...,117.758956,14.038882,116.744746,1.840036,460.028857,101.778500,47.518505,49.671120,53.334328,fail
5,0.470359,0.675365,0.061040,0.024214,0.126086,0.044894,0.005379,0.105173,0.045646,0.009315,...,74.070120,10.750727,73.871818,1.305455,143.967864,62.098636,25.631011,24.207921,23.957759,fail
6,0.523252,0.670870,0.106137,0.033647,0.160596,0.093755,0.007993,0.219299,0.096629,0.016170,...,182.400005,24.265866,182.781151,2.981699,347.467963,131.774231,63.364857,68.013837,74.582491,fail
7,0.432755,0.627498,0.081380,0.021783,0.255758,0.036128,0.002226,0.139151,0.002846,0.000033,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,fail
8,0.505095,0.626881,0.087381,0.031595,0.214301,0.062145,0.005020,0.118902,0.071366,0.011649,...,131.328004,17.471424,131.602429,2.146823,250.176934,94.877447,45.622697,48.969963,53.699394,fail
9,0.385361,0.604609,0.143225,0.037196,0.395557,0.081337,0.003720,0.194703,0.057179,0.008239,...,99.727971,11.320796,99.334563,1.487273,357.149846,76.646032,39.489332,44.283182,49.981701,fail
10,0.324541,0.277942,0.120103,0.043390,0.351071,0.071008,0.006806,0.214561,0.057060,0.010289,...,96.132569,13.898363,96.320587,1.669192,132.959309,72.873187,31.838446,31.722085,32.884413,pass
11,0.262248,0.204836,0.064560,0.027175,0.232736,0.038046,0.002782,0.099775,0.022758,0.004019,...,36.922060,5.802044,37.168416,0.673777,7.328106,26.371476,10.969811,10.499001,10.537945,pass
12,0.363990,0.449692,0.085705,0.033894,0.241751,0.060602,0.004925,0.191102,0.043686,0.006028,...,81.121093,9.258326,80.999037,1.205102,263.107958,59.127313,31.380564,35.881091,41.026585,pass
13,0.413931,0.429866,0.096635,0.031023,0.365611,0.029699,0.002896,0.094337,0.022704,0.004160,...,29.323587,3.951916,29.008092,0.500997,101.232223,27.730604,11.387315,10.660149,10.448768,pass
14,0.472133,0.511917,0.148813,0.048948,0.326157,0.114095,0.008712,0.368088,0.064261,0.009307,...,112.007571,12.732269,111.551366,1.672593,402.126544,86.378013,44.374922,49.667419,55.987533,pass
15,0.333487,0.373813,0.096493,0.038697,0.354562,0.043716,0.003786,0.109988,0.050250,0.006508,...,90.695940,10.086635,90.509201,1.326481,312.884571,66.196152,35.636153,41.087397,47.223733,pass
16,0.508056,0.625256,0.082675,0.033453,0.262080,0.045789,0.004485,0.206395,0.014666,0.002299,...,15.168074,1.943682,14.926574,0.253922,66.980415,15.383696,6.300065,5.869812,5.723351,pass
17,0.453651,0.415722,0.107537,0.050837,0.426259,0.056749,0.005236,0.140973,0.061366,0.009789,...,106.460988,14.310638,106.664066,1.754115,198.376967,77.667484,36.836751,39.145305,42.618950,pass
18,0.434660,0.523457,0.105825,0.037936,0.343098,0.045642,0.005320,0.126568,0.043480,0.008872,...,58.601185,7.509328,57.668161,0.981016,258.775880,59.434231,24.340022,22.677758,22.111916,pass
19,0.384702,0.515594,0.153585,0.032732,0.293238,0.109139,0.006363,0.219057,0.092563,0.015336,...,172.800005,22.988715,173.161091,2.824767,329.180176,124.838746,60.029864,64.434162,70.657097,pass

[[1.26196127 1.1046214  1.46810157 1.61180868 1.63491101 1.53690458
  1.57569317 1.34544252 1.9056776  1.88104305 2.01397651 1.84830758
  1.91450193 1.92226338 2.02778637 1.90970668 2.03804312 1.94123801
  2.0729244  1.9567185  1.99383458 1.95564963 2.01719666 1.96982218
  1.98622788 1.95843744 2.015632   1.98826983 1.95663095 1.98070369
  1.95570907 2.19559118 1.97693803 1.95944818 2.19680266 1.98340971
  2.20108475 1.97714968 1.96135621 2.19668826 1.98078002 2.20526282
  1.97761893 1.91484797 2.20649703 1.97959761 2.20344061 1.97504289
  2.20431333 1.98228629 2.19492158 2.06143349 2.19380618 2.01060856
  2.19828845 2.06729523 2.19846923 2.01317114 2.16818699 2.09776099
  2.16642476 2.10826575 2.11707032 1.94969138 1.98385941 1.96537695
  1.95308403 2.01907606 2.11361237 1.96260168 2.03626089 2.08015015
  1.96257932 2.11294168 1.97292231 2.00454467 1.96349332 2.10830882
  1.97279487 2.07724629 1.96424968 2.10724917 1.9708134  2.00916794
  1.960539   2.03124959 1.98027982 2.00714946 1.96161857 2.03027725
  1.99852055 1.95947119 1.99617804 1.97345329 2.19806595 1.99584108
  1.96623077 2.19645544 1.99847533 2.19631496 1.99640542 1.96485408
  2.19039362 1.99047082 2.20010872 1.99352235 2.20143824 1.99292102
  2.19748881 1.99030141 2.19823241 1.99059469 2.19118595 2.06847207
  2.19017788 2.01990411 2.19307845 2.07143687 2.19351967 2.02049344
  2.16983795 2.09938082 2.16712693 2.10879725 2.12243089 1.94961368
  1.9859911  1.97477578 1.95315786 2.02279235 2.11372926 1.96696995
  2.04104242 2.08251067 1.96387014 2.11285871 1.97621131 2.00961554
  1.96465076 2.10822604 1.97512694 2.07830838 1.96522297 2.10690114
  1.97226574 2.013805   1.96096716 2.03429754 1.98172219 2.01141018
  1.96202326 2.03343037 2.00293207 1.9596132  2.00049353 1.97394839
  2.19247531 2.00021588 1.9665951  2.19077239 2.00189616 2.19077112
  2.00023055 1.96465896 2.18485969 1.99419738 2.19312686 1.99679768
  2.19438252 1.99650158 2.19135226 1.99389639 2.19207673 1.99407058
  2.18608378 2.06734935 2.18516508 2.02185746 2.18796706 2.07079657
  2.18845692 2.02213517 2.16576614 2.09685301 2.16336681 2.10564722
  2.11851309 2.01361592 1.93787618 1.98241941 2.01967519 2.04848883]]
BARINEL SCORES

,u 190,p 182,p 180,u 191,p 176,x 148,p 178,cp 129,h 3,p 174,...,u 121,u 59,h 0,cx 183,cx 186,p 185,u 184,cx 189,p 188,u 187
sum,0.585514,0.528774,0.527183,0.527163,0.527125,0.526853,0.525681,0.524887,0.524688,0.524558,...,0.517895,0.517869,0.517677,0.517484,0.49818,0.497149,0.480759,0.47881,0.450689,0.430812

custom SCORES

,cp 160,cp 150,cp 147,cp 155,cp 145,cp 143,cp 157,cp 141,cp 137,cp 135,...,cx 179,cx 183,u 190,u 191,p 185,cx 186,cx 189,u 184,p 188,u 187
sum,0.810395,0.81022,0.810218,0.810097,0.80994,0.809911,0.809815,0.809742,0.809683,0.809655,...,0.769353,0.764024,0.747207,0.693477,0.692988,0.689594,0.654545,0.642468,0.632295,0.606897

DSTAR SCORES

,cx 18,x 4,cx 22,cx 26,cx 10,cx 14,cx 37,cx 31,cx 39,cx 20,...,p 178,p 163,p 182,p 176,p 170,p 185,p 180,cp 129,p 168,x 148
sum,3524.916239,2505.749104,2473.668676,2443.46289,2108.830473,1847.782438,1803.189281,1731.498185,1709.414893,1639.254036,...,0.001426,0.001349,0.000733,0.000529,0.00042,0.000256,0.000204,0.000186,0.000106,0.000007

ERROR GATE LOCATION:
148
Now evolving the following mutant:  AddGate_x_inGap_34_.qasm

100%|██████████| 10/10 [03:19<00:00, 19.97s/it]
100%|██████████| 10/10 [02:44<00:00, 16.40s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.538699,0.553221,0.089098,0.036492,0.215996,0.063628,0.006172,0.187878,0.051694,0.009823,...,78.295570,9.605131,77.399364,1.257254,321.326284,72.221595,31.953127,31.968346,33.166488,fail
1,0.392267,0.611870,0.103225,0.019037,0.261766,0.051771,0.001857,0.098147,0.037028,0.004945,...,68.960632,7.669370,68.818645,1.008589,237.901694,50.332225,27.095939,31.240791,35.906552,fail
2,0.303450,0.392478,0.116802,0.025733,0.206965,0.078191,0.006319,0.225228,0.054706,0.008335,...,98.868124,11.311455,98.455980,1.483188,352.752508,76.615988,39.096267,43.568418,48.969618,fail
3,0.519352,0.635045,0.090112,0.030087,0.257519,0.042258,0.004655,0.125553,0.031004,0.006226,...,41.175443,5.276342,40.519864,0.689300,181.825870,41.760773,17.102234,15.934264,15.536681,fail
4,0.542923,0.686910,0.086154,0.040121,0.152849,0.083735,0.009143,0.311589,0.048434,0.009796,...,78.285430,11.412864,78.115044,1.382364,144.843764,65.112202,26.884511,25.407524,25.161709,fail
5,0.509942,0.348129,0.159444,0.051575,0.403695,0.099588,0.008158,0.259895,0.080473,0.013091,...,139.105837,17.866337,138.949741,2.238335,351.488540,106.236389,50.758628,54.146178,59.079143,fail
6,0.504367,0.682020,0.067435,0.031869,0.146448,0.059644,0.006492,0.186707,0.041627,0.007818,...,70.444989,10.915170,70.794441,1.277476,36.489199,51.916016,21.560760,20.579153,20.596295,fail
7,0.598408,0.525440,0.122718,0.051810,0.332034,0.087217,0.009524,0.213478,0.091919,0.016799,...,159.219442,21.453593,158.979403,2.652685,363.204227,125.539623,56.856370,58.231403,61.642676,fail
8,0.397761,0.589259,0.125905,0.026512,0.155927,0.098288,0.007062,0.094941,0.119108,0.022145,...,208.831513,27.749833,208.310819,3.454619,520.611563,167.031048,75.829433,77.773238,82.403260,fail
9,0.473719,0.312113,0.143739,0.053125,0.278833,0.126595,0.010277,0.374005,0.086218,0.013860,...,156.342861,20.799314,156.669558,2.555742,297.829683,112.949341,54.312734,58.297575,63.927850,fail
10,0.477568,0.492241,0.106179,0.047625,0.336084,0.074014,0.006320,0.111371,0.091012,0.017738,...,150.691442,21.068387,150.294776,2.585223,329.554052,123.900633,53.281499,52.235957,53.384661,pass
11,0.341777,0.267523,0.102689,0.042329,0.215016,0.077373,0.008881,0.245816,0.062037,0.012451,...,98.365841,14.226485,98.063084,1.731026,198.547194,82.990832,34.244485,32.327371,31.976472,pass
12,0.339641,0.501279,0.110158,0.033372,0.333493,0.049968,0.003786,0.106838,0.050386,0.006462,...,90.695940,10.086635,90.509201,1.326481,312.884571,66.196152,35.636153,41.087397,47.223733,pass
13,0.327028,0.450967,0.065274,0.013631,0.120563,0.046755,0.002487,0.085234,0.042776,0.006969,...,75.919564,8.773377,75.492962,1.151604,280.744603,60.955395,30.267592,33.105754,36.734908,pass
14,0.328234,0.300778,0.122173,0.032553,0.339808,0.059626,0.004768,0.251329,0.017449,0.001804,...,25.272536,2.810653,25.220501,0.369625,87.185675,18.445640,9.930058,11.449054,13.158952,pass
15,0.436694,0.577066,0.111218,0.027668,0.252648,0.066339,0.005531,0.175532,0.041884,0.007884,...,73.055780,11.480206,73.543232,1.333168,14.499746,52.179882,21.705400,20.773832,20.850888,pass
16,0.551956,0.593960,0.086339,0.036810,0.132506,0.083221,0.008540,0.206700,0.084151,0.013672,...,157.625796,20.604194,157.885635,2.547859,326.168475,114.000610,55.521497,60.119288,66.326218,pass
17,0.360456,0.564889,0.091461,0.032550,0.148023,0.090437,0.006938,0.220980,0.063038,0.011105,...,115.546056,16.429221,115.988513,1.972244,145.260982,83.116193,37.934371,39.202114,41.829868,pass
18,0.598402,0.481844,0.090414,0.047503,0.309356,0.058581,0.006371,0.306318,0.012764,0.001101,...,14.830205,1.649323,14.799671,0.216900,51.161524,10.824107,5.827069,6.718432,7.721819,pass
19,0.429593,0.515955,0.166200,0.046929,0.426632,0.089252,0.008164,0.107346,0.118604,0.020802,...,209.193275,27.652256,208.974922,3.434011,489.888538,161.749365,75.145821,78.517798,84.389326,pass

[[1.25166664 1.28719624 1.4434165  1.45008378 1.67367132 1.60061381
  1.47536827 1.80033187 1.85465942 1.96255639 1.8311038  1.95656099
  1.83002805 1.93270736 1.82587191 1.94610974 1.88543598 1.91711126
  1.87744848 1.90644673 1.88239831 1.90172844 1.88775489 1.88507394
  1.88013691 1.90714263 1.87457794 1.87952968 1.90921925 1.88191689
  1.91020621 1.93865299 1.87899776 1.90735321 1.93304429 1.88662135
  1.93143749 1.88096472 1.90580336 1.93117187 1.88380012 1.92873422
  1.88115173 1.92758993 1.88493494 1.92812901 1.87794276 1.92712329
  1.88022528 1.93413556 1.89180664 1.93278805 1.89009406 1.93069206
  1.88819508 1.93030449 1.88601738 1.94125464 1.90304488 1.93746182
  1.90103853 1.94789944 1.91493021 1.88769494 1.8716378  1.91225456
  1.86076809 1.88632827 1.90485918 1.84707748 1.87249583 1.90527761
  1.87569318 1.89727172 1.8620573  1.90453343 1.87451758 1.89729292
  1.86933251 1.90391907 1.87363359 1.89906359 1.87160325 1.90677277
  1.8712337  1.89123272 1.87038594 1.90591384 1.87086708 1.87142456
  1.90750015 1.87223899 1.8961145  1.92492436 1.86795364 1.90227086
  1.92402277 1.87560594 1.92475389 1.86994383 1.90304883 1.92492032
  1.87838181 1.92356999 1.87083641 1.92262395 1.87690781 1.92405842
  1.87120431 1.92390209 1.87649711 1.92653086 1.88464623 1.92642316
  1.88321194 1.92665214 1.88360547 1.92677401 1.88202396 1.92790953
  1.89936667 1.9278944  1.89875378 1.92093831 1.91449752 1.88587319
  1.86934798 1.9118113  1.86012174 1.88537306 1.90117298 1.84747262
  1.87145487 1.90466849 1.87604232 1.89556039 1.86249085 1.90406448
  1.87488862 1.91169947 1.89633393 1.86960493 1.90362169 1.87422373
  1.89900578 1.87138557 1.9067223  1.87135036 1.89123324 1.87081619
  1.90591433 1.87152952 1.8717644  1.90752985 1.8725879  1.89607524
  1.92352286 1.86877777 1.90238215 1.92277891 1.87591234 1.92339034
  1.87046267 1.9033223  1.92360742 1.87859676 1.92254543 1.87143352
  1.92173069 1.87731582 1.92293679 1.87179415 1.9228227  1.87703846
  1.92509691 1.88494787 1.92501265 1.88351511 1.9253086  1.88396369
  1.92543631 1.88260215 1.9262333  1.89928008 1.92627702 1.89889131
  1.91928038 1.85384933 1.9205258  1.88888859 1.86440891 1.8459914 ]]
BARINEL SCORES

,x 4,u 184,u 191,cx 186,p 182,p 185,p 176,p 180,u 190,cx 127,...,cp 138,cp 160,cp 155,cp 146,cp 144,cp 150,cp 148,cx 189,p 188,u 187
sum,0.556737,0.533372,0.532854,0.532071,0.530194,0.529947,0.529586,0.529296,0.529256,0.529102,...,0.514697,0.514636,0.514532,0.514491,0.514468,0.51438,0.514344,0.512178,0.503706,0.479896

custom SCORES

,x 4,p 182,p 180,p 176,p 178,h 3,p 174,u 129,u 67,p 126,...,cp 148,cp 86,cx 177,cx 186,p 185,u 191,u 190,cx 189,p 188,u 187
sum,0.814763,0.790328,0.788197,0.787244,0.784651,0.78299,0.782121,0.78156,0.781531,0.781061,...,0.762205,0.762137,0.762015,0.744981,0.725413,0.699592,0.699571,0.696999,0.68631,0.680692

DSTAR SCORES

,cx 18,x 4,cx 22,cx 26,cx 10,cx 14,cx 37,cx 31,cx 39,cx 20,...,p 174,p 178,p 163,p 182,p 176,p 170,p 185,p 180,cp 130,p 168
sum,4519.532035,3511.472191,3171.200659,3134.346747,2693.76063,2361.071014,2309.183508,2217.980906,2188.024185,2101.697022,...,0.004796,0.002363,0.002174,0.001261,0.00089,0.000677,0.000482,0.000352,0.000315,0.000168

ERROR GATE LOCATION:
52
Now evolving the following mutant:  AddGate_y_inGap_31_.qasm

100%|██████████| 10/10 [03:39<00:00, 21.94s/it]
100%|██████████| 10/10 [02:52<00:00, 17.22s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.341674,0.319164,0.182867,0.041034,0.284994,0.132722,0.010629,0.226772,0.143231,0.026164,...,252.207787,33.164079,251.593081,4.140915,643.284705,200.474787,92.036799,95.229787,101.577572,fail
1,0.534451,0.587812,0.063560,0.037975,0.162370,0.059002,0.006566,0.210570,0.041037,0.008459,...,56.953460,7.412251,56.135540,0.959364,234.911228,56.583205,23.190548,21.636440,21.128636,fail
2,0.410822,0.523983,0.124350,0.037881,0.406509,0.051255,0.004615,0.233244,0.004704,0.000041,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,fail
3,0.488267,0.542172,0.121425,0.051719,0.287081,0.090835,0.010006,0.219145,0.096619,0.017560,...,165.419919,22.321475,165.140269,2.760208,379.669757,131.036165,59.126056,60.371813,63.756397,fail
4,0.440160,0.365024,0.130490,0.052169,0.365352,0.079440,0.009265,0.259899,0.065605,0.012830,...,104.185758,15.317603,104.059389,1.846413,174.025948,85.321428,35.253739,33.357474,33.077921,fail
5,0.414757,0.475348,0.129081,0.044904,0.325597,0.093846,0.007987,0.291445,0.053414,0.010332,...,89.293460,13.596587,89.550147,1.606849,81.020856,68.279773,28.304423,26.931450,26.864879,fail
6,0.452200,0.608687,0.103650,0.042904,0.323707,0.067328,0.005990,0.166761,0.062999,0.011176,...,105.790848,13.883152,105.482917,1.736794,277.477991,84.861297,38.815165,40.037024,42.601620,fail
7,0.460957,0.444483,0.096985,0.042371,0.224968,0.077546,0.007124,0.146973,0.094029,0.017060,...,158.938932,20.448351,158.233046,2.584582,466.830057,130.443089,59.728947,61.617636,65.553597,fail
8,0.461717,0.391096,0.106023,0.045560,0.249288,0.088760,0.007885,0.172847,0.097635,0.017710,...,168.990787,22.699186,168.731068,2.809488,389.438135,133.122950,60.464907,62.067830,65.817858,fail
9,0.526870,0.423542,0.151101,0.053902,0.350605,0.105908,0.008784,0.199822,0.111852,0.019973,...,191.157505,25.194036,190.685034,3.143908,485.702829,152.225502,69.696862,71.962021,76.635271,fail
10,0.265090,0.345295,0.081679,0.023916,0.255405,0.038843,0.002116,0.091617,0.029825,0.003746,...,52.245015,5.810363,52.137444,0.764114,180.235841,38.132015,20.528056,23.668222,27.203033,pass
11,0.365455,0.440168,0.100021,0.037510,0.259367,0.060118,0.006865,0.240978,0.032655,0.005783,...,53.629794,8.427548,53.987629,0.978670,10.644174,38.304927,15.933799,15.249941,15.306508,pass
12,0.420058,0.285774,0.125231,0.051089,0.501139,0.040255,0.005759,0.237791,0.007982,0.000413,...,3.378392,0.530891,3.400934,0.061651,0.670526,2.413007,1.003745,0.960665,0.964229,pass
13,0.476627,0.577363,0.081203,0.026374,0.304424,0.027726,0.001793,0.109048,0.011981,0.001680,...,15.285231,2.401967,15.387219,0.278935,3.033736,10.917433,4.541353,4.346444,4.362566,pass
14,0.450975,0.491357,0.144130,0.043925,0.275268,0.098088,0.008719,0.265018,0.077487,0.013235,...,128.938426,15.196513,127.971358,1.992838,493.706753,108.498967,51.797606,55.069907,59.880787,pass
15,0.456181,0.462148,0.126021,0.040620,0.274394,0.094282,0.007260,0.225531,0.080994,0.013991,...,135.881756,16.287609,134.961015,2.119545,495.084830,113.458220,53.860519,57.044283,61.862487,pass
16,0.325818,0.243458,0.114579,0.043719,0.261133,0.090797,0.007746,0.269668,0.067451,0.011037,...,119.504309,15.916300,119.646498,1.960012,240.445092,88.213347,41.852960,44.470397,48.405473,pass
17,0.420354,0.345772,0.098574,0.045336,0.312270,0.062528,0.005811,0.175251,0.057379,0.008343,...,98.357290,11.214612,97.928829,1.473004,355.060751,76.422515,39.012053,43.481797,48.876339,pass
18,0.495278,0.404296,0.139540,0.049565,0.397013,0.075974,0.006805,0.241922,0.056807,0.010310,...,84.588059,10.304943,83.678897,1.349286,343.034233,76.814287,34.425566,34.818992,36.442873,pass
19,0.493720,0.365144,0.056789,0.041296,0.211941,0.049078,0.005728,0.125941,0.050093,0.009299,...,80.164319,10.670075,79.780857,1.336058,222.283350,67.287538,29.703776,29.747436,30.921549,pass

[[1.17931438 1.30025002 1.51187643 1.19669924 1.36390664 1.56763239
  1.34802964 1.36990844 1.85742436 1.85163143 1.90083667 1.8270589
  1.88653615 1.89922664 1.91178915 1.88333878 1.96650492 1.91991003
  1.96157094 1.93946195 1.97822255 1.93773408 1.97017765 1.9546926
  1.98516311 1.9418305  1.9946909  1.98781904 1.93954288 1.98411829
  1.93846143 1.88544043 1.98913925 1.94306689 1.89402436 1.97601833
  1.89618132 1.9857484  1.94553174 1.89680125 1.98096009 1.90016955
  1.98545423 1.90185514 1.97910424 1.90120483 1.99098023 1.90263906
  1.98692406 1.89245531 1.96422939 1.89448763 1.96924299 1.89748961
  1.96998923 1.89809754 1.97590272 1.88283633 1.94455789 1.88855447
  1.94735259 1.87493661 1.93161879 1.97434736 2.00229268 1.93571773
  2.01880072 1.97114931 1.94714975 2.04235902 1.99583455 1.94647763
  1.98898503 1.95902389 2.01718838 1.94763774 1.99117679 1.95899456
  2.00137613 1.94859663 1.99272392 1.95619063 2.00044494 1.94416004
  2.00011774 1.96863435 2.0026241  1.9454944  2.00078908 2.00121521
  1.94303797 1.99991964 1.96089329 1.90629875 2.0073143  1.9511767
  1.90774151 1.99406708 1.90662763 2.00385423 1.94997593 1.90660336
  1.98969746 1.90829305 2.00244378 1.90969285 1.99209246 1.90764663
  2.00195169 1.90785718 1.99289073 1.90411245 1.97584886 1.90431582
  1.98030407 1.90385413 1.97745889 1.90365125 1.98227118 1.90283839
  1.95041214 1.90296636 1.95101599 1.91538615 1.93230528 1.97729242
  2.00582768 1.9364184  2.0197691  1.97272823 1.95292363 2.04142879
  1.99751006 1.94740494 1.98839791 1.961686   2.01620518 1.94834591
  1.99055102 1.96046497 2.00086206 1.9490364  1.93660142 1.99173632
  1.95622483 2.00061659 1.94422358 1.99978507 1.96857312 2.00169861
  1.94547714 1.9995157  2.00043983 1.94298467 1.9991341  1.96093701
  1.90866304 2.00569844 1.95098184 1.90987149 1.99339789 1.90893281
  2.00279402 1.94954245 1.90883037 1.98917345 1.91013824 2.00127486
  1.91134209 1.99124554 1.90960636 2.00078202 1.90975328 1.99182104
  1.90650085 1.97539395 1.90666549 1.97971348 1.90610388 1.97688828
  1.9058896  1.98123117 1.90555304 1.95065577 1.90557939 1.95092303
  1.91810943 2.05367325 1.9232996  1.97242516 2.012415   2.04375778]]
BARINEL SCORES

,cp 160,cp 130,cp 134,cp 142,cp 132,cp 157,cp 140,cp 155,cp 152,cp 138,...,u 122,p 185,x 4,cx 186,u 190,cx 189,p 188,u 191,u 184,u 187
sum,0.650352,0.649927,0.649884,0.64819,0.648033,0.647799,0.647507,0.647333,0.646935,0.646805,...,0.597723,0.573654,0.571958,0.570386,0.541688,0.531126,0.527565,0.52082,0.517604,0.494042

custom SCORES

,cp 160,cp 134,cp 142,cp 130,cp 157,cp 155,cp 140,cp 132,cp 152,cp 138,...,u 122,x 4,cx 186,p 185,cx 189,u 190,u 184,p 188,u 191,u 187
sum,0.956903,0.95579,0.954858,0.95457,0.954535,0.954198,0.954181,0.953994,0.953711,0.953631,...,0.902915,0.865611,0.793925,0.76698,0.731875,0.71777,0.694872,0.685399,0.674372,0.662499

DSTAR SCORES

,cx 18,cx 22,cx 26,cx 10,x 4,cx 14,cx 37,cx 31,cx 39,cx 20,...,p 174,p 178,p 163,p 182,p 176,p 170,p 185,p 180,cp 130,p 168
sum,7263.317071,5105.530709,5060.828073,4463.147286,4167.739176,3921.982512,3668.900556,3563.141117,3471.279019,3320.021778,...,0.00692,0.003499,0.003065,0.001981,0.001347,0.00095,0.000618,0.00056,0.000479,0.00023

ERROR GATE LOCATION:
49
Now evolving the following mutant:  AddGate_y_inGap_45_.qasm

100%|██████████| 10/10 [02:25<00:00, 14.55s/it]
100%|██████████| 10/10 [02:35<00:00, 15.52s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.396841,0.455209,0.116868,0.043513,0.375814,0.061786,0.004690,0.023531,0.099428,0.017183,...,171.665083,22.092382,171.225544,2.777384,462.980494,135.423455,63.410136,66.599411,71.834151,fail
1,0.566528,0.818844,0.120175,0.036997,0.337877,0.077360,0.004872,0.201031,0.048374,0.008856,...,82.104065,12.902081,82.651890,1.498287,16.295605,58.642594,24.393711,23.346764,23.433364,fail
2,0.617238,0.511604,0.131359,0.057767,0.376742,0.091017,0.007663,0.225975,0.079584,0.013270,...,128.938426,15.196513,127.971358,1.992838,493.706753,108.498967,51.797606,55.069907,59.880787,fail
3,0.532030,0.466429,0.141226,0.051038,0.392202,0.084802,0.008499,0.206596,0.079749,0.016047,...,127.304750,18.467465,126.956236,2.243179,248.874200,106.831413,44.092425,41.641235,41.207634,fail
4,0.536659,0.514147,0.130972,0.046822,0.154658,0.131689,0.011893,0.346085,0.108737,0.020145,...,189.550423,25.194156,189.077675,3.136228,472.260690,151.630069,68.819385,70.568664,74.757721,fail
5,0.381264,0.500426,0.149923,0.028353,0.318512,0.086024,0.005410,0.234075,0.057423,0.008584,...,105.031029,13.063746,105.077659,1.645224,264.445607,76.188542,38.383954,42.503231,47.604134,fail
6,0.479258,0.464266,0.102960,0.036076,0.314452,0.059285,0.004154,0.233923,0.017094,0.001898,...,25.799305,2.869237,25.746186,0.377330,89.002933,18.830112,10.137036,11.687693,13.433231,fail
7,0.549527,0.544699,0.115525,0.047028,0.439608,0.050335,0.005475,0.278522,0.005727,0.000049,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,fail
8,0.525134,0.500513,0.094056,0.039346,0.317350,0.052042,0.005116,0.174580,0.038820,0.007048,...,64.999051,10.214147,65.432746,1.186144,12.900687,46.425387,19.311688,18.482855,18.551413,fail
9,0.433500,0.577202,0.133654,0.029688,0.337877,0.076642,0.003083,0.189559,0.048952,0.006528,...,90.695940,10.086635,90.509201,1.326481,312.884571,66.196152,35.636153,41.087397,47.223733,fail
10,0.457763,0.513646,0.105951,0.024979,0.204027,0.077866,0.005619,0.230357,0.043803,0.008423,...,77.998862,12.256977,78.519296,1.423373,15.480824,55.710464,23.174025,22.179426,22.261696,pass
11,0.428966,0.474889,0.041783,0.020030,0.179329,0.013932,0.002428,0.094645,0.004742,0.000391,...,5.101672,0.567376,5.091168,0.074615,17.599845,3.723552,2.004544,2.311178,2.656348,pass
12,0.230079,0.265111,0.085331,0.025533,0.174108,0.058441,0.005276,0.119051,0.053629,0.010884,...,85.586588,11.609554,85.007518,1.453238,248.649387,75.349551,31.972229,30.912031,31.197773,pass
13,0.443045,0.452557,0.113481,0.040815,0.166039,0.093093,0.009306,0.246620,0.089338,0.015797,...,152.153368,19.277562,151.488935,2.447648,459.372548,123.821687,57.570506,60.095971,64.505564,pass
14,0.337458,0.406242,0.140333,0.030031,0.346955,0.068300,0.004596,0.294608,0.004825,0.000006,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,pass
15,0.357340,0.472081,0.104379,0.040467,0.329401,0.054066,0.004827,0.150767,0.050905,0.006486,...,90.695940,10.086635,90.509201,1.326481,312.884571,66.196152,35.636153,41.087397,47.223733,pass
16,0.378200,0.346983,0.086133,0.033838,0.193603,0.068343,0.005972,0.119286,0.078132,0.013743,...,132.375752,15.632397,131.357710,2.049808,508.623903,111.908137,53.219224,56.417987,61.216618,pass
17,0.324114,0.360522,0.107144,0.031453,0.287654,0.054799,0.004763,0.128333,0.053909,0.009043,...,89.998349,10.781601,89.446195,1.400664,320.886650,74.149220,35.487221,37.817947,41.199877,pass
18,0.476042,0.287302,0.110035,0.048484,0.288011,0.075644,0.008490,0.306235,0.040609,0.008096,...,53.642023,6.891882,52.802007,0.898935,234.253990,54.218020,22.206696,20.694813,20.183516,pass
19,0.538881,0.522487,0.102033,0.036322,0.229542,0.076241,0.005654,0.256963,0.031830,0.003782,...,53.202296,5.916826,53.092754,0.778114,183.538287,38.830704,20.904190,24.101893,27.701471,pass

[[1.2300523  1.52959498 1.21226193 1.38653    1.30637783 1.70806491
  1.95432123 1.63720727 1.86228701 2.02246084 1.91489129 1.99296549
  1.94263244 1.98361323 1.9196978  2.00267953 1.92216539 1.97219326
  1.91528112 1.9574199  1.92593896 1.95546924 1.92670295 1.94193608
  1.92465002 1.95612127 1.91308637 1.92293161 1.95844879 1.92669597
  1.95919644 1.94314566 1.92455082 1.95564875 1.93737997 1.9308612
  1.93508439 1.92642491 1.95385929 1.93553957 1.92853866 1.931609
  1.92656845 1.93030315 1.92987492 1.93135449 1.92387232 1.9302174
  1.92473805 1.93879037 1.92138527 1.9376507  1.92914102 1.93478906
  1.91676243 1.93438503 1.92465692 1.95058915 1.92578389 1.94717633
  1.92189006 1.96635047 1.96492909 1.93178336 1.91947405 1.96166776
  1.89871333 1.9064342  1.95262514 1.88202554 1.89894726 1.95303987
  1.89608211 1.94324048 1.90269652 1.95213801 1.89577127 1.9432852
  1.89636631 1.95139313 1.89509432 1.94539536 1.91122701 1.95489005
  1.90674947 1.93592993 1.91040627 1.95384457 1.9065694  1.91304144
  1.95580425 1.91428103 1.94200465 1.92916129 1.91012826 1.94940367
  1.92856213 1.9171628  1.92930702 1.91198064 1.95042568 1.93053196
  1.92139085 1.92746226 1.91339864 1.92629289 1.91948262 1.92841216
  1.91436408 1.9281251  1.91951448 1.93197517 1.91305993 1.93204987
  1.92064446 1.93175538 1.91148939 1.93179628 1.91936644 1.93716611
  1.92186901 1.93763924 1.91954481 1.93888326 1.96451958 1.9295938
  1.91545324 1.96121927 1.96103887 1.89738405 1.90547226 1.94818739
  1.88152601 1.89748766 1.95219975 1.89644123 1.94094315 1.90217539
  1.95146046 1.89615193 1.9419061  1.89643902 1.95091851 1.8957394
  1.94506605 1.91014741 1.95476008 1.9062979  1.93566006 1.91003402
  1.95376902 1.90663535 1.91255064 1.95580669 1.91381674 1.9418732
  1.92878316 1.91012022 1.94944446 1.92835614 1.91682448 1.92895825
  1.9117752  1.95073068 1.93023253 1.92090441 1.92770416 1.9133727
  1.92667702 1.91921362 1.92840757 1.91427069 1.92816537 1.91939586
  1.93147886 1.91356371 1.9315608  1.9205791  1.93134933 1.91195989
  1.93138716 1.91962957 1.93625008 1.92224638 1.9367254  1.92025557
  1.93796542 2.08020913 1.97263744 1.93322603 1.90218618 1.87868321]]
BARINEL SCORES

,cp 160,cp 155,cp 142,cp 157,cp 150,cp 148,cp 138,cp 140,cp 146,cp 152,...,cx 145,u 122,cx 117,cx 189,cx 65,cx 127,cx 186,u 184,p 185,x 4
sum,0.588818,0.58786,0.587798,0.587759,0.587716,0.587602,0.587425,0.587414,0.587406,0.587368,...,0.554926,0.554727,0.554599,0.553758,0.553172,0.552724,0.546135,0.520564,0.51665,0.507708

custom SCORES

,cp 160,cp 142,cp 134,cp 157,cp 155,cp 140,cp 152,cp 138,cp 150,cp 136,...,u 122,u 190,cx 186,u 187,x 4,p 185,p 188,u 184,u 191,cx 189
sum,0.874858,0.872702,0.872701,0.872437,0.87225,0.871965,0.871587,0.871561,0.871525,0.871405,...,0.81573,0.782689,0.779344,0.774514,0.771742,0.769075,0.74948,0.733632,0.72983,0.721583

DSTAR SCORES

,cx 18,cx 22,cx 26,cx 10,x 4,cx 14,cx 37,cx 31,cx 39,cx 20,...,p 174,p 178,p 163,p 182,p 176,p 170,p 185,p 180,cp 130,p 168
sum,4509.643393,3169.62566,3131.476417,2755.570849,2437.079517,2416.445606,2303.227144,2221.429322,2184.287359,2084.550457,...,0.003765,0.001853,0.001707,0.000985,0.000695,0.000531,0.000368,0.000278,0.000255,0.000132

ERROR GATE LOCATION:
63
Now evolving the following mutant:  AddGate_y_inGap_78_.qasm

100%|██████████| 10/10 [03:03<00:00, 18.37s/it]
100%|██████████| 10/10 [02:44<00:00, 16.47s/it]

,u 191,u 190,cx 189,p 188,u 187,cx 186,p 185,u 184,cx 183,p 182,...,cx 8,cp 7,cx 6,cp 5,x 4,h 3,h 2,h 1,h 0,pass/fail
0,0.372516,0.509971,0.111003,0.028102,0.322981,0.039717,0.003851,0.150817,0.024910,0.002965,...,41.610665,4.627678,41.524991,0.608580,143.549262,30.370333,16.349619,18.850612,21.665920,fail
1,0.557061,0.535835,0.157260,0.054754,0.417532,0.091419,0.008872,0.358060,0.039987,0.007677,...,50.610115,6.485329,49.804321,0.847241,223.488260,51.329563,21.020928,19.585337,19.096654,fail
2,0.616710,0.420693,0.114552,0.059698,0.349017,0.078706,0.008901,0.151234,0.096736,0.018009,...,159.340745,21.834425,158.930198,2.694394,368.042771,129.580963,56.949430,56.882969,59.028089,fail
3,0.492019,0.645763,0.134183,0.042974,0.376765,0.075383,0.006055,0.116037,0.088295,0.016825,...,146.804089,20.261327,146.422940,2.495214,332.691573,119.853320,52.269565,51.868878,53.541251,fail
4,0.470156,0.471665,0.130231,0.046993,0.310194,0.101549,0.007596,0.183189,0.099584,0.016179,...,182.400005,24.265866,182.781151,2.981699,347.467963,131.774231,63.364857,68.013837,74.582491,fail
5,0.603027,0.512296,0.116561,0.052913,0.227498,0.104208,0.009295,0.283552,0.082167,0.013862,...,135.078351,15.920157,134.065232,2.087735,517.216598,113.665584,54.264158,57.692284,62.732253,fail
6,0.458146,0.441184,0.129618,0.046708,0.293408,0.102444,0.007465,0.366177,0.047957,0.006199,...,86.161143,9.582303,85.983741,1.260157,297.240343,62.886344,33.854346,39.033028,44.862546,fail
7,0.422094,0.391763,0.202862,0.052560,0.586693,0.094051,0.005665,0.176674,0.091888,0.015340,...,149.297125,17.595963,148.177362,2.307497,571.660451,125.630383,59.976175,63.765156,69.335648,fail
8,0.414849,0.369391,0.134225,0.045969,0.409133,0.075444,0.005732,0.140943,0.083320,0.013805,...,148.087449,19.473122,148.143508,2.412398,324.856392,110.630442,52.630467,56.008689,61.023290,fail
9,0.469378,0.342649,0.144422,0.057799,0.406693,0.084854,0.010195,0.314437,0.061375,0.012188,...,89.245026,12.324794,88.516467,1.540225,264.857916,81.321506,33.444528,31.391511,30.857990,fail
10,0.366671,0.315284,0.061799,0.031409,0.166726,0.049663,0.005762,0.188084,0.033257,0.005755,...,57.150693,8.168125,57.320907,0.981397,76.049064,42.057715,18.866655,19.222840,20.286763,pass
11,0.427411,0.324610,0.133999,0.053346,0.272512,0.122031,0.008754,0.179784,0.132277,0.023840,...,228.331212,30.015618,227.738789,3.749761,587.346742,182.080253,83.457773,86.238954,91.892808,pass
12,0.447061,0.466184,0.113864,0.045130,0.292649,0.087355,0.008305,0.210769,0.069857,0.013978,...,117.041034,17.511286,117.135665,2.090030,151.336103,92.707953,38.365446,36.398710,36.196819,pass
13,0.377532,0.478363,0.129631,0.028319,0.247549,0.081013,0.006413,0.300086,0.030180,0.005557,...,48.369843,7.372031,48.514206,0.870777,42.896106,36.916235,15.304544,14.564486,14.530946,pass
14,0.547100,0.430129,0.178611,0.067992,0.541293,0.108033,0.007993,0.223012,0.097127,0.016224,...,157.591410,18.573516,156.409437,2.435691,603.419365,132.609849,63.308185,67.307664,73.187629,pass
15,0.565760,0.566010,0.068984,0.042665,0.341884,0.025749,0.003399,0.033779,0.043331,0.008842,...,58.068501,7.441069,57.143958,0.972099,256.423611,58.893975,24.118771,22.471618,21.910919,pass
16,0.276365,0.369454,0.047035,0.020816,0.110122,0.035245,0.004132,0.191746,0.004824,0.000482,...,4.457358,0.700443,4.487099,0.081341,0.884674,3.183655,1.324313,1.267476,1.272177,pass
17,0.472355,0.514189,0.096952,0.035595,0.249206,0.059518,0.006482,0.218875,0.037961,0.006775,...,62.849071,9.876293,63.268420,1.146910,12.473970,44.889769,18.672913,17.871496,17.937786,pass
18,0.466821,0.360685,0.085308,0.037019,0.210477,0.070177,0.006489,0.300262,0.019018,0.003524,...,23.109548,2.961325,22.741607,0.386867,102.049022,23.438062,9.598558,8.943040,8.719898,pass
19,0.342874,0.256942,0.079947,0.034701,0.213532,0.062497,0.005567,0.152300,0.060574,0.010562,...,108.157659,15.604160,108.614688,1.863919,120.010946,77.724778,35.038361,35.867374,38.000128,pass

[[1.26479705 1.39136858 1.47544782 1.22214558 1.5856937  1.22919853
  1.38472342 1.63389992 1.39040709 1.46359928 1.45912336 1.47632418
  1.3691163  1.38847944 1.47068015 1.41721874 1.48017102 1.37980229
  1.51424389 1.39738144 1.43901963 1.39675918 1.45992348 1.41290308
  1.43241148 1.39932872 1.46212624 1.4346813  1.39713695 1.42687459
  1.39612379 1.62103486 1.42402641 1.40036578 1.62401245 1.42824311
  1.62882799 1.42373803 1.40252878 1.62448971 1.42646989 1.63391507
  1.42412559 1.63551469 1.42505964 1.63225592 1.42249143 1.63345492
  1.42880644 1.62177542 1.50194983 1.62107821 1.45331513 1.62625109
  1.50864559 1.62655136 1.45683373 1.59278021 1.53436421 1.59219017
  1.54527662 1.5402924  1.38931021 1.42840926 1.41489387 1.39315866
  1.46904448 1.55473617 1.40395802 1.48924922 1.52551775 1.40383098
  1.39361842 1.55706175 1.41561077 1.45469984 1.40487907 1.55278868
  1.41548497 1.5235194  1.40574633 1.55198315 1.413164   1.45671215
  1.40153496 1.47811754 1.42411102 1.45508346 1.40276674 1.47727156
  1.4465373  1.4003481  1.44408672 1.41640648 1.62782403 1.44484988
  1.40802921 1.6264775  1.4454294  1.62610824 1.44488664 1.40653572
  1.62008245 1.43707205 1.63031127 1.44190042 1.63195145 1.43978599
  1.62751045 1.43872725 1.62831062 1.43766846 1.6203818  1.51076019
  1.61939945 1.46403593 1.62225194 1.51394324 1.622659   1.46491339
  1.59852277 1.53699587 1.59581661 1.54645092 1.5535108  1.38934691
  1.4308996  1.42438783 1.3933398  1.4728063  1.55512188 1.40900396
  1.49381419 1.52812476 1.40519927 1.55688151 1.41915592 1.45947219
  1.40608687 1.55260308 1.41793332 1.5244905  1.40673771 1.55147353
  1.41454993 1.46123028 1.4019499  1.48104057 1.42547926 1.45907112
  1.40314693 1.48015311 1.45068102 1.40047389 1.44813221 1.41688453
  1.62261452 1.44883535 1.40834415 1.62112696 1.44862785 1.62093657
  1.44842114 1.40628276 1.6149144  1.44057574 1.62357483 1.44488451
  1.62509509 1.44310476 1.621663   1.44201584 1.62242919 1.44085123
  1.61568711 1.50958099 1.61478864 1.46583717 1.61751766 1.51321912
  1.61797149 1.46634343 1.59496212 1.53453372 1.59255186 1.54330363
  1.55013118 1.68578116 1.37688982 1.42673773 1.46868858 1.50148112]]
BARINEL SCORES

,x 4,u 122,h 0,u 59,cx 116,u 62,u 125,cx 54,cx 64,cx 127,...,cp 142,cp 130,cp 134,cp 160,p 188,cx 186,p 185,u 190,u 191,u 184
sum,0.634561,0.605573,0.605275,0.605089,0.6009,0.600602,0.600551,0.600385,0.599543,0.599118,...,0.557834,0.556923,0.556532,0.555862,0.551656,0.547285,0.537719,0.532062,0.531967,0.528589

custom SCORES

,x 4,h 0,u 59,u 122,u 62,u 125,cx 54,cx 116,cx 112,cx 50,...,p 176,cp 130,p 182,p 180,u 184,p 185,p 188,u 190,cx 186,u 191
sum,0.901994,0.832477,0.831061,0.831035,0.821745,0.82111,0.819447,0.819433,0.818933,0.818817,...,0.771783,0.771379,0.76891,0.768223,0.744504,0.723867,0.720207,0.717136,0.715466,0.700174

DSTAR SCORES

,cx 18,x 4,cx 22,cx 26,cx 10,cx 37,cx 14,cx 31,cx 39,cx 20,...,p 174,p 178,p 163,p 182,p 176,p 170,p 185,p 180,cp 130,p 168
sum,6597.86822,5858.386587,4623.570252,4559.703556,3864.026076,3396.544222,3380.200812,3238.76055,3222.120014,3100.288554,...,0.005805,0.00285,0.002643,0.0015,0.001066,0.000823,0.000539,0.000425,0.000352,0.000205

ERROR GATE LOCATION:
119
Now evolving the following mutant:  AddGate_y_inGap_117_.qasm

100%|██████████| 10/10 [02:35<00:00, 15.51s/it]
  0%|          | 0/10 [00:00<?, ?it/s]