<h1 style="text-align: center;">HEISENBERG-BASED FAULT LOCALIZATION (HBFL)</h1>

<h2 style="text-align: center;">Download Initial Dependencies</h2>

In [1]:
import numpy as np
import pandas as pd
import json
import math
from tqdm import tqdm
from qiskit.quantum_info import SparsePauliOp, Operator, Pauli, Clifford
import qiskit.qasm2 as q2
from qiskit import QuantumCircuit
from IPython.display import display

from heisenbergUtilities import *

In [2]:
# from qiskit_aer import AerSimulator
# simulator = AerSimulator()

# print(simulator.available_devices())

<h2 style="text-align: center;">CONTROL PANEL</h2>

In [3]:
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------GENERAL PARAMETERS---------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
ALG_NAME = "ghz"
ORIGINAL_QASM = f"{ALG_NAME}_5_qubits.qasm"                                                 #| The original algorithm QASM circuit file name.                           
ORIGINAL_QASM_FOLDER = "SBFL_circuits/MQTBench/"                                            #| The folder containing the original QASM circuit file.                    
QASM_MUTANT_FOLDER = f"SBFL_circuits/QMutBenchMutants/Mutants_{ALG_NAME}_5_qubits/"         #| The folder containing all mutants related to the original QASM circuit.  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#-------------------------------------------------------------------------SB-QOPS PARAMETERS---------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
RUNS = 10                                                                                   #| Number of times SB-QOPS will run to find a failing or passing test case.            
SHOTS = 20000                                                                               #| Number of shots for SB-QOPS to use to create the compact program specification.     
EPOCH = 80                                                                                  #| Number of epochs SB-QOPS will run to navigate the search space of test cases.       
SBQOPS_TOL = 0.1                                                                            #| Tolerance value SB-QOPS uses to determine if a test case is failing or passing.     
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
#---------------------------------------------------------------------HEISENBERG SBFL PARAMETERS-----------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#
LAMBDA_PHASE = 2                                                                        #| The hyperparameter used to weight the phase change of the Pauli propagation
LAMBDA_CHANGE = 1                                                                         #| The hyperparameter used to weight the change of string of the Pauli propagation
LAMBDA_SIMILARITY = 1                                                                       #| The hyperparameter used to weight the similarity difference between current and target Pauli
ATOL = 1e-4                                                                                 #| The tolerance value used to prune negligible magnitudes during Pauli propagation.   
MAX_TERMS = 100                                                                             #| The maximum number of terms to keep during Pauli propagation. If None, use all.     
SEARCH_STEP = 3                                                                             #| The search step size used during Pauli propagation. If None, pauli-prop uses 4.     
VERBOSE = 1                                                                                 #| A boolean value to determine if the program should print out detailed information.  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------#

Generate the linked list of all operations that take place in the inverse circuit

In [4]:
"""
LinkedListNode: A class that holds information related to a gate in a quantum circuit. 

PROPERTIES:
    - value (String): The name of the quantum gate
    - depth (int): The depth of the gate in the circuit
    - count (Int): The probability that the gate will meaningfully change the Pauli string.
    - next (LinkedListNode): The next gate in the circuit

"""

class LinkedListNode:
    def __init__(self, name="Initial", depth=0, count=0,  next=None):
        self.value = name
        self.depth = depth
        self.next = next
        self.count = count

class LinkedList:
    def __init__(self):
        self.head = None

    def append(self, name, depth):
        new_node = LinkedListNode(name, depth)
        if not self.head:
            self.head = new_node
            return
        last_node = self.head
        while last_node.next:
            last_node = last_node.next
        last_node.next = new_node

    def mark(self, depth):
        current_node = self.head
        while current_node:
            if current_node.depth == depth:
                current_node.count += 1
                return
            current_node = current_node.next

    def reset(self):
        current_node = self.head
        while current_node:
            current_node.count = 0
            current_node = current_node.next

<h3>Download MQT Benchmark circuits.</h3>

We'll start with DJ, RealAmpRandom, and GHZ since SB-QOPS caught those mutants 100% of the time for 5 qubit circuits

<h3>Generate mutants.</h3>

We'll start with mutants that add an unnecessary gate, then add mutants that replace a certain gate later.

The mutants were downloaded from QMutBench, choosing specifically mutants that added a gate anywhere with 0-10% survival scores

In [5]:
correct_circuit = load_program(ORIGINAL_QASM, ORIGINAL_QASM_FOLDER).copy()
correct_list = LinkedList()
correct_list = construct_list(correct_list, correct_circuit, inverse=False)

<h2 style="text-align: center;"> SB-QOPS </h2>

This is where we will use SB-QOPS on a provided circuit and its mutants

For a single mutant, it took about 2 minutes to generate a 20 test suite (10 fail, 10 pass) on an RTX 4090 SUPER. It can only be run on a Linux environment since the AER Simulator does not support Windows

There are 113 mutants for the DJ algorithm in use: 226 minutes or 3 3/4 hours

There are 89 mutants for the GHZ algorithm in use: 178 minutes or about 3 hours

There are 125 mutants for the RealAmpRandom algorithm in use: 250 minutes or just over 4 hours

BUT this cell should only need to be run once per algorithm with mutants under test. After it saves to the csv file at the end, this cell can be commented out as to not accidentally run it again. 

In the future if we want to test this methodology on higher qubit circuits or other algorithms, we'll likely either want to reduce the number of tests in the suite or the number of mutants we're analyzing

In [6]:
# import QOPS as qops
# from QOPS_test import get_compact_program_specification_Z
# from pathlib import Path

# ga_result = pd.DataFrame(columns=['Program',"path_to_mutant",'catch_avg','avg_fitness','failing_testcases', 'passing_testcases'])
# program_history = {}

# #program_specification = The compact program specification. SB-QOPS needs this to generate failing test cases.
# # In a public-use environment, this would be provided by the user.
# program_specification = get_compact_program_specification_Z(correct_circuit, shots=SHOTS)

# #mutants = A python list of qiskit QuantumCircuit variables with a mutation in them
# mutants = []
# mutants_names = []
# root = Path(QASM_MUTANT_FOLDER)
# for qasm_mutant in root.rglob("*.qasm"):
#     mutants.append(load_program(qasm_mutant.name, QASM_MUTANT_FOLDER))
#     mutants_names.append(qasm_mutant.name)

# for mutant_index,mutant in enumerate(mutants):
#     tester = qops.Circuit_Tester(CUT=mutant)
#     tester.set_applicable_families_Z(program_specification)
#     mutants_per_run = []
#     fitness_per_run = []
#     failing_testcases_per_run = []
#     history_per_run = []

#     print("NOW RUNNING TO FIND FAILING TESTS")
#     #For a predefined number of attempts, try to find a set of failing test cases (output is above predefined tolerance)
#     for runs in range(RUNS):
#         killed = 0
#         pauli = {}
#         fitness = 0
#         for i in range(len(tester.applicable_families)):
#             best_function,testcase, history = tester.run_mealoneplusone(i, EPOCH)
#             if best_function > SBQOPS_TOL:
#                 killed = 1
#                 pauli = testcase
#                 fitness = best_function
#                 break
#         mutants_per_run.append(killed)
#         failing_testcases_per_run.append(pauli)
#         fitness_per_run.append(fitness)
#         history_per_run.append(history)

#     avg_score = np.mean(mutants_per_run)
#     avg_fitness = np.mean(fitness_per_run)

#     #Here is our new, modified algorithm from the SB-QOPS method that attempts to find passing test cases as well. We'll need them for SBFL
#     passing_testcases_per_run = []

#     print("NOW RUNNING TO FIND PASSING TESTS")
#     for runs in range(RUNS):
#         pauli = {}
#         fitness = 0
#         for i in range(len(tester.applicable_families)):
#             best_function, testcase, history = tester.run_reverse_mealoneplusone(i,EPOCH)
#             if best_function < SBQOPS_TOL:
#                 pauli = testcase
#                 break
#         passing_testcases_per_run.append(pauli)

#     #Replace static program file with "program_name" when ready to test fully
#     """
#     ga_result: A pandas dataframe with the following columns
#         Program: Name of the mutant quantum circuit file
#         Path_To_Mutant: Path to the mutant file
#         Catch_Avg: The average number of times the mutant was identified by SB-QOPS
#         Avg_Fitness: The average fitness of the search algorithm used. Higher usually indicates higher Catch_Avg
#         Failing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a failing test case
#         Passing_Testcases: A list of dicts indicating the set of Pauli strings and the weights that should be applied to generate a passing test case
#     """
#     ga_result = pd.concat([pd.DataFrame([[mutants_names[mutant_index],QASM_MUTANT_FOLDER,avg_score,avg_fitness,json.dumps(failing_testcases_per_run), json.dumps(passing_testcases_per_run)]],columns=ga_result.columns),ga_result],ignore_index=True)
#     ga_result.to_csv(f'realamprandom_ga_result', index=False)

ga_result is a slightly altered pandas Dataframe with similar structure found in SB-QOPS's results folder. The differences are changing the column "Program" to be the name of the mutant file instead of the original quantum circuit, changing "Mutant" to be the path to the mutant file instead of being an arbitrary index value, and adding a passing_testcases column that returns Pauli strings and coefficients that generate passing tests.

Now we want to run SBFL using Heisenberg evolution trees on each circuit placed in ga_result

Evolution analysis tends to take about 5 minutes for 10 failing tests on a very complex algorithm such as QNN, so about 10 minutes for 20 total tests

DJ was a relatively small algorithm with few to no branching gates, so it only ended up taking about 5-6 minutes to evolve and analyze all 113 DJ mutants

About 890 minutes for GHZ, or 14.8 hours to evolve and analyze all 89 GHZ mutants

About 1250 minutes for RealAmpRandom, or 20.8 hours to evolve and analyze all 125 RealAmpRandom mutants

The runtime of this code segment is directly tied to the depth of the circuit being analyzed and the number of 2-branching gates such as rotation or phase gates that exist in the circuit.

This is something to note in the final paper. Regardless of accuracy this methodology takes a long time to run. If results are promising, then we'll want to look into the tradeoffs between EXAM and hyperparameters to speed this up. Primarily the atol, max_terms, and search_step parameters in the evolve_pauli_exact method in HeisenbergUtilities.py

<h2 style="text-align: center;">HEISENBERG EVOLUTIONS (PAULI PROPAGATION)</h2>

In [7]:
from heisenbergTree import *

ga_result = pd.read_csv(f'{ALG_NAME}_ga_result.csv')
tarantula_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','exam_score'])
barinel_sbfl_result = pd.DataFrame(columns=['Program','path_to_mutant','exam_score'])

#For each mutant of a circuit, run the SBFL implementation
for mutant, path in zip(ga_result.loc[:,"Program"], ga_result.loc[:,"path_to_mutant"]):
    print("Now evolving the following mutant: ", mutant)

    #Extract the raw test cases found for each mutant
    desired_failing_testcases = ga_result.loc[(ga_result["Program"] == mutant), ["failing_testcases"]]
    desired_passing_testcases = ga_result.loc[(ga_result["Program"] == mutant), ["passing_testcases"]]
    raw_failing_testcases = desired_failing_testcases["failing_testcases"].values[0].split("}")
    raw_passing_testcases = desired_passing_testcases["passing_testcases"].values[0].split("}")

    #Remove empty tests
    raw_failing_testcases = remove_null_tests(raw_failing_testcases)
    raw_passing_testcases = remove_null_tests(raw_passing_testcases)

    circuit_inverse = load_program(mutant,path).copy().inverse()  # Invert to track backward evolution of the operator
    forward_mutant = load_program(mutant, path).copy()

    #Create the linked list of operations in the inverse circuit
    operation_list = LinkedList()
    operation_list = construct_list(operation_list, circuit_inverse, True)

    forward_list = LinkedList()
    forward_list = construct_list(forward_list, forward_mutant, False)

    #Create list of nodes in linked list. Somewhere down the road remove the linked list implementation. It's unnecessary and giving me a headache
    node_list = []
    node = operation_list.head
    while node:
        node_list.append(node)
        node = node.next

    #Perform Pauli propagation (Heisenberg evolution) for all test cases. Returns a dataframe with all counts for all operations
    global_frame_fail = heisenberg_evolve(circuit_inverse, 
                                          operation_list, 
                                          raw_failing_testcases, 
                                          "fail", 
                                          LAMBDA_PHASE, 
                                          LAMBDA_CHANGE, 
                                          LAMBDA_SIMILARITY, 
                                          atol = ATOL, 
                                          max_terms = MAX_TERMS, 
                                          search_step = SEARCH_STEP)
    
    global_frame_pass = heisenberg_evolve(circuit_inverse, 
                                          operation_list, 
                                          raw_passing_testcases, 
                                          "pass", 
                                          LAMBDA_PHASE, 
                                          LAMBDA_CHANGE, 
                                          LAMBDA_SIMILARITY, 
                                          atol = ATOL, 
                                          max_terms = MAX_TERMS, 
                                          search_step = SEARCH_STEP)

    global_frame = pd.concat([global_frame_fail, global_frame_pass], ignore_index=True)

    global_frame = global_frame.drop(["Initial"],axis=1)
    if VERBOSE:
        display(global_frame)

    tarantula_scores = tarantula(global_frame)
    barinel_scores = barinel(global_frame)

    if VERBOSE:
        print("BARINEL SCORES")
        display(barinel_scores)
        print("TARANTULA SCORES")
        display(tarantula_scores)
    
    # Here is where analysis of the methodology begins. 
    # We first extract the position of the erroneous gate by comparing it to the original MQT gate
    # NOTE: This method is intended for single-added gates for now. Other types of mutants will require other methods later
    error_gate_location = find_erroneous_gate(forward_mutant, correct_circuit)

    if VERBOSE:
        print("ERROR GATE LOCATION:")
        print(error_gate_location)

    # Calculate the EXAM score for Barinel by counting the number of gates we would have to observe before we reach the erroneous gate.
    gates_observed = 0
    barinel_exam_score = 0
    for col_name, col_date in barinel_scores.items():
        gates_observed += 1

        #Extract depth from column name
        gate_depth = int(col_name.split()[1])

        if gate_depth == error_gate_location:
            barinel_exam_score = gates_observed/(circuit_inverse.size())
            break

    # Calculate the EXAM score for Tarantula by counting the number of gates we would have to observe before we reach the erroneous gate.
    gates_observed = 0
    tarantula_exam_score = 0
    for col_name, col_date in tarantula_scores.items():
        gates_observed += 1

        #Extract depth from column name
        gate_depth = int(col_name.split()[1])

        if gate_depth == error_gate_location:
            tarantula_exam_score = gates_observed/(circuit_inverse.size())
            break

    # Here we store the results from the HBFL analysis for both barinel and tarantula into a csv file for later analysis.
    barinel_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,barinel_exam_score]],columns=barinel_sbfl_result.columns),barinel_sbfl_result],ignore_index=True)
    barinel_sbfl_result.sort_values(by=['exam_score'], ascending=False)
    barinel_sbfl_result.to_csv(f'{ALG_NAME}_barinel_sbfl_result.csv', index=False)

    tarantula_sbfl_result = pd.concat([pd.DataFrame([[mutant,QASM_MUTANT_FOLDER,tarantula_exam_score]],columns=tarantula_sbfl_result.columns),tarantula_sbfl_result],ignore_index=True)
    tarantula_sbfl_result.sort_values(by=['exam_score'], ascending=False)
    tarantula_sbfl_result.to_csv(f'{ALG_NAME}_tarantula_sbfl_result.csv', index=False)

if VERBOSE:
    display(barinel_sbfl_result)
    display(tarantula_sbfl_result)

Now evolving the following mutant:  AddGate_y_inGap_9_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.89it/s]
100%|██████████| 10/10 [00:00<00:00, 12.47it/s]

         y 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.847061  1.426738  1.034788  0.785597  0.600992  0.563573      fail
1   0.668761  1.311947  0.945404  0.780660  0.590792  0.550129      fail
2   1.026366  1.362889  1.047307  0.859069  0.631627  0.584196      fail
3   1.127369  1.379878  1.030120  0.800218  0.578396  0.539438      fail
4   0.972656  1.256377  0.970285  0.755963  0.526341  0.492478      fail
5   0.781193  1.164018  0.865658  0.658116  0.488138  0.453233      fail
6   0.844152  1.181119  0.947993  0.740320  0.554579  0.508893      fail
7   0.815064  1.212898  0.912555  0.669215  0.548608  0.506496      fail
8   0.843522  1.261132  0.967841  0.711333  0.552267  0.514737      fail
9   0.974443  1.250655  0.940215  0.708481  0.553117  0.509757      fail
10  0.694721  0.722313  0.583555  0.487591  0.372435  0.339612      pass
11  0.510030  0.995167  0.771842  0.631467  0.445037  0.411547      pass
12  0.211624  0.595972  0.491154  0.370034  0.273007  0.251737      pass
13  0.893460  1.236111  0.946160  0.724751  0.527231  0.492705      pass
14  0.436001  0.836271  0.659907  0.511286  0.388386  0.361238      pass
15  0.700517  0.963648  0.743599  0.546121  0.429306  0.400811      pass
16  0.906170  1.081179  0.792448  0.634050  0.482073  0.450060      pass
17  0.594096  1.203785  0.961334  0.693990  0.515446  0.474564      pass
18  0.526243  0.862334  0.647200  0.467161  0.328489  0.305433      pass
19  0.566059  0.965562  0.748618  0.586016  0.449480  0.414696      pass

BARINEL SCORES

          y 5      cx 4       h 0      cx 1      cx 2      cx 3
sum  0.595775  0.575108  0.572355  0.571879  0.569219  0.568096

TARANTULA SCORES

          y 5      cx 4       h 0      cx 1      cx 2      cx 3
sum  0.595775  0.575108  0.572355  0.571879  0.569219  0.568096

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_y_inGap_10_.qasm

100%|██████████| 10/10 [00:00<00:00, 12.04it/s]
100%|██████████| 10/10 [00:00<00:00, 12.56it/s]

         y 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.879080  1.200054  0.898552  0.674012  0.549577  0.507059      fail
1   0.833409  1.138441  0.942609  0.702477  0.524479  0.484839      fail
2   0.884239  1.233091  0.976519  0.772915  0.595881  0.551092      fail
3   0.754155  1.184525  0.900609  0.688430  0.526228  0.488108      fail
4   0.853135  1.166142  0.848481  0.577240  0.441581  0.412874      fail
5   1.181434  1.322016  0.987162  0.733176  0.573200  0.525434      fail
6   0.941606  1.304551  1.023638  0.835359  0.629367  0.582776      fail
7   0.928584  1.456810  1.136095  0.872461  0.660112  0.610724      fail
8   0.794117  1.357432  0.987148  0.780274  0.632114  0.586535      fail
9   0.936033  1.242618  0.945499  0.694482  0.568496  0.525239      fail
10  0.693440  1.031926  0.793665  0.615874  0.450083  0.414915      pass
11  0.424649  0.850169  0.647354  0.489938  0.383016  0.354876      pass
12  0.540509  1.004813  0.833576  0.646545  0.481649  0.445817      pass
13  0.613746  1.124707  0.849720  0.658194  0.490020  0.455742      pass
14  0.805473  1.296803  0.955702  0.663431  0.502834  0.467400      pass
15  0.667385  0.935491  0.690319  0.512643  0.361148  0.333833      pass
16  0.680217  1.144027  0.932460  0.685151  0.506587  0.469446      pass
17  0.865023  1.172836  0.881032  0.684730  0.497938  0.459695      pass
18  0.778854  1.154958  0.839461  0.634526  0.511400  0.470294      pass
19  0.631636  1.066381  0.809545  0.585265  0.440766  0.410265      pass

BARINEL SCORES

          y 5     cx 1      h 0      cx 2      cx 3      cx 4
sum  0.572828  0.55208  0.55192  0.542738  0.539529  0.538985

TARANTULA SCORES

          y 5     cx 1      h 0      cx 2      cx 3      cx 4
sum  0.572828  0.55208  0.55192  0.542738  0.539529  0.538985

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_x_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.62it/s]
100%|██████████| 10/10 [00:00<00:00, 10.39it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       x 0 pass/fail
0   0.454514  1.047386  0.817514  0.631470  0.585805  1.162866      fail
1   0.413612  0.981383  0.709196  0.517670  0.485918  0.872916      fail
2   0.340170  1.020752  0.794850  0.615047  0.573743  1.138368      fail
3   0.422803  0.973911  0.754339  0.566338  0.525221  0.992754      fail
4   0.199027  0.825456  0.657664  0.484016  0.454189  0.935771      fail
5   0.361317  0.937120  0.739739  0.574188  0.526762  1.027948      fail
6   0.273985  0.866434  0.645441  0.498624  0.462319  0.941339      fail
7   0.407491  1.037178  0.810909  0.605811  0.560462  1.083599      fail
8   0.411200  0.982200  0.765369  0.575063  0.535613  1.017593      fail
9   0.372902  0.894621  0.705314  0.539674  0.500750  1.011070      fail
10  0.272983  0.602009  0.447813  0.345142  0.317849  0.581552      pass
11  0.428173  1.050057  0.772233  0.582730  0.543722  1.046359      pass
12  0.426460  0.979246  0.779452  0.594246  0.543446  0.954594      pass
13  0.221916  0.569233  0.401141  0.305208  0.285754  0.509956      pass
14  0.347048  0.929958  0.715185  0.539163  0.500763  0.979226      pass
15  0.304933  0.812999  0.655542  0.489011  0.453172  0.905290      pass
16  0.376285  0.909052  0.625564  0.473827  0.441098  0.861037      pass
17  0.340857  1.003843  0.796187  0.573643  0.533395  1.095908      pass
18  0.229852  0.883662  0.718813  0.527660  0.491004  0.954798      pass
19  0.240076  0.738274  0.601339  0.419517  0.386688  0.756400      pass

BARINEL SCORES

         x 0       h 1      cx 2      cx 5      cx 3     cx 4
sum  0.54087  0.536769  0.536228  0.534215  0.531878  0.53015

TARANTULA SCORES

         x 0       h 1      cx 2      cx 5      cx 3     cx 4
sum  0.54087  0.536769  0.536228  0.534215  0.531878  0.53015

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_cx_inGap_3_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.71it/s]
100%|██████████| 10/10 [00:00<00:00, 10.84it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.336539  0.913327  0.702453  0.678089  0.490142  0.460097      fail
1   0.520011  1.077549  0.840714  0.821179  0.599465  0.560175      fail
2   0.185736  0.798522  0.620304  0.606208  0.468151  0.435284      fail
3   0.352038  1.020456  0.795787  0.787408  0.591034  0.554837      fail
4   0.419596  1.052853  0.815373  0.797033  0.553431  0.516457      fail
5   0.351784  0.928995  0.726148  0.714278  0.544019  0.505613      fail
6   0.345466  0.944460  0.747700  0.742955  0.527862  0.492436      fail
7   0.216846  0.865702  0.683048  0.670307  0.545205  0.507090      fail
8   0.275954  0.773262  0.667731  0.713277  0.526887  0.488365      fail
9   0.351075  0.804723  0.677153  0.712055  0.480822  0.445943      fail
10  0.454235  0.893024  0.666107  0.625217  0.440840  0.413656      pass
11  0.492753  1.066207  0.841591  0.836796  0.578139  0.539514      pass
12  0.300583  0.715960  0.535767  0.501865  0.392799  0.362640      pass
13  0.327035  0.934849  0.730731  0.718012  0.570304  0.532677      pass
14  0.260808  0.716214  0.547177  0.522513  0.393421  0.365343      pass
15  0.377770  0.833879  0.630090  0.601218  0.463075  0.429483      pass
16  0.271937  0.713690  0.521811  0.478730  0.337067  0.313727      pass
17  0.252278  0.551393  0.430979  0.425294  0.332795  0.308486      pass
18  0.265451  0.826963  0.574309  0.497521  0.397700  0.372544      pass
19  0.316028  0.864541  0.667335  0.652120  0.507077  0.469547      pass

BARINEL SCORES

         cx 2       h 0      cx 1      cx 3      cx 4      cx 5
sum  0.552797  0.547316  0.546909  0.542113  0.530732  0.502709

TARANTULA SCORES

         cx 2       h 0      cx 1      cx 3      cx 4      cx 5
sum  0.552797  0.547316  0.546909  0.542113  0.530732  0.502709

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_x_inGap_9_.qasm

100%|██████████| 10/10 [00:00<00:00, 12.19it/s]
100%|██████████| 10/10 [00:00<00:00, 13.21it/s]

         x 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.836710  1.283607  1.022226  0.818536  0.600401  0.557776      fail
1   0.668346  1.351999  1.047789  0.799232  0.589567  0.547911      fail
2   0.784068  1.149876  0.830912  0.640085  0.490938  0.459246      fail
3   0.950548  1.238788  0.963926  0.751761  0.552009  0.510732      fail
4   1.007201  1.429969  1.079938  0.865268  0.651688  0.604495      fail
5   0.865103  1.019665  0.734186  0.590905  0.470771  0.436174      fail
6   0.788003  1.089619  0.899596  0.682576  0.529718  0.493935      fail
7   0.868270  1.277209  1.025357  0.860147  0.670588  0.621826      fail
8   1.097320  1.408125  1.074404  0.833073  0.652323  0.601744      fail
9   0.763131  1.155245  0.910021  0.718680  0.537278  0.500930      fail
10  0.311546  0.790720  0.546555  0.445160  0.362128  0.334008      pass
11  0.933593  1.343082  1.016169  0.785784  0.580179  0.544119      pass
12  0.683631  1.283346  0.999485  0.802787  0.603356  0.554915      pass
13  0.776317  1.340896  1.001253  0.802881  0.599849  0.559713      pass
14  0.629675  1.101862  0.881705  0.678908  0.546365  0.507849      pass
15  0.776930  1.257935  0.912938  0.744703  0.541429  0.501892      pass
16  0.619489  0.939438  0.744488  0.577304  0.430436  0.402135      pass
17  0.382451  0.704190  0.526574  0.378350  0.291156  0.267516      pass
18  0.706387  1.321268  1.045348  0.802745  0.601139  0.556816      pass
19  0.703203  1.157308  0.858799  0.690788  0.535546  0.496152      pass

BARINEL SCORES

          x 5       h 0      cx 1      cx 2     cx 3      cx 4
sum  0.569479  0.530301  0.530161  0.529813  0.52911  0.524616

TARANTULA SCORES

          x 5       h 0      cx 1      cx 2     cx 3      cx 4
sum  0.569479  0.530301  0.530161  0.529813  0.52911  0.524616

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_x_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.62it/s]
100%|██████████| 10/10 [00:00<00:00, 10.74it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       x 0 pass/fail
0   0.511963  1.074125  0.775015  0.619500  0.572058  1.225497      fail
1   0.397363  0.981879  0.713750  0.548963  0.509979  1.020874      fail
2   0.476496  1.103680  0.840129  0.622835  0.577389  1.185108      fail
3   0.462641  0.939249  0.724190  0.509223  0.473411  1.007509      fail
4   0.408294  0.920732  0.696156  0.533791  0.490822  0.951026      fail
5   0.455874  0.982208  0.727808  0.582183  0.540326  1.126835      fail
6   0.385535  0.903933  0.694263  0.554530  0.516991  1.078918      fail
7   0.389687  1.059328  0.734083  0.552649  0.508190  0.954096      fail
8   0.294364  0.872382  0.691205  0.509159  0.470080  0.882303      fail
9   0.547896  1.037050  0.798260  0.614162  0.569313  1.224698      fail
10  0.408754  0.969665  0.718142  0.545822  0.503201  0.971686      pass
11  0.416900  0.968756  0.798690  0.606557  0.561334  1.137000      pass
12  0.292286  0.813450  0.616229  0.465488  0.433336  0.782374      pass
13  0.343534  0.754988  0.589525  0.439051  0.409701  0.872066      pass
14  0.350922  0.856072  0.604774  0.460839  0.430371  0.816932      pass
15  0.279721  0.812009  0.600516  0.454024  0.422983  0.773245      pass
16  0.440082  1.077785  0.797098  0.609073  0.565681  1.125682      pass
17  0.367890  0.927566  0.703869  0.519334  0.483398  0.973144      pass
18  0.309027  0.931640  0.686240  0.521640  0.480714  0.892228      pass
19  0.191045  0.577164  0.427086  0.306417  0.283930  0.481754      pass

BARINEL SCORES

        cx 5       x 0      cx 2       h 1     cx 4      cx 3
sum  0.56015  0.546983  0.533983  0.533352  0.53193  0.530591

TARANTULA SCORES

        cx 5       x 0      cx 2       h 1     cx 4      cx 3
sum  0.56015  0.546983  0.533983  0.533352  0.53193  0.530591

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_swap_inGap_2_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.30it/s]
100%|██████████| 10/10 [00:01<00:00,  9.40it/s]

        cx 5      cx 4      cx 3      cx 2    swap 1       h 0 pass/fail
0   0.356098  0.954568  0.708696  0.536896  0.483870  0.431763      fail
1   0.381980  0.974573  0.788388  0.602961  0.539413  0.484141      fail
2   0.350263  0.945825  0.711258  0.572694  0.502997  0.445868      fail
3   0.307327  0.826299  0.654424  0.471169  0.464952  0.411790      fail
4   0.374500  0.924659  0.704122  0.548830  0.539665  0.471824      fail
5   0.392258  1.060804  0.799408  0.587292  0.443071  0.413154      fail
6   0.329490  0.983456  0.735727  0.542831  0.502298  0.445091      fail
7   0.335685  0.873717  0.686054  0.533778  0.447379  0.400699      fail
8   0.419146  1.013559  0.783721  0.597310  0.492007  0.445099      fail
9   0.335743  0.758100  0.588672  0.474043  0.438270  0.386587      fail
10  0.348913  0.935888  0.710743  0.573062  0.527255  0.465856      pass
11  0.304629  0.815731  0.591212  0.469232  0.359114  0.328710      pass
12  0.404512  1.049391  0.785264  0.591653  0.498594  0.448605      pass
13  0.354632  0.971872  0.669458  0.519191  0.403228  0.368266      pass
14  0.259610  0.794669  0.601902  0.449319  0.390838  0.349913      pass
15  0.428699  0.950429  0.732740  0.579388  0.483423  0.437491      pass
16  0.203424  0.715895  0.587189  0.433681  0.340679  0.311571      pass
17  0.363148  0.985942  0.758116  0.564776  0.472632  0.424976      pass
18  0.365124  0.937088  0.671536  0.525126  0.442665  0.396770      pass
19  0.195431  0.595199  0.456330  0.351948  0.337712  0.298114      pass

BARINEL SCORES

       swap 1       h 0      cx 5      cx 3      cx 2      cx 4
sum  0.532809  0.530965  0.526016  0.521712  0.519497  0.515593

TARANTULA SCORES

       swap 1       h 0      cx 5      cx 3      cx 2      cx 4
sum  0.532809  0.530965  0.526016  0.521712  0.519497  0.515593

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_sx_inGap_2_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.62it/s]
100%|██████████| 10/10 [00:01<00:00,  9.96it/s]

        cx 5      cx 4      cx 3      cx 2       h 1    sxdg 0 pass/fail
0   0.379882  1.014084  0.758194  0.602434  0.552144  1.085932      fail
1   0.330574  0.873309  0.668326  0.498813  0.460281  0.823141      fail
2   0.366141  1.028626  0.778040  0.609182  0.563447  1.114111      fail
3   0.330204  0.928685  0.692610  0.530412  0.491883  0.931056      fail
4   0.422505  0.924553  0.735670  0.558540  0.519397  0.985467      fail
5   0.301897  0.836333  0.638246  0.523348  0.482116  0.994735      fail
6   0.393781  1.017128  0.789720  0.618960  0.571788  1.119951      fail
7   0.291340  0.904838  0.646619  0.517267  0.480806  0.923504      fail
8   0.383506  0.995479  0.739605  0.555671  0.514146  0.963265      fail
9   0.361945  1.021017  0.750429  0.622411  0.573154  1.158759      fail
10  0.288377  0.766429  0.630426  0.472878  0.436850  0.839594      pass
11  0.395266  0.981072  0.720830  0.516984  0.478388  0.823987      pass
12  0.253478  0.621172  0.475963  0.358281  0.327751  0.620444      pass
13  0.358564  1.113694  0.816377  0.588124  0.544702  0.951773      pass
14  0.343214  0.827264  0.631506  0.439659  0.408516  0.680465      pass
15  0.284500  0.763141  0.564902  0.416168  0.383663  0.690237      pass
16  0.266346  0.657015  0.491432  0.379785  0.353406  0.671717      pass
17  0.401710  1.045057  0.762291  0.599782  0.554371  1.077693      pass
18  0.257553  0.652728  0.497459  0.369605  0.344888  0.613244      pass
19  0.333525  0.864115  0.619275  0.439045  0.408917  0.678082      pass

BARINEL SCORES

       sxdg 0      cx 2       h 1      cx 3      cx 4      cx 5
sum  0.569101  0.551712  0.551198  0.536807  0.535108  0.528116

TARANTULA SCORES

       sxdg 0      cx 2       h 1      cx 3      cx 4      cx 5
sum  0.569101  0.551712  0.551198  0.536807  0.535108  0.528116

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_ry_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.65it/s]
100%|██████████| 10/10 [00:00<00:00, 10.16it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      ry 0 pass/fail
0   0.406591  0.952390  0.693695  0.512633  0.472018  0.910958      fail
1   0.482955  1.040088  0.747610  0.550255  0.510621  0.963236      fail
2   0.470749  1.034808  0.787384  0.564522  0.527664  0.994719      fail
3   0.389155  0.848090  0.664475  0.512016  0.479557  0.918495      fail
4   0.484626  0.997496  0.786342  0.553379  0.510383  1.028520      fail
5   0.420634  0.968930  0.784253  0.575345  0.532763  1.001530      fail
6   0.409527  1.023300  0.807995  0.643206  0.598917  1.081970      fail
7   0.371849  0.891285  0.688431  0.541563  0.504355  0.942290      fail
8   0.418426  1.066510  0.820283  0.630706  0.584560  1.130052      fail
9   0.405886  0.920201  0.715712  0.523431  0.488423  0.908480      fail
10  0.277571  0.728039  0.580113  0.469678  0.434604  0.807459      pass
11  0.348468  0.767809  0.584478  0.445439  0.407276  0.821110      pass
12  0.441734  0.899272  0.696790  0.519525  0.477691  0.891387      pass
13  0.383074  0.885143  0.643939  0.475440  0.439182  0.846227      pass
14  0.390214  0.948052  0.717954  0.533437  0.495230  0.881029      pass
15  0.291224  0.851641  0.691473  0.532345  0.493102  0.873216      pass
16  0.379685  0.989304  0.768246  0.553661  0.510445  0.952762      pass
17  0.429147  1.006292  0.752547  0.570053  0.526866  1.027452      pass
18  0.275736  0.710188  0.533707  0.391722  0.365099  0.627525      pass
19  0.287098  0.770248  0.621516  0.480381  0.443064  0.783316      pass

BARINEL SCORES

         cx 5      ry 0      cx 4      cx 3       h 1      cx 2
sum  0.548713  0.537211  0.532436  0.532137  0.531459  0.530031

TARANTULA SCORES

         cx 5      ry 0      cx 4      cx 3       h 1      cx 2
sum  0.548713  0.537211  0.532436  0.532137  0.531459  0.530031

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_ccx_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  5.03it/s]
100%|██████████| 10/10 [00:01<00:00,  5.36it/s]

        cx 5      cx 4      cx 3     ccx 2      cx 1       h 0 pass/fail
0   0.469836  1.172020  0.861090  0.830628  0.524521  0.482739      fail
1   0.278144  0.733699  0.603102  0.536239  0.362061  0.334283      fail
2   0.366878  0.773438  0.632690  0.565779  0.360961  0.334004      fail
3   0.276273  0.689049  0.536503  0.498436  0.330790  0.307302      fail
4   0.481436  1.028257  0.817401  0.747375  0.490684  0.454805      fail
5   0.502953  1.128609  0.900828  0.818699  0.526835  0.482407      fail
6   0.267569  0.812356  0.657365  0.590358  0.371777  0.342706      fail
7   0.306424  0.801059  0.639078  0.581975  0.374507  0.350886      fail
8   0.402398  1.049508  0.834957  0.760104  0.488840  0.449938      fail
9   0.336238  0.861959  0.656248  0.616129  0.385657  0.355993      fail
10  0.358046  0.814369  0.632142  0.586467  0.374818  0.347803      pass
11  0.271072  0.657097  0.470358  0.464585  0.299742  0.273553      pass
12  0.195982  0.477958  0.358872  0.341041  0.221577  0.202946      pass
13  0.303891  0.721651  0.577761  0.525342  0.343119  0.320157      pass
14  0.448771  1.009264  0.771690  0.722996  0.467968  0.432549      pass
15  0.371330  0.900327  0.677282  0.643774  0.415678  0.379131      pass
16  0.414292  0.897699  0.684112  0.643208  0.415897  0.382849      pass
17  0.387231  0.893135  0.635468  0.626690  0.413838  0.377214      pass
18  0.285101  0.696297  0.516512  0.494662  0.304867  0.280562      pass
19  0.339120  0.911328  0.658252  0.640414  0.409839  0.375314      pass

BARINEL SCORES

        cx 3       h 0     ccx 2      cx 1      cx 4     cx 5
sum  0.54408  0.535983  0.535004  0.534836  0.531441  0.52218

TARANTULA SCORES

        cx 3       h 0     ccx 2      cx 1      cx 4     cx 5
sum  0.54408  0.535983  0.535004  0.534836  0.531441  0.52218

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_h_inGap_2_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.05it/s]
100%|██████████| 10/10 [00:00<00:00, 10.33it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       h 0 pass/fail
0   0.326144  0.790416  0.634609  0.485757  0.444733  0.438788      fail
1   0.408176  0.956318  0.734489  0.566313  0.522071  0.498259      fail
2   0.472236  0.981499  0.741415  0.626739  0.577709  0.558433      fail
3   0.353834  0.812255  0.703670  0.533411  0.496508  0.481672      fail
4   0.530168  1.181572  0.886458  0.679912  0.633226  0.609349      fail
5   0.319489  0.977075  0.758264  0.575325  0.536060  0.520973      fail
6   0.321949  0.963573  0.762895  0.635357  0.589559  0.571191      fail
7   0.281586  0.741542  0.573760  0.462826  0.425485  0.412002      fail
8   0.421019  0.898001  0.674390  0.550133  0.506230  0.488206      fail
9   0.332924  0.909177  0.677829  0.525234  0.488892  0.473132      fail
10  0.263817  0.588670  0.446381  0.319842  0.301343  0.291242      pass
11  0.226605  0.744481  0.541930  0.426102  0.394887  0.378476      pass
12  0.410812  0.823426  0.618828  0.453086  0.420838  0.402683      pass
13  0.338566  0.807974  0.672092  0.539932  0.501528  0.488756      pass
14  0.212662  0.740525  0.541045  0.394889  0.370563  0.358124      pass
15  0.448920  0.906324  0.712518  0.490606  0.459646  0.448977      pass
16  0.377160  0.773282  0.594672  0.463816  0.432322  0.409870      pass
17  0.365297  1.026230  0.778641  0.590144  0.546310  0.525180      pass
18  0.403174  0.930126  0.707794  0.546053  0.498924  0.478428      pass
19  0.347282  0.880803  0.673271  0.505707  0.474693  0.454967      pass

BARINEL SCORES

         cx 2       h 0       h 1      cx 3      cx 4      cx 5
sum  0.543912  0.543887  0.542582  0.532029  0.528382  0.526057

TARANTULA SCORES

         cx 2       h 0       h 1      cx 3      cx 4      cx 5
sum  0.543912  0.543887  0.542582  0.532029  0.528382  0.526057

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_ccx_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  5.52it/s]
100%|██████████| 10/10 [00:01<00:00,  5.21it/s]

        cx 5     ccx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.395514  1.106092  0.773978  0.592617  0.441323  0.407359      fail
1   0.440797  1.157948  0.767637  0.595650  0.451870  0.414182      fail
2   0.404828  1.091518  0.705978  0.531172  0.406465  0.377301      fail
3   0.526141  1.298576  0.875171  0.701078  0.535751  0.497458      fail
4   0.531568  1.239576  0.816239  0.631753  0.483418  0.445176      fail
5   0.469564  1.095174  0.770905  0.580722  0.432276  0.401622      fail
6   0.417780  1.153410  0.762889  0.583287  0.449517  0.416156      fail
7   0.387631  1.157473  0.804463  0.611989  0.455724  0.420976      fail
8   0.394898  1.061716  0.732134  0.576723  0.435849  0.404526      fail
9   0.385317  1.052578  0.678117  0.507732  0.375485  0.350106      fail
10  0.202178  0.612157  0.404031  0.301947  0.239210  0.221643      pass
11  0.377457  0.988145  0.672897  0.524973  0.388344  0.359907      pass
12  0.273713  1.064697  0.736631  0.563787  0.426635  0.395610      pass
13  0.354189  0.971006  0.648724  0.498125  0.380090  0.350222      pass
14  0.312100  0.899863  0.586606  0.451604  0.331101  0.305881      pass
15  0.312830  1.070293  0.707642  0.536928  0.410528  0.380774      pass
16  0.276696  0.810767  0.531925  0.407169  0.298569  0.279295      pass
17  0.363529  1.021371  0.654215  0.500198  0.373616  0.344323      pass
18  0.301535  1.030815  0.699174  0.539232  0.403311  0.372039      pass
19  0.333296  1.020358  0.687614  0.530045  0.405947  0.379612      pass

BARINEL SCORES

         cx 5      cx 1       h 0      cx 2      cx 3     ccx 4
sum  0.583529  0.549866  0.549544  0.549166  0.548443  0.546035

TARANTULA SCORES

         cx 5      cx 1       h 0      cx 2      cx 3     ccx 4
sum  0.583529  0.549866  0.549544  0.549166  0.548443  0.546035

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_y_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.70it/s]
100%|██████████| 10/10 [00:00<00:00, 10.20it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       y 0 pass/fail
0   0.343957  0.959758  0.703994  0.518859  0.482374  0.970666      fail
1   0.393093  0.930715  0.715347  0.547352  0.511609  0.925384      fail
2   0.278007  0.837007  0.594738  0.441897  0.407966  0.798179      fail
3   0.384099  1.077622  0.772222  0.597244  0.550559  1.102111      fail
4   0.378602  1.060443  0.837525  0.651859  0.604927  1.237250      fail
5   0.418185  1.057354  0.833233  0.627671  0.580911  1.165621      fail
6   0.422812  1.079981  0.843609  0.647296  0.601101  1.159225      fail
7   0.393899  0.964046  0.712445  0.528396  0.492291  0.971468      fail
8   0.374398  1.080030  0.846653  0.651984  0.602186  1.190725      fail
9   0.415672  0.973412  0.780818  0.571877  0.531302  1.069832      fail
10  0.422430  0.919167  0.702345  0.497725  0.459638  0.804298      pass
11  0.379764  0.910700  0.748350  0.579707  0.532841  1.006176      pass
12  0.366111  0.808927  0.638569  0.450086  0.416973  0.770473      pass
13  0.405410  0.926891  0.749148  0.541102  0.502353  0.932410      pass
14  0.467583  1.154119  0.895086  0.636876  0.588567  1.218422      pass
15  0.332446  0.934776  0.688505  0.549108  0.507384  1.007007      pass
16  0.364404  0.970420  0.766437  0.613572  0.564215  1.143956      pass
17  0.147837  0.432561  0.343726  0.264531  0.243927  0.410554      pass
18  0.419408  0.855519  0.622635  0.489796  0.450477  0.869412      pass
19  0.293507  0.719250  0.585466  0.447684  0.414169  0.747603      pass

BARINEL SCORES

          y 0      cx 4       h 1      cx 2      cx 3      cx 5
sum  0.543079  0.537207  0.534078  0.532901  0.531303  0.513769

TARANTULA SCORES

          y 0      cx 4       h 1      cx 2      cx 3      cx 5
sum  0.543079  0.537207  0.534078  0.532901  0.531303  0.513769

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_h_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.14it/s]
100%|██████████| 10/10 [00:00<00:00, 10.06it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       h 0 pass/fail
0   0.331548  0.810269  0.675927  0.467793  0.434277  0.417580      fail
1   0.485176  0.961763  0.764110  0.566715  0.523927  0.502904      fail
2   0.371492  0.979472  0.765890  0.555755  0.520032  0.502461      fail
3   0.475043  0.989606  0.773567  0.619972  0.577469  0.551633      fail
4   0.489824  1.124671  0.867242  0.682498  0.631647  0.607326      fail
5   0.340519  1.038223  0.808575  0.628659  0.582337  0.561162      fail
6   0.407737  0.941005  0.694879  0.555361  0.514759  0.503440      fail
7   0.419528  1.029686  0.835208  0.568153  0.527617  0.503437      fail
8   0.401145  0.978022  0.771067  0.562515  0.519985  0.496885      fail
9   0.273748  0.872245  0.697543  0.546271  0.510303  0.490937      fail
10  0.366407  0.968826  0.710948  0.497787  0.465108  0.453278      pass
11  0.358638  0.904363  0.712575  0.570731  0.534041  0.516820      pass
12  0.387217  0.912272  0.727884  0.609900  0.562074  0.536728      pass
13  0.357905  0.790777  0.585903  0.435340  0.406289  0.386258      pass
14  0.368193  0.820828  0.595913  0.473303  0.438675  0.420277      pass
15  0.370784  0.951904  0.767315  0.581911  0.537993  0.513975      pass
16  0.349494  0.870740  0.700243  0.534998  0.496217  0.472083      pass
17  0.339929  0.865935  0.639196  0.489834  0.452623  0.439803      pass
18  0.274760  0.929490  0.686245  0.509889  0.469634  0.451320      pass
19  0.438423  1.033249  0.797726  0.608604  0.564552  0.547850      pass

BARINEL SCORES

         cx 5     cx 3       h 0       h 1      cx 2     cx 4
sum  0.525239  0.52504  0.520219  0.520213  0.519944  0.51802

TARANTULA SCORES

         cx 5     cx 3       h 0       h 1      cx 2     cx 4
sum  0.525239  0.52504  0.520219  0.520213  0.519944  0.51802

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_rxx_inGap_4_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.34it/s]
100%|██████████| 10/10 [00:00<00:00, 12.05it/s]

        cx 5      cx 4     rxx 3      cx 2      cx 1       h 0 pass/fail
0   0.401041  0.985369  1.504863  0.712936  0.560315  0.518147      fail
1   0.347047  0.858958  1.263701  0.631170  0.499290  0.456379      fail
2   0.306799  0.866099  1.211576  0.654638  0.483844  0.445772      fail
3   0.345424  0.943652  1.446754  0.669360  0.509975  0.472572      fail
4   0.348928  0.863702  1.285477  0.637389  0.479873  0.446376      fail
5   0.396427  0.905508  1.411556  0.611789  0.499798  0.460963      fail
6   0.424052  0.897984  1.426328  0.605941  0.468704  0.430465      fail
7   0.336084  0.897637  1.407500  0.595919  0.455281  0.418495      fail
8   0.377034  1.003822  1.531945  0.706900  0.557320  0.514238      fail
9   0.408950  0.995689  1.657547  0.695360  0.541172  0.498763      fail
10  0.314414  0.755854  1.036226  0.564868  0.411731  0.380254      pass
11  0.346838  0.926261  1.359778  0.673413  0.507019  0.469797      pass
12  0.334331  0.806874  1.270985  0.566523  0.456393  0.419928      pass
13  0.410060  0.935595  1.329146  0.693160  0.509105  0.467632      pass
14  0.286311  0.729079  1.099390  0.519327  0.375222  0.349410      pass
15  0.323144  0.690602  1.094917  0.486385  0.373721  0.342022      pass
16  0.353398  0.947153  1.309255  0.704911  0.522483  0.475323      pass
17  0.402571  1.080707  1.505831  0.794315  0.616458  0.565472      pass
18  0.239299  0.640802  0.921713  0.459721  0.352003  0.324329      pass
19  0.301103  0.834298  1.268957  0.633746  0.487397  0.444004      pass

BARINEL SCORES

        rxx 3      cx 5      cx 4       h 0      cx 1      cx 2
sum  0.537031  0.527153  0.524798  0.523819  0.522967  0.516843

TARANTULA SCORES

        rxx 3      cx 5      cx 4       h 0      cx 1      cx 2
sum  0.537031  0.527153  0.524798  0.523819  0.522967  0.516843

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_y_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.62it/s]
100%|██████████| 10/10 [00:00<00:00, 10.01it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       y 0 pass/fail
0   0.499631  0.998947  0.754072  0.570785  0.530691  1.145286      fail
1   0.383123  0.881295  0.665208  0.495608  0.465380  0.882868      fail
2   0.567455  1.203909  0.912195  0.708147  0.656375  1.386374      fail
3   0.414447  0.912445  0.713279  0.521964  0.486772  0.983973      fail
4   0.413581  0.944095  0.693701  0.536112  0.498510  0.965041      fail
5   0.440586  1.035390  0.819027  0.625718  0.577005  1.151969      fail
6   0.485118  1.068537  0.803308  0.623328  0.579033  1.226545      fail
7   0.406542  0.814881  0.641861  0.492330  0.451312  0.909912      fail
8   0.424532  0.877998  0.670493  0.484567  0.447162  0.950675      fail
9   0.438956  1.104866  0.802392  0.603302  0.562600  1.118080      fail
10  0.318352  0.827094  0.636036  0.506000  0.466898  0.910844      pass
11  0.397304  1.046464  0.762009  0.556597  0.515141  0.973448      pass
12  0.230976  0.493608  0.387016  0.298580  0.277149  0.541919      pass
13  0.386392  1.007209  0.775953  0.587545  0.543486  1.105287      pass
14  0.241111  0.700255  0.547363  0.410867  0.379215  0.637586      pass
15  0.184358  0.727771  0.543671  0.418008  0.385010  0.647166      pass
16  0.526925  1.146312  0.832793  0.643843  0.600443  1.241333      pass
17  0.385254  1.057733  0.795038  0.609324  0.562408  1.088111      pass
18  0.328008  0.875053  0.714027  0.502949  0.472340  0.866040      pass
19  0.335830  0.882851  0.652370  0.501215  0.463947  0.901286      pass

BARINEL SCORES

         cx 5       y 0       h 1      cx 3      cx 2      cx 4
sum  0.572963  0.546036  0.529675  0.529361  0.529305  0.528968

TARANTULA SCORES

         cx 5       y 0       h 1      cx 3      cx 2      cx 4
sum  0.572963  0.546036  0.529675  0.529361  0.529305  0.528968

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_cx_inGap_5_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.42it/s]
100%|██████████| 10/10 [00:00<00:00, 11.73it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.514869  1.425262  1.088259  0.789096  0.578512  0.539144      fail
1   0.517842  1.509790  1.151850  0.851583  0.632198  0.586649      fail
2   0.410016  1.253203  0.947827  0.697455  0.514269  0.480637      fail
3   0.358790  1.129013  0.841831  0.683560  0.529007  0.492777      fail
4   0.453098  1.309223  1.036383  0.762369  0.594901  0.554283      fail
5   0.476503  1.419523  1.072443  0.855227  0.670765  0.623339      fail
6   0.384126  1.202223  0.877951  0.660615  0.484042  0.454747      fail
7   0.463508  1.382810  1.081125  0.833402  0.639363  0.595451      fail
8   0.471058  1.357337  1.072060  0.820255  0.630053  0.587728      fail
9   0.453642  1.313894  1.008738  0.746516  0.559415  0.518468      fail
10  0.370040  1.146009  0.854853  0.660728  0.489466  0.451615      pass
11  0.166799  0.611622  0.492974  0.378791  0.284048  0.261139      pass
12  0.244279  0.925209  0.700108  0.544393  0.418236  0.386379      pass
13  0.386364  1.326092  1.005839  0.767034  0.591405  0.557840      pass
14  0.267855  1.000764  0.810339  0.593051  0.448735  0.415359      pass
15  0.412820  1.236607  0.966971  0.734470  0.556635  0.515680      pass
16  0.436468  1.289963  0.990091  0.774823  0.579734  0.532372      pass
17  0.526779  1.445542  1.013869  0.781745  0.574742  0.533580      pass
18  0.356112  1.137462  0.873303  0.623025  0.449591  0.414660      pass
19  0.425231  1.241344  0.944652  0.683192  0.547546  0.508817      pass

BARINEL SCORES

         cx 5       h 0      cx 1      cx 2      cx 3      cx 4
sum  0.556243  0.542744  0.541419  0.540685  0.540503  0.539364

TARANTULA SCORES

         cx 5       h 0      cx 1      cx 2      cx 3      cx 4
sum  0.556243  0.542744  0.541419  0.540685  0.540503  0.539364

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_h_inGap_10_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.12it/s]
100%|██████████| 10/10 [00:00<00:00, 12.92it/s]

         h 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.430844  0.991006  0.732850  0.563025  0.910298  0.893217      fail
1   0.305150  1.199387  0.958901  0.707807  0.890047  0.867857      fail
2   0.374490  1.156660  0.913120  0.702725  0.987248  0.964887      fail
3   0.383742  1.233422  0.912776  0.692544  0.915568  0.898359      fail
4   0.343877  1.087129  0.863862  0.673644  0.903149  0.880027      fail
5   0.338334  1.076624  0.860062  0.662386  0.878803  0.865062      fail
6   0.317316  1.250801  0.927909  0.702791  0.884186  0.866728      fail
7   0.346147  1.230879  0.900342  0.709533  0.948635  0.924767      fail
8   0.313431  1.128904  0.804772  0.646371  0.931051  0.902426      fail
9   0.360114  1.188280  0.895326  0.780914  1.023918  1.005420      fail
10  0.238430  1.109390  0.901185  0.658271  0.687058  0.673367      pass
11  0.239134  0.987280  0.784762  0.610330  0.828472  0.803839      pass
12  0.361430  1.068115  0.833765  0.669627  0.950572  0.933742      pass
13  0.242221  0.785633  0.585333  0.482737  0.516188  0.507862      pass
14  0.318095  1.122342  0.866698  0.686602  0.777000  0.762657      pass
15  0.307046  0.997581  0.757062  0.597382  0.752060  0.736319      pass
16  0.176576  0.848884  0.661837  0.485907  0.494267  0.483770      pass
17  0.372768  1.164180  0.821233  0.621166  0.766542  0.759657      pass
18  0.196331  1.037784  0.754183  0.603501  0.713864  0.692065      pass
19  0.182608  1.036478  0.781219  0.619839  0.667877  0.651294      pass

BARINEL SCORES

         h 5      cx 1       h 0      cx 4      cx 2      cx 3
sum  0.57147  0.564498  0.564211  0.531921  0.531311  0.530957

TARANTULA SCORES

         h 5      cx 1       h 0      cx 4      cx 2      cx 3
sum  0.57147  0.564498  0.564211  0.531921  0.531311  0.530957

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_sx_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.86it/s]
100%|██████████| 10/10 [00:00<00:00, 12.50it/s]

      sxdg 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.213857  1.237370  0.990699  0.734277  0.550154  0.506476      fail
1   1.011323  1.072036  0.793190  0.606633  0.448706  0.418829      fail
2   1.154800  1.181119  0.896746  0.642490  0.505294  0.469245      fail
3   1.654264  1.350835  1.049795  0.754532  0.575484  0.523194      fail
4   1.396727  1.199621  0.929904  0.686112  0.530294  0.488736      fail
5   1.130939  1.032905  0.791942  0.596772  0.464544  0.419484      fail
6   1.067633  1.073936  0.790979  0.591984  0.455221  0.417857      fail
7   0.894340  0.875155  0.656889  0.518235  0.407494  0.373409      fail
8   1.010342  1.117391  0.836719  0.618526  0.448408  0.412701      fail
9   1.314365  1.302323  0.927537  0.701500  0.535551  0.490107      fail
10  0.780084  1.033786  0.854542  0.637946  0.503520  0.459575      pass
11  1.026803  1.065219  0.829984  0.606808  0.459970  0.423253      pass
12  1.029352  1.214340  0.945258  0.718554  0.527821  0.490662      pass
13  1.130644  1.119988  0.873199  0.631299  0.497955  0.458981      pass
14  1.283993  1.137659  0.875115  0.649371  0.473237  0.436402      pass
15  0.906185  1.041246  0.784718  0.641055  0.493594  0.455911      pass
16  0.751807  0.938358  0.656092  0.488055  0.369182  0.335380      pass
17  1.146378  1.173291  0.867966  0.680161  0.513652  0.476342      pass
18  0.800641  1.110658  0.871476  0.627283  0.476774  0.440204      pass
19  0.873392  0.911118  0.688684  0.516092  0.381870  0.350810      pass

BARINEL SCORES

       sxdg 5      cx 4     cx 3      cx 1      h 0      cx 2
sum  0.549108  0.515707  0.51234  0.511622  0.51088  0.510059

TARANTULA SCORES

       sxdg 5      cx 4     cx 3      cx 1      h 0      cx 2
sum  0.549108  0.515707  0.51234  0.511622  0.51088  0.510059

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ccx_inGap_8_.qasm

100%|██████████| 10/10 [00:02<00:00,  3.38it/s]
100%|██████████| 10/10 [00:03<00:00,  2.96it/s]

       ccx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.617449  1.023793  0.923530  0.694687  0.558345  0.513515      fail
1   0.562599  0.991233  0.852958  0.610541  0.498348  0.455651      fail
2   0.510893  0.829516  0.700389  0.514164  0.414886  0.383900      fail
3   0.478470  0.733467  0.664328  0.470911  0.383526  0.355075      fail
4   0.494207  0.870600  0.717393  0.493096  0.403797  0.370993      fail
5   0.451770  0.774399  0.650321  0.457139  0.381558  0.350324      fail
6   0.487025  0.858627  0.809050  0.560846  0.454460  0.418692      fail
7   0.558468  0.861429  0.802176  0.592030  0.483388  0.441078      fail
8   0.525335  0.915089  0.800107  0.566312  0.471034  0.429973      fail
9   0.595336  0.958791  0.803433  0.577450  0.469421  0.439467      fail
10  0.289447  0.511460  0.452787  0.345883  0.274697  0.252340      pass
11  0.522796  0.843467  0.795477  0.575576  0.465550  0.428746      pass
12  0.489901  0.804267  0.679156  0.478999  0.390249  0.358947      pass
13  0.534697  0.879551  0.776884  0.531127  0.436978  0.406245      pass
14  0.559604  0.936547  0.772365  0.536751  0.448953  0.413901      pass
15  0.442747  0.789447  0.687538  0.483325  0.395162  0.365207      pass
16  0.613727  0.989759  0.856796  0.603682  0.487274  0.448365      pass
17  0.359550  0.587078  0.533738  0.362342  0.290926  0.268619      pass
18  0.519336  0.885521  0.751711  0.504405  0.410238  0.380319      pass
19  0.489416  0.857224  0.713524  0.474415  0.390253  0.360737      pass

BARINEL SCORES

         cx 1      cx 2       h 0      cx 3     ccx 5      cx 4
sum  0.531054  0.530702  0.530301  0.523865  0.522782  0.521674

TARANTULA SCORES

         cx 1      cx 2       h 0      cx 3     ccx 5      cx 4
sum  0.531054  0.530702  0.530301  0.523865  0.522782  0.521674

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ccx_inGap_9_.qasm

100%|██████████| 10/10 [00:03<00:00,  3.19it/s]
100%|██████████| 10/10 [00:02<00:00,  3.41it/s]

       ccx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.679560  0.894939  0.706597  0.680585  0.481721  0.445370      fail
1   0.576962  0.738431  0.547873  0.466547  0.328525  0.307582      fail
2   0.692277  0.942084  0.792103  0.697301  0.488890  0.450900      fail
3   0.603912  0.812545  0.637832  0.563202  0.389883  0.361781      fail
4   0.634601  0.913159  0.735669  0.693796  0.491814  0.454332      fail
5   0.727883  1.001727  0.772561  0.699927  0.497643  0.454273      fail
6   0.625841  0.743091  0.566960  0.507383  0.361609  0.336377      fail
7   0.688791  1.008733  0.794043  0.711372  0.503583  0.464758      fail
8   0.707002  0.909213  0.751476  0.714967  0.499656  0.455598      fail
9   0.602970  0.777560  0.648311  0.602040  0.433388  0.399000      fail
10  0.647454  0.895767  0.716965  0.652265  0.460670  0.422284      pass
11  0.687824  1.008589  0.781139  0.745036  0.516183  0.477287      pass
12  0.623360  0.894915  0.617307  0.572268  0.406251  0.374986      pass
13  0.693067  0.934520  0.746906  0.654870  0.462629  0.427434      pass
14  0.811492  1.095389  0.868493  0.776305  0.540262  0.500544      pass
15  0.515767  0.701205  0.529475  0.496933  0.355667  0.326248      pass
16  0.654868  0.875719  0.709985  0.670384  0.475103  0.436542      pass
17  0.592781  0.811541  0.636937  0.594748  0.407314  0.377078      pass
18  0.561905  0.738940  0.574174  0.521786  0.360362  0.335960      pass
19  0.554341  0.756518  0.630081  0.583708  0.413891  0.383427      pass

BARINEL SCORES

        ccx 5      cx 3      cx 1       h 0     cx 2      cx 4
sum  0.507644  0.505157  0.504416  0.504162  0.50273  0.500813

TARANTULA SCORES

        ccx 5      cx 3      cx 1       h 0     cx 2      cx 4
sum  0.507644  0.505157  0.504416  0.504162  0.50273  0.500813

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cx_inGap_10_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.39it/s]
100%|██████████| 10/10 [00:01<00:00,  9.67it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.402802  1.035713  0.726286  0.605533  0.490058  0.452212      fail
1   0.342744  0.845140  0.575068  0.456316  0.344514  0.317700      fail
2   0.497961  0.992783  0.701413  0.626550  0.485770  0.446846      fail
3   0.453701  1.070023  0.850888  0.658547  0.498215  0.456023      fail
4   0.436761  1.012854  0.845811  0.734872  0.568673  0.525632      fail
5   0.321542  0.983072  0.753748  0.642481  0.475187  0.437600      fail
6   0.396954  0.879775  0.727791  0.627582  0.472036  0.433860      fail
7   0.490179  1.086975  0.791515  0.748376  0.553140  0.506507      fail
8   0.328431  0.877795  0.596200  0.499886  0.378716  0.352033      fail
9   0.396788  0.956183  0.738414  0.623320  0.464918  0.428209      fail
10  0.159146  0.606689  0.502327  0.388547  0.291007  0.271474      pass
11  0.351945  0.960957  0.736802  0.611504  0.424646  0.390408      pass
12  0.296113  0.663654  0.518416  0.468366  0.345613  0.319177      pass
13  0.332415  0.824996  0.659980  0.563684  0.450505  0.413172      pass
14  0.280153  0.743268  0.568569  0.444898  0.326740  0.301603      pass
15  0.311412  0.907352  0.716018  0.621939  0.480123  0.440998      pass
16  0.275993  0.866302  0.679746  0.523542  0.395240  0.368119      pass
17  0.332939  0.943607  0.739522  0.585148  0.467685  0.433033      pass
18  0.384290  0.932413  0.704721  0.595990  0.424699  0.390253      pass
19  0.142280  0.452510  0.316854  0.258656  0.209363  0.194583      pass

BARINEL SCORES

         cx 5      cx 1      h 0      cx 4      cx 2      cx 3
sum  0.586608  0.553564  0.55291  0.552107  0.551445  0.543278

TARANTULA SCORES

         cx 5      cx 1      h 0      cx 4      cx 2      cx 3
sum  0.586608  0.553564  0.55291  0.552107  0.551445  0.543278

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_swap_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  7.09it/s]
100%|██████████| 10/10 [00:01<00:00,  8.59it/s]

        cx 5    swap 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.324660  1.087277  0.855593  0.636275  0.489159  0.443575      fail
1   0.334839  0.897139  0.745866  0.540441  0.431069  0.395480      fail
2   0.423245  1.043384  0.886236  0.677901  0.510738  0.474410      fail
3   0.403533  0.932901  0.792799  0.568065  0.417173  0.389838      fail
4   0.340967  0.869633  0.730684  0.562270  0.409961  0.375181      fail
5   0.411425  1.049572  0.881111  0.643845  0.464135  0.428306      fail
6   0.386437  1.096299  0.901055  0.687922  0.499854  0.462835      fail
7   0.406621  1.032554  0.876099  0.672883  0.506064  0.462632      fail
8   0.331717  0.957615  0.770267  0.569376  0.405581  0.374122      fail
9   0.364506  1.072387  0.849832  0.635609  0.489949  0.448803      fail
10  0.359981  0.839270  0.709477  0.494139  0.379898  0.349534      pass
11  0.207237  0.685911  0.534076  0.403889  0.281729  0.260136      pass
12  0.333555  0.816307  0.683545  0.519387  0.421234  0.385909      pass
13  0.310513  0.860970  0.690634  0.527008  0.429508  0.395023      pass
14  0.321490  0.858938  0.687155  0.503973  0.397153  0.362935      pass
15  0.243971  0.790906  0.627040  0.481718  0.374394  0.344102      pass
16  0.280240  0.748580  0.586707  0.432299  0.321754  0.298285      pass
17  0.426957  0.895066  0.784051  0.588720  0.445035  0.409276      pass
18  0.247367  0.778171  0.608008  0.409821  0.322811  0.295145      pass
19  0.287541  0.702497  0.592581  0.427967  0.293517  0.271028      pass

BARINEL SCORES

        cx 2      cx 3       h 0      cx 1    swap 4      cx 5
sum  0.56399  0.560376  0.557943  0.557694  0.557233  0.552551

TARANTULA SCORES

        cx 2      cx 3       h 0      cx 1    swap 4      cx 5
sum  0.56399  0.560376  0.557943  0.557694  0.557233  0.552551

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_x_inGap_6_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.76it/s]
100%|██████████| 10/10 [00:00<00:00, 10.99it/s]

         x 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.212018  1.511570  1.170701  0.828437  0.629044  0.585150      fail
1   0.669097  1.156574  0.912863  0.654565  0.511950  0.479103      fail
2   0.838928  1.079540  0.813524  0.567913  0.414860  0.385122      fail
3   1.077600  1.408284  1.005331  0.777759  0.604205  0.558463      fail
4   1.015331  1.365089  1.095431  0.826188  0.599058  0.555266      fail
5   0.896324  1.251719  0.976912  0.725821  0.568110  0.533665      fail
6   1.068941  1.413743  1.097849  0.830211  0.635313  0.589414      fail
7   0.818177  1.204657  0.942146  0.721516  0.553810  0.513495      fail
8   0.806317  1.118745  0.819170  0.623445  0.447114  0.414839      fail
9   0.735808  1.118801  0.851267  0.691074  0.530186  0.488076      fail
10  0.698443  1.133895  0.934205  0.659333  0.480999  0.448814      pass
11  0.746097  1.243067  1.012072  0.771316  0.549321  0.513118      pass
12  0.524038  0.987912  0.745199  0.563878  0.409776  0.382158      pass
13  0.803924  1.223939  0.962296  0.745063  0.567847  0.521952      pass
14  0.870408  1.269725  0.938678  0.709017  0.553606  0.515932      pass
15  0.690233  1.148842  0.895010  0.666527  0.491838  0.455623      pass
16  0.623526  1.161195  0.867371  0.625475  0.493695  0.455164      pass
17  0.938930  1.415026  1.225271  0.926834  0.725680  0.673614      pass
18  0.863073  1.128670  0.886370  0.671903  0.527599  0.494292      pass
19  0.807076  1.246161  1.029178  0.824071  0.600211  0.556876      pass

BARINEL SCORES

          x 5      cx 4      cx 3      cx 1       h 0      cx 2
sum  0.547078  0.513631  0.504941  0.504272  0.504202  0.502898

TARANTULA SCORES

          x 5      cx 4      cx 3      cx 1       h 0      cx 2
sum  0.547078  0.513631  0.504941  0.504272  0.504202  0.502898

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ry_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.17it/s]
100%|██████████| 10/10 [00:01<00:00,  8.93it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      ry 0 pass/fail
0   0.393224  0.845186  0.689206  0.541386  0.502587  1.034477      fail
1   0.342460  0.839277  0.647682  0.465478  0.437744  0.806027      fail
2   0.314953  0.839362  0.666629  0.509586  0.476067  0.895778      fail
3   0.434931  1.073937  0.823126  0.600160  0.558103  1.036140      fail
4   0.392962  1.035895  0.819539  0.587899  0.550422  1.067563      fail
5   0.418919  1.042110  0.788323  0.583561  0.538850  1.007395      fail
6   0.404417  1.009863  0.806055  0.593134  0.550183  1.091964      fail
7   0.362483  0.895275  0.705730  0.529791  0.490678  0.975618      fail
8   0.281634  0.833379  0.630961  0.510778  0.472635  0.902436      fail
9   0.512101  1.223738  0.970117  0.745182  0.694247  1.378302      fail
10  0.175385  0.460679  0.338184  0.245023  0.226371  0.379177      pass
11  0.276446  0.690616  0.479414  0.352314  0.329054  0.532503      pass
12  0.314630  0.768480  0.551458  0.399950  0.368711  0.628954      pass
13  0.375135  0.901867  0.718541  0.497267  0.456090  0.910964      pass
14  0.396616  0.921991  0.710974  0.532387  0.498551  0.927501      pass
15  0.278790  0.776865  0.576027  0.438423  0.405196  0.758590      pass
16  0.374153  0.958422  0.719201  0.524230  0.481990  0.865381      pass
17  0.279405  0.798641  0.582730  0.437603  0.403503  0.712850      pass
18  0.271602  0.640650  0.457126  0.384493  0.353755  0.618115      pass
19  0.265484  0.628315  0.529960  0.402112  0.371868  0.743628      pass

BARINEL SCORES

         ry 0       h 1      cx 2      cx 3      cx 5      cx 4
sum  0.590256  0.575078  0.573535  0.571295  0.561934  0.560854

TARANTULA SCORES

         ry 0       h 1      cx 2      cx 3      cx 5      cx 4
sum  0.590256  0.575078  0.573535  0.571295  0.561934  0.560854

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_h_inGap_1_.qasm

100%|██████████| 10/10 [00:01<00:00,  6.08it/s]
100%|██████████| 10/10 [00:01<00:00,  7.47it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       h 0 pass/fail
0   0.376286  1.012203  0.742023  0.576335  0.531719  0.545637      fail
1   0.327894  0.933578  0.708260  0.511350  0.471343  0.489156      fail
2   0.308951  0.898409  0.689217  0.540374  0.495199  0.510786      fail
3   0.363231  0.873787  0.659510  0.472395  0.434281  0.452310      fail
4   0.380562  0.965303  0.684166  0.493509  0.460284  0.472486      fail
5   0.338094  0.993668  0.769547  0.603458  0.558219  0.571435      fail
6   0.310155  0.837059  0.623198  0.458003  0.420485  0.438091      fail
7   0.432457  0.965736  0.720432  0.558901  0.515391  0.529503      fail
8   0.302452  0.873429  0.678635  0.523191  0.482505  0.496468      fail
9   0.401763  0.910020  0.692084  0.527687  0.484975  0.500254      fail
10  0.300333  0.758881  0.579845  0.410668  0.386176  0.393250      pass
11  0.301949  0.821508  0.613279  0.458017  0.424615  0.436064      pass
12  0.172843  0.477702  0.356724  0.279927  0.258252  0.264315      pass
13  0.337734  0.827756  0.594733  0.455758  0.421709  0.434835      pass
14  0.385447  0.959433  0.700922  0.520550  0.485319  0.497361      pass
15  0.337891  0.850231  0.616262  0.467377  0.434103  0.444898      pass
16  0.261227  0.550552  0.451532  0.336802  0.309123  0.319915      pass
17  0.282669  0.887669  0.605954  0.442394  0.409707  0.423926      pass
18  0.391238  0.907958  0.711111  0.550639  0.506554  0.522061      pass
19  0.329177  0.978511  0.738227  0.559907  0.522228  0.532036      pass

BARINEL SCORES

         cx 2       h 0       h 1      cx 3      cx 4      cx 5
sum  0.540174  0.539756  0.538649  0.538594  0.535959  0.533221

TARANTULA SCORES

         cx 2       h 0       h 1      cx 3      cx 4      cx 5
sum  0.540174  0.539756  0.538649  0.538594  0.535959  0.533221

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_h_inGap_8_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.29it/s]
100%|██████████| 10/10 [00:00<00:00, 11.25it/s]

         h 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.339370  1.133825  1.286709  0.724159  0.568182  0.523835      fail
1   0.416200  1.300167  1.486989  0.803252  0.613009  0.567180      fail
2   0.314732  1.172757  1.462335  0.821781  0.614409  0.566416      fail
3   0.370423  1.337424  1.564280  0.886690  0.668460  0.616995      fail
4   0.334815  1.190312  1.330908  0.794341  0.571518  0.526910      fail
5   0.318691  1.215606  1.534067  0.874796  0.703821  0.641183      fail
6   0.307301  0.875358  1.085558  0.595504  0.445814  0.409385      fail
7   0.370351  1.268214  1.623021  0.908233  0.666351  0.616438      fail
8   0.356574  1.349696  1.481192  0.849316  0.604921  0.557800      fail
9   0.341441  1.290163  1.547674  0.873541  0.624422  0.580958      fail
10  0.200810  0.907029  0.959608  0.659836  0.509890  0.467225      pass
11  0.364847  1.277269  1.557781  0.878370  0.648808  0.598100      pass
12  0.301486  1.001494  1.242726  0.654246  0.525217  0.483224      pass
13  0.348535  1.299990  1.541267  0.867933  0.665917  0.612422      pass
14  0.143425  0.841555  0.991904  0.606950  0.436264  0.403887      pass
15  0.308586  0.835513  1.056222  0.605846  0.420483  0.389890      pass
16  0.370557  1.254460  1.611636  0.889870  0.677487  0.617465      pass
17  0.194083  0.896411  1.167084  0.733740  0.558265  0.516876      pass
18  0.254604  0.944142  1.069617  0.650026  0.493036  0.460546      pass
19  0.305756  1.126061  1.356983  0.830402  0.621605  0.575182      pass

BARINEL SCORES

          h 5     cx 4      cx 3      cx 2     cx 1      h 0
sum  0.554068  0.53885  0.534274  0.524321  0.52251  0.52247

TARANTULA SCORES

          h 5     cx 4      cx 3      cx 2     cx 1      h 0
sum  0.554068  0.53885  0.534274  0.524321  0.52251  0.52247

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rx_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.47it/s]
100%|██████████| 10/10 [00:01<00:00,  9.70it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      rx 0 pass/fail
0   0.361886  0.979004  0.795125  0.611822  0.572031  1.086071      fail
1   0.355354  1.067193  0.851375  0.617870  0.574569  1.056762      fail
2   0.345293  0.861978  0.662298  0.496779  0.460615  0.904288      fail
3   0.405266  1.001825  0.745971  0.601257  0.558005  1.059440      fail
4   0.324892  0.991077  0.762822  0.575781  0.529147  1.048685      fail
5   0.396896  1.050546  0.784792  0.615362  0.568652  1.149626      fail
6   0.368418  0.952507  0.715412  0.526950  0.487805  0.983342      fail
7   0.463067  1.045820  0.832386  0.599688  0.556105  1.096021      fail
8   0.361612  0.923006  0.653440  0.487933  0.453264  0.947044      fail
9   0.306101  0.917346  0.678647  0.506915  0.473517  0.921304      fail
10  0.447164  1.037339  0.755007  0.590997  0.545906  0.943031      pass
11  0.334129  0.875856  0.694882  0.545829  0.500648  1.021034      pass
12  0.199848  0.908477  0.695032  0.525682  0.483993  0.925178      pass
13  0.316836  0.831247  0.622618  0.460357  0.427983  0.836932      pass
14  0.238124  0.657609  0.434130  0.309289  0.288899  0.485247      pass
15  0.242056  0.649640  0.540034  0.404707  0.372295  0.665100      pass
16  0.421753  0.889001  0.640384  0.504355  0.465696  0.773522      pass
17  0.322050  0.806783  0.555856  0.408662  0.381110  0.686454      pass
18  0.364228  0.786684  0.647431  0.499831  0.461313  0.858340      pass
19  0.249443  0.718011  0.540167  0.392349  0.366489  0.558344      pass

BARINEL SCORES

         rx 0      cx 3       h 1      cx 2      cx 4      cx 5
sum  0.569406  0.549851  0.549295  0.548544  0.545392  0.540528

TARANTULA SCORES

         rx 0      cx 3       h 1      cx 2      cx 4      cx 5
sum  0.569406  0.549851  0.549295  0.548544  0.545392  0.540528

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_y_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.23it/s]
100%|██████████| 10/10 [00:00<00:00, 12.77it/s]

         y 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.939448  1.404203  1.079547  0.767036  0.570077  0.529517      fail
1   1.320457  1.387211  1.034552  0.758621  0.573806  0.532366      fail
2   0.789984  1.110760  0.861889  0.654908  0.448642  0.419762      fail
3   0.750801  1.157402  0.934904  0.694123  0.552808  0.514460      fail
4   0.886961  1.163250  0.859667  0.676107  0.521701  0.484586      fail
5   0.961006  1.018048  0.847508  0.623813  0.459499  0.429761      fail
6   0.697180  1.135880  0.905414  0.652596  0.502851  0.463739      fail
7   1.081957  1.457480  1.120136  0.835828  0.641457  0.588083      fail
8   1.161957  1.353297  1.158743  0.865789  0.652652  0.605641      fail
9   1.045561  1.354223  1.050435  0.861020  0.624048  0.582974      fail
10  0.697313  1.284204  1.040856  0.819424  0.628933  0.578257      pass
11  0.909798  1.180462  0.908417  0.680243  0.505647  0.465230      pass
12  0.523908  0.704590  0.594253  0.464266  0.341962  0.315915      pass
13  0.751224  1.046566  0.854762  0.674135  0.505104  0.469284      pass
14  0.644585  1.141131  0.973063  0.692836  0.528425  0.490481      pass
15  0.867320  1.105581  0.751837  0.610212  0.420104  0.395650      pass
16  0.785336  1.148162  0.751484  0.599654  0.480990  0.447759      pass
17  0.871839  1.127674  0.839040  0.618020  0.472019  0.433944      pass
18  0.902203  1.392268  1.013949  0.763182  0.543841  0.505734      pass
19  0.868968  1.013743  0.782965  0.663522  0.468879  0.429718      pass

BARINEL SCORES

         y 5      cx 3       h 0      cx 1      cx 4      cx 2
sum  0.55192  0.536545  0.531959  0.531198  0.529498  0.528777

TARANTULA SCORES

         y 5      cx 3       h 0      cx 1      cx 4      cx 2
sum  0.55192  0.536545  0.531959  0.531198  0.529498  0.528777

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rxx_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.00it/s]
100%|██████████| 10/10 [00:00<00:00, 10.41it/s]

        cx 5      cx 4      cx 3     rxx 2      cx 1       h 0 pass/fail
0   0.443345  0.995359  0.750317  1.256613  0.560960  0.523862      fail
1   0.399604  1.108690  0.876852  1.345377  0.659644  0.611652      fail
2   0.338435  0.935669  0.768075  1.135051  0.606019  0.564095      fail
3   0.445772  0.986031  0.740451  1.088763  0.550393  0.508154      fail
4   0.525602  1.189253  0.953462  1.545496  0.715293  0.660975      fail
5   0.382377  0.996439  0.699608  1.084958  0.521254  0.485193      fail
6   0.326339  0.872541  0.659904  1.149054  0.473179  0.442503      fail
7   0.459648  0.967927  0.722981  1.206282  0.514272  0.475848      fail
8   0.329589  0.780900  0.596764  1.048413  0.398432  0.376098      fail
9   0.315117  0.887209  0.663882  1.087532  0.480396  0.449168      fail
10  0.350758  0.894721  0.709415  1.099052  0.533737  0.489728      pass
11  0.335921  0.861760  0.646088  0.895941  0.508415  0.471750      pass
12  0.333590  0.756966  0.603223  0.962882  0.441086  0.404092      pass
13  0.481088  1.207850  0.923489  1.314704  0.734690  0.675187      pass
14  0.381896  0.923537  0.659983  0.940409  0.523067  0.476194      pass
15  0.248989  0.601655  0.459652  0.641944  0.346248  0.323162      pass
16  0.160638  0.476509  0.346289  0.498639  0.290047  0.270538      pass
17  0.318230  0.771216  0.598373  0.930636  0.421133  0.393024      pass
18  0.353172  0.786745  0.594068  0.860144  0.458015  0.423416      pass
19  0.163290  0.449890  0.374502  0.539311  0.297375  0.278398      pass

BARINEL SCORES

      rxx 2      cx 5      cx 4      cx 3       h 0      cx 1
sum  0.5791  0.559087  0.556993  0.556836  0.547945  0.546146

TARANTULA SCORES

      rxx 2      cx 5      cx 4      cx 3       h 0      cx 1
sum  0.5791  0.559087  0.556993  0.556836  0.547945  0.546146

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_h_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.76it/s]
100%|██████████| 10/10 [00:01<00:00,  9.25it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       h 0 pass/fail
0   0.426666  0.914313  0.681297  0.490438  0.455758  0.408949      fail
1   0.527658  1.084654  0.795580  0.610607  0.567569  0.516191      fail
2   0.446267  0.868240  0.653469  0.499346  0.469056  0.417439      fail
3   0.424061  0.924182  0.689952  0.522537  0.486503  0.435270      fail
4   0.408265  1.064403  0.782799  0.582438  0.539813  0.485982      fail
5   0.450630  1.006380  0.786277  0.600464  0.556695  0.498493      fail
6   0.369807  1.020633  0.766912  0.576444  0.539305  0.490213      fail
7   0.331533  0.925732  0.695813  0.529580  0.496431  0.459505      fail
8   0.503038  1.055355  0.863348  0.627138  0.584333  0.518912      fail
9   0.373337  0.854696  0.672134  0.515498  0.479527  0.434251      fail
10  0.245664  0.597643  0.478984  0.346891  0.324611  0.298346      pass
11  0.219342  0.493365  0.395401  0.298352  0.275348  0.255654      pass
12  0.367987  1.028650  0.725012  0.548718  0.507151  0.460500      pass
13  0.413895  0.957942  0.748199  0.587233  0.543022  0.485417      pass
14  0.345695  0.997512  0.766402  0.573282  0.528090  0.480302      pass
15  0.221590  0.538124  0.449870  0.345762  0.321130  0.292103      pass
16  0.471379  1.113852  0.812127  0.648514  0.600172  0.537283      pass
17  0.362835  0.798431  0.624456  0.456992  0.424058  0.374620      pass
18  0.267348  0.821949  0.639487  0.510063  0.473355  0.435779      pass
19  0.353658  0.895800  0.691362  0.520488  0.485732  0.437982      pass

BARINEL SCORES

         cx 5      cx 4      cx 3       h 1       h 0      cx 2
sum  0.565855  0.541068  0.538497  0.535843  0.534805  0.534559

TARANTULA SCORES

         cx 5      cx 4      cx 3       h 1       h 0      cx 2
sum  0.565855  0.541068  0.538497  0.535843  0.534805  0.534559

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_y_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.75it/s]
100%|██████████| 10/10 [00:01<00:00,  9.32it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       y 0 pass/fail
0   0.427429  0.972031  0.732052  0.524615  0.489554  0.914587      fail
1   0.334076  0.990983  0.776459  0.568237  0.532767  1.018560      fail
2   0.355630  0.976194  0.788603  0.618067  0.575315  1.143992      fail
3   0.357050  1.008413  0.789579  0.594706  0.547091  1.108758      fail
4   0.459677  1.114520  0.896975  0.701736  0.652740  1.322330      fail
5   0.417911  1.126591  0.856918  0.635383  0.590623  1.148957      fail
6   0.331131  0.841279  0.661508  0.482076  0.451491  0.914853      fail
7   0.331351  0.919217  0.756500  0.590001  0.549725  1.116805      fail
8   0.342295  0.851079  0.719876  0.513559  0.480379  1.041326      fail
9   0.382355  0.968230  0.774302  0.593176  0.550785  1.129865      fail
10  0.297812  0.720538  0.503316  0.398405  0.366382  0.626674      pass
11  0.387180  0.831546  0.672792  0.501967  0.459423  0.959649      pass
12  0.345515  0.836319  0.645068  0.539239  0.498008  0.978678      pass
13  0.396216  0.915525  0.729925  0.561945  0.521298  1.064450      pass
14  0.373840  0.886301  0.668404  0.503748  0.466072  0.930252      pass
15  0.323991  0.785328  0.606182  0.463913  0.428323  0.794933      pass
16  0.261605  0.726356  0.507195  0.389917  0.359526  0.622787      pass
17  0.356475  0.912890  0.726618  0.534548  0.494327  0.979280      pass
18  0.425299  0.925741  0.757080  0.566497  0.523599  1.068995      pass
19  0.322141  0.792244  0.571891  0.449368  0.415801  0.734099      pass

BARINEL SCORES

          y 0      cx 3       h 1      cx 2      cx 4      cx 5
sum  0.553523  0.548238  0.544594  0.542494  0.539659  0.517211

TARANTULA SCORES

          y 0      cx 3       h 1      cx 2      cx 4      cx 5
sum  0.553523  0.548238  0.544594  0.542494  0.539659  0.517211

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_x_inGap_10_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.37it/s]
100%|██████████| 10/10 [00:00<00:00, 12.14it/s]

         x 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.009159  1.286484  0.886384  0.731579  0.574269  0.528249      fail
1   0.915553  1.275734  0.929869  0.717630  0.546952  0.507462      fail
2   0.896969  1.372690  1.001793  0.760526  0.600311  0.557829      fail
3   0.767960  1.321321  1.017158  0.760143  0.604222  0.561069      fail
4   0.919186  1.340717  1.061384  0.833075  0.646281  0.596530      fail
5   0.887219  1.019362  0.762374  0.545680  0.397611  0.368102      fail
6   0.984837  1.216801  0.961146  0.730063  0.561395  0.515067      fail
7   0.869898  1.205556  0.887575  0.696151  0.527487  0.492215      fail
8   1.025770  1.175334  0.932039  0.706368  0.530605  0.490732      fail
9   0.727338  1.243710  0.967861  0.674899  0.537120  0.498232      fail
10  0.946295  1.140371  0.943198  0.737269  0.512270  0.470484      pass
11  0.860855  1.039522  0.783892  0.615092  0.489070  0.448237      pass
12  0.427736  1.206430  0.918679  0.713228  0.522131  0.491670      pass
13  0.664532  1.210137  0.952229  0.716824  0.537934  0.499788      pass
14  0.551266  0.994663  0.802956  0.612239  0.462000  0.427266      pass
15  0.340671  1.155629  0.980078  0.687531  0.530563  0.500610      pass
16  0.910826  1.356247  1.102761  0.833470  0.614878  0.569696      pass
17  0.777881  1.187571  0.985419  0.788003  0.597095  0.554017      pass
18  0.552760  0.878838  0.690624  0.491995  0.416837  0.384236      pass
19  0.953379  1.237777  1.012684  0.786910  0.647616  0.592130      pass

BARINEL SCORES

          x 5     cx 4     cx 1      h 0      cx 3      cx 2
sum  0.563092  0.52201  0.50902  0.50882  0.506326  0.506138

TARANTULA SCORES

          x 5     cx 4     cx 1      h 0      cx 3      cx 2
sum  0.563092  0.52201  0.50902  0.50882  0.506326  0.506138

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rxx_inGap_7_.qasm

100%|██████████| 10/10 [00:01<00:00,  7.77it/s]
100%|██████████| 10/10 [00:01<00:00,  9.03it/s]

       rxx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.295456  1.545345  1.552986  1.061929  0.755902  0.697247      fail
1   0.260709  1.545962  1.498317  0.981263  0.763250  0.697773      fail
2   0.262979  1.567847  1.531238  0.898786  0.706045  0.649403      fail
3   0.227866  1.310272  1.235557  0.843778  0.662743  0.612646      fail
4   0.245702  1.419220  1.396214  0.784630  0.610037  0.561804      fail
5   0.312411  1.571175  1.542822  0.915966  0.679935  0.625984      fail
6   0.252631  1.484426  1.492008  0.937056  0.716087  0.664041      fail
7   0.262552  1.363362  1.367970  0.903934  0.642378  0.589920      fail
8   0.281529  1.434306  1.420636  1.007986  0.772133  0.708738      fail
9   0.282956  1.500435  1.493126  1.011140  0.780606  0.719555      fail
10  0.123090  0.736327  0.769519  0.472330  0.326771  0.297175      pass
11  0.207672  1.546398  1.417280  0.994001  0.692837  0.652393      pass
12  0.202717  1.386687  1.300477  0.912620  0.691172  0.628728      pass
13  0.248298  1.261579  1.257987  0.878038  0.647843  0.593946      pass
14  0.227775  1.210669  1.141384  0.800136  0.575154  0.534679      pass
15  0.197244  1.267066  1.190067  0.766730  0.596083  0.543871      pass
16  0.277545  1.668265  1.616683  0.858276  0.679833  0.623723      pass
17  0.249186  1.643121  1.614842  0.929369  0.679806  0.617828      pass
18  0.107824  0.661552  0.659614  0.444766  0.352384  0.321226      pass
19  0.167356  0.939818  0.962911  0.534002  0.373125  0.343238      pass

BARINEL SCORES

        rxx 5      h 0      cx 1      cx 2     cx 3      cx 4
sum  0.572023  0.55864  0.558017  0.551846  0.54913  0.544725

TARANTULA SCORES

        rxx 5      h 0      cx 1      cx 2     cx 3      cx 4
sum  0.572023  0.55864  0.558017  0.551846  0.54913  0.544725

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rx_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.11it/s]
100%|██████████| 10/10 [00:01<00:00,  9.70it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      rx 0 pass/fail
0   0.491436  1.143051  0.855540  0.607909  0.561678  1.075634      fail
1   0.464148  1.087061  0.784916  0.581301  0.537293  1.061311      fail
2   0.318997  0.804609  0.606005  0.444760  0.412447  0.710201      fail
3   0.460003  0.986349  0.773673  0.561543  0.519777  1.029124      fail
4   0.383272  1.034767  0.769372  0.613126  0.570144  0.990032      fail
5   0.367010  0.936188  0.666325  0.485538  0.455986  0.802217      fail
6   0.390763  0.898073  0.714226  0.523099  0.483653  0.881833      fail
7   0.416761  0.854121  0.649321  0.489551  0.454736  0.901909      fail
8   0.404893  1.056329  0.823972  0.620879  0.578616  1.062446      fail
9   0.452038  1.054381  0.811687  0.627140  0.582206  1.088947      fail
10  0.250747  0.662292  0.525807  0.372979  0.346181  0.620573      pass
11  0.369862  0.907545  0.698858  0.548570  0.502118  0.974504      pass
12  0.342654  0.905606  0.651590  0.446869  0.416476  0.714030      pass
13  0.260282  0.763422  0.598604  0.430694  0.402137  0.715575      pass
14  0.329950  0.947142  0.695292  0.562163  0.517052  0.942587      pass
15  0.326755  0.946295  0.659046  0.501139  0.466337  0.780784      pass
16  0.355966  0.875483  0.658932  0.463415  0.424639  0.743280      pass
17  0.363428  0.832876  0.637213  0.502491  0.466341  0.838269      pass
18  0.250753  0.765096  0.559876  0.451509  0.417049  0.647578      pass
19  0.466763  1.090481  0.837646  0.626532  0.580257  1.172606      pass

BARINEL SCORES

         cx 5      rx 0      cx 3       h 1     cx 4      cx 2
sum  0.555726  0.540946  0.533344  0.531869  0.53123  0.530995

TARANTULA SCORES

         cx 5      rx 0      cx 3       h 1     cx 4      cx 2
sum  0.555726  0.540946  0.533344  0.531869  0.53123  0.530995

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_y_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.38it/s]
100%|██████████| 10/10 [00:00<00:00, 11.91it/s]

         y 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.960461  1.330393  1.041940  0.784739  0.591297  0.542935      fail
1   0.867484  1.216843  0.852304  0.644220  0.487874  0.453381      fail
2   0.952602  1.353561  1.067824  0.859737  0.638616  0.588605      fail
3   0.741093  1.149381  0.885563  0.687793  0.512055  0.478658      fail
4   1.226194  1.529812  1.150257  0.853935  0.619883  0.570575      fail
5   1.103644  1.454349  1.135641  0.888727  0.654717  0.607801      fail
6   0.882763  1.223929  0.897655  0.715820  0.528129  0.491235      fail
7   0.864968  1.219891  0.956879  0.703528  0.512992  0.479351      fail
8   0.853606  1.323243  0.979480  0.780294  0.601345  0.557102      fail
9   1.052987  1.542640  1.127416  0.909607  0.661820  0.616017      fail
10  0.625016  1.151284  0.937977  0.723134  0.554040  0.513423      pass
11  0.595576  1.019640  0.752478  0.575641  0.462729  0.428803      pass
12  0.917488  1.292100  0.884023  0.698256  0.533519  0.497912      pass
13  1.058824  1.521083  1.215909  0.932068  0.696058  0.638095      pass
14  0.899021  1.376820  0.966209  0.767246  0.582868  0.537589      pass
15  0.863744  1.240799  0.941205  0.674185  0.527284  0.486823      pass
16  0.903483  1.179294  0.818900  0.639233  0.489066  0.452250      pass
17  1.062525  1.535647  1.130140  0.906063  0.659553  0.614899      pass
18  0.421057  1.010915  0.789262  0.575438  0.415496  0.387298      pass
19  1.005954  1.484585  1.066710  0.815137  0.603336  0.560565      pass

BARINEL SCORES

          y 5      cx 2      cx 3       h 0      cx 1      cx 4
sum  0.532285  0.517245  0.515107  0.512758  0.512565  0.510167

TARANTULA SCORES

          y 5      cx 2      cx 3       h 0      cx 1      cx 4
sum  0.532285  0.517245  0.515107  0.512758  0.512565  0.510167

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ry_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.24it/s]
100%|██████████| 10/10 [00:00<00:00, 11.58it/s]

        ry 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.778524  1.262899  1.028643  0.779727  0.583413  0.548861      fail
1   0.798270  1.136734  0.867009  0.632646  0.433391  0.402681      fail
2   0.884899  1.152206  0.915849  0.717870  0.531952  0.491130      fail
3   0.792169  1.265236  0.990173  0.764020  0.561141  0.520795      fail
4   0.858106  1.205827  0.935688  0.757129  0.569782  0.527243      fail
5   0.877639  1.253576  0.908870  0.632642  0.510921  0.473483      fail
6   0.735009  1.134771  0.849364  0.682806  0.517719  0.483709      fail
7   0.920645  1.382874  1.095785  0.863734  0.638891  0.591857      fail
8   0.811734  1.186782  0.857230  0.634103  0.483088  0.452718      fail
9   1.015902  1.278593  0.926518  0.707907  0.547096  0.510891      fail
10  0.832275  1.140990  0.887791  0.667193  0.527296  0.485851      pass
11  0.869070  1.195339  0.907557  0.736553  0.605991  0.560594      pass
12  1.092178  1.466021  1.093189  0.822445  0.662358  0.613993      pass
13  0.922945  1.158332  0.862878  0.669215  0.515214  0.475011      pass
14  0.817237  1.267482  0.906986  0.662991  0.463647  0.429253      pass
15  0.790599  1.141528  0.870313  0.720145  0.514456  0.475459      pass
16  0.559382  1.174230  0.930368  0.732470  0.552506  0.510748      pass
17  0.675788  1.150750  0.896489  0.686200  0.524072  0.487678      pass
18  0.977280  1.350907  1.075652  0.873803  0.703073  0.654083      pass
19  0.501849  0.698461  0.500684  0.376995  0.289372  0.269482      pass

BARINEL SCORES

         ry 5      cx 3      cx 4      cx 2       h 0      cx 1
sum  0.513151  0.512105  0.510737  0.507952  0.502068  0.500904

TARANTULA SCORES

         ry 5      cx 3      cx 4      cx 2       h 0      cx 1
sum  0.513151  0.512105  0.510737  0.507952  0.502068  0.500904

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rxx_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.35it/s]
100%|██████████| 10/10 [00:00<00:00, 11.48it/s]

       rxx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.037771  1.245568  0.891955  0.626421  0.451243  0.425043      fail
1   0.773421  1.252184  0.985639  0.753921  0.585314  0.539880      fail
2   1.001501  1.285672  0.950330  0.729935  0.543427  0.504230      fail
3   0.917677  1.280586  0.924447  0.677792  0.528036  0.490096      fail
4   0.809209  1.217280  0.937941  0.741946  0.575748  0.532920      fail
5   0.848160  1.154249  0.791449  0.616018  0.430579  0.404826      fail
6   0.858233  1.306717  1.011334  0.779518  0.563818  0.524290      fail
7   0.895485  1.464432  1.129760  0.858718  0.661519  0.615575      fail
8   1.009360  1.219288  0.940011  0.687900  0.499880  0.466182      fail
9   0.935389  1.146716  0.970108  0.748784  0.565296  0.523086      fail
10  0.689382  0.800035  0.611717  0.434175  0.345893  0.324591      pass
11  0.829264  1.056939  0.806704  0.558268  0.431166  0.399636      pass
12  0.644394  1.116737  0.822720  0.712429  0.519266  0.480712      pass
13  0.494502  1.028433  0.812039  0.581414  0.465564  0.428920      pass
14  0.774613  0.947342  0.716724  0.541289  0.361248  0.334976      pass
15  0.578058  1.335636  1.013019  0.795184  0.554927  0.510256      pass
16  0.572041  1.087448  0.842154  0.651712  0.503360  0.459948      pass
17  0.577457  1.154828  0.876150  0.641817  0.511281  0.475224      pass
18  0.678593  1.192029  0.887782  0.653463  0.499926  0.460912      pass
19  0.582581  0.860798  0.628591  0.504778  0.366596  0.345292      pass

BARINEL SCORES

        rxx 5       h 0      cx 3      cx 2      cx 4      cx 1
sum  0.585939  0.543565  0.543172  0.543113  0.543028  0.542434

TARANTULA SCORES

        rxx 5       h 0      cx 3      cx 2      cx 4      cx 1
sum  0.585939  0.543565  0.543172  0.543113  0.543028  0.542434

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rx_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.16it/s]
100%|██████████| 10/10 [00:00<00:00, 11.25it/s]

        rx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.893271  1.256360  0.926342  0.729032  0.519653  0.484545      fail
1   0.963709  1.271102  0.930920  0.722109  0.514361  0.479845      fail
2   1.038025  1.338975  0.978376  0.709816  0.524169  0.489004      fail
3   0.857076  1.185845  0.928162  0.713241  0.543032  0.503798      fail
4   1.057474  1.373273  1.102743  0.806212  0.602250  0.559874      fail
5   0.983910  1.289971  1.028471  0.754209  0.567178  0.522086      fail
6   0.930031  1.249957  0.993750  0.794019  0.617470  0.569394      fail
7   0.712535  1.139488  0.878667  0.647905  0.488897  0.459598      fail
8   0.793687  1.187095  0.902513  0.673178  0.504791  0.466404      fail
9   0.981367  1.308594  0.990328  0.740432  0.533376  0.494361      fail
10  0.780820  1.288268  1.048175  0.791867  0.614061  0.563955      pass
11  0.421824  0.747223  0.551922  0.420991  0.325248  0.301335      pass
12  0.718496  1.052715  0.742738  0.596347  0.462262  0.427338      pass
13  0.491286  1.037517  0.774710  0.631629  0.481747  0.442537      pass
14  0.786473  1.300402  0.985780  0.735467  0.573014  0.530844      pass
15  0.675448  1.168063  0.877813  0.704413  0.545512  0.503280      pass
16  0.815593  0.975324  0.725104  0.536338  0.414962  0.384216      pass
17  0.816115  1.222423  0.895626  0.662739  0.501181  0.465930      pass
18  0.375983  0.777335  0.591247  0.450786  0.327184  0.304375      pass
19  0.455946  0.842491  0.732426  0.518320  0.402148  0.372238      pass

BARINEL SCORES

         rx 5      cx 3      cx 4      cx 2       h 0      cx 1
sum  0.592388  0.549322  0.547559  0.546527  0.539296  0.538155

TARANTULA SCORES

         rx 5      cx 3      cx 4      cx 2       h 0      cx 1
sum  0.592388  0.549322  0.547559  0.546527  0.539296  0.538155

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_h_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.27it/s]
100%|██████████| 10/10 [00:01<00:00,  9.70it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       h 0 pass/fail
0   0.329587  0.942534  0.669848  0.492631  0.456673  0.430348      fail
1   0.359781  0.992578  0.757493  0.558914  0.517333  0.501941      fail
2   0.324581  0.924968  0.694050  0.513100  0.481158  0.462280      fail
3   0.253504  0.797921  0.643944  0.485224  0.451648  0.429286      fail
4   0.404621  1.000082  0.765440  0.580822  0.544800  0.528156      fail
5   0.232290  0.900423  0.683062  0.548653  0.508977  0.486489      fail
6   0.277324  0.967699  0.729201  0.542820  0.508513  0.486641      fail
7   0.373745  0.987374  0.714920  0.531476  0.492851  0.478145      fail
8   0.429810  1.096962  0.814078  0.647791  0.597254  0.578746      fail
9   0.381263  0.942670  0.721398  0.528719  0.492829  0.478733      fail
10  0.312778  0.917671  0.704637  0.545723  0.504518  0.480075      pass
11  0.266088  0.746040  0.555623  0.432368  0.399609  0.388460      pass
12  0.400145  1.080923  0.810821  0.592584  0.551120  0.531504      pass
13  0.333404  0.800854  0.573508  0.418710  0.390897  0.380110      pass
14  0.211945  0.598636  0.456103  0.318921  0.296243  0.285796      pass
15  0.418290  0.896687  0.711617  0.546872  0.512092  0.499112      pass
16  0.490215  1.073506  0.838496  0.604157  0.561600  0.546050      pass
17  0.204346  0.562630  0.423041  0.339913  0.318079  0.302290      pass
18  0.209486  0.546660  0.421287  0.336691  0.312020  0.304439      pass
19  0.300352  0.696388  0.507497  0.425893  0.392115  0.382261      pass

BARINEL SCORES

         cx 4     cx 3       h 1      cx 2       h 0      cx 5
sum  0.546735  0.54512  0.543795  0.543451  0.542444  0.516846

TARANTULA SCORES

         cx 4     cx 3       h 1      cx 2       h 0      cx 5
sum  0.546735  0.54512  0.543795  0.543451  0.542444  0.516846

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_x_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.45it/s]
100%|██████████| 10/10 [00:00<00:00, 11.74it/s]

         x 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.917198  1.306483  1.001618  0.771694  0.574356  0.533893      fail
1   1.037693  1.260915  0.931325  0.698335  0.526119  0.490284      fail
2   0.859699  1.296819  0.987649  0.748003  0.566607  0.530063      fail
3   0.965442  1.425375  1.081809  0.827591  0.633321  0.583004      fail
4   1.052259  1.410519  1.047380  0.733982  0.558229  0.521564      fail
5   0.873140  1.307067  1.018059  0.761209  0.573118  0.533390      fail
6   1.062260  1.185376  0.890969  0.633510  0.504819  0.471545      fail
7   1.105170  1.397808  1.084321  0.798428  0.626383  0.578654      fail
8   0.894876  1.223611  0.874990  0.646949  0.485525  0.451913      fail
9   0.688312  1.214497  0.899364  0.681882  0.504993  0.470892      fail
10  0.441310  0.933701  0.713771  0.594780  0.435147  0.404092      pass
11  0.375123  0.915863  0.687713  0.563296  0.422797  0.391909      pass
12  0.715224  1.297376  0.979893  0.721498  0.547767  0.511935      pass
13  0.706651  1.187543  0.859081  0.611729  0.492629  0.456272      pass
14  0.628656  1.142083  0.898635  0.691098  0.529043  0.490302      pass
15  0.368214  1.066602  0.782467  0.614595  0.473225  0.437738      pass
16  0.907963  1.313512  1.015005  0.735814  0.555494  0.514947      pass
17  0.598101  1.089598  0.837281  0.654007  0.453125  0.419422      pass
18  0.734428  1.194178  0.906293  0.745100  0.502952  0.465851      pass
19  0.776678  1.344831  0.992124  0.809538  0.565059  0.527559      pass

BARINEL SCORES

          x 5      cx 4      cx 3       h 0     cx 1      cx 2
sum  0.601974  0.531476  0.530969  0.527857  0.52736  0.519943

TARANTULA SCORES

          x 5      cx 4      cx 3       h 0     cx 1      cx 2
sum  0.601974  0.531476  0.530969  0.527857  0.52736  0.519943

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rxx_inGap_9_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.11it/s]
100%|██████████| 10/10 [00:01<00:00,  8.65it/s]

       rxx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.045166  0.819898  0.612278  0.684452  0.685737  0.740050      fail
1   1.043398  1.005951  0.699377  0.789397  0.759915  0.773587      fail
2   1.026957  1.276230  0.918304  0.986614  0.914128  0.981364      fail
3   1.117759  1.264196  1.017621  0.995459  0.961913  1.097167      fail
4   1.076585  1.081173  0.823095  0.933711  0.902912  0.865144      fail
5   1.258361  1.255377  0.905158  1.058305  1.020999  1.008370      fail
6   1.354714  1.203332  0.930032  1.037516  1.040419  1.078538      fail
7   1.041798  1.189475  0.905395  0.951382  0.923956  0.988839      fail
8   1.126987  0.978815  0.711723  0.853473  0.835146  0.784618      fail
9   1.109501  1.129127  0.920163  0.996817  0.961631  1.040980      fail
10  1.310642  0.917072  0.696567  0.760568  0.799362  0.968091      pass
11  0.741626  0.923956  0.689131  0.714374  0.678730  0.719921      pass
12  0.882635  0.946970  0.738307  0.673020  0.634224  0.813167      pass
13  0.913172  1.186269  0.908213  0.912351  0.870833  0.993791      pass
14  1.444444  1.224287  0.957531  1.147773  1.180412  1.426497      pass
15  1.016395  0.952068  0.724738  0.729950  0.695607  0.877792      pass
16  1.274264  1.064967  0.875069  0.928082  0.943901  1.225546      pass
17  1.089408  0.956708  0.771785  0.842599  0.817898  1.136791      pass
18  0.933817  0.991253  0.723468  0.800553  0.771132  0.898782      pass
19  1.219576  0.968606  0.750584  0.787446  0.804582  1.034573      pass

BARINEL SCORES

         cx 2      cx 4      cx 1      cx 3     rxx 5       h 0
sum  0.528163  0.525109  0.523544  0.518667  0.508518  0.481076

TARANTULA SCORES

         cx 2      cx 4      cx 1      cx 3     rxx 5       h 0
sum  0.528163  0.525109  0.523544  0.518667  0.508518  0.481076

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cx_inGap_2_.qasm

100%|██████████| 10/10 [00:01<00:00,  6.94it/s]
100%|██████████| 10/10 [00:01<00:00,  8.54it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.289571  0.748118  0.581964  0.466333  0.473841  0.421325      fail
1   0.357061  0.831650  0.650651  0.515721  0.520356  0.457335      fail
2   0.449732  0.999302  0.796664  0.615751  0.609192  0.537926      fail
3   0.561611  1.232862  0.865728  0.670446  0.655754  0.586919      fail
4   0.456244  0.973256  0.760873  0.584830  0.573625  0.511125      fail
5   0.291404  0.813676  0.623532  0.503567  0.515677  0.463555      fail
6   0.394494  1.024662  0.772243  0.613244  0.617098  0.555381      fail
7   0.324287  0.848233  0.625726  0.481119  0.467169  0.417241      fail
8   0.320011  0.855254  0.666794  0.518488  0.516244  0.459467      fail
9   0.454024  0.911311  0.733550  0.559652  0.544599  0.493075      fail
10  0.398209  0.890036  0.714080  0.543369  0.531485  0.481927      pass
11  0.410797  0.969481  0.745036  0.549227  0.515554  0.459977      pass
12  0.341278  0.873171  0.673678  0.501136  0.476250  0.420082      pass
13  0.456030  1.054928  0.767495  0.566390  0.528860  0.463485      pass
14  0.396963  1.014315  0.821795  0.614804  0.588099  0.540497      pass
15  0.392103  1.003957  0.760197  0.585579  0.573479  0.504517      pass
16  0.166919  0.488200  0.350817  0.265331  0.252991  0.227658      pass
17  0.358674  0.933655  0.686950  0.552833  0.563732  0.495587      pass
18  0.311306  0.797458  0.614173  0.475847  0.467933  0.420013      pass
19  0.145748  0.481060  0.368228  0.272648  0.254365  0.227660      pass

BARINEL SCORES

          h 0     cx 1     cx 5      cx 2      cx 3      cx 4
sum  0.536193  0.53615  0.53576  0.528786  0.521181  0.520628

TARANTULA SCORES

          h 0     cx 1     cx 5      cx 2      cx 3      cx 4
sum  0.536193  0.53615  0.53576  0.528786  0.521181  0.520628

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_sx_inGap_7_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.44it/s]
100%|██████████| 10/10 [00:00<00:00, 10.85it/s]

      sxdg 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.292043  1.395508  0.989351  0.746922  0.578157  0.528848      fail
1   1.398711  1.282662  0.998693  0.754761  0.585191  0.534355      fail
2   1.189553  1.472939  1.105839  0.847153  0.663001  0.607399      fail
3   1.248219  1.303393  0.976448  0.716666  0.535254  0.495888      fail
4   0.924940  0.957843  0.718520  0.579826  0.433468  0.400957      fail
5   1.179179  1.568283  1.186894  0.904613  0.699774  0.642438      fail
6   1.255739  1.215469  0.901856  0.665043  0.507759  0.460840      fail
7   1.497020  1.467081  1.135292  0.848652  0.637810  0.589174      fail
8   1.329092  1.354983  1.040572  0.802854  0.575941  0.531657      fail
9   1.084550  1.145462  0.932976  0.721677  0.507704  0.469463      fail
10  0.600350  0.832124  0.635972  0.463428  0.342825  0.316775      pass
11  1.019875  1.307854  1.027448  0.745747  0.582522  0.533411      pass
12  1.248227  1.490390  1.202218  0.872043  0.659566  0.599320      pass
13  0.795637  0.896634  0.674576  0.489459  0.382714  0.351516      pass
14  1.191374  1.329912  1.031513  0.776923  0.574958  0.525258      pass
15  0.875696  1.351320  1.121598  0.795673  0.598436  0.549629      pass
16  1.093800  1.225065  0.998138  0.747462  0.576058  0.524995      pass
17  0.981270  1.144930  0.841324  0.629764  0.500047  0.457030      pass
18  1.116890  1.176429  0.904042  0.661714  0.490895  0.447833      pass
19  1.289312  1.370560  1.005126  0.751944  0.556876  0.503748      pass

BARINEL SCORES

       sxdg 5      cx 2       h 0      cx 1      cx 4      cx 3
sum  0.548352  0.522517  0.522417  0.520892  0.520531  0.514013

TARANTULA SCORES

       sxdg 5      cx 2       h 0      cx 1      cx 4      cx 3
sum  0.548352  0.522517  0.522417  0.520892  0.520531  0.514013

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ry_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 12.10it/s]
100%|██████████| 10/10 [00:00<00:00, 11.78it/s]

        ry 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.344142  1.740859  0.931157  0.694667  0.532752  0.481397      fail
1   1.280052  1.760433  0.958025  0.726681  0.555720  0.507002      fail
2   1.143316  1.606080  0.905243  0.683703  0.514483  0.463599      fail
3   1.115261  1.541760  0.953645  0.726916  0.558520  0.515990      fail
4   1.504719  2.008579  1.128192  0.917184  0.663352  0.605962      fail
5   1.397420  1.910921  1.094421  0.822064  0.629175  0.574389      fail
6   1.261627  1.812864  1.021460  0.801831  0.581175  0.529866      fail
7   0.913622  1.544176  0.932659  0.710081  0.550333  0.504493      fail
8   1.266092  1.947383  1.109126  0.836778  0.619412  0.567622      fail
9   1.292239  2.044666  1.121486  0.878416  0.645051  0.583122      fail
10  0.900446  1.290369  0.733404  0.548259  0.381270  0.356751      pass
11  1.000071  1.793015  1.088548  0.800763  0.579072  0.537112      pass
12  0.875931  1.481594  0.910058  0.725721  0.513843  0.471774      pass
13  1.352143  1.931810  0.978528  0.716178  0.550241  0.503697      pass
14  1.187910  1.843265  1.096872  0.821704  0.621678  0.569130      pass
15  0.971858  1.461900  0.778711  0.529065  0.436616  0.398414      pass
16  1.338733  2.013067  1.141706  0.833087  0.628379  0.575284      pass
17  0.896536  1.663171  1.012972  0.748051  0.509355  0.469515      pass
18  0.955452  1.678791  1.014247  0.813289  0.573196  0.523317      pass
19  0.529052  0.970683  0.597789  0.478793  0.366628  0.333158      pass

BARINEL SCORES

        ry 5      cx 1       h 0      cx 2      cx 4     cx 3
sum  0.55572  0.531321  0.529553  0.526443  0.526289  0.52057

TARANTULA SCORES

        ry 5      cx 1       h 0      cx 2      cx 4     cx 3
sum  0.55572  0.531321  0.529553  0.526443  0.526289  0.52057

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rx_inGap_8_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.89it/s]
100%|██████████| 10/10 [00:00<00:00, 10.61it/s]

        rx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.367764  1.233251  1.169472  0.884618  0.673337  0.621806      fail
1   0.436920  1.152155  1.055604  0.753950  0.546940  0.504029      fail
2   0.321545  1.136084  1.062775  0.854310  0.662234  0.612305      fail
3   0.375786  1.077905  1.024014  0.747716  0.565641  0.519408      fail
4   0.292272  1.161173  1.029231  0.747718  0.616920  0.566947      fail
5   0.417689  1.187300  1.104962  0.851181  0.585581  0.539269      fail
6   0.331774  1.230732  1.166130  0.924723  0.712758  0.654188      fail
7   0.319410  1.283318  1.178927  0.919942  0.677760  0.625571      fail
8   0.379799  1.122079  1.019640  0.760528  0.537079  0.492122      fail
9   0.345494  1.083282  1.045774  0.852327  0.628034  0.580869      fail
10  0.276689  1.088844  0.987081  0.833479  0.648562  0.592999      pass
11  0.306553  1.132418  1.056668  0.827789  0.616270  0.567151      pass
12  0.327818  1.147720  1.081066  0.881736  0.653869  0.597745      pass
13  0.270285  0.947720  0.919178  0.719485  0.530144  0.485214      pass
14  0.266849  1.034345  0.934100  0.716027  0.520250  0.473742      pass
15  0.183565  0.834112  0.746581  0.600403  0.425639  0.389339      pass
16  0.327314  1.075991  0.984072  0.776083  0.595520  0.550683      pass
17  0.367629  0.993085  0.957031  0.718743  0.514491  0.474249      pass
18  0.298195  1.260708  1.085295  0.834237  0.596991  0.547686      pass
19  0.251192  0.991046  0.835509  0.639270  0.473693  0.434936      pass

BARINEL SCORES

         rx 5      cx 3       h 0      cx 1      cx 4     cx 2
sum  0.555098  0.531061  0.527828  0.526773  0.526187  0.52366

TARANTULA SCORES

         rx 5      cx 3       h 0      cx 1      cx 4     cx 2
sum  0.555098  0.531061  0.527828  0.526773  0.526187  0.52366

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ccx_inGap_7_.qasm

100%|██████████| 10/10 [00:03<00:00,  3.17it/s]
100%|██████████| 10/10 [00:03<00:00,  3.19it/s]

       ccx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.530082  0.968328  0.700441  0.580556  0.448444  0.415884      fail
1   0.570900  1.032167  0.782960  0.641890  0.482022  0.449066      fail
2   0.473983  0.966238  0.714016  0.573784  0.424175  0.394640      fail
3   0.596802  1.035805  0.784919  0.650505  0.491982  0.456053      fail
4   0.576094  1.108181  0.848859  0.701683  0.532523  0.493138      fail
5   0.453047  0.873074  0.611947  0.503437  0.379740  0.350839      fail
6   0.473911  0.888116  0.680526  0.538208  0.401316  0.370943      fail
7   0.544496  1.094886  0.810768  0.668906  0.508494  0.472967      fail
8   0.449054  0.864192  0.626454  0.508222  0.403925  0.373618      fail
9   0.543710  1.054279  0.754552  0.628775  0.486185  0.451133      fail
10  0.535016  0.998158  0.724047  0.598894  0.441007  0.406019      pass
11  0.386712  0.675387  0.472346  0.387962  0.292383  0.273476      pass
12  0.587810  1.199941  0.860392  0.678417  0.527716  0.489076      pass
13  0.450305  0.821635  0.620939  0.508832  0.378012  0.350657      pass
14  0.511702  1.030562  0.744531  0.620971  0.478214  0.438000      pass
15  0.378464  0.752365  0.553426  0.445365  0.332244  0.307921      pass
16  0.523942  1.025298  0.754526  0.612616  0.460939  0.425776      pass
17  0.692345  1.361136  0.989496  0.811141  0.610376  0.565817      pass
18  0.514797  0.847386  0.618222  0.496099  0.376078  0.351792      pass
19  0.318428  0.594430  0.397185  0.328424  0.263009  0.244642      pass

BARINEL SCORES

          h 0      cx 1      cx 2      cx 3     ccx 5      cx 4
sum  0.523208  0.522872  0.522084  0.520652  0.515456  0.515084

TARANTULA SCORES

          h 0      cx 1      cx 2      cx 3     ccx 5      cx 4
sum  0.523208  0.522872  0.522084  0.520652  0.515456  0.515084

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_sx_inGap_10_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.90it/s]
100%|██████████| 10/10 [00:01<00:00,  8.87it/s]

      sxdg 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.190686  1.403276  1.106886  0.814161  0.733007  0.954148      fail
1   0.984132  0.910394  0.743851  0.516396  0.472352  0.600816      fail
2   1.440620  1.034028  0.749821  0.583436  0.556170  0.765836      fail
3   1.251195  1.261802  1.007211  0.751249  0.701263  0.948550      fail
4   1.589612  1.140734  0.856070  0.651863  0.635204  0.947968      fail
5   1.739303  1.405003  1.115461  0.756167  0.722834  1.036976      fail
6   1.048441  1.008241  0.800989  0.618899  0.559908  0.748029      fail
7   1.210485  1.359733  1.030510  0.745094  0.653713  0.870091      fail
8   1.121025  1.148314  0.871466  0.692702  0.629561  0.787073      fail
9   1.068780  1.239256  0.891811  0.668384  0.608692  0.741281      fail
10  0.912571  1.066871  0.773614  0.604555  0.543396  0.729641      pass
11  1.004399  1.043880  0.826872  0.591143  0.535022  0.684912      pass
12  1.356464  1.434215  1.156179  0.840871  0.719872  0.923539      pass
13  0.781082  1.055696  0.780935  0.576608  0.486556  0.589452      pass
14  1.021594  1.062944  0.790565  0.644492  0.593041  0.790257      pass
15  1.284494  1.084865  0.813802  0.578525  0.521969  0.727548      pass
16  0.449905  0.660390  0.507897  0.391094  0.351693  0.478590      pass
17  1.007800  1.145086  0.909243  0.671112  0.600611  0.763064      pass
18  0.868690  1.162956  0.890425  0.673026  0.597624  0.853683      pass
19  1.351429  1.214812  0.843925  0.641271  0.599985  0.886122      pass

BARINEL SCORES

       sxdg 5       h 0      cx 1      cx 3      cx 2      cx 4
sum  0.557441  0.530768  0.530575  0.525207  0.522506  0.521431

TARANTULA SCORES

       sxdg 5       h 0      cx 1      cx 3      cx 2      cx 4
sum  0.557441  0.530768  0.530575  0.525207  0.522506  0.521431

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cx_inGap_6_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.63it/s]
100%|██████████| 10/10 [00:00<00:00, 11.24it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.421539  1.304222  0.944816  0.712609  0.530607  0.493011      fail
1   0.410605  1.237348  0.947204  0.713067  0.563597  0.522661      fail
2   0.461327  1.372335  1.027659  0.790627  0.594478  0.551751      fail
3   0.488430  1.372438  1.042411  0.845506  0.645542  0.601894      fail
4   0.448106  1.362931  0.973937  0.765221  0.529151  0.494537      fail
5   0.418823  1.217932  0.954237  0.734257  0.589501  0.547310      fail
6   0.390840  1.225637  0.992204  0.756832  0.574526  0.533020      fail
7   0.339990  1.155398  0.905728  0.653478  0.478445  0.443035      fail
8   0.456111  1.373490  0.995791  0.752717  0.606314  0.565150      fail
9   0.482128  1.394237  1.068152  0.825311  0.625726  0.586501      fail
10  0.264214  0.944925  0.725863  0.512869  0.361466  0.339514      pass
11  0.270615  0.994253  0.801908  0.611839  0.451106  0.420485      pass
12  0.262209  0.852973  0.628952  0.480738  0.375136  0.348777      pass
13  0.413011  1.273251  1.016736  0.737273  0.554487  0.517206      pass
14  0.457131  1.370955  1.071307  0.814505  0.637958  0.597762      pass
15  0.354699  1.122275  0.881672  0.656632  0.460151  0.431245      pass
16  0.259854  0.792393  0.595326  0.457144  0.334093  0.311700      pass
17  0.338870  1.026447  0.753272  0.567561  0.439354  0.411644      pass
18  0.442733  1.271302  0.915160  0.658103  0.528481  0.493076      pass
19  0.288311  0.939971  0.691001  0.538468  0.411164  0.379728      pass

BARINEL SCORES

         cx 5      cx 1       h 0      cx 2      cx 4      cx 3
sum  0.562993  0.557548  0.556712  0.555742  0.551414  0.549376

TARANTULA SCORES

         cx 5      cx 1       h 0      cx 2      cx 4      cx 3
sum  0.562993  0.557548  0.556712  0.555742  0.551414  0.549376

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_h_inGap_7_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.87it/s]
100%|██████████| 10/10 [00:00<00:00, 12.14it/s]

         h 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.380141  1.884692  1.001888  0.786315  0.630157  0.574249      fail
1   0.346038  1.640044  0.943738  0.742214  0.556618  0.512447      fail
2   0.414569  1.805048  1.000105  0.748815  0.599773  0.543648      fail
3   0.310495  1.734375  1.066366  0.837384  0.609547  0.558880      fail
4   0.409411  1.984462  1.141995  0.886846  0.613987  0.561348      fail
5   0.290102  1.714566  1.024621  0.735718  0.547251  0.500492      fail
6   0.316476  1.804902  1.120300  0.836065  0.622311  0.565835      fail
7   0.265950  1.665280  1.107242  0.786344  0.598889  0.555283      fail
8   0.370431  1.825814  1.028814  0.728452  0.571819  0.525048      fail
9   0.359663  1.832538  1.063504  0.764780  0.558016  0.507009      fail
10  0.252917  1.851057  1.104880  0.771734  0.623412  0.574205      pass
11  0.413670  2.091275  1.151269  0.824660  0.587015  0.538143      pass
12  0.125785  1.189465  0.861293  0.655937  0.527282  0.490883      pass
13  0.298866  1.705097  0.971206  0.733119  0.558626  0.516852      pass
14  0.292990  1.763511  1.041539  0.785971  0.597325  0.543851      pass
15  0.399015  2.044969  1.147782  0.865841  0.642997  0.592388      pass
16  0.321556  1.559818  0.925898  0.677996  0.541842  0.496572      pass
17  0.327642  1.854444  1.024767  0.807454  0.592520  0.542149      pass
18  0.325152  1.712609  1.034145  0.735827  0.641673  0.588801      pass
19  0.216844  1.081812  0.619991  0.484929  0.368375  0.335641      pass

BARINEL SCORES

          h 5      cx 2      cx 3      cx 4      cx 1       h 0
sum  0.537967  0.516763  0.515107  0.514932  0.509806  0.508695

TARANTULA SCORES

          h 5      cx 2      cx 3      cx 4      cx 1       h 0
sum  0.537967  0.516763  0.515107  0.514932  0.509806  0.508695

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_sx_inGap_9_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.43it/s]
100%|██████████| 10/10 [00:00<00:00, 10.60it/s]

      sxdg 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.455681  1.235816  0.942400  0.866880  0.631300  0.584380      fail
1   1.318868  1.034432  0.773812  0.748872  0.576612  0.531445      fail
2   1.028957  1.110484  0.821196  0.723312  0.517429  0.481195      fail
3   1.216952  1.118773  0.888066  0.775139  0.543251  0.504255      fail
4   1.660258  1.418861  1.060953  1.000834  0.787779  0.730122      fail
5   0.926483  1.159041  0.889038  0.820526  0.653531  0.604843      fail
6   1.415097  1.056277  0.800470  0.757028  0.554174  0.516188      fail
7   1.309805  1.113802  0.921489  0.876466  0.724836  0.664383      fail
8   1.063012  1.174729  0.883154  0.776547  0.598847  0.552689      fail
9   1.431117  1.197786  0.906076  0.830309  0.628844  0.575241      fail
10  0.921940  0.896062  0.706805  0.661917  0.469313  0.431922      pass
11  1.137722  1.009895  0.802811  0.746221  0.589474  0.542541      pass
12  0.735660  0.751960  0.592711  0.534793  0.391603  0.358686      pass
13  1.234117  1.218655  0.912964  0.834912  0.681370  0.623930      pass
14  0.824962  0.782801  0.575541  0.528514  0.427655  0.393297      pass
15  1.210518  1.292631  0.994863  0.921843  0.704137  0.646079      pass
16  1.204379  1.334953  1.008363  0.942114  0.744320  0.683614      pass
17  1.131886  1.096799  0.861586  0.775695  0.586262  0.541721      pass
18  1.026948  0.911907  0.701262  0.640817  0.491184  0.456409      pass
19  0.925978  0.938866  0.653144  0.613214  0.505268  0.466895      pass

BARINEL SCORES

       sxdg 5     cx 3      cx 2      cx 4       h 0     cx 1
sum  0.553324  0.53224  0.531734  0.531698  0.527532  0.52651

TARANTULA SCORES

       sxdg 5     cx 3      cx 2      cx 4       h 0     cx 1
sum  0.553324  0.53224  0.531734  0.531698  0.527532  0.52651

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_sx_inGap_5_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.05it/s]
100%|██████████| 10/10 [00:01<00:00,  9.83it/s]

        cx 5      cx 4      cx 3      cx 2       h 1    sxdg 0 pass/fail
0   0.424761  0.857674  0.675175  0.525980  0.487272  0.912950      fail
1   0.333702  0.892699  0.713978  0.524094  0.483959  0.897456      fail
2   0.418897  1.085081  0.829041  0.631075  0.587755  1.090327      fail
3   0.391358  0.878258  0.674647  0.528638  0.491702  0.944260      fail
4   0.371280  0.924668  0.743939  0.563760  0.529020  0.988664      fail
5   0.448950  1.146673  0.825648  0.655141  0.611190  1.164816      fail
6   0.356064  0.976011  0.708613  0.527261  0.489732  0.850455      fail
7   0.440866  1.052993  0.811010  0.596305  0.553936  1.037533      fail
8   0.378345  0.947295  0.726617  0.558326  0.516134  0.976403      fail
9   0.421949  0.984351  0.752731  0.565209  0.525947  1.038310      fail
10  0.197486  0.554915  0.397792  0.296842  0.272455  0.472761      pass
11  0.336190  1.102068  0.813832  0.612051  0.564279  0.983046      pass
12  0.284803  0.898529  0.690611  0.520283  0.481425  0.843748      pass
13  0.287444  0.771677  0.559361  0.438533  0.405127  0.679885      pass
14  0.512650  1.109252  0.854840  0.617601  0.565892  1.125415      pass
15  0.325666  0.872295  0.618762  0.451676  0.422400  0.767144      pass
16  0.364491  0.773493  0.584183  0.440697  0.413863  0.723885      pass
17  0.415231  0.898665  0.664857  0.494991  0.463179  0.891405      pass
18  0.202468  0.588566  0.420647  0.323589  0.299678  0.529571      pass
19  0.244097  0.836613  0.684476  0.510447  0.469772  0.778338      pass

BARINEL SCORES

       sxdg 0      cx 5      h 1      cx 2      cx 3      cx 4
sum  0.559503  0.556985  0.54767  0.546669  0.542617  0.536901

TARANTULA SCORES

       sxdg 0      cx 5      h 1      cx 2      cx 3      cx 4
sum  0.559503  0.556985  0.54767  0.546669  0.542617  0.536901

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_cswap_inGap_5_.qasm

100%|██████████| 10/10 [00:02<00:00,  3.55it/s]
100%|██████████| 10/10 [00:02<00:00,  3.52it/s]

        cx 5   cswap 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.425753  1.264713  0.865344  0.624703  0.483858  0.443600      fail
1   0.431315  1.217635  0.843373  0.612519  0.477207  0.443066      fail
2   0.355014  1.278761  0.921374  0.668239  0.489696  0.457528      fail
3   0.370424  1.102028  0.777894  0.546274  0.409840  0.374943      fail
4   0.312025  1.174432  0.794606  0.600663  0.463050  0.428097      fail
5   0.299492  1.123612  0.766190  0.554997  0.417643  0.385892      fail
6   0.349336  1.127207  0.834500  0.625464  0.467229  0.428534      fail
7   0.420299  1.309567  0.904915  0.666059  0.508028  0.471135      fail
8   0.249036  1.030116  0.733949  0.547692  0.407938  0.377583      fail
9   0.349880  1.139106  0.790842  0.548986  0.420818  0.390429      fail
10  0.236666  0.875002  0.631187  0.459059  0.342577  0.315170      pass
11  0.425606  1.328247  0.951543  0.686087  0.516142  0.478698      pass
12  0.377158  1.089882  0.810483  0.545739  0.398413  0.369759      pass
13  0.502897  1.253772  0.896122  0.640571  0.472518  0.436449      pass
14  0.323689  1.017214  0.726717  0.517577  0.389893  0.355904      pass
15  0.269276  1.092659  0.780173  0.570747  0.429166  0.396784      pass
16  0.207587  0.731243  0.537548  0.385697  0.288088  0.265548      pass
17  0.340466  1.139526  0.814933  0.594379  0.431598  0.400799      pass
18  0.413075  1.380586  0.947933  0.674789  0.487316  0.452442      pass
19  0.322188  1.004625  0.729089  0.546890  0.407750  0.373578      pass

BARINEL SCORES

          h 0      cx 1   cswap 4    cx 2     cx 3      cx 5
sum  0.522103  0.521923  0.518836  0.5161  0.51268  0.510311

TARANTULA SCORES

          h 0      cx 1   cswap 4    cx 2     cx 3      cx 5
sum  0.522103  0.521923  0.518836  0.5161  0.51268  0.510311

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_ry_inGap_8_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.50it/s]
100%|██████████| 10/10 [00:00<00:00, 12.02it/s]

        ry 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.446890  1.078435  1.500246  0.789795  0.616557  0.560552      fail
1   1.310389  1.240937  1.662553  0.935072  0.689931  0.627573      fail
2   1.034633  1.199893  1.274837  0.750907  0.578022  0.531460      fail
3   1.185418  1.047898  1.286905  0.752304  0.563558  0.511844      fail
4   1.018508  1.183241  1.247349  0.720267  0.582320  0.536009      fail
5   0.828226  1.019163  1.164368  0.687321  0.541204  0.493837      fail
6   1.301060  1.237131  1.579498  0.867501  0.678056  0.621541      fail
7   1.132937  0.968998  1.145202  0.606846  0.488040  0.450278      fail
8   1.263957  0.980103  1.355292  0.741222  0.555994  0.515519      fail
9   1.156097  1.145627  1.314545  0.759192  0.581791  0.536700      fail
10  1.074319  1.099837  1.321872  0.762486  0.624560  0.576385      pass
11  0.603349  0.931664  0.957587  0.666512  0.460786  0.425156      pass
12  1.133031  1.324340  1.397588  0.817517  0.646172  0.595963      pass
13  0.822830  0.913474  1.200849  0.658019  0.532718  0.495763      pass
14  1.144541  1.207678  1.370033  0.773902  0.620453  0.571301      pass
15  0.908421  1.128973  1.342200  0.832602  0.670405  0.612507      pass
16  0.903368  1.007184  1.219419  0.726437  0.507922  0.469413      pass
17  0.423204  0.629467  0.637226  0.427720  0.333147  0.303273      pass
18  0.777947  1.075093  1.233472  0.770327  0.577385  0.527043      pass
19  1.056143  0.947107  1.079417  0.624700  0.514102  0.474837      pass

BARINEL SCORES

         ry 5      cx 3      cx 4      cx 2      cx 1       h 0
sum  0.568963  0.535016  0.519578  0.518752  0.517065  0.515985

TARANTULA SCORES

         ry 5      cx 3      cx 4      cx 2      cx 1       h 0
sum  0.568963  0.535016  0.519578  0.518752  0.517065  0.515985

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cx_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.09it/s]
100%|██████████| 10/10 [00:00<00:00, 10.68it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.427339  1.000279  0.940280  0.731733  0.516244  0.483393      fail
1   0.313862  0.849382  0.863035  0.604974  0.467021  0.437641      fail
2   0.416449  1.185272  1.235494  0.913617  0.718856  0.669526      fail
3   0.288419  0.939213  0.941075  0.718062  0.565498  0.529915      fail
4   0.312752  0.874329  0.833779  0.620244  0.474376  0.443389      fail
5   0.349945  1.010435  0.989878  0.711847  0.527848  0.490023      fail
6   0.356142  0.906320  0.882054  0.716175  0.574973  0.528689      fail
7   0.433243  0.958086  0.897772  0.701430  0.520724  0.488700      fail
8   0.281201  0.916391  0.958449  0.731757  0.597204  0.556897      fail
9   0.364753  1.070804  1.017453  0.720173  0.532864  0.497871      fail
10  0.270560  0.703605  0.659780  0.474701  0.366047  0.342828      pass
11  0.281508  0.720607  0.675685  0.532845  0.382089  0.358651      pass
12  0.366484  0.908325  0.891163  0.686458  0.520488  0.481582      pass
13  0.371541  1.073357  1.058111  0.805743  0.605246  0.567208      pass
14  0.341358  0.932663  0.955508  0.665296  0.521966  0.483573      pass
15  0.365837  0.917412  0.909367  0.683860  0.495362  0.461669      pass
16  0.258728  0.793140  0.800801  0.549515  0.432083  0.396892      pass
17  0.297618  0.744820  0.686720  0.448378  0.344052  0.321107      pass
18  0.317863  0.787478  0.710746  0.492880  0.360712  0.332347      pass
19  0.328945  0.837987  0.822681  0.630694  0.523389  0.487220      pass

BARINEL SCORES

          h 0      cx 1      cx 2      cx 3      cx 4      cx 5
sum  0.547706  0.546988  0.545647  0.539163  0.535607  0.525477

TARANTULA SCORES

          h 0      cx 1      cx 2      cx 3      cx 4      cx 5
sum  0.547706  0.546988  0.545647  0.539163  0.535607  0.525477

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_x_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.98it/s]
100%|██████████| 10/10 [00:01<00:00,  9.73it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       x 0 pass/fail
0   0.299767  0.975335  0.761994  0.585907  0.545434  1.078244      fail
1   0.413447  0.925471  0.685347  0.516252  0.483576  0.887092      fail
2   0.304322  0.860415  0.688913  0.507742  0.475170  0.978013      fail
3   0.292875  0.803682  0.676665  0.490107  0.456271  0.949974      fail
4   0.373123  0.933442  0.742371  0.565991  0.526121  1.053124      fail
5   0.427131  1.028352  0.812049  0.647326  0.604531  1.224094      fail
6   0.406517  0.953424  0.829564  0.636318  0.588547  1.304417      fail
7   0.413004  1.038050  0.825665  0.618642  0.572775  1.167373      fail
8   0.424162  0.975882  0.761637  0.557112  0.518598  1.033979      fail
9   0.419142  1.083881  0.885846  0.679537  0.631264  1.284912      fail
10  0.391965  0.981788  0.791558  0.569853  0.530950  1.071854      pass
11  0.432882  1.089788  0.796107  0.615410  0.568989  1.075316      pass
12  0.256055  0.655619  0.499677  0.373279  0.342565  0.654768      pass
13  0.286425  0.936459  0.667789  0.515549  0.478081  0.846948      pass
14  0.122503  0.475618  0.382044  0.259389  0.238508  0.469763      pass
15  0.344579  0.749353  0.579152  0.415007  0.387442  0.744297      pass
16  0.473475  1.005241  0.741896  0.565942  0.525499  0.979427      pass
17  0.236430  0.547494  0.417228  0.306993  0.284593  0.542342      pass
18  0.419383  0.987854  0.745885  0.593930  0.549438  1.064178      pass
19  0.337621  0.821968  0.675897  0.500967  0.465817  0.983403      pass

BARINEL SCORES

        x 0       h 1      cx 2      cx 3      cx 4     cx 5
sum  0.5652  0.552711  0.551734  0.549144  0.537207  0.53337

TARANTULA SCORES

        x 0       h 1      cx 2      cx 3      cx 4     cx 5
sum  0.5652  0.552711  0.551734  0.549144  0.537207  0.53337

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_rxx_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.29it/s]
100%|██████████| 10/10 [00:00<00:00, 12.06it/s]

       rxx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.839103  1.133734  0.895748  0.670022  0.525964  0.488332      fail
1   0.734019  1.256614  0.936817  0.726162  0.534683  0.498544      fail
2   0.963245  1.558551  1.196219  0.866590  0.623991  0.580671      fail
3   0.805827  1.234579  0.957798  0.733024  0.545203  0.506554      fail
4   0.808564  1.040277  0.844292  0.650976  0.464486  0.433683      fail
5   0.780235  1.327998  0.987537  0.734675  0.556261  0.522475      fail
6   0.685866  1.221554  0.900108  0.674750  0.517801  0.481823      fail
7   0.783688  1.071722  0.841445  0.673200  0.477819  0.442500      fail
8   0.688741  1.055785  0.799301  0.605456  0.437137  0.408576      fail
9   0.850253  1.298212  1.004223  0.736656  0.572759  0.528866      fail
10  0.623495  1.277496  0.928591  0.703268  0.540373  0.495617      pass
11  0.504433  0.950212  0.682815  0.530355  0.385683  0.354245      pass
12  0.902175  1.073457  0.900330  0.649362  0.479168  0.444145      pass
13  0.695204  0.981904  0.769976  0.597634  0.423382  0.390386      pass
14  0.917132  1.248738  0.983556  0.744091  0.569062  0.530250      pass
15  0.411879  0.924540  0.654988  0.495065  0.399564  0.369028      pass
16  0.713484  1.155475  0.880746  0.658293  0.500738  0.465710      pass
17  0.703565  1.130318  0.853897  0.677385  0.512468  0.467926      pass
18  0.578151  1.253492  0.920348  0.704491  0.500944  0.464364      pass
19  0.594405  1.025384  0.764873  0.592578  0.419960  0.389501      pass

BARINEL SCORES

        rxx 5      cx 3       h 0     cx 2      cx 1      cx 4
sum  0.544421  0.528903  0.528114  0.52678  0.526271  0.525366

TARANTULA SCORES

        rxx 5      cx 3       h 0     cx 2      cx 1      cx 4
sum  0.544421  0.528903  0.528114  0.52678  0.526271  0.525366

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rxx_inGap_5_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.01it/s]
100%|██████████| 10/10 [00:00<00:00, 11.62it/s]

        cx 5     rxx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.382354  1.972356  0.953946  0.684395  0.527248  0.489469      fail
1   0.323492  1.905727  0.874086  0.676045  0.506476  0.471289      fail
2   0.420879  1.976697  0.941416  0.706957  0.547261  0.507841      fail
3   0.311604  1.811518  0.885721  0.725843  0.542822  0.503785      fail
4   0.430606  2.078333  0.969958  0.801303  0.622193  0.578785      fail
5   0.300157  1.705078  0.727685  0.563602  0.444175  0.413881      fail
6   0.486952  2.187438  1.070221  0.827367  0.642176  0.596206      fail
7   0.358285  1.935988  0.964485  0.737390  0.554790  0.517978      fail
8   0.371322  1.943532  0.918687  0.685323  0.530421  0.495356      fail
9   0.316298  1.828254  0.921974  0.690939  0.527516  0.493571      fail
10  0.429415  1.752397  0.888466  0.606029  0.490419  0.450198      pass
11  0.383272  1.771512  1.009810  0.690846  0.508439  0.470209      pass
12  0.305917  1.637236  0.728675  0.582788  0.427335  0.397616      pass
13  0.206375  1.415641  0.627120  0.483405  0.369148  0.342019      pass
14  0.493000  2.109606  1.103072  0.832561  0.623952  0.572587      pass
15  0.219398  1.565964  0.778915  0.609031  0.445226  0.416050      pass
16  0.248295  1.144824  0.563688  0.400522  0.306133  0.286185      pass
17  0.289074  1.326588  0.808420  0.638595  0.475358  0.440105      pass
18  0.298825  1.795126  0.865263  0.615085  0.432547  0.402993      pass
19  0.379619  2.018912  0.986612  0.695905  0.552257  0.512656      pass

BARINEL SCORES

          h 0      cx 1     rxx 4      cx 2      cx 5     cx 3
sum  0.541541  0.540407  0.539115  0.535627  0.532261  0.52468

TARANTULA SCORES

          h 0      cx 1     rxx 4      cx 2      cx 5     cx 3
sum  0.541541  0.540407  0.539115  0.535627  0.532261  0.52468

ERROR GATE LOCATION:
4
Now evolving the following mutant:  AddGate_ccx_inGap_6_.qasm

100%|██████████| 10/10 [00:02<00:00,  4.45it/s]
100%|██████████| 10/10 [00:02<00:00,  4.31it/s]

       ccx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.474791  0.824055  0.681456  0.526495  0.397051  0.367352      fail
1   0.644406  1.071993  0.859834  0.664632  0.502092  0.467024      fail
2   0.503998  0.876596  0.708354  0.541567  0.407285  0.375072      fail
3   0.619653  1.011843  0.820368  0.635401  0.475933  0.442316      fail
4   0.507505  0.945968  0.781085  0.596316  0.450581  0.416185      fail
5   0.509280  0.887092  0.743815  0.558919  0.424322  0.393456      fail
6   0.444757  0.863375  0.705645  0.541021  0.405900  0.378322      fail
7   0.548289  1.042914  0.851404  0.635898  0.468058  0.436166      fail
8   0.618891  0.991687  0.802574  0.626522  0.470116  0.438380      fail
9   0.547337  0.997644  0.830357  0.636743  0.486690  0.449902      fail
10  0.396894  0.669968  0.535421  0.398737  0.302592  0.284412      pass
11  0.482944  0.777452  0.644323  0.476716  0.355988  0.331142      pass
12  0.335590  0.615891  0.495287  0.377170  0.285569  0.264901      pass
13  0.559748  0.832760  0.715730  0.537920  0.400118  0.374826      pass
14  0.555273  0.863827  0.703367  0.540069  0.399954  0.371085      pass
15  0.438497  0.723096  0.571188  0.446172  0.328930  0.304384      pass
16  0.488552  0.774805  0.629012  0.483066  0.353152  0.326511      pass
17  0.533750  0.859438  0.716120  0.553676  0.418891  0.389216      pass
18  0.521044  0.834469  0.710758  0.551890  0.420863  0.388851      pass
19  0.501988  0.917101  0.748793  0.565023  0.427872  0.397128      pass

BARINEL SCORES

         cx 1       h 0      cx 2      cx 4      cx 3     ccx 5
sum  0.548527  0.548161  0.547415  0.547301  0.546121  0.529542

TARANTULA SCORES

         cx 1       h 0      cx 2      cx 4      cx 3     ccx 5
sum  0.548527  0.548161  0.547415  0.547301  0.546121  0.529542

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rx_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.76it/s]
100%|██████████| 10/10 [00:01<00:00,  9.13it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      rx 0 pass/fail
0   0.357072  0.973508  0.797143  0.598771  0.549454  0.530041      fail
1   0.331098  1.029880  0.805773  0.628396  0.580164  0.567133      fail
2   0.348064  0.936042  0.794818  0.605271  0.564285  0.533156      fail
3   0.297564  0.840215  0.685265  0.493649  0.462382  0.447346      fail
4   0.371285  0.911020  0.760283  0.557021  0.518462  0.496559      fail
5   0.422226  0.987812  0.768401  0.596028  0.552752  0.528062      fail
6   0.368178  0.820844  0.663347  0.509005  0.470460  0.449595      fail
7   0.436677  1.111601  0.826516  0.613312  0.570946  0.554263      fail
8   0.340668  0.913179  0.739267  0.570367  0.527496  0.511308      fail
9   0.368841  0.918483  0.738766  0.530561  0.494361  0.470764      fail
10  0.430756  1.160915  0.921077  0.705584  0.653857  0.628857      pass
11  0.300428  0.720303  0.518208  0.400383  0.372230  0.354705      pass
12  0.462025  1.039323  0.770706  0.567185  0.525425  0.506091      pass
13  0.262511  0.808977  0.647169  0.493842  0.454375  0.436712      pass
14  0.371893  0.930669  0.725846  0.547942  0.507242  0.486994      pass
15  0.291350  0.733866  0.588421  0.442406  0.410575  0.393058      pass
16  0.417523  0.907320  0.707819  0.510447  0.480826  0.461819      pass
17  0.290181  0.884589  0.662262  0.529973  0.490882  0.480081      pass
18  0.314412  0.819501  0.638428  0.468883  0.431788  0.413217      pass
19  0.401955  0.927597  0.724165  0.563276  0.522478  0.506291      pass

BARINEL SCORES

         cx 3       h 1      cx 2      rx 0      cx 4      cx 5
sum  0.523319  0.521749  0.521608  0.521546  0.513864  0.506865

TARANTULA SCORES

         cx 3       h 1      cx 2      rx 0      cx 4      cx 5
sum  0.523319  0.521749  0.521608  0.521546  0.513864  0.506865

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_y_inGap_2_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.48it/s]
100%|██████████| 10/10 [00:01<00:00,  9.87it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       y 0 pass/fail
0   0.356841  0.839938  0.636361  0.493849  0.454981  0.892418      fail
1   0.356873  0.897565  0.699358  0.519799  0.482518  0.897481      fail
2   0.386962  0.890247  0.660374  0.528998  0.490026  0.976612      fail
3   0.326404  0.997280  0.770314  0.590382  0.545232  1.049353      fail
4   0.347184  0.839812  0.623369  0.516360  0.480783  1.003954      fail
5   0.334598  0.928367  0.708375  0.540163  0.497069  0.959153      fail
6   0.450553  0.970934  0.758341  0.592088  0.548603  1.087601      fail
7   0.368642  1.085401  0.834884  0.668710  0.620369  1.269515      fail
8   0.340065  0.943852  0.705959  0.593445  0.550832  1.175281      fail
9   0.455730  1.039316  0.791472  0.642456  0.593877  1.235580      fail
10  0.249068  0.666463  0.466488  0.346790  0.324968  0.587205      pass
11  0.458385  1.036876  0.779208  0.581008  0.536256  1.016770      pass
12  0.363514  0.998029  0.759307  0.542830  0.504814  0.878915      pass
13  0.411985  0.885943  0.670713  0.503302  0.465370  0.880117      pass
14  0.297174  0.817823  0.602796  0.476767  0.435974  0.861250      pass
15  0.408940  1.113960  0.868908  0.660446  0.613695  1.177115      pass
16  0.332668  0.775083  0.635290  0.466122  0.426902  0.801959      pass
17  0.354766  0.981054  0.786770  0.622706  0.576810  1.160323      pass
18  0.300412  0.865826  0.603789  0.445494  0.411544  0.741286      pass
19  0.352127  0.930069  0.701685  0.535628  0.497058  0.937764      pass

BARINEL SCORES

          y 0      h 1      cx 2     cx 5      cx 3      cx 4
sum  0.538394  0.52341  0.523242  0.51343  0.511158  0.509771

TARANTULA SCORES

          y 0      h 1      cx 2     cx 5      cx 3      cx 4
sum  0.538394  0.52341  0.523242  0.51343  0.511158  0.509771

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_sx_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.75it/s]
100%|██████████| 10/10 [00:00<00:00, 10.09it/s]

        cx 5      cx 4      cx 3      cx 2       h 1    sxdg 0 pass/fail
0   0.194767  0.746717  0.572093  0.438535  0.405343  0.806678      fail
1   0.495107  1.078892  0.849226  0.645506  0.595748  1.117037      fail
2   0.348839  1.023760  0.763070  0.560894  0.516217  1.053806      fail
3   0.285095  0.928011  0.697609  0.498748  0.467882  0.963747      fail
4   0.416612  0.983725  0.704877  0.562406  0.523255  0.962346      fail
5   0.373314  0.896960  0.633854  0.479242  0.439524  0.874492      fail
6   0.313584  0.865757  0.699577  0.535651  0.501107  0.942340      fail
7   0.369686  0.896097  0.688419  0.525002  0.482705  0.970214      fail
8   0.286842  0.903838  0.643994  0.471395  0.440810  0.913574      fail
9   0.470724  1.090666  0.828314  0.632197  0.584671  1.147292      fail
10  0.282283  0.765892  0.612457  0.464947  0.429532  0.847208      pass
11  0.419601  0.957736  0.686496  0.521738  0.483006  0.849719      pass
12  0.336152  0.891311  0.688255  0.512538  0.474105  0.945928      pass
13  0.337015  0.955750  0.781095  0.545199  0.506687  0.973846      pass
14  0.428771  0.943662  0.704247  0.524606  0.484465  0.924694      pass
15  0.204598  0.579720  0.440067  0.311623  0.285139  0.511833      pass
16  0.326383  0.942943  0.746266  0.566488  0.521356  1.006753      pass
17  0.356722  0.986409  0.750794  0.564217  0.527781  0.947739      pass
18  0.409692  0.954070  0.690778  0.551524  0.512067  0.922988      pass
19  0.238942  0.815847  0.637968  0.476191  0.442648  0.743671      pass

BARINEL SCORES

       sxdg 0      cx 4      cx 5       h 1      cx 2      cx 3
sum  0.529229  0.517055  0.515549  0.515091  0.514944  0.512396

TARANTULA SCORES

       sxdg 0      cx 4      cx 5       h 1      cx 2      cx 3
sum  0.529229  0.517055  0.515549  0.515091  0.514944  0.512396

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_swap_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.96it/s]
100%|██████████| 10/10 [00:01<00:00,  9.56it/s]

        cx 5      cx 4    swap 3      cx 2      cx 1       h 0 pass/fail
0   0.437477  1.043771  0.928499  0.778729  0.601594  0.559969      fail
1   0.315039  0.897865  0.746991  0.640666  0.509387  0.473679      fail
2   0.322853  0.839919  0.798493  0.638609  0.499515  0.468001      fail
3   0.380672  0.880220  0.801906  0.637726  0.461222  0.430543      fail
4   0.281084  0.723732  0.591053  0.474604  0.361568  0.334822      fail
5   0.297090  0.796536  0.727841  0.584179  0.462569  0.429050      fail
6   0.454713  1.073712  0.990718  0.806653  0.614778  0.568447      fail
7   0.370959  0.986112  0.781990  0.657608  0.546121  0.505352      fail
8   0.361298  0.976244  0.898136  0.764139  0.598860  0.556251      fail
9   0.329675  0.952284  0.804032  0.636300  0.443381  0.411354      fail
10  0.316033  0.832647  0.698379  0.557788  0.431446  0.396672      pass
11  0.286366  0.702928  0.584292  0.483543  0.370281  0.343748      pass
12  0.430144  1.044461  0.837998  0.710106  0.565281  0.523295      pass
13  0.456768  0.875926  0.794114  0.653548  0.484566  0.449387      pass
14  0.261156  0.811907  0.756525  0.652623  0.455992  0.425400      pass
15  0.281900  0.791460  0.651779  0.560196  0.429565  0.402202      pass
16  0.405292  0.971018  0.892372  0.763143  0.587295  0.546436      pass
17  0.399532  0.840075  0.722348  0.580445  0.452015  0.425452      pass
18  0.339843  0.832913  0.629278  0.520180  0.379839  0.353264      pass
19  0.453405  1.004492  0.825566  0.683415  0.543139  0.500637      pass

BARINEL SCORES

       swap 3     cx 1       h 0      cx 2      cx 4      cx 5
sum  0.521892  0.52039  0.520374  0.517765  0.512937  0.494459

TARANTULA SCORES

       swap 3     cx 1       h 0      cx 2      cx 4      cx 5
sum  0.521892  0.52039  0.520374  0.517765  0.512937  0.494459

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_rxx_inGap_2_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.98it/s]
100%|██████████| 10/10 [00:01<00:00,  9.59it/s]

        cx 5      cx 4      cx 3      cx 2     rxx 1       h 0 pass/fail
0   0.342941  0.913877  0.691170  0.563733  0.932789  0.638549      fail
1   0.302624  0.925261  0.676201  0.507665  0.834537  0.605128      fail
2   0.339935  0.925817  0.692011  0.546594  0.899019  0.621881      fail
3   0.331139  0.830683  0.696262  0.556338  0.890921  0.621141      fail
4   0.442763  1.022400  0.815000  0.627864  1.055196  0.715689      fail
5   0.394113  0.830268  0.621865  0.518179  0.864513  0.585737      fail
6   0.447565  1.129644  0.837369  0.684906  1.045348  0.719177      fail
7   0.428983  1.080201  0.836532  0.640388  0.952784  0.722750      fail
8   0.397273  1.074170  0.833354  0.631163  1.001476  0.733346      fail
9   0.317325  0.780518  0.604423  0.489217  0.805885  0.547455      fail
10  0.260932  0.812873  0.608667  0.463675  0.720013  0.549182      pass
11  0.273744  0.600164  0.484603  0.359803  0.593709  0.438343      pass
12  0.192280  0.506049  0.401759  0.294597  0.562689  0.396130      pass
13  0.354850  0.787642  0.600068  0.483004  0.712003  0.527659      pass
14  0.404464  0.891454  0.658918  0.520687  0.763345  0.556449      pass
15  0.349880  0.927085  0.706853  0.528133  0.790452  0.632671      pass
16  0.215765  0.681089  0.550016  0.387920  0.600621  0.456231      pass
17  0.272440  0.996825  0.774218  0.612450  0.817174  0.650806      pass
18  0.375449  0.941761  0.730068  0.557991  0.929138  0.648203      pass
19  0.364797  1.022633  0.806315  0.615056  0.956344  0.708154      pass

BARINEL SCORES

        rxx 1      cx 5      cx 2       h 0      cx 4      cx 3
sum  0.554908  0.549936  0.544513  0.539215  0.538044  0.536061

TARANTULA SCORES

        rxx 1      cx 5      cx 2       h 0      cx 4      cx 3
sum  0.554908  0.549936  0.544513  0.539215  0.538044  0.536061

ERROR GATE LOCATION:
1
Now evolving the following mutant:  AddGate_rx_inGap_10_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.73it/s]
100%|██████████| 10/10 [00:00<00:00, 11.62it/s]

        rx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.088257  1.139764  0.881744  0.631800  0.561485  0.722685      fail
1   1.262976  1.376253  1.052753  0.796476  0.716980  0.921432      fail
2   1.204859  1.165947  0.915624  0.711096  0.654731  0.830837      fail
3   1.470710  1.260052  0.970434  0.757531  0.731210  1.013344      fail
4   1.278727  1.180257  0.836787  0.616377  0.556337  0.793907      fail
5   1.166574  1.238158  0.926269  0.709565  0.642488  0.902712      fail
6   1.183043  1.313029  0.967036  0.692061  0.626437  0.830839      fail
7   1.521516  1.038675  0.792734  0.592673  0.574080  0.836914      fail
8   1.113768  1.150205  0.873689  0.652373  0.576527  0.697164      fail
9   1.158480  1.301189  0.906107  0.646849  0.593701  0.745227      fail
10  1.423717  1.262911  0.910812  0.724545  0.665868  0.953273      pass
11  1.276949  1.092299  0.786707  0.564770  0.497525  0.660267      pass
12  0.995344  0.937329  0.778280  0.581395  0.542044  0.793380      pass
13  0.970509  0.927503  0.735802  0.550903  0.482520  0.633984      pass
14  0.683274  0.921204  0.724020  0.550993  0.472766  0.666378      pass
15  1.166915  1.273744  1.010135  0.751028  0.674290  0.901029      pass
16  0.960671  0.904604  0.677588  0.513467  0.450935  0.665074      pass
17  0.873990  0.795990  0.630050  0.494721  0.429364  0.576001      pass
18  1.213726  1.344617  1.021009  0.760067  0.726472  1.049292      pass
19  0.897979  0.783722  0.617493  0.436386  0.391001  0.529981      pass

BARINEL SCORES

         rx 5      cx 4      cx 1      cx 3      cx 2       h 0
sum  0.543336  0.542834  0.538956  0.536182  0.534492  0.527551

TARANTULA SCORES

         rx 5      cx 4      cx 1      cx 3      cx 2       h 0
sum  0.543336  0.542834  0.538956  0.536182  0.534492  0.527551

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ry_inGap_4_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.12it/s]
100%|██████████| 10/10 [00:01<00:00,  9.75it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      ry 0 pass/fail
0   0.475017  1.013981  0.779147  0.573609  0.535167  1.002924      fail
1   0.348756  0.867477  0.664441  0.509141  0.475203  0.946222      fail
2   0.266326  0.880741  0.620811  0.514791  0.477324  0.954320      fail
3   0.289477  0.970793  0.730497  0.564585  0.524640  1.054418      fail
4   0.428887  1.037005  0.762432  0.589947  0.545567  1.060444      fail
5   0.302638  0.954192  0.713180  0.560647  0.517459  1.040797      fail
6   0.322861  1.012614  0.802362  0.659209  0.605122  1.208257      fail
7   0.371959  0.947785  0.710187  0.520468  0.486306  0.940605      fail
8   0.381925  1.045904  0.779505  0.582193  0.539500  1.058934      fail
9   0.354998  0.893605  0.641090  0.502604  0.467120  0.927789      fail
10  0.350414  0.997765  0.763379  0.580859  0.542664  1.125642      pass
11  0.281236  0.811646  0.628167  0.469882  0.432542  0.826783      pass
12  0.362142  0.882768  0.681332  0.513801  0.476965  0.816212      pass
13  0.223679  0.767382  0.630382  0.493978  0.457368  0.884828      pass
14  0.352799  0.833267  0.670718  0.478649  0.442428  0.772455      pass
15  0.280517  0.713145  0.500497  0.397008  0.368112  0.566904      pass
16  0.333620  0.811032  0.569614  0.480340  0.447702  0.768701      pass
17  0.410586  0.948053  0.729552  0.585417  0.539820  1.012113      pass
18  0.323696  0.930736  0.617224  0.470685  0.438802  0.779952      pass
19  0.355242  0.913165  0.654697  0.481756  0.450570  0.840861      pass

BARINEL SCORES

         ry 0     cx 2       h 1      cx 4     cx 3      cx 5
sum  0.548422  0.52967  0.529499  0.527838  0.52777  0.519725

TARANTULA SCORES

         ry 0     cx 2       h 1      cx 4     cx 3      cx 5
sum  0.548422  0.52967  0.529499  0.527838  0.52777  0.519725

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_rx_inGap_2_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.75it/s]
100%|██████████| 10/10 [00:00<00:00, 10.39it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      rx 0 pass/fail
0   0.379484  0.953129  0.700990  0.541803  0.499207  0.974905      fail
1   0.406549  1.051126  0.810351  0.650101  0.602850  1.238725      fail
2   0.396136  1.051471  0.784626  0.586582  0.547280  1.003403      fail
3   0.343925  1.027082  0.783310  0.609074  0.568482  1.127993      fail
4   0.361141  0.928648  0.677606  0.529075  0.488734  0.951730      fail
5   0.376511  0.962285  0.766377  0.579543  0.534216  1.017440      fail
6   0.395754  0.992582  0.756257  0.589779  0.545370  1.087893      fail
7   0.380664  0.990298  0.695216  0.558558  0.518935  1.057744      fail
8   0.397535  0.975219  0.727646  0.580672  0.542127  1.078910      fail
9   0.210099  0.645436  0.505678  0.429952  0.395248  0.847961      fail
10  0.249989  0.636593  0.489480  0.393303  0.363813  0.728923      pass
11  0.296413  0.756960  0.568064  0.416324  0.384255  0.690668      pass
12  0.322636  0.816714  0.663016  0.500257  0.469003  0.893586      pass
13  0.408965  0.890060  0.670848  0.528531  0.494549  0.965030      pass
14  0.183555  0.794094  0.640369  0.486306  0.451090  0.884550      pass
15  0.240945  0.581482  0.459594  0.334439  0.308739  0.560101      pass
16  0.343170  1.032915  0.831597  0.658297  0.602418  1.235777      pass
17  0.401433  0.929455  0.683128  0.484362  0.445396  0.779138      pass
18  0.236256  0.648235  0.499567  0.387305  0.353951  0.718078      pass
19  0.301229  0.701648  0.505022  0.371929  0.352153  0.627413      pass

BARINEL SCORES

         rx 0       h 1      cx 2      cx 4      cx 5      cx 3
sum  0.562356  0.553713  0.553547  0.551514  0.549998  0.545291

TARANTULA SCORES

         rx 0       h 1      cx 2      cx 4      cx 5      cx 3
sum  0.562356  0.553713  0.553547  0.551514  0.549998  0.545291

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_cswap_inGap_4_.qasm

100%|██████████| 10/10 [00:02<00:00,  3.70it/s]
100%|██████████| 10/10 [00:02<00:00,  3.98it/s]

        cx 5      cx 4   cswap 3      cx 2      cx 1       h 0 pass/fail
0   0.412399  0.832574  0.839699  0.585635  0.415911  0.385606      fail
1   0.435722  1.011883  1.058207  0.749477  0.534469  0.496776      fail
2   0.308154  0.893186  0.882278  0.625239  0.452642  0.417283      fail
3   0.357453  0.912599  0.891895  0.628485  0.457759  0.421738      fail
4   0.452739  0.994856  1.001446  0.697550  0.490860  0.453590      fail
5   0.418475  1.075715  1.082633  0.769833  0.547966  0.509162      fail
6   0.458337  0.899192  0.896541  0.640031  0.463149  0.426518      fail
7   0.418375  0.988920  0.994386  0.714538  0.525588  0.488141      fail
8   0.535526  1.149106  1.199688  0.859146  0.617330  0.570953      fail
9   0.282236  0.829395  0.853054  0.605414  0.442193  0.412781      fail
10  0.382985  0.872032  0.888247  0.627856  0.454206  0.422114      pass
11  0.278502  0.758067  0.751217  0.509710  0.355306  0.328807      pass
12  0.262294  0.678384  0.666604  0.468286  0.342026  0.312937      pass
13  0.251787  0.840254  0.861954  0.608542  0.440429  0.408652      pass
14  0.380546  0.844148  0.887813  0.596688  0.431312  0.404220      pass
15  0.366428  0.871505  0.873696  0.612680  0.439688  0.406438      pass
16  0.340698  1.016453  1.044991  0.738214  0.540411  0.496996      pass
17  0.432092  0.989670  1.036437  0.748390  0.545652  0.506927      pass
18  0.202974  0.594311  0.607835  0.426364  0.317352  0.295626      pass
19  0.305607  0.851443  0.878615  0.622663  0.464388  0.426746      pass

BARINEL SCORES

         cx 5      cx 2    cx 4      h 0      cx 1   cswap 3
sum  0.560103  0.535683  0.5355  0.53335  0.533254  0.533039

TARANTULA SCORES

         cx 5      cx 2    cx 4      h 0      cx 1   cswap 3
sum  0.560103  0.535683  0.5355  0.53335  0.533254  0.533039

ERROR GATE LOCATION:
3
Now evolving the following mutant:  AddGate_ry_inGap_2_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.03it/s]
100%|██████████| 10/10 [00:00<00:00, 10.11it/s]

        cx 5      cx 4      cx 3      cx 2       h 1      ry 0 pass/fail
0   0.323003  1.011713  0.728289  0.573088  0.538792  1.038107      fail
1   0.374351  0.877229  0.658735  0.537285  0.497059  1.027852      fail
2   0.457893  1.137990  0.876902  0.661843  0.617048  1.183261      fail
3   0.304851  0.875563  0.693977  0.535798  0.491862  0.987543      fail
4   0.499939  1.022073  0.746312  0.600513  0.550506  1.115819      fail
5   0.486251  1.075622  0.830142  0.636763  0.585876  1.135707      fail
6   0.406698  0.995032  0.727843  0.562182  0.521358  1.010631      fail
7   0.290685  0.876012  0.608461  0.493755  0.462604  0.905223      fail
8   0.445534  0.988270  0.728547  0.594236  0.548109  1.130688      fail
9   0.343685  0.965620  0.756109  0.601451  0.550322  1.129342      fail
10  0.286695  0.683063  0.543697  0.443917  0.408467  0.859000      pass
11  0.332667  0.750148  0.583322  0.450011  0.418708  0.834107      pass
12  0.422914  0.973350  0.714548  0.539630  0.497805  0.963050      pass
13  0.284094  0.851895  0.591542  0.444697  0.419599  0.753244      pass
14  0.427382  1.013853  0.763594  0.563134  0.522677  0.981219      pass
15  0.323664  0.792003  0.612167  0.479859  0.447624  0.881384      pass
16  0.408805  1.067231  0.782507  0.593686  0.550267  1.051158      pass
17  0.365974  0.924544  0.685866  0.526893  0.487484  0.933577      pass
18  0.389474  1.011942  0.825865  0.598729  0.558082  1.023779      pass
19  0.365918  0.933837  0.752334  0.497585  0.465862  0.726657      pass

BARINEL SCORES

         ry 0      cx 2       h 1      cx 4     cx 5      cx 3
sum  0.542117  0.530122  0.528943  0.521864  0.52157  0.517588

TARANTULA SCORES

         ry 0      cx 2       h 1      cx 4     cx 5      cx 3
sum  0.542117  0.530122  0.528943  0.521864  0.52157  0.517588

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_rxx_inGap_10_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.33it/s]
100%|██████████| 10/10 [00:00<00:00, 10.72it/s]

       rxx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.294239  1.340947  1.003181  1.116790  1.057110  0.976148      fail
1   0.325134  0.998658  0.748443  0.980306  0.986404  0.987480      fail
2   0.283999  1.057773  0.785043  0.993144  0.990749  1.033636      fail
3   0.292114  1.247001  0.906130  1.045842  1.048159  1.083216      fail
4   0.313607  1.050437  0.806531  0.980493  1.037498  1.246595      fail
5   0.243458  1.074502  0.863912  0.951458  0.922834  0.953551      fail
6   0.285020  0.986065  0.732769  0.811248  0.771198  0.869107      fail
7   0.247096  1.157521  0.827602  0.933921  0.887030  1.008837      fail
8   0.321455  1.014960  0.733047  0.921066  0.916066  1.017662      fail
9   0.299237  1.099870  0.847842  1.030285  1.024397  1.034613      fail
10  0.271863  1.353278  1.008466  1.028877  0.989156  1.168732      pass
11  0.291995  1.059182  0.828338  0.949413  0.970560  1.073681      pass
12  0.279472  1.152202  0.862805  0.924031  0.898111  0.999723      pass
13  0.212971  1.250124  1.010934  0.949004  0.909625  1.137011      pass
14  0.153214  0.945388  0.659516  0.643163  0.569647  0.578571      pass
15  0.232659  1.237915  0.869122  0.731852  0.674871  0.949286      pass
16  0.185642  1.113222  0.843026  0.871553  0.776934  0.682205      pass
17  0.176296  0.942528  0.708517  0.697007  0.663822  0.791906      pass
18  0.156358  1.175698  0.818561  0.771236  0.639260  0.695514      pass
19  0.211370  1.127438  0.876749  0.884733  0.830938  0.881439      pass

BARINEL SCORES

        rxx 5      cx 1     cx 2       h 0      cx 3      cx 4
sum  0.572237  0.548921  0.53606  0.532677  0.493085  0.492646

TARANTULA SCORES

        rxx 5      cx 1     cx 2       h 0      cx 3      cx 4
sum  0.572237  0.548921  0.53606  0.532677  0.493085  0.492646

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rxx_inGap_1_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.59it/s]
100%|██████████| 10/10 [00:00<00:00, 10.17it/s]

        cx 5      cx 4      cx 3      cx 2       h 1     rxx 0 pass/fail
0   0.414209  1.055164  0.827540  0.622929  0.577867  0.578262      fail
1   0.327536  0.891116  0.682321  0.498591  0.468491  0.463778      fail
2   0.436869  1.041625  0.767556  0.576482  0.534310  0.525526      fail
3   0.409428  0.982270  0.721209  0.587475  0.543212  0.538343      fail
4   0.396689  0.866124  0.670913  0.533662  0.499706  0.501769      fail
5   0.405592  1.073105  0.811684  0.660446  0.608285  0.602178      fail
6   0.394453  1.092096  0.810389  0.611248  0.564977  0.555057      fail
7   0.370965  1.072223  0.832748  0.643066  0.596422  0.584088      fail
8   0.438353  1.044906  0.816408  0.641555  0.590945  0.589662      fail
9   0.256054  0.770307  0.619287  0.464664  0.428006  0.421820      fail
10  0.400747  0.985873  0.778494  0.548839  0.512562  0.514243      pass
11  0.302906  0.816812  0.633840  0.451740  0.418034  0.426504      pass
12  0.327878  0.936819  0.686311  0.462357  0.430565  0.428530      pass
13  0.341021  0.942446  0.675398  0.486045  0.450279  0.450211      pass
14  0.326407  0.851150  0.679601  0.521230  0.487035  0.495674      pass
15  0.254987  0.784410  0.521568  0.387197  0.356025  0.360906      pass
16  0.394652  0.945884  0.727911  0.569909  0.526110  0.534005      pass
17  0.208146  0.810659  0.574254  0.423049  0.394897  0.391090      pass
18  0.335624  0.771801  0.582743  0.443030  0.408746  0.399740      pass
19  0.200824  0.468929  0.373014  0.276379  0.257564  0.260772      pass

BARINEL SCORES

         cx 2       h 1     rxx 0      cx 5      cx 3      cx 4
sum  0.561016  0.560617  0.557098  0.554509  0.548101  0.543237

TARANTULA SCORES

         cx 2       h 1     rxx 0      cx 5      cx 3      cx 4
sum  0.561016  0.560617  0.557098  0.554509  0.548101  0.543237

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_swap_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.07it/s]
100%|██████████| 10/10 [00:01<00:00,  9.22it/s]

        cx 5      cx 4      cx 3    swap 2      cx 1       h 0 pass/fail
0   0.311170  0.932975  0.679228  0.562429  0.439851  0.409000      fail
1   0.355773  0.925686  0.688177  0.580374  0.478096  0.443597      fail
2   0.441752  1.005315  0.784737  0.734760  0.605915  0.564366      fail
3   0.347977  0.963163  0.690989  0.613629  0.494954  0.459043      fail
4   0.360263  0.803289  0.604569  0.529577  0.428334  0.395568      fail
5   0.313775  0.941297  0.711974  0.651135  0.527202  0.491278      fail
6   0.435625  1.016188  0.798556  0.679265  0.575872  0.533218      fail
7   0.317022  0.843509  0.629178  0.662028  0.544314  0.509537      fail
8   0.473335  1.045177  0.800755  0.711949  0.587335  0.545662      fail
9   0.294225  0.860013  0.595369  0.527796  0.409077  0.380627      fail
10  0.225190  0.748153  0.584072  0.534853  0.447068  0.412576      pass
11  0.325139  0.767293  0.590496  0.475646  0.400965  0.370769      pass
12  0.223063  0.713055  0.547441  0.492840  0.412661  0.384689      pass
13  0.351735  0.886923  0.735209  0.554072  0.480984  0.446910      pass
14  0.350329  0.779950  0.638579  0.513309  0.445685  0.412295      pass
15  0.335916  0.886396  0.666800  0.581366  0.472181  0.435865      pass
16  0.395906  0.983742  0.709855  0.605738  0.477558  0.442701      pass
17  0.442609  0.990112  0.781486  0.586632  0.501521  0.463663      pass
18  0.283025  0.764632  0.562397  0.449044  0.354590  0.328214      pass
19  0.297868  0.728437  0.579243  0.501181  0.427068  0.395867      pass

BARINEL SCORES

       swap 2       h 0      cx 1      cx 4      cx 5      cx 3
sum  0.541492  0.536165  0.535257  0.530933  0.530526  0.521973

TARANTULA SCORES

       swap 2       h 0      cx 1      cx 4      cx 5      cx 3
sum  0.541492  0.536165  0.535257  0.530933  0.530526  0.521973

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_cswap_inGap_3_.qasm

100%|██████████| 10/10 [00:02<00:00,  3.93it/s]
100%|██████████| 10/10 [00:02<00:00,  4.39it/s]

        cx 5      cx 4      cx 3   cswap 2      cx 1       h 0 pass/fail
0   0.348577  0.872549  0.711067  0.714614  0.505032  0.486348      fail
1   0.383494  0.964316  0.719096  0.734065  0.499671  0.487395      fail
2   0.419593  1.028682  0.797329  0.800541  0.557872  0.537916      fail
3   0.463995  0.956260  0.673432  0.685318  0.461598  0.449738      fail
4   0.249041  0.700064  0.522521  0.513110  0.358881  0.347457      fail
5   0.417688  0.978765  0.728627  0.720914  0.479787  0.464414      fail
6   0.445554  0.974713  0.714489  0.717007  0.487150  0.470556      fail
7   0.445080  1.027509  0.817842  0.849101  0.589861  0.577076      fail
8   0.305389  0.941874  0.717771  0.733467  0.508982  0.492563      fail
9   0.326825  0.953376  0.698941  0.716896  0.485693  0.478194      fail
10  0.259353  0.789811  0.622061  0.638038  0.458016  0.444843      pass
11  0.427781  1.050893  0.794244  0.828455  0.569808  0.556544      pass
12  0.283532  0.820121  0.616767  0.634278  0.451844  0.441389      pass
13  0.195531  0.564809  0.386047  0.402959  0.278983  0.272262      pass
14  0.315178  0.905765  0.719083  0.743374  0.512234  0.503507      pass
15  0.349354  0.795438  0.549107  0.578462  0.397729  0.392230      pass
16  0.269274  0.667068  0.579625  0.609147  0.435341  0.424473      pass
17  0.264510  0.782573  0.598270  0.623435  0.444401  0.430122      pass
18  0.227481  0.699241  0.527505  0.545634  0.373294  0.364230      pass
19  0.320966  0.571397  0.453737  0.463504  0.326141  0.317930      pass

BARINEL SCORES

         cx 5      cx 4      cx 3   cswap 2      cx 1       h 0
sum  0.566407  0.551363  0.548452  0.542172  0.537394  0.536028

TARANTULA SCORES

         cx 5      cx 4      cx 3   cswap 2      cx 1       h 0
sum  0.566407  0.551363  0.548452  0.542172  0.537394  0.536028

ERROR GATE LOCATION:
2
Now evolving the following mutant:  AddGate_sx_inGap_3_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.83it/s]
100%|██████████| 10/10 [00:00<00:00, 10.18it/s]

        cx 5      cx 4      cx 3      cx 2       h 1    sxdg 0 pass/fail
0   0.452880  1.152124  0.920534  0.669543  0.615636  1.252197      fail
1   0.485029  1.003515  0.822980  0.600987  0.559033  1.155292      fail
2   0.337431  0.913577  0.715923  0.562342  0.522280  1.019355      fail
3   0.242463  0.753360  0.596865  0.466051  0.436877  0.811258      fail
4   0.329018  0.856523  0.672751  0.476276  0.442976  0.842822      fail
5   0.366874  1.051117  0.843454  0.601300  0.559485  1.140644      fail
6   0.241570  0.788846  0.608970  0.483747  0.448855  0.865216      fail
7   0.306627  1.047570  0.823811  0.605333  0.563729  1.126085      fail
8   0.390910  0.943387  0.743469  0.532355  0.498799  0.941811      fail
9   0.327197  0.866120  0.713208  0.537961  0.499318  1.018042      fail
10  0.308863  0.663388  0.498974  0.357194  0.332383  0.625905      pass
11  0.245660  0.724908  0.553368  0.401263  0.375842  0.673219      pass
12  0.362739  0.857888  0.647554  0.508158  0.469551  0.852110      pass
13  0.397242  1.011763  0.746406  0.560325  0.523702  0.926725      pass
14  0.382737  0.894335  0.688779  0.540330  0.496359  0.971641      pass
15  0.330616  0.923508  0.732851  0.557738  0.518526  1.020105      pass
16  0.177441  0.716107  0.567235  0.424957  0.396991  0.753867      pass
17  0.318435  0.814761  0.588252  0.427451  0.394391  0.665417      pass
18  0.268066  0.835589  0.625639  0.444258  0.413833  0.764434      pass
19  0.357904  0.877319  0.636857  0.458531  0.426385  0.713435      pass

BARINEL SCORES

       sxdg 0      cx 3       h 1      cx 2      cx 4     cx 5
sum  0.560803  0.542772  0.542076  0.541879  0.529854  0.52491

TARANTULA SCORES

       sxdg 0      cx 3       h 1      cx 2      cx 4     cx 5
sum  0.560803  0.542772  0.542076  0.541879  0.529854  0.52491

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_rx_inGap_9_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.94it/s]
100%|██████████| 10/10 [00:00<00:00, 11.07it/s]

        rx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.397968  1.255377  0.939102  0.842400  0.631581  0.584226      fail
1   0.423903  1.260484  0.888176  0.842930  0.649514  0.597372      fail
2   0.381480  1.228078  0.900026  0.860703  0.676327  0.626961      fail
3   0.307045  1.291282  0.948079  0.782956  0.566754  0.530514      fail
4   0.394051  0.979701  0.741744  0.727754  0.570478  0.526858      fail
5   0.303343  1.307192  1.007064  0.913558  0.689494  0.637887      fail
6   0.343632  0.920197  0.768659  0.724385  0.563917  0.523070      fail
7   0.322177  0.949030  0.704668  0.639027  0.484676  0.449716      fail
8   0.379693  1.109436  0.875564  0.823664  0.613610  0.564649      fail
9   0.323337  1.183744  0.918010  0.807235  0.604885  0.564982      fail
10  0.346106  1.138161  0.841345  0.762686  0.561173  0.518416      pass
11  0.203249  0.956327  0.663214  0.596276  0.491803  0.451709      pass
12  0.392136  1.197268  0.881603  0.798857  0.564225  0.522939      pass
13  0.319952  1.151061  0.844721  0.762512  0.553688  0.510433      pass
14  0.405225  1.255811  0.897581  0.848647  0.640030  0.594064      pass
15  0.275295  1.180894  0.931490  0.852246  0.639284  0.589704      pass
16  0.276542  1.046037  0.843290  0.770307  0.549975  0.506256      pass
17  0.278786  1.171619  0.850440  0.750290  0.561862  0.516735      pass
18  0.312081  1.129291  0.828946  0.725325  0.587595  0.540440      pass
19  0.374535  1.242599  0.930226  0.842720  0.653280  0.601752      pass

BARINEL SCORES

         rx 5       h 0      cx 1      cx 2     cx 3      cx 4
sum  0.529045  0.511579  0.510474  0.508126  0.50518  0.500337

TARANTULA SCORES

         rx 5       h 0      cx 1      cx 2     cx 3      cx 4
sum  0.529045  0.511579  0.510474  0.508126  0.50518  0.500337

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_rx_inGap_7_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.79it/s]
100%|██████████| 10/10 [00:00<00:00, 10.51it/s]

        rx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.930774  1.404516  1.016482  0.777619  0.610557  0.563892      fail
1   1.550318  1.402077  1.071140  0.808100  0.578328  0.530176      fail
2   1.119918  1.276750  0.998847  0.724282  0.553174  0.509181      fail
3   0.809297  1.181187  0.914115  0.683743  0.473181  0.439859      fail
4   1.183960  1.338039  0.953418  0.734890  0.581227  0.532656      fail
5   1.090847  1.387636  1.046347  0.841387  0.655823  0.597547      fail
6   1.092128  1.567923  1.201118  0.887631  0.700804  0.651972      fail
7   1.291486  1.240012  0.942847  0.705952  0.530411  0.486633      fail
8   0.994289  1.193943  0.931690  0.771020  0.570089  0.525971      fail
9   1.401557  1.362374  1.026005  0.752549  0.574432  0.526179      fail
10  1.070052  1.385322  1.133822  0.788141  0.624832  0.575529      pass
11  1.064841  1.068650  0.853531  0.626927  0.481950  0.441030      pass
12  0.553086  1.103893  0.944668  0.747089  0.565294  0.518107      pass
13  1.057862  1.241365  0.989868  0.687556  0.495469  0.450698      pass
14  1.031629  1.250264  0.960054  0.694914  0.504727  0.465117      pass
15  0.863714  1.174144  0.868654  0.644300  0.490316  0.447111      pass
16  1.388659  1.529846  1.176965  0.806805  0.641020  0.589990      pass
17  0.763891  1.225679  1.075577  0.789734  0.554028  0.504573      pass
18  0.575680  0.981087  0.807527  0.633946  0.485997  0.447571      pass
19  0.797402  1.201198  0.941340  0.712894  0.531363  0.482436      pass

BARINEL SCORES

         rx 5      cx 4      h 0      cx 1      cx 2      cx 3
sum  0.555686  0.523378  0.52148  0.520219  0.518721  0.508814

TARANTULA SCORES

         rx 5      cx 4      h 0      cx 1      cx 2      cx 3
sum  0.555686  0.523378  0.52148  0.520219  0.518721  0.508814

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cx_inGap_7_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.24it/s]
100%|██████████| 10/10 [00:00<00:00, 10.35it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.381613  0.814927  0.684139  0.519232  0.416029  0.383550      fail
1   0.338367  0.944525  0.728360  0.563341  0.438050  0.406200      fail
2   0.370449  0.962908  0.806443  0.625179  0.480137  0.442424      fail
3   0.421267  0.969503  0.795387  0.614077  0.431016  0.400846      fail
4   0.384790  0.891124  0.719295  0.519502  0.386688  0.361066      fail
5   0.466320  0.982763  0.808022  0.622964  0.453068  0.420007      fail
6   0.418197  0.997355  0.798294  0.630917  0.498506  0.460211      fail
7   0.367053  0.903351  0.717282  0.552576  0.422388  0.388383      fail
8   0.450116  1.082499  0.846855  0.634957  0.485935  0.450785      fail
9   0.505747  0.939999  0.844281  0.635789  0.467987  0.436414      fail
10  0.231660  0.684195  0.586667  0.452868  0.335092  0.310562      pass
11  0.217329  0.698625  0.578176  0.431249  0.344388  0.320349      pass
12  0.462746  1.069000  0.866980  0.626139  0.477616  0.446846      pass
13  0.406318  0.958307  0.773559  0.644303  0.455770  0.421461      pass
14  0.314398  0.857979  0.707499  0.553759  0.394227  0.366409      pass
15  0.306777  0.818336  0.670845  0.462036  0.353582  0.329412      pass
16  0.366950  0.984899  0.836866  0.665531  0.489184  0.451867      pass
17  0.319547  0.904568  0.765090  0.571657  0.440043  0.404151      pass
18  0.412910  0.909647  0.725769  0.526353  0.386815  0.359498      pass
19  0.220090  0.874969  0.703458  0.547638  0.414390  0.384438      pass

BARINEL SCORES

         cx 5      cx 1       h 0      cx 4      cx 2      cx 3
sum  0.557397  0.522675  0.522335  0.519958  0.519167  0.517825

TARANTULA SCORES

         cx 5      cx 1       h 0      cx 4      cx 2      cx 3
sum  0.557397  0.522675  0.522335  0.519958  0.519167  0.517825

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_x_inGap_2_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.59it/s]
100%|██████████| 10/10 [00:00<00:00, 10.32it/s]

        cx 5      cx 4      cx 3      cx 2       h 1       x 0 pass/fail
0   0.443293  1.070401  0.824493  0.645746  0.596122  1.179151      fail
1   0.296018  0.953853  0.753927  0.601441  0.556844  1.147284      fail
2   0.416307  1.048571  0.843804  0.657999  0.605268  1.213436      fail
3   0.371340  0.907510  0.720190  0.548599  0.507326  0.991043      fail
4   0.347992  0.779221  0.611617  0.461264  0.428961  0.799021      fail
5   0.341834  0.956177  0.685181  0.535586  0.494271  0.978847      fail
6   0.422332  0.981658  0.738609  0.618614  0.573869  1.224661      fail
7   0.331936  0.933162  0.693674  0.539601  0.499200  0.965051      fail
8   0.446460  1.065458  0.826394  0.632214  0.583549  1.140117      fail
9   0.366305  0.982427  0.727396  0.569427  0.527246  1.041231      fail
10  0.328047  0.826673  0.681067  0.503379  0.464980  0.885461      pass
11  0.325323  0.840446  0.645574  0.494155  0.454873  0.887305      pass
12  0.351921  0.882332  0.751477  0.560215  0.515809  1.014161      pass
13  0.412970  0.908768  0.700651  0.518086  0.475444  0.904873      pass
14  0.230497  0.631462  0.502067  0.392262  0.359427  0.730898      pass
15  0.358779  0.816374  0.598534  0.441744  0.406638  0.752088      pass
16  0.374362  0.906117  0.707894  0.515595  0.476019  0.871275      pass
17  0.336157  0.843325  0.627453  0.484695  0.448401  0.880191      pass
18  0.403104  0.914778  0.710906  0.520784  0.491459  0.888276      pass
19  0.303929  0.888306  0.680321  0.544128  0.504895  1.008312      pass

BARINEL SCORES

          x 0      h 1     cx 2      cx 4      cx 3      cx 5
sum  0.547609  0.53885  0.53873  0.533629  0.529197  0.524881

TARANTULA SCORES

          x 0      h 1     cx 2      cx 4      cx 3      cx 5
sum  0.547609  0.53885  0.53873  0.533629  0.529197  0.524881

ERROR GATE LOCATION:
0
Now evolving the following mutant:  AddGate_sx_inGap_8_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.13it/s]
100%|██████████| 10/10 [00:00<00:00, 11.48it/s]

      sxdg 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   1.295017  1.151286  1.086375  0.845579  0.606843  0.562626      fail
1   1.122511  1.316355  1.203186  0.907249  0.663596  0.611413      fail
2   1.126542  1.120401  0.982453  0.723412  0.573504  0.526131      fail
3   1.177982  1.308674  1.200742  0.954703  0.724963  0.668349      fail
4   1.342598  1.195240  1.097036  0.853384  0.662832  0.605187      fail
5   1.087857  0.969091  0.875277  0.680726  0.488434  0.449890      fail
6   1.361248  1.288529  1.158272  0.835669  0.618820  0.569147      fail
7   1.202391  1.154198  1.057953  0.815303  0.597152  0.553120      fail
8   1.017817  0.943846  0.887448  0.638499  0.472453  0.439813      fail
9   1.177134  1.316819  1.164887  0.931402  0.653862  0.607611      fail
10  1.048082  1.215349  1.038935  0.742419  0.524008  0.481639      pass
11  1.067396  1.147540  1.066579  0.864102  0.614306  0.564738      pass
12  1.012647  0.971184  0.940754  0.734419  0.541015  0.494472      pass
13  1.147503  0.925232  0.866559  0.685625  0.531856  0.486315      pass
14  1.395161  1.138198  1.099957  0.862529  0.641206  0.593367      pass
15  0.852044  0.929737  0.816336  0.643396  0.476312  0.440389      pass
16  1.278726  1.335837  1.254124  1.038773  0.744011  0.682817      pass
17  0.926827  0.968225  0.926630  0.735910  0.535483  0.495935      pass
18  1.362711  1.304102  1.223265  0.990927  0.745555  0.693387      pass
19  1.006139  0.802881  0.752682  0.564021  0.427587  0.392992      pass

BARINEL SCORES

         cx 4    sxdg 5     cx 3       h 0      cx 1      cx 2
sum  0.522801  0.517686  0.51758  0.512237  0.511868  0.510089

TARANTULA SCORES

         cx 4    sxdg 5     cx 3       h 0      cx 1      cx 2
sum  0.522801  0.517686  0.51758  0.512237  0.511868  0.510089

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_y_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 11.18it/s]
100%|██████████| 10/10 [00:00<00:00, 12.22it/s]

         y 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.874452  1.262811  0.934003  0.756579  0.555372  0.516287      fail
1   0.902627  1.306102  0.957185  0.755495  0.593864  0.548751      fail
2   1.004821  1.111098  0.811382  0.594843  0.425728  0.400301      fail
3   0.951841  1.273053  0.993593  0.740571  0.533370  0.496870      fail
4   0.789424  1.262652  1.041668  0.807293  0.590939  0.547909      fail
5   0.546515  1.149549  0.977661  0.762720  0.554882  0.516455      fail
6   0.975879  1.253454  0.982869  0.738916  0.566113  0.523647      fail
7   1.138114  1.330921  1.010887  0.738135  0.539025  0.500349      fail
8   1.039700  1.621986  1.273439  0.919215  0.710163  0.653807      fail
9   1.092935  1.359851  1.037235  0.809308  0.605471  0.559747      fail
10  0.533729  0.783475  0.622949  0.464239  0.346472  0.322856      pass
11  0.800023  1.334844  1.024608  0.781952  0.586284  0.540814      pass
12  0.623713  1.190817  0.962920  0.753691  0.557219  0.520447      pass
13  0.595383  1.115513  0.869923  0.614599  0.482921  0.447449      pass
14  0.673723  1.062683  0.832709  0.566428  0.426372  0.399841      pass
15  0.594664  0.960742  0.772723  0.556074  0.440070  0.407451      pass
16  0.600915  1.297908  1.043806  0.847943  0.629129  0.579495      pass
17  0.973655  1.233997  0.967689  0.721435  0.535176  0.495371      pass
18  0.876134  1.291093  0.955564  0.669121  0.493164  0.459019      pass
19  0.969678  1.151118  0.859816  0.671094  0.478717  0.444358      pass

BARINEL SCORES

          y 5      cx 2      cx 1      h 0      cx 4      cx 3
sum  0.562649  0.534216  0.532834  0.53274  0.530987  0.529241

TARANTULA SCORES

          y 5      cx 2      cx 1      h 0      cx 4      cx 3
sum  0.562649  0.534216  0.532834  0.53274  0.530987  0.529241

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cx_inGap_9_.qasm

100%|██████████| 10/10 [00:01<00:00,  8.24it/s]
100%|██████████| 10/10 [00:01<00:00,  9.46it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.432290  1.088132  0.821954  0.600399  0.487493  0.451088      fail
1   0.383591  0.909061  0.746082  0.570474  0.438582  0.409586      fail
2   0.453658  1.128620  0.917027  0.710748  0.574130  0.532818      fail
3   0.429607  0.952549  0.718677  0.548995  0.434870  0.404994      fail
4   0.357085  1.007047  0.769180  0.612200  0.473312  0.441494      fail
5   0.411320  1.005457  0.788308  0.601254  0.501597  0.458635      fail
6   0.348559  0.889997  0.716815  0.530110  0.424103  0.388711      fail
7   0.497256  1.100358  0.869755  0.684782  0.540290  0.503143      fail
8   0.315143  0.890313  0.668448  0.512704  0.402023  0.377325      fail
9   0.354386  0.957918  0.718381  0.558171  0.433935  0.405123      fail
10  0.227555  0.817779  0.625377  0.481219  0.394715  0.362421      pass
11  0.415867  0.963044  0.737524  0.534771  0.442111  0.407220      pass
12  0.297005  0.780570  0.619190  0.446760  0.340488  0.317383      pass
13  0.266156  0.816560  0.664831  0.472359  0.387276  0.357328      pass
14  0.263731  0.612796  0.439317  0.341482  0.276224  0.252224      pass
15  0.260632  0.733905  0.557752  0.443539  0.327006  0.310898      pass
16  0.297059  0.852304  0.630021  0.513815  0.417249  0.388177      pass
17  0.327052  0.886038  0.646891  0.519130  0.382310  0.360836      pass
18  0.232871  0.615860  0.472140  0.345968  0.296091  0.269384      pass
19  0.272906  0.711534  0.557451  0.437954  0.350739  0.324274      pass

BARINEL SCORES

         cx 5      cx 2       h 0      cx 1      cx 3      cx 4
sum  0.581977  0.566536  0.566215  0.565837  0.565185  0.560358

TARANTULA SCORES

         cx 5      cx 2       h 0      cx 1      cx 3      cx 4
sum  0.581977  0.566536  0.566215  0.565837  0.565185  0.560358

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ry_inGap_9_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.57it/s]
100%|██████████| 10/10 [00:00<00:00, 11.70it/s]

        ry 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.266532  0.847089  0.668766  0.763251  0.429347  0.392168      fail
1   0.388998  1.068239  0.852182  1.168403  0.602175  0.554600      fail
2   0.373420  1.228913  0.901179  1.039979  0.624594  0.569871      fail
3   0.403350  0.997433  0.748435  1.128106  0.607917  0.559244      fail
4   0.400336  1.139280  0.838643  1.097027  0.556395  0.509548      fail
5   0.456785  1.047919  0.797828  1.198133  0.608364  0.559710      fail
6   0.378334  1.277422  0.985194  1.096262  0.612908  0.563895      fail
7   0.359541  1.160638  0.908142  1.066984  0.573833  0.531628      fail
8   0.390643  1.192536  0.925668  1.245401  0.624113  0.570345      fail
9   0.272979  1.209806  0.941093  1.132776  0.641977  0.585821      fail
10  0.210560  0.856791  0.608555  0.777568  0.425073  0.391789      pass
11  0.257019  1.005744  0.739079  0.901782  0.507804  0.463467      pass
12  0.232641  0.962113  0.678628  0.768912  0.465845  0.431082      pass
13  0.340097  1.210069  0.926283  1.097841  0.606759  0.556028      pass
14  0.305489  1.047182  0.748079  0.908520  0.519046  0.478064      pass
15  0.290101  0.813851  0.566141  0.713825  0.389161  0.358443      pass
16  0.395492  1.168227  0.868893  1.150487  0.605733  0.556330      pass
17  0.313495  1.394155  1.022242  1.107340  0.659564  0.611188      pass
18  0.186948  0.761398  0.555930  0.695828  0.400963  0.367766      pass
19  0.219968  1.109961  0.840352  1.004538  0.608914  0.562680      pass

BARINEL SCORES

         ry 5    cx 2      cx 3      cx 1      h 0      cx 4
sum  0.572881  0.5451  0.531416  0.531289  0.53047  0.519531

TARANTULA SCORES

         ry 5    cx 2      cx 3      cx 1      h 0      cx 4
sum  0.572881  0.5451  0.531416  0.531289  0.53047  0.519531

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_cx_inGap_8_.qasm

100%|██████████| 10/10 [00:01<00:00,  9.11it/s]
100%|██████████| 10/10 [00:01<00:00,  9.39it/s]

        cx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.294099  0.769435  0.600604  0.470355  0.361006  0.333781      fail
1   0.615232  1.243491  0.955283  0.769723  0.567324  0.522651      fail
2   0.297012  0.917071  0.689160  0.575249  0.434355  0.404359      fail
3   0.420734  0.926087  0.697912  0.580819  0.441687  0.409134      fail
4   0.439395  1.000384  0.791224  0.622418  0.477164  0.441888      fail
5   0.408205  0.933339  0.708979  0.577299  0.424923  0.397167      fail
6   0.314755  0.836933  0.658148  0.543250  0.411184  0.382221      fail
7   0.341355  0.841576  0.638641  0.525676  0.396383  0.363534      fail
8   0.474488  1.126039  0.880753  0.675418  0.486412  0.454234      fail
9   0.429972  0.972575  0.763725  0.601693  0.444119  0.412764      fail
10  0.382323  0.991576  0.773163  0.579532  0.460757  0.425022      pass
11  0.332788  0.795495  0.569735  0.459244  0.324055  0.298151      pass
12  0.356895  0.939461  0.723327  0.586953  0.446331  0.414087      pass
13  0.276273  0.877608  0.710219  0.544949  0.410359  0.381646      pass
14  0.465830  0.948363  0.720160  0.599628  0.440936  0.407802      pass
15  0.328690  0.892803  0.659064  0.550671  0.429688  0.395910      pass
16  0.382786  0.994816  0.707872  0.595009  0.424164  0.394238      pass
17  0.276639  0.868317  0.575251  0.530940  0.390756  0.364981      pass
18  0.263101  0.859080  0.665133  0.529199  0.393503  0.361541      pass
19  0.336492  0.873554  0.611062  0.542678  0.404978  0.376374      pass

BARINEL SCORES

         cx 5     cx 3       h 0      cx 1      cx 2     cx 4
sum  0.542586  0.52374  0.519013  0.518613  0.518458  0.51413

TARANTULA SCORES

         cx 5     cx 3       h 0      cx 1      cx 2     cx 4
sum  0.542586  0.52374  0.519013  0.518613  0.518458  0.51413

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_h_inGap_9_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.81it/s]
100%|██████████| 10/10 [00:00<00:00, 11.38it/s]

         h 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.310815  1.097661  0.854586  1.039267  0.545892  0.501922      fail
1   0.341056  1.173932  0.967272  1.247079  0.688610  0.633853      fail
2   0.428992  1.022394  0.745534  0.976645  0.478890  0.439055      fail
3   0.360443  1.183012  0.940607  1.089608  0.636958  0.589188      fail
4   0.414487  1.261154  0.932702  1.237499  0.692479  0.639841      fail
5   0.314146  1.365508  1.071146  1.102128  0.631790  0.583920      fail
6   0.340014  1.175015  0.924580  1.177373  0.631871  0.579850      fail
7   0.418558  1.247524  0.942295  1.337095  0.691530  0.637551      fail
8   0.256360  0.764064  0.543081  0.675365  0.340432  0.309927      fail
9   0.323723  1.092652  0.804132  0.944966  0.569016  0.524166      fail
10  0.303033  1.291704  1.051328  1.203480  0.736355  0.679892      pass
11  0.168776  1.016728  0.784140  0.922511  0.528898  0.480645      pass
12  0.293474  1.044039  0.753126  0.967817  0.565496  0.517393      pass
13  0.210745  1.180464  0.908653  0.895490  0.574078  0.528580      pass
14  0.329238  1.109609  0.897005  1.078667  0.640015  0.596792      pass
15  0.310436  0.953111  0.688493  0.883180  0.486358  0.450189      pass
16  0.293885  1.318435  1.015816  1.075258  0.659803  0.608128      pass
17  0.209498  0.942917  0.641390  0.623366  0.394684  0.364884      pass
18  0.161483  1.053130  0.791835  0.810807  0.521752  0.481655      pass
19  0.184289  0.664936  0.541214  0.669533  0.395585  0.363864      pass

BARINEL SCORES

          h 5      cx 2      cx 3      cx 4      cx 1       h 0
sum  0.587365  0.542514  0.519434  0.518395  0.517722  0.517469

TARANTULA SCORES

          h 5      cx 2      cx 3      cx 4      cx 1       h 0
sum  0.587365  0.542514  0.519434  0.518395  0.517722  0.517469

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_h_inGap_6_.qasm

100%|██████████| 10/10 [00:00<00:00, 14.19it/s]
100%|██████████| 10/10 [00:00<00:00, 16.88it/s]

         h 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.406711  0.858730  0.623493  0.509880  0.405530  0.376317      fail
1   0.377077  0.728558  0.563272  0.463371  0.357437  0.328901      fail
2   0.392215  0.869846  0.715891  0.501517  0.382262  0.355485      fail
3   0.382162  0.755022  0.576728  0.407034  0.299647  0.278968      fail
4   0.357669  0.752450  0.597004  0.411558  0.320536  0.298195      fail
5   0.348398  0.795092  0.604233  0.457392  0.345327  0.319712      fail
6   0.404994  0.936173  0.768410  0.512603  0.397603  0.369353      fail
7   0.382150  0.787159  0.593552  0.462248  0.332238  0.308000      fail
8   0.363435  0.701778  0.565289  0.452646  0.345003  0.317532      fail
9   0.344920  0.784632  0.598414  0.436864  0.348086  0.319290      fail
10  0.343373  0.821047  0.724631  0.557057  0.421123  0.390518      pass
11  0.238338  0.604624  0.505356  0.386749  0.295783  0.275786      pass
12  0.274488  0.702237  0.560939  0.396370  0.315357  0.290991      pass
13  0.233244  0.826515  0.643422  0.533892  0.388133  0.356439      pass
14  0.240617  0.654554  0.483768  0.419867  0.307083  0.286413      pass
15  0.250487  0.632950  0.519611  0.398983  0.318512  0.295900      pass
16  0.376015  0.957343  0.799858  0.570630  0.449349  0.415634      pass
17  0.320964  0.836685  0.633497  0.488229  0.354429  0.329393      pass
18  0.293149  0.704372  0.506198  0.365745  0.289693  0.265797      pass
19  0.152958  0.757701  0.617649  0.495920  0.386840  0.359280      pass

BARINEL SCORES

          h 5      cx 4      cx 3      cx 1       h 0      cx 2
sum  0.579904  0.515239  0.508661  0.500522  0.500428  0.500091

TARANTULA SCORES

          h 5      cx 4      cx 3      cx 1       h 0      cx 2
sum  0.579904  0.515239  0.508661  0.500522  0.500428  0.500091

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_x_inGap_7_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.49it/s]
100%|██████████| 10/10 [00:00<00:00, 12.16it/s]

         x 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.832985  0.965106  0.764068  0.607927  0.430104  0.399118      fail
1   0.958615  1.198857  0.901476  0.667105  0.537823  0.496994      fail
2   1.040936  1.339085  1.126287  0.821664  0.605268  0.556972      fail
3   0.807024  1.284605  0.951793  0.687332  0.513993  0.477253      fail
4   0.838541  1.155524  0.876081  0.630259  0.442593  0.410787      fail
5   0.728784  1.134488  0.844236  0.658895  0.478873  0.447262      fail
6   1.077925  1.282916  0.866900  0.655808  0.492529  0.459005      fail
7   0.810260  1.180817  0.877799  0.686975  0.499145  0.466304      fail
8   0.754557  1.137710  0.833093  0.666559  0.517084  0.479186      fail
9   0.803214  1.124607  0.892743  0.683179  0.504199  0.471244      fail
10  0.589815  1.075432  0.817981  0.643713  0.492088  0.455582      pass
11  0.725119  0.877008  0.676027  0.502000  0.389528  0.363763      pass
12  0.808009  1.128708  0.906658  0.621171  0.470383  0.434783      pass
13  0.503901  1.091262  0.876206  0.646418  0.536664  0.492578      pass
14  0.477939  1.209010  0.983113  0.733832  0.527055  0.486840      pass
15  0.812907  1.129806  0.808265  0.651233  0.491510  0.451949      pass
16  0.811959  1.168356  0.896428  0.705283  0.552122  0.509664      pass
17  0.685225  1.226653  0.971951  0.770240  0.574392  0.529063      pass
18  0.852278  1.137313  0.870990  0.632236  0.467577  0.434564      pass
19  0.863094  1.376959  1.055158  0.804899  0.584237  0.538222      pass

BARINEL SCORES

          x 5     cx 4      cx 2      cx 3       h 0      cx 1
sum  0.548235  0.50825  0.502029  0.502014  0.498244  0.496837

TARANTULA SCORES

          x 5     cx 4      cx 2      cx 3       h 0      cx 1
sum  0.548235  0.50825  0.502029  0.502014  0.498244  0.496837

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ry_inGap_10_.qasm

100%|██████████| 10/10 [00:00<00:00, 10.63it/s]
100%|██████████| 10/10 [00:00<00:00, 12.39it/s]

        ry 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.821106  1.197135  0.917443  0.667930  0.532072  0.494433      fail
1   0.810869  1.251998  0.927484  0.729865  0.576771  0.532686      fail
2   0.937980  1.187319  0.944324  0.698894  0.563694  0.522266      fail
3   0.718276  1.081774  0.874622  0.662224  0.539583  0.500737      fail
4   0.891890  1.291942  0.917574  0.735814  0.578125  0.530610      fail
5   0.930683  1.367145  1.008461  0.752314  0.592307  0.546376      fail
6   0.812134  1.130609  0.776690  0.584262  0.480199  0.444366      fail
7   0.794614  1.072418  0.854888  0.627982  0.497034  0.460128      fail
8   0.916753  1.283994  1.048370  0.827086  0.616940  0.570630      fail
9   0.950535  1.497662  1.091122  0.832851  0.629714  0.581755      fail
10  0.819954  1.067195  0.832863  0.652529  0.500241  0.460766      pass
11  1.005678  1.203318  0.892442  0.665018  0.512385  0.477729      pass
12  0.620036  0.987609  0.748958  0.565054  0.423191  0.397512      pass
13  0.991086  1.238269  1.043873  0.827958  0.650763  0.593963      pass
14  0.583006  1.320530  1.018081  0.800473  0.626329  0.581983      pass
15  0.915759  1.270718  0.911689  0.708914  0.526257  0.486519      pass
16  0.816850  1.016966  0.796419  0.621473  0.470657  0.431989      pass
17  0.711653  1.067618  0.847121  0.621243  0.482481  0.449162      pass
18  0.325052  0.996229  0.804101  0.619175  0.471650  0.440574      pass
19  0.540469  1.300483  0.997178  0.747927  0.573984  0.533133      pass

BARINEL SCORES

         ry 5      cx 4      cx 1       h 0      cx 3      cx 2
sum  0.539439  0.518737  0.516991  0.516471  0.512826  0.510376

TARANTULA SCORES

         ry 5      cx 4      cx 1       h 0      cx 3      cx 2
sum  0.539439  0.518737  0.516991  0.516471  0.512826  0.510376

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ccx_inGap_10_.qasm

100%|██████████| 10/10 [00:02<00:00,  3.68it/s]
100%|██████████| 10/10 [00:02<00:00,  3.66it/s]

       ccx 5      cx 4      cx 3      cx 2      cx 1       h 0 pass/fail
0   0.770340  0.885459  0.732881  0.613518  0.572745  0.534619      fail
1   0.780086  0.916311  0.779413  0.637726  0.597088  0.558284      fail
2   0.844280  1.044231  0.907391  0.735247  0.697522  0.650769      fail
3   0.786904  0.924025  0.777295  0.628624  0.582400  0.542012      fail
4   0.773523  0.885786  0.710715  0.593382  0.572609  0.534881      fail
5   0.786383  0.824424  0.695658  0.579573  0.522131  0.488155      fail
6   0.679894  0.727056  0.576782  0.474276  0.452607  0.420943      fail
7   0.720528  0.749598  0.591380  0.488330  0.424037  0.391093      fail
8   0.745177  0.823224  0.658875  0.533945  0.489376  0.455460      fail
9   0.745646  0.798816  0.603160  0.497906  0.461698  0.428462      fail
10  0.636877  0.841077  0.678071  0.542578  0.544230  0.510460      pass
11  0.716094  0.966418  0.739525  0.604507  0.626526  0.591354      pass
12  0.603942  0.714869  0.554015  0.439266  0.423833  0.397615      pass
13  0.738379  0.913287  0.778097  0.635851  0.623570  0.583191      pass
14  0.608172  0.729296  0.575172  0.485944  0.472917  0.445924      pass
15  0.693402  0.763791  0.621951  0.520153  0.509422  0.475602      pass
16  0.764607  0.890246  0.697486  0.578865  0.562395  0.524696      pass
17  0.651685  0.766825  0.633657  0.513998  0.480669  0.447589      pass
18  0.727124  0.866679  0.721162  0.575088  0.581060  0.544970      pass
19  0.599396  0.690234  0.547173  0.472399  0.437762  0.407869      pass

BARINEL SCORES

        ccx 5      cx 2     cx 3      cx 4      cx 1       h 0
sum  0.531069  0.518558  0.51794  0.513043  0.505164  0.503796

TARANTULA SCORES

        ccx 5      cx 2     cx 3      cx 4      cx 1       h 0
sum  0.531069  0.518558  0.51794  0.513043  0.505164  0.503796

ERROR GATE LOCATION:
5
Now evolving the following mutant:  AddGate_ccx_inGap_4_.qasm

100%|██████████| 10/10 [00:02<00:00,  4.50it/s]
100%|██████████| 10/10 [00:01<00:00,  5.18it/s]

        cx 5      cx 4     ccx 3      cx 2      cx 1       h 0 pass/fail
0   0.374740  1.099612  0.954029  0.649392  0.485181  0.447210      fail
1   0.400435  1.043042  0.934555  0.622437  0.474452  0.442642      fail
2   0.425298  0.996522  0.894827  0.569441  0.432483  0.402161      fail
3   0.334358  0.961726  0.852473  0.581726  0.427577  0.396755      fail
4   0.362063  0.988578  0.895085  0.568895  0.429365  0.400641      fail
5   0.361017  0.946130  0.883006  0.592698  0.447942  0.414139      fail
6   0.424358  1.078347  0.970582  0.646705  0.490590  0.453020      fail
7   0.402580  1.117979  0.984209  0.654941  0.490068  0.454319      fail
8   0.501881  1.112598  1.011395  0.673860  0.509470  0.472917      fail
9   0.362596  1.016312  0.888912  0.594572  0.449638  0.417734      fail
10  0.146052  0.452112  0.452555  0.301705  0.226110  0.210465      pass
11  0.359602  0.879472  0.840919  0.530946  0.409312  0.380759      pass
12  0.258730  0.755026  0.690832  0.441694  0.340216  0.317985      pass
13  0.330024  0.786632  0.772842  0.491874  0.371196  0.343556      pass
14  0.471821  1.061615  0.987222  0.661300  0.501898  0.464770      pass
15  0.242109  0.766913  0.690528  0.452701  0.346180  0.321354      pass
16  0.364000  0.772897  0.747905  0.492437  0.377831  0.352661      pass
17  0.332827  0.844285  0.796583  0.539611  0.400342  0.371418      pass
18  0.272224  0.847375  0.778807  0.502070  0.362762  0.337676      pass
19  0.182817  0.626925  0.595260  0.401653  0.308745  0.287021      pass

BARINEL SCORES

         cx 5      cx 4      cx 2      cx 1       h 0     ccx 3
sum  0.571576  0.570717  0.561012  0.559904  0.559426  0.557621

TARANTULA SCORES

         cx 5      cx 4      cx 2      cx 1       h 0     ccx 3
sum  0.571576  0.570717  0.561012  0.559904  0.559426  0.557621

ERROR GATE LOCATION:
3

,Program,path_to_mutant,exam_score
0,AddGate_ccx_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,1.0
1,AddGate_ccx_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
2,AddGate_ry_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
3,AddGate_x_inGap_7_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
4,AddGate_h_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
...,...,...,...
84,AddGate_x_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
85,AddGate_cx_inGap_3_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.666667
86,AddGate_x_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
87,AddGate_y_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
88,AddGate_y_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667

,Program,path_to_mutant,exam_score
0,AddGate_ccx_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,1.0
1,AddGate_ccx_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
2,AddGate_ry_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
3,AddGate_x_inGap_7_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
4,AddGate_h_inGap_6_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
...,...,...,...
84,AddGate_x_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
85,AddGate_cx_inGap_3_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.666667
86,AddGate_x_inGap_4_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
87,AddGate_y_inGap_10_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667
88,AddGate_y_inGap_9_.qasm,SBFL_circuits/QMutBenchMutants/Mutants_ghz_5_q...,0.166667